from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Daily life"


def daily_life_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "daily-morning",
            "Morning",
            [
                _w("despertarse", "dejar de dormir", "Me despierto a las 7."),
                _w("levantarse", "salir de la cama", "Levántate, es tarde."),
                _w("ducharse", "lavarse bajo el agua", "Me ducho cada mañana."),
                _w("cepillarse", "limpiar con cepillo", "Cepíllate los dientes."),
                _w("vestirse", "ponerse la ropa", "Vístete rápido."),
                _w("desayunar", "tomar la primera comida", "Desayuna."),
                _w("café", "bebida de la mañana", "Necesito café."),
                _w("salir", "irse de un lugar", "Salgo a las 8."),
                _w("traslado", "viaje diario al trabajo o escuela", "Un traslado largo."),
                _w("temprano", "antes de lo usual", "Me desperté temprano."),
                _w("despertador", "reloj que suena", "Pon el despertador."),
                _w("cansado", "con necesidad de descanso", "Sigo cansado."),
            ],
            domain=DOMAIN,
            sort_order=80,
        ),
        _deck(
            "es",
            "daily-work",
            "Work and school",
            [
                _w("trabajo", "empleo o lugar donde trabajas", "Voy al trabajo."),
                _w("escuela", "lugar donde estudian los niños", "La escuela empieza a las 8."),
                _w("oficina", "lugar de escritorios", "Está en la oficina."),
                _w("clase", "lección con un profesor", "Clase de mates."),
                _w("reunión", "gente que se junta a hablar", "Una reunión a las 10."),
                _w("tarea", "trabajo escolar en casa", "Haz la tarea."),
                _w("jefe", "persona a cargo en el trabajo", "Pregunta a tu jefe."),
                _w("profesor", "quien enseña", "Mi profesor es amable."),
                _w("estudiante", "quien estudia", "Un estudiante nuevo."),
                _w("descanso", "pausa corta", "Un descanso para comer."),
                _w("ocupado", "con mucho que hacer", "Estoy ocupado hoy."),
                _w("terminar", "completar algo", "Termino a las 5."),
            ],
            domain=DOMAIN,
            sort_order=81,
        ),
        _deck(
            "es",
            "daily-shopping",
            "Shopping",
            [
                _w("comprar", "dar dinero por algo", "Compro el sábado."),
                _w("tienda", "lugar que vende cosas", "Una tienda de comida."),
                _w("vender", "dar algo por dinero", "Venden pan."),
                _w("precio", "cuánto cuesta", "¿Cuál es el precio?"),
                _w("barato", "que cuesta poco", "Una camisa barata."),
                _w("caro", "que cuesta mucho", "Demasiado caro."),
                _w("efectivo", "dinero en billetes o monedas", "Pago en efectivo."),
                _w("tarjeta", "plástico para pagar", "Pago con tarjeta."),
                _w("bolsa", "para llevar lo comprado", "Una bolsa."),
                _w("recibo", "prueba de lo que pagaste", "Guarda el recibo."),
                _w("cambio", "dinero que te devuelven", "Aquí está tu cambio."),
                _w("oferta", "precio más bajo", "Está en oferta."),
            ],
            domain=DOMAIN,
            sort_order=82,
        ),
        _deck(
            "es",
            "daily-free-time",
            "Free time",
            [
                _w("tiempo libre", "cuando no trabajas", "En mi tiempo libre leo."),
                _w("descansar", "dejar de trabajar", "Descansa después del trabajo."),
                _w("leer", "mirar palabras escritas", "Leo de noche."),
                _w("ver", "mirar un rato", "Ver una película."),
                _w("escuchar", "oír con atención", "Escuchar música."),
                _w("pasear", "caminar por gusto", "Un paseo en el parque."),
                _w(
                    "hacer ejercicio",
                    "actividad para estar en forma",
                    "Hago ejercicio el domingo.",
                ),
                _w("pasatiempo", "actividad por gusto", "Cocinar es mi pasatiempo."),
                _w("amigo", "alguien con quien pasas tiempo", "Llama a un amigo."),
                _w("fin de semana", "sábado y domingo", "Nos vemos este fin de semana."),
                _w("película", "un filme", "Una película graciosa."),
                _w("dormir", "descansar con los ojos cerrados", "Necesito dormir."),
            ],
            domain=DOMAIN,
            sort_order=83,
        ),
    ]
