from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Family"


def family_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "family-immediate",
            "Immediate family",
            [
                _w("padre", "progenitor hombre", "Mi padre cocina."),
                _w("madre", "progenitora", "Mi madre llamó."),
                _w("papá", "padre informal", "Papá lee."),
                _w("mamá", "madre informal", "Mamá está en casa."),
                _w("hijo", "niño varón", "Su hijo tiene seis."),
                _w("hija", "niña", "Su hija canta."),
                _w("hermano", "varón de los mismos padres", "Mi hermano corre."),
                _w("hermana", "mujer de los mismos padres", "Mi hermana lee."),
                _w("padres", "madre y padre", "Mis padres viven cerca."),
                _w("hijos", "hijos e hijas", "Tienen dos hijos."),
                _w("bebé", "niño muy pequeño", "El bebé duerme."),
                _w("niño", "niño o niña", "El niño juega."),
            ],
            domain=DOMAIN,
            sort_order=20,
        ),
        _deck(
            "es",
            "family-extended",
            "Extended family",
            [
                _w("abuela", "madre del padre o de la madre", "La abuela cuenta cuentos."),
                _w("abuelo", "padre del padre o de la madre", "El abuelo sonríe."),
                _w("nieta", "hija del hijo o de la hija", "Su nieta dibuja."),
                _w("nieto", "hijo del hijo o de la hija", "Su nieto juega."),
                _w("tía", "hermana del padre o de la madre", "Mi tía llama."),
                _w("tío", "hermano del padre o de la madre", "Mi tío visita."),
                _w("sobrina", "hija del hermano o de la hermana", "Mi sobrina visita."),
                _w("sobrino", "hijo del hermano o de la hermana", "Mi sobrino ríe."),
                _w("primo", "hijo del tío o de la tía", "Mi primo estudia."),
                _w("prima", "hija del tío o de la tía", "Mi prima canta."),
                _w("bisabuela", "abuela de un padre", "Mi bisabuela tiene 96."),
                _w("bisabuelo", "abuelo de un padre", "Mi bisabuelo cultivaba."),
                _w("tía abuela", "hermana de un abuelo", "Mi tía abuela escribe."),
            ],
            domain=DOMAIN,
            sort_order=21,
        ),
        _deck(
            "es",
            "family-marriage",
            "Marriage and partnerships",
            [
                _w("esposo", "marido", "Su esposo cocina."),
                _w("esposa", "mujer casada", "Su esposa trabaja."),
                _w("marido", "hombre casado", "Su marido llegó."),
                _w("mujer", "esposa", "Su mujer trabaja."),
                _w("pareja", "persona con quien compartes la vida", "Mi pareja y yo nos mudamos."),
                _w("prometido", "hombre que va a casarse", "Su prometido llegó."),
                _w("prometida", "mujer que va a casarse", "Su prometida sonrió."),
                _w("novia", "mujer en una boda o relación", "La novia entró."),
                _w("novio", "hombre en una boda o relación", "El novio esperaba."),
                _w("matrimonio", "unión legal de pareja", "Su matrimonio es feliz."),
                _w("boda", "ceremonia de casamiento", "La boda es en junio."),
                _w("divorcio", "fin legal del matrimonio", "Pidieron el divorcio."),
                _w("separación", "vivir aparte estando casados", "Eligieron la separación."),
            ],
            domain=DOMAIN,
            sort_order=22,
        ),
        _deck(
            "es",
            "family-relationships",
            "Family relationships",
            [
                _w("pariente", "miembro de la familia", "Un pariente visitó."),
                _w("familiar", "de la familia", "Un familiar cercano."),
                _w("antepasado", "persona de la que desciendes", "Nuestros antepasados llegaron."),
                _w("descendiente", "persona que viene de ti", "Es descendiente de poetas."),
                _w(
                    "generación",
                    "personas nacidas en la misma época",
                    "Tres generaciones viven aquí.",
                ),
                _w("suegro", "padre del cónyuge", "Mi suegro llegó."),
                _w("suegra", "madre del cónyuge", "Mi suegra ayuda."),
                _w("cuñado", "hermano del cónyuge", "Mi cuñado viaja."),
                _w("cuñada", "hermana del cónyuge", "Mi cuñada llama."),
                _w("yerno", "esposo de la hija", "Su yerno cocina."),
                _w("nuera", "esposa del hijo", "Su nuera estudia."),
                _w("árbol genealógico", "gráfico de parientes", "Dibujamos el árbol genealógico."),
            ],
            domain=DOMAIN,
            sort_order=23,
        ),
        _deck(
            "es",
            "family-parenthood",
            "Parenthood",
            [
                _w("criar", "educar a un niño", "Crían a dos hijos."),
                _w("educación", "forma de criar", "Tuvo una buena educación."),
                _w("disciplina", "enseñanza de conducta", "La disciplina justa ayuda."),
                _w("cuidar", "atender a alguien", "Cuido a mi hermana."),
                _w("proteger", "mantener a salvo", "Los padres protegen."),
                _w("adoptar", "tomar como hijo legalmente", "Quieren adoptar."),
                _w("adopción", "proceso legal de adoptar", "La adopción salió bien."),
                _w("acoger", "cuidar a un niño temporalmente", "Acogen a un adolescente."),
                _w("tutor", "adulto responsable legalmente", "Su tutor firmó."),
                _w("custodia", "cuidado legal de un niño", "Comparten la custodia."),
                _w("criar un hijo", "hacerse cargo de un niño", "Criar un hijo es duro."),
                _w("apoyar", "dar sostén", "Me apoyan siempre."),
            ],
            domain=DOMAIN,
            sort_order=24,
        ),
        _deck(
            "es",
            "family-birth",
            "Birth and childhood",
            [
                _w("embarazo", "tiempo antes del nacimiento", "El embarazo va bien."),
                _w("embarazada", "que espera un bebé", "Está embarazada."),
                _w("nacimiento", "el nacer", "El nacimiento fue en casa."),
                _w("recién nacido", "bebé que acaba de nacer", "El recién nacido duerme."),
                _w("lactante", "bebé que toma leche", "El lactante lloró."),
                _w("niñez", "tiempo de ser niño", "Recuerdo mi niñez."),
                _w("infancia", "primeros años", "Una infancia feliz."),
                _w("adolescencia", "años de adolescente", "La adolescencia es difícil."),
                _w("adolescente", "persona de unos 13 a 19 años", "El adolescente estudia."),
                _w("crecer", "hacerse adulto", "Crecí aquí."),
                _w("nacer", "venir al mundo", "Nació en mayo."),
                _w("dar a luz", "tener un bebé", "Dio a luz al amanecer."),
            ],
            domain=DOMAIN,
            sort_order=25,
        ),
        _deck(
            "es",
            "family-conflict",
            "Family conflict",
            [
                _w("discutir", "pelear con palabras", "Discuten por las tareas."),
                _w("discrepar", "tener otra opinión", "A veces discrepamos."),
                _w("pelea", "discusión fuerte", "La pelea terminó pronto."),
                _w("conflicto", "choque de opiniones", "El conflicto familiar es normal."),
                _w("tensión", "ambiente tenso", "Había tensión en la cena."),
                _w("rencor", "enojo que dura", "El rencor creció."),
                _w("celos", "querer lo que otro tiene", "Los celos duelen."),
                _w("traición", "romper la confianza", "La traición la sorprendió."),
                _w("perdonar", "dejar de culpar", "Te perdono."),
                _w("disculparse", "pedir perdón", "Debes disculparte."),
                _w("reconciliarse", "volver a ser amigos", "Se reconciliaron."),
                _w("enemistarse", "dejar de llevarse bien", "Se enemistaron."),
                _w("hacer las paces", "volver a la amistad", "Hicieron las paces."),
                _w("llevarse bien", "tener buena relación", "Nos llevamos bien."),
            ],
            domain=DOMAIN,
            sort_order=26,
        ),
        _deck(
            "es",
            "family-affection",
            "Family affection",
            [
                _w("amor", "cariño profundo", "Amo a mi familia."),
                _w("cariño", "afecto cálido", "Muestra cariño."),
                _w("confianza", "creer en alguien", "La confianza tarda."),
                _w("respeto", "valoración de alguien", "Respeta a tus mayores."),
                _w("afecto", "ternura", "Siente afecto."),
                _w("cercanía", "sentirse cerca", "Hay cercanía entre ellos."),
                _w("vínculo", "lazo fuerte", "Un vínculo familiar."),
                _w("abrazo", "envolver con los brazos", "Dame un abrazo."),
                _w("beso", "tocar con los labios", "Un beso en la mejilla."),
                _w("consolar", "aliviar a alguien triste", "La consolé."),
                _w("animar", "dar ánimo", "Me animan."),
                _w("querer", "amar o estimar", "Te quiero."),
            ],
            domain=DOMAIN,
            sort_order=27,
        ),
        _deck(
            "es",
            "family-responsibilities",
            "Family responsibilities",
            [
                _w("proveer", "dar lo necesario", "Proveen la comida."),
                _w("mantener", "sostener con dinero", "Él mantiene a la familia."),
                _w("depender", "necesitar de alguien", "Los niños dependen de sus padres."),
                _w("responsabilidad", "deber que debes cumplir", "Es mi responsabilidad."),
                _w("obligación", "algo que debes hacer", "Una obligación legal."),
                _w("hogar", "casa y quienes viven juntos", "Todo el hogar comió."),
                _w("cuidado infantil", "atención a los niños", "Necesitan cuidado infantil."),
                _w("ayuda económica", "dinero para sostener", "Envía ayuda económica."),
                _w("tarea", "quehacer de casa", "Lavar es mi tarea."),
                _w("mesada", "dinero regular para un hijo", "Una mesada semanal."),
                _w("encargarse de", "hacerse cargo", "Me encargo de los niños."),
                _w("sostén", "apoyo, a menudo económico", "Ella es el sostén."),
            ],
            domain=DOMAIN,
            sort_order=28,
        ),
        _deck(
            "es",
            "family-structure",
            "Family structure",
            [
                _w(
                    "familia monoparental",
                    "familia con un solo padre",
                    "Una familia monoparental.",
                ),
                _w("familia nuclear", "padres e hijos", "Una familia nuclear."),
                _w(
                    "familia ensamblada",
                    "familia unida tras un nuevo matrimonio",
                    "Una familia ensamblada.",
                ),
                _w("padrastro", "nuevo esposo de la madre", "Mi padrastro entrena."),
                _w("madrastra", "nueva esposa del padre", "Mi madrastra cocina."),
                _w("hijastro", "hijo de la pareja de antes", "Su hijastro tiene diez."),
                _w("hijastra", "hija de la pareja de antes", "Su hijastra dibuja."),
                _w(
                    "medio hermano",
                    "hermano con un solo padre en común",
                    "Mi medio hermano visitó.",
                ),
                _w(
                    "media hermana",
                    "hermana con un solo padre en común",
                    "Mi media hermana llamó.",
                ),
                _w("hijo adoptivo", "hijo unido por adopción", "Su hijo adoptivo tiene cinco."),
                _w("hijo único", "sin hermanos", "Soy hijo único."),
                _w(
                    "familia extendida",
                    "parientes más allá de padres e hijos",
                    "La familia extendida vino.",
                ),
            ],
            domain=DOMAIN,
            sort_order=29,
        ),
        _deck(
            "es",
            "family-death",
            "Death and family",
            [
                _w("muerte", "fin de la vida", "Lloraron su muerte."),
                _w("morir", "dejar de vivir", "Murió el año pasado."),
                _w("fallecido", "que ya no vive", "El fallecido dejó una nota."),
                _w("funeral", "ceremonia tras la muerte", "El funeral es el viernes."),
                _w("entierro", "poner el cuerpo en la tierra", "El entierro fue silencioso."),
                _w("duelo", "tristeza profunda por una pérdida", "El duelo llega por oleadas."),
                _w("llorar", "mostrar pena", "Lloran juntos."),
                _w("viuda", "mujer cuyo esposo murió", "La viuda habló."),
                _w("viudo", "hombre cuya esposa murió", "El viudo se mudó."),
                _w("homenaje", "acto para recordar a alguien", "Un homenaje el domingo."),
                _w("heredar", "recibir tras una muerte", "Ella heredará la casa."),
                _w("herencia", "lo que se deja a alguien", "Una herencia pequeña."),
                _w("testamento", "documento sobre bienes al morir", "Escribió un testamento."),
                _w("patrimonio", "bienes dejados al morir", "El patrimonio se dividió."),
            ],
            domain=DOMAIN,
            sort_order=30,
        ),
        _deck(
            "es",
            "family-expressions",
            "Family expressions",
            [
                _w("llevarse bien con", "tener buena relación con", "Me llevo bien con ella."),
                _w("salir a", "parecerse a un pariente", "Sale a su madre."),
                _w("criar a", "educar a un niño", "Nos criaron aquí."),
                _w("establecerse", "empezar una vida estable", "Quieren establecerse."),
                _w("formar una familia", "empezar a tener hijos", "Formaron una familia."),
                _w("tener hijos", "ser padre o madre", "Tienen hijos."),
                _w("casarse", "unirse en matrimonio", "Se casaron en mayo."),
                _w("divorciarse", "terminar el matrimonio", "Se divorciaron."),
                _w("ser pariente de", "tener lazos familiares", "Soy pariente de él."),
                _w("ser cercano a", "sentirse cerca de", "Soy cercano a mi hermana."),
                _w("enemistarse con", "dejar de ser amigos", "Me enemisté con él."),
                _w("hacer las paces con", "volver a la amistad", "Hice las paces con ella."),
            ],
            domain=DOMAIN,
            sort_order=31,
        ),
    ]
