from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Food"


def food_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "food-drinks",
            "Drinks",
            [
                _w("agua", "bebida sin sabor", "Bebo agua."),
                _w("café", "bebida caliente de granos", "Café negro."),
                _w("té", "bebida caliente de hojas", "Té verde."),
                _w("leche", "bebida blanca de vaca", "Un vaso de leche."),
                _w("jugo", "bebida de fruta", "Jugo de naranja."),
                _w("refresco", "bebida dulce con gas", "Una lata de refresco."),
                _w("vino", "bebida de uvas", "Una copa de vino."),
                _w("cerveza", "bebida de grano", "Una cerveza fría."),
                _w("sed", "necesidad de beber", "Tengo sed."),
                _w("sorbo", "beber un poco", "Dio un sorbo al té."),
                _w("botella", "envase para líquido", "Una botella de agua."),
                _w("taza", "recipiente pequeño para beber", "Una taza de café."),
            ],
            domain=DOMAIN,
            sort_order=40,
        ),
        _deck(
            "es",
            "food-meals",
            "Meals",
            [
                _w("desayuno", "primera comida del día", "Como desayuno."),
                _w("almuerzo", "comida del mediodía", "El almuerzo es al mediodía."),
                _w("cena", "comida de la noche", "La cena está lista."),
                _w("merienda", "comida pequeña entre horas", "Una merienda de fruta."),
                _w("pan", "alimento horneado de harina", "Pan fresco."),
                _w("arroz", "grano cocido", "Un plato de arroz."),
                _w("huevo", "alimento de gallina", "Huevos cocidos."),
                _w("queso", "alimento de leche", "Queso en el pan."),
                _w("sopa", "comida líquida caliente", "Sopa de tomate."),
                _w("sándwich", "comida entre pan", "Un sándwich de queso."),
                _w("hambre", "necesidad de comer", "Tengo hambre."),
                _w("comida", "alimentos de una vez", "Una comida sencilla."),
            ],
            domain=DOMAIN,
            sort_order=41,
        ),
        _deck(
            "es",
            "food-produce",
            "Fruit and vegetables",
            [
                _w("manzana", "fruta redonda", "Una manzana roja."),
                _w("plátano", "fruta larga amarilla", "Como un plátano."),
                _w("naranja", "cítrico", "Pela la naranja."),
                _w("uva", "fruta pequeña en racimos", "Uvas dulces."),
                _w("tomate", "fruta roja usada como verdura", "Corta el tomate."),
                _w("papa", "tubérculo", "Hierve las papas."),
                _w("cebolla", "bulbo de sabor fuerte", "Pica una cebolla."),
                _w("zanahoria", "verdura naranja", "Una zanahoria cruda."),
                _w("lechuga", "hoja para ensalada", "Lava la lechuga."),
                _w("frijol", "semilla que se come", "Frijoles negros."),
                _w("fruta", "alimento dulce de planta", "Come más fruta."),
                _w("verdura", "alimento de planta, a menudo salado", "Cocina las verduras."),
            ],
            domain=DOMAIN,
            sort_order=42,
        ),
        _deck(
            "es",
            "food-cooking",
            "Cooking",
            [
                _w("cocinar", "preparar comida con calor", "Cocino la cena."),
                _w("hornear", "cocinar en el horno", "Hornea el pan."),
                _w("hervir", "calentar hasta que burbujee", "Hierve el agua."),
                _w("freír", "cocinar en aceite caliente", "Fríe los huevos."),
                _w("cortar", "dividir con cuchillo", "Corta la cebolla."),
                _w("mezclar", "juntar revolviendo", "Mezcla la salsa."),
                _w("receta", "pasos para un plato", "Sigue la receta."),
                _w("ingrediente", "parte de una receta", "Lista los ingredientes."),
                _w("sal", "condimento blanco", "Añade sal."),
                _w("pimienta", "condimento picante", "Pimienta negra."),
                _w("aceite", "grasa líquida para cocinar", "Aceite de oliva."),
                _w("sabor", "gusto en la boca", "Prueba la sopa."),
            ],
            domain=DOMAIN,
            sort_order=43,
        ),
        _deck(
            "es",
            "food-restaurant",
            "Restaurant",
            [
                _w("restaurante", "lugar que sirve comidas", "Un restaurante pequeño."),
                _w("menú", "lista de platos", "Mira el menú."),
                _w("mesero", "persona que sirve la comida", "El mesero sonrió."),
                _w("pedir", "solicitar comida", "Quisiera pedir."),
                _w("cuenta", "cantidad a pagar", "La cuenta, por favor."),
                _w("propina", "dinero extra por el servicio", "Deja una propina."),
                _w("mesa", "lugar para sentarse a comer", "Una mesa para dos."),
                _w("reserva", "mesa apartada", "Tenemos una reserva."),
                _w("delicioso", "muy rico", "Está delicioso."),
                _w("picante", "con mucho chile", "La salsa está picante."),
                _w("vegetariano", "quien no come carne", "Un plato vegetariano."),
                _w("para llevar", "comida que se lleva", "Café para llevar."),
            ],
            domain=DOMAIN,
            sort_order=44,
        ),
    ]
