from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Greetings"


def greetings_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "greetings-hello",
            "Hello and goodbye",
            [
                _w("hola", "saludo", "Hola, ¿cómo estás?"),
                _w("buenos días", "saludo de la mañana", "Buenos días."),
                _w("buenas tardes", "saludo de la tarde", "Buenas tardes."),
                _w("buenas noches", "saludo o despedida de noche", "Buenas noches."),
                _w("adiós", "despedida", "Adiós."),
                _w("hasta luego", "despedida informal", "Hasta luego."),
                _w("hasta mañana", "despedida hasta el día siguiente", "Hasta mañana."),
                _w("nos vemos", "despedida casual", "Nos vemos."),
                _w("chao", "adiós informal", "Chao."),
                _w("bienvenido", "saludo a un invitado", "Bienvenido a casa."),
                _w("cuídate", "despedida cariñosa", "Cuídate."),
                _w("hasta pronto", "despedida breve", "Hasta pronto."),
            ],
            domain=DOMAIN,
            sort_order=10,
        ),
        _deck(
            "es",
            "greetings-courtesy",
            "Courtesy",
            [
                _w("por favor", "petición educada", "Siéntate, por favor."),
                _w("gracias", "agradecimiento", "Gracias."),
                _w("muchas gracias", "agradecimiento fuerte", "Muchas gracias."),
                _w("de nada", "respuesta a gracias", "De nada."),
                _w("perdón", "disculpa", "Perdón, llego tarde."),
                _w("lo siento", "lamento", "Lo siento."),
                _w("disculpe", "interrupción educada", "Disculpe."),
                _w("con permiso", "para pasar o irse", "Con permiso."),
                _w("no hay problema", "está bien", "No hay problema."),
                _w("claro", "por supuesto", "Claro."),
                _w("felicidades", "elogio por un logro", "¡Felicidades!"),
                _w("salud", "brindis o tras un estornudo", "¡Salud!"),
            ],
            domain=DOMAIN,
            sort_order=11,
        ),
        _deck(
            "es",
            "greetings-meeting",
            "Meeting people",
            [
                _w("mucho gusto", "al conocer a alguien", "Mucho gusto."),
                _w("me llamo", "dice tu nombre", "Me llamo Ana."),
                _w("soy", "dice quién eres", "Soy profesor."),
                _w("este es", "presenta a otra persona", "Este es mi amigo."),
                _w("amigo", "persona que te cae bien", "Un amigo cercano."),
                _w("amiga", "amiga mujer", "Mi amiga llegó."),
                _w("vecino", "quien vive cerca", "Nuestro vecino saludó."),
                _w("compañero", "persona de clase o trabajo", "Mi compañero ayudó."),
                _w("desconocido", "alguien que no conoces", "No hables con desconocidos."),
                _w("presentar", "dar a conocer a alguien", "Te lo presento."),
                _w("apretón de manos", "saludo con las manos", "Se dieron un apretón de manos."),
                _w("sonrisa", "expresión de alegría", "Una sonrisa."),
            ],
            domain=DOMAIN,
            sort_order=12,
        ),
        _deck(
            "es",
            "greetings-how-are-you",
            "How are you",
            [
                _w("¿cómo estás?", "pregunta por el ánimo", "¿Cómo estás?"),
                _w("¿qué tal?", "pregunta informal", "¿Qué tal?"),
                _w("bien", "de forma aceptable", "Estoy bien."),
                _w("muy bien", "excelente", "Muy bien, gracias."),
                _w("regular", "ni bien ni mal", "Estoy regular."),
                _w("cansado", "con necesidad de descanso", "Estoy cansado."),
                _w("ocupado", "con mucho que hacer", "Estoy ocupado."),
                _w("mal", "no bien", "Me siento mal."),
                _w("¿y tú?", "devuelve la pregunta", "Bien, ¿y tú?"),
                _w("todo bien", "todo marcha", "Todo bien."),
                _w("más o menos", "así así", "Más o menos."),
                _w("¿qué pasa?", "qué hay de nuevo", "¿Qué pasa?"),
            ],
            domain=DOMAIN,
            sort_order=13,
        ),
    ]
