from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Home"


def home_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "home-rooms",
            "Rooms",
            [
                _w("casa", "edificio donde se vive", "Una casa pequeña."),
                _w("apartamento", "vivienda en un edificio", "Un apartamento en la ciudad."),
                _w("cuarto", "espacio dentro de la casa", "Un cuarto tranquilo."),
                _w("cocina", "habitación para cocinar", "Está en la cocina."),
                _w("dormitorio", "habitación para dormir", "El dormitorio está oscuro."),
                _w("baño", "habitación con retrete y lavabo", "El baño está libre."),
                _w("sala", "habitación para estar juntos", "La tele está en la sala."),
                _w("pasillo", "paso entre habitaciones", "Los zapatos en el pasillo."),
                _w("balcón", "plataforma exterior", "Siéntate en el balcón."),
                _w("jardín", "espacio con plantas", "Un jardín pequeño."),
                _w("garaje", "lugar para el coche", "El coche está en el garaje."),
                _w("arriba", "en un piso más alto", "Los niños están arriba."),
            ],
            domain=DOMAIN,
            sort_order=50,
        ),
        _deck(
            "es",
            "home-furniture",
            "Furniture",
            [
                _w("mesa", "superficie plana con patas", "Pon la mesa."),
                _w("silla", "asiento para una persona", "Acerca una silla."),
                _w("sofá", "asiento largo y blando", "Siéntate en el sofá."),
                _w("cama", "mueble para dormir", "Haz la cama."),
                _w("escritorio", "mesa para escribir", "Un escritorio de madera."),
                _w("lámpara", "luz que puedes mover", "Enciende la lámpara."),
                _w("estante", "tabla para guardar cosas", "Libros en el estante."),
                _w("armario", "espacio para la ropa", "Cuélgalo en el armario."),
                _w("espejo", "cristal que muestra tu cara", "Mírate en el espejo."),
                _w("cortina", "tela sobre la ventana", "Abre las cortinas."),
                _w("alfombra", "cubierta gruesa del suelo", "Una alfombra roja."),
                _w("almohada", "apoyo blando para la cabeza", "Una almohada suave."),
            ],
            domain=DOMAIN,
            sort_order=51,
        ),
        _deck(
            "es",
            "home-chores",
            "Kitchen and chores",
            [
                _w("limpiar", "quitar la suciedad", "Limpia el suelo."),
                _w("lavar", "limpiar con agua", "Lava los platos."),
                _w("platos", "vajilla después de comer", "Lava los platos."),
                _w("ropa sucia", "ropa para lavar", "Haz la ropa sucia."),
                _w("aspirar", "limpiar con aspiradora", "Aspira la alfombra."),
                _w("barrer", "limpiar con escoba", "Barre la cocina."),
                _w("basura", "lo que se tira", "Saca la basura."),
                _w("fregadero", "pila con grifo", "Lávalo en el fregadero."),
                _w("estufa", "aparato para cocinar", "La olla está en la estufa."),
                _w("nevera", "caja fría para comida", "La leche está en la nevera."),
                _w("escoba", "herramienta para barrer", "Trae la escoba."),
                _w("jabón", "se usa para lavar", "Usa jabón y agua."),
            ],
            domain=DOMAIN,
            sort_order=52,
        ),
        _deck(
            "es",
            "home-living",
            "Living at home",
            [
                _w("hogar", "el lugar donde vives", "Voy a casa."),
                _w("alquiler", "dinero por vivir en un sitio", "Pagamos el alquiler."),
                _w("casero", "quien alquila una casa", "Llama al casero."),
                _w("vecino", "quien vive cerca", "Nuestro vecino saludó."),
                _w("llave", "metal que abre un candado", "Perdí la llave."),
                _w("cerradura", "mecanismo que cierra la puerta", "Cierra con llave."),
                _w("timbre", "botón que suena en la puerta", "Toca el timbre."),
                _w("silencio", "con poco ruido", "Haz silencio."),
                _w("desordenado", "sin orden", "El cuarto está desordenado."),
                _w("ordenado", "en su sitio", "Mantén tu cuarto ordenado."),
                _w("mudarse", "empezar a vivir en otro sitio", "Nos mudamos el lunes."),
                _w("irse", "dejar una casa", "Se fueron."),
            ],
            domain=DOMAIN,
            sort_order=53,
        ),
    ]
