from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Hotel"


def hotel_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "hotel-arrival",
            "Arrival",
            [
                _w("hotel", "lugar que alquila habitaciones", "Un hotel en el centro."),
                _w("reserva", "habitación apartada", "Tengo una reserva."),
                _w("registrarse", "darse de alta como huésped", "Nos registramos a las 3."),
                _w("recepción", "mostrador del hotel", "Pregunta en recepción."),
                _w("recepcionista", "persona del mostrador", "La recepcionista sonrió."),
                _w("pasaporte", "documento de viaje", "Muestra el pasaporte."),
                _w("huésped", "persona que se aloja", "Un huésped del hotel."),
                _w("vestíbulo", "entrada amplia", "Espera en el vestíbulo."),
                _w("ascensor", "sube entre pisos", "Toma el ascensor."),
                _w("piso", "nivel de un edificio", "Tercer piso."),
                _w("tarjeta", "plástico que abre la habitación", "Tu tarjeta."),
                _w("noche", "una estancia", "Dos noches, por favor."),
            ],
            domain=DOMAIN,
            sort_order=60,
        ),
        _deck(
            "es",
            "hotel-room",
            "The room",
            [
                _w("habitación", "cuarto del hotel", "Una habitación doble."),
                _w("habitación individual", "cuarto para una persona", "Individual, por favor."),
                _w("habitación doble", "cuarto para dos", "Una habitación doble."),
                _w("cama", "mueble para dormir", "Una cama grande."),
                _w("baño", "cuarto con ducha o bañera", "Un baño privado."),
                _w("ducha", "lugar para lavarse de pie", "Una ducha caliente."),
                _w("toalla", "tela para secarse", "Toallas limpias."),
                _w("wifi", "internet inalámbrico", "La clave del wifi."),
                _w("aire acondicionado", "sistema que enfría", "Enciende el aire acondicionado."),
                _w("vista", "lo que se ve por la ventana", "Vista al mar."),
                _w("habitación tranquila", "cuarto con poco ruido", "Una habitación tranquila."),
                _w("caja fuerte", "caja que guarda objetos", "Ponlo en la caja fuerte."),
            ],
            domain=DOMAIN,
            sort_order=61,
        ),
        _deck(
            "es",
            "hotel-services",
            "Hotel services",
            [
                _w("desayuno", "comida de la mañana en el hotel", "El desayuno está incluido."),
                _w("incluido", "ya está en el precio", "El wifi está incluido."),
                _w("piscina", "lugar para nadar", "La piscina del hotel."),
                _w("gimnasio", "sala para hacer ejercicio", "El gimnasio abre a las 6."),
                _w("spa", "lugar de descanso y tratamientos", "Reserva el spa."),
                _w(
                    "servicio a la habitación",
                    "comida que llevan a tu cuarto",
                    "Llama al servicio a la habitación.",
                ),
                _w("limpieza", "personal que limpia", "Limpieza a las 11."),
                _w("lavandería", "servicio de lavar ropa", "Lavandería del hotel."),
                _w("conserje", "personal que ayuda con planes", "Pregunta al conserje."),
                _w("estacionamiento", "lugar para el coche", "¿El estacionamiento es gratis?"),
                _w("salida tardía", "irse más tarde de lo usual", "¿Puedo tener salida tardía?"),
                _w("llamada de despertador", "llamada para despertarte", "Una llamada a las 7."),
            ],
            domain=DOMAIN,
            sort_order=62,
        ),
        _deck(
            "es",
            "hotel-problems",
            "Problems and checkout",
            [
                _w("salir", "irse y pagar", "Salimos a las 11."),
                _w("factura", "cantidad a pagar", "La factura del hotel."),
                _w("recibo", "prueba de pago", "Necesito un recibo."),
                _w("queja", "decir que algo está mal", "Tengo una queja."),
                _w("ruidoso", "con mucho ruido", "La habitación es ruidosa."),
                _w("roto", "que no funciona", "La ducha está rota."),
                _w("sucio", "no limpio", "Las toallas están sucias."),
                _w("demasiado pequeño", "no lo bastante grande", "La cama es demasiado pequeña."),
                _w(
                    "cambiar de habitación",
                    "pasar a otro cuarto",
                    "¿Podemos cambiar de habitación?",
                ),
                _w("reembolso", "dinero que te devuelven", "Quiero un reembolso."),
                _w("perdido", "que no se encuentra", "Perdí la tarjeta."),
                _w("ayuda", "asistencia", "Necesito ayuda."),
            ],
            domain=DOMAIN,
            sort_order=63,
        ),
    ]
