from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Numbers and time"


def numbers_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "numbers-count",
            "Numbers",
            [
                _w("cero", "0", "El marcador es cero."),
                _w("uno", "1", "Tengo uno."),
                _w("dos", "2", "Dos libros."),
                _w("tres", "3", "Tres sillas."),
                _w("cuatro", "4", "Cuatro puertas."),
                _w("cinco", "5", "Cinco manzanas."),
                _w("diez", "10", "Diez dólares."),
                _w("veinte", "20", "Veinte estudiantes."),
                _w("cien", "100", "Cien personas."),
                _w("mil", "1.000", "Mil años."),
                _w("primero", "número 1 en orden", "El primer tren."),
                _w("segundo", "número 2 en orden", "La segunda puerta."),
                _w("mitad", "una de dos partes iguales", "La mitad del pastel."),
            ],
            domain=DOMAIN,
            sort_order=90,
        ),
        _deck(
            "es",
            "numbers-clock",
            "Clock time",
            [
                _w("hora", "60 minutos", "Espera una hora."),
                _w("minuto", "60 segundos", "Espera un minuto."),
                _w("en punto", "exactamente en la hora", "Son las tres en punto."),
                _w("mañana", "parte temprana del día", "Por la mañana."),
                _w("tarde", "después del mediodía", "Esta tarde."),
                _w("noche", "parte oscura del día", "Por la noche."),
                _w("ahora", "en este momento", "Hazlo ahora."),
                _w("luego", "después de ahora", "Luego esta noche."),
                _w("temprano", "antes de lo usual", "Un tren temprano."),
                _w("atrasado", "después de lo usual", "Perdón por llegar atrasado."),
                _w("mediodía", "las 12 del día", "Nos vemos al mediodía."),
                _w("medianoche", "las 12 de la noche", "A medianoche."),
            ],
            domain=DOMAIN,
            sort_order=91,
        ),
        _deck(
            "es",
            "numbers-days",
            "Days and months",
            [
                _w("hoy", "este día", "Hoy es lunes."),
                _w("mañana", "el día siguiente", "Nos vemos mañana."),
                _w("ayer", "el día anterior", "Ayer hizo frío."),
                _w("lunes", "primer día laboral", "Trabajo el lunes."),
                _w("viernes", "fin de la semana laboral", "El viernes por la noche."),
                _w("domingo", "último día de la semana", "Descanso el domingo."),
                _w("semana", "siete días", "Esta semana."),
                _w("mes", "unos 30 días", "El mes que viene."),
                _w("año", "12 meses", "El año que viene."),
                _w("enero", "primer mes", "Nació en enero."),
                _w("junio", "sexto mes", "La escuela termina en junio."),
                _w("diciembre", "último mes", "Nieve en diciembre."),
            ],
            domain=DOMAIN,
            sort_order=92,
        ),
        _deck(
            "es",
            "numbers-duration",
            "Duration",
            [
                _w("segundo", "un tiempo muy corto", "Espera un segundo."),
                _w("día", "24 horas", "Un día largo."),
                _w("fin de semana", "sábado y domingo", "Este fin de semana."),
                _w("estación", "una de las cuatro partes del año", "El verano es mi estación."),
                _w("siempre", "en todo momento", "Siempre sonríe."),
                _w("a menudo", "muchas veces", "A menudo camino."),
                _w("a veces", "no siempre", "A veces cocino."),
                _w("nunca", "en ningún momento", "Nunca fumo."),
                _w("pronto", "en poco tiempo", "Nos vemos pronto."),
                _w("ya", "antes de ahora", "Ya comí."),
                _w("todavía", "que continúa", "¿Todavía estás aquí?"),
                _w("aún no", "hasta ahora no", "Aún no."),
            ],
            domain=DOMAIN,
            sort_order=93,
        ),
    ]
