from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Travel"


def travel_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "es",
            "travel-around",
            "Getting around",
            [
                _w("viajar", "ir de un lugar a otro", "Viajo por trabajo."),
                _w("viaje", "un recorrido", "Un viaje de fin de semana."),
                _w("autobús", "vehículo grande de pasajeros", "Toma el autobús."),
                _w("tren", "vehículos sobre rieles", "El tren llega tarde."),
                _w("taxi", "coche que pagas", "Llama un taxi."),
                _w("metro", "tren bajo tierra", "Toma el metro."),
                _w("coche", "vehículo de pocas personas", "Alquilamos un coche."),
                _w("caminar", "ir a pie", "Podemos caminar."),
                _w("mapa", "dibujo de un lugar", "Mira el mapa."),
                _w("boleto", "prueba de que pagaste el viaje", "Compra un boleto."),
                _w("estación", "donde paran trenes o autobuses", "La estación de tren."),
                _w("parada", "donde para el autobús", "La próxima parada es la mía."),
            ],
            domain=DOMAIN,
            sort_order=70,
        ),
        _deck(
            "es",
            "travel-airport",
            "Airport",
            [
                _w("aeropuerto", "lugar de aviones", "Estamos en el aeropuerto."),
                _w("avión", "aeronave que vuela", "El avión está abordando."),
                _w("vuelo", "viaje en avión", "El vuelo está retrasado."),
                _w("pasaporte", "documento de viaje", "Muestra el pasaporte."),
                _w(
                    "tarjeta de embarque",
                    "pase para subir al avión",
                    "Aquí está mi tarjeta de embarque.",
                ),
                _w("puerta", "donde se aborda", "Puerta 12."),
                _w("equipaje", "maletas de viaje", "Factura el equipaje."),
                _w("equipaje de mano", "bolsa que llevas al avión", "Un equipaje de mano."),
                _w("seguridad", "control del aeropuerto", "Pasa por seguridad."),
                _w("retraso", "cuando algo llega tarde", "Dos horas de retraso."),
                _w("llegada", "el llegar", "Llegada a las 6."),
                _w("salida", "el partir", "Salida a las 9."),
            ],
            domain=DOMAIN,
            sort_order=71,
        ),
        _deck(
            "es",
            "travel-directions",
            "Directions",
            [
                _w("izquierda", "lo contrario de derecha", "Gira a la izquierda."),
                _w("derecha", "lo contrario de izquierda", "Gira a la derecha."),
                _w("recto", "adelante, sin girar", "Sigue recto."),
                _w("cerca", "no lejos", "El banco está cerca."),
                _w("lejos", "a mucha distancia", "Está lejos de aquí."),
                _w("al lado de", "junto a", "Al lado del parque."),
                _w("frente a", "al otro lado de", "Frente al hotel."),
                _w("esquina", "donde se cruzan dos calles", "En la esquina."),
                _w("cuadra", "tramo entre calles", "Camina dos cuadras."),
                _w("norte", "hacia arriba en el mapa", "Ve al norte."),
                _w("sur", "hacia abajo en el mapa", "Ve al sur."),
                _w("perdido", "sin saber dónde estás", "Estoy perdido."),
            ],
            domain=DOMAIN,
            sort_order=72,
        ),
        _deck(
            "es",
            "travel-tickets",
            "Tickets and places",
            [
                _w("billete", "prueba de pago para viajar o entrar", "Un billete de tren."),
                _w("solo ida", "viaje en una dirección", "Un boleto de solo ida."),
                _w("ida y vuelta", "ir y volver", "Un boleto de ida y vuelta."),
                _w("ciudad", "población grande", "Una ciudad ocupada."),
                _w("pueblo", "más pequeño que una ciudad", "Un pueblo tranquilo."),
                _w("país", "una nación", "¿Qué país?"),
                _w("playa", "arena junto al mar", "Una playa soleada."),
                _w("museo", "lugar de arte o historia", "Visita el museo."),
                _w("parque", "espacio verde público", "Camina en el parque."),
                _w("turista", "quien visita por placer", "Muchos turistas."),
                _w("recuerdo", "cosa que compras de un viaje", "Un recuerdo pequeño."),
                _w("mapa turístico", "plano para visitantes", "Pide un mapa turístico."),
            ],
            domain=DOMAIN,
            sort_order=73,
        ),
    ]
