"""Operation names and which chemistry kind each one belongs to."""

from __future__ import annotations

from typing import Literal

ChemistryKind = Literal[
    "equations",
    "amounts",
    "stoichiometry",
    "solutions",
    "acid_base",
    "gases",
    "thermochemistry",
    "equilibrium",
    "kinetics",
    "electrochemistry",
    "nuclear",
    "spectroscopy",
    "structure",
    "organic",
    "inorganic",
    "analytical",
    "biochemistry",
]

ChemistryOp = Literal[
    "balance",
    "molar_mass",
    "mass_to_moles",
    "moles_to_mass",
    "moles_to_particles",
    "particles_to_moles",
    "percent_composition",
    "percent_yield",
    "stoichiometry",
    "limiting_reagent",
    "molarity",
    "dilution",
    "molality",
    "mass_percent",
    "ph_from_h",
    "ph_from_poh",
    "h_from_ph",
    "poh_from_oh",
    "buffer_ph",
    "gibbs",
    "equilibrium_constant",
    "reaction_quotient",
    "first_order_half_life",
    "first_order_concentration",
    "arrhenius",
    "cell_gibbs",
    "nernst",
    "electrolysis_mass",
    "beer_lambert",
    "empirical_formula",
    "molecular_formula",
    "mass_stoichiometry",
    "solution_stoichiometry",
    "gas_stoichiometry",
    "limiting_mass",
    "limiting_solution",
    "strong_acid_ph",
    "strong_base_ph",
    "weak_acid_ph",
    "weak_base_ph",
    "ka_kb",
    "titration_strong",
    "titration_weak",
    "buffer_addition",
    "polyprotic_ph",
    "dalton",
    "partial_pressure",
    "gas_over_water",
    "calorimetry",
    "hess",
    "formation_enthalpy",
    "bond_enthalpy",
    "ksp",
    "precipitation",
    "common_ion",
    "kp",
    "kc_kp",
    "ice_equilibrium",
    "zero_order",
    "second_order",
    "zero_order_half_life",
    "second_order_half_life",
    "rate_law",
    "arrhenius_two_point",
    "cell_potential",
    "galvanic_cell",
    "nuclear_equation",
    "oxidation_state",
    "vsepr",
    "formal_charge",
    "functional_groups",
    "stereochemistry",
    "isomers",
    "coordination_complex",
    "boiling_elevation",
    "freezing_depression",
    "osmotic_pressure",
    "raoult",
    "calibration",
    "gravimetric",
    "standard_addition",
    "mass_defect",
    "crystal_field",
    "standard_deviation",
    "standard_error",
    "percent_error",
    "relative_uncertainty",
    "chromatography_rf",
    "iupac_name",
    "named_reaction",
    "ir_ranges",
    "ir_peak",
    "nmr_ranges",
    "nmr_peak",
    "nmr_splitting",
    "molecular_ion",
    "michaelis_menten",
    "solution_mass",
    "molality_from_mass",
    "mass_percent_solvent",
    "mole_fraction",
    "particles_to_mass",
    "gas_density",
    "molar_mass_from_density",
    "percent_ionization",
    "reaction_heat",
    "electrolysis_time",
    "titration_concentration",
    "graham_ratio",
    "element_mass",
    "average_atomic_mass",
    "electron_configuration",
]

OPS_BY_KIND: dict[ChemistryKind, frozenset[ChemistryOp]] = {
    "equations": frozenset({"balance"}),
    "amounts": frozenset(
        {
            "particles_to_mass",
            "element_mass",
            "average_atomic_mass",
            "molar_mass",
            "mass_to_moles",
            "moles_to_mass",
            "moles_to_particles",
            "particles_to_moles",
            "percent_composition",
            "percent_yield",
            "empirical_formula",
            "molecular_formula",
        }
    ),
    "stoichiometry": frozenset(
        {
            "stoichiometry",
            "limiting_reagent",
            "mass_stoichiometry",
            "solution_stoichiometry",
            "gas_stoichiometry",
            "limiting_mass",
            "limiting_solution",
        }
    ),
    "solutions": frozenset(
        {
            "mole_fraction",
            "mass_percent_solvent",
            "molality_from_mass",
            "solution_mass",
            "molarity",
            "dilution",
            "molality",
            "mass_percent",
            "boiling_elevation",
            "freezing_depression",
            "osmotic_pressure",
            "raoult",
        }
    ),
    "acid_base": frozenset(
        {
            "titration_concentration",
            "percent_ionization",
            "ph_from_h",
            "ph_from_poh",
            "h_from_ph",
            "poh_from_oh",
            "buffer_ph",
            "strong_acid_ph",
            "strong_base_ph",
            "weak_acid_ph",
            "weak_base_ph",
            "ka_kb",
            "titration_strong",
            "titration_weak",
            "buffer_addition",
            "polyprotic_ph",
        }
    ),
    "gases": frozenset(
        {
            "graham_ratio",
            "molar_mass_from_density",
            "gas_density",
            "dalton",
            "partial_pressure",
            "gas_over_water",
        }
    ),
    "thermochemistry": frozenset(
        {"reaction_heat", "gibbs", "calorimetry", "hess", "formation_enthalpy", "bond_enthalpy"}
    ),
    "equilibrium": frozenset(
        {
            "equilibrium_constant",
            "reaction_quotient",
            "ksp",
            "precipitation",
            "common_ion",
            "kp",
            "kc_kp",
            "ice_equilibrium",
        }
    ),
    "kinetics": frozenset(
        {
            "first_order_half_life",
            "first_order_concentration",
            "arrhenius",
            "zero_order",
            "second_order",
            "zero_order_half_life",
            "second_order_half_life",
            "rate_law",
            "arrhenius_two_point",
        }
    ),
    "electrochemistry": frozenset(
        {
            "electrolysis_time",
            "cell_gibbs",
            "nernst",
            "electrolysis_mass",
            "cell_potential",
            "galvanic_cell",
        }
    ),
    "nuclear": frozenset(
        {
            "nuclear_equation",
            "mass_defect",
        }
    ),
    "spectroscopy": frozenset(
        {
            "beer_lambert",
            "ir_ranges",
            "ir_peak",
            "nmr_ranges",
            "nmr_peak",
            "nmr_splitting",
            "molecular_ion",
        }
    ),
    "structure": frozenset({"electron_configuration", "oxidation_state", "vsepr", "formal_charge"}),
    "organic": frozenset(
        {
            "functional_groups",
            "stereochemistry",
            "isomers",
            "iupac_name",
            "named_reaction",
        }
    ),
    "inorganic": frozenset({"coordination_complex", "crystal_field"}),
    "analytical": frozenset(
        {
            "calibration",
            "gravimetric",
            "standard_addition",
            "standard_deviation",
            "standard_error",
            "percent_error",
            "relative_uncertainty",
            "chromatography_rf",
        }
    ),
    "biochemistry": frozenset({"michaelis_menten"}),
}
