from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Casual expressions"


def american_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-awesome",
            "Awesome and cool",
            [
                _w(
                    "awesome",
                    "very good",
                    "That concert was awesome.",
                    ipa="ˈɔsəm",
                    pos="adjective",
                    simple="very good",
                ),
                _w(
                    "cool",
                    "good or okay",
                    "That's cool with me.",
                    ipa="kul",
                    pos="adjective",
                    simple="good / okay",
                ),
                _w(
                    "sure",
                    "certainly; okay",
                    "Sure, I can help.",
                    ipa="ʃʊr",
                    pos="adverb",
                    simple="yes / okay",
                ),
                _w(
                    "pretty",
                    "fairly; to a fairly large degree",
                    "It's pretty good.",
                    ipa="ˈprɪti",
                    pos="adverb",
                    simple="fairly",
                ),
                _w(
                    "totally",
                    "completely; definitely",
                    "I totally agree.",
                    ipa="ˈtoʊtəli",
                    pos="adverb",
                    simple="completely",
                ),
                _w(
                    "seriously",
                    "genuinely; used for emphasis",
                    "Seriously, I'm not joking.",
                    ipa="ˈsɪriəsli",
                    pos="adverb",
                    simple="for real",
                ),
                _w(
                    "literally",
                    "exactly as stated; also used for emphasis",
                    "I literally just got here.",
                    ipa="ˈlɪtərəli",
                    pos="adverb",
                    simple="exactly / for emphasis",
                ),
                _w(
                    "yep",
                    "informal yes",
                    "Yep, I'm ready.",
                    example2="Yep, that works.",
                    ipa="jɛp",
                    pos="interjection",
                    simple="yes",
                ),
            ],
            domain=DOMAIN,
            sort_order=80,
        ),
        _deck(
            "en",
            "conv-dude",
            "Dude and chill",
            [
                _w(
                    "dude",
                    "informal way to address someone",
                    "Dude, look at this.",
                    ipa="dud",
                    pos="noun",
                    simple="informal address",
                ),
                _w(
                    "buddy",
                    "friend; informal address",
                    "Thanks, buddy.",
                    ipa="ˈbʌdi",
                    pos="noun",
                    simple="friend",
                ),
                _w(
                    "chill",
                    "relax; calm",
                    "Let's just chill tonight.",
                    ipa="tʃɪl",
                    pos="verb",
                    simple="relax",
                ),
                _w(
                    "awkward",
                    "socially uncomfortable",
                    "That silence was awkward.",
                    ipa="ˈɔkwərd",
                    pos="adjective",
                    simple="socially uncomfortable",
                ),
                _w(
                    "random",
                    "unexpected or unrelated",
                    "That's a random question.",
                    ipa="ˈrændəm",
                    pos="adjective",
                    simple="unexpected",
                ),
                _w(
                    "legit",
                    "genuine; really good",
                    "This place is legit.",
                    ipa="ləˈdʒɪt",
                    pos="adjective",
                    simple="real / really good",
                ),
                _w(
                    "solid",
                    "reliable; good",
                    "That's solid advice.",
                    ipa="ˈsɑlɪd",
                    pos="adjective",
                    simple="good / reliable",
                ),
                _w(
                    "whatever",
                    "anything; expression of indifference",
                    "Whatever, I don't mind.",
                    ipa="wʌtˈɛvər",
                    pos="pronoun",
                    simple="I don't care / anything",
                ),
            ],
            domain=DOMAIN,
            sort_order=81,
        ),
    ]
