from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Mouth and body sounds"


def body_sounds_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-snore-yawn",
            "Snore and yawn",
            [
                _w(
                    "snore",
                    "make a rough sound while sleeping",
                    "He snores loudly at night.",
                    ipa="snɔr",
                    pos="verb",
                    simple="make noise while sleeping",
                ),
                _w(
                    "burp",
                    "release gas from your stomach through your mouth",
                    "Don't burp at the table.",
                    ipa="bɜrp",
                    pos="verb",
                    simple="release gas through your mouth",
                ),
                _w(
                    "wheeze",
                    "breathe with a rough, whistling sound",
                    "He wheezed after climbing the stairs.",
                    ipa="wiz",
                    pos="verb",
                    simple="breathe with a whistling sound",
                ),
                _w(
                    "cough",
                    "force air out of your lungs suddenly",
                    "She coughed during the movie.",
                    ipa="kɔf",
                    pos="verb",
                    simple="force air from your lungs",
                ),
                _w(
                    "sneeze",
                    "suddenly blow air out through your nose or mouth",
                    "Cover your mouth when you sneeze.",
                    ipa="sniz",
                    pos="verb",
                    simple="sudden nose blow",
                ),
                _w(
                    "yawn",
                    "open your mouth wide when tired",
                    "I yawn when I'm bored.",
                    ipa="jɔn",
                    pos="verb",
                    simple="open your mouth when tired",
                ),
                _w(
                    "hiccup",
                    "make repeated sudden sounds from your throat",
                    "I get hiccups after soda.",
                    ipa="ˈhɪkʌp",
                    pos="verb",
                    simple="involuntary hic sound",
                ),
            ],
            domain=DOMAIN,
            sort_order=90,
        ),
        _deck(
            "en",
            "conv-sniff-sigh",
            "Sniff and sigh",
            [
                _w(
                    "sniff",
                    "breathe in through your nose, often to smell something",
                    "The dog sniffed the bag.",
                    ipa="snɪf",
                    pos="verb",
                    simple="breathe in through your nose",
                ),
                _w(
                    "snort",
                    "make a loud sound through your nose",
                    "He snorted at the joke.",
                    ipa="snɔrt",
                    pos="verb",
                    simple="loud sound through the nose",
                ),
                _w(
                    "sigh",
                    "breathe out deeply, often from tiredness or frustration",
                    "She sighed and sat down.",
                    ipa="saɪ",
                    pos="verb",
                    simple="breathe out deeply",
                ),
                _w(
                    "gasp",
                    "breathe in suddenly from shock or lack of air",
                    "The crowd gasped.",
                    ipa="ɡæsp",
                    pos="verb",
                    simple="suddenly breathe in",
                ),
                _w(
                    "pant",
                    "breathe quickly and heavily",
                    "He was panting after the run.",
                    ipa="pænt",
                    pos="verb",
                    simple="breathe hard and fast",
                ),
            ],
            domain=DOMAIN,
            sort_order=91,
        ),
        _deck(
            "en",
            "conv-whisper-yell",
            "Whisper and yell",
            [
                _w(
                    "mumble",
                    "speak quietly and unclearly",
                    "Don't mumble; I can't hear you.",
                    ipa="ˈmʌmbəl",
                    pos="verb",
                    simple="speak quietly and unclearly",
                ),
                _w(
                    "whisper",
                    "speak very quietly",
                    "She whispered the answer.",
                    ipa="ˈwɪspər",
                    pos="verb",
                    simple="speak very quietly",
                ),
                _w(
                    "groan",
                    "make a low sound from pain or annoyance",
                    "He groaned when he stood up.",
                    ipa="ɡroʊn",
                    pos="verb",
                    simple="low sound from pain or annoyance",
                ),
                _w(
                    "moan",
                    "make a long, low sound",
                    "The wind moaned through the trees.",
                    ipa="moʊn",
                    pos="verb",
                    simple="a long low sound",
                ),
                _w(
                    "scream",
                    "make a very loud, high sound",
                    "Don't scream in the house.",
                    ipa="skrim",
                    pos="verb",
                    simple="very loud high sound",
                ),
                _w(
                    "yell",
                    "shout loudly",
                    "He yelled for help.",
                    ipa="jɛl",
                    pos="verb",
                    simple="shout loudly",
                ),
                _w(
                    "whistle",
                    "make a high sound by blowing through your lips",
                    "She whistled a tune.",
                    ipa="ˈwɪsəl",
                    pos="verb",
                    simple="sound by blowing through your lips",
                ),
                _w(
                    "hum",
                    "make a musical sound with your mouth closed",
                    "He hummed while he cooked.",
                    ipa="hʌm",
                    pos="verb",
                    simple="sing with your mouth closed",
                ),
            ],
            domain=DOMAIN,
            sort_order=92,
        ),
    ]
