from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Communication"


def communication_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-ask-tell",
            "Ask and tell",
            [
                _w(
                    "ask",
                    "request information",
                    "Ask her what time it starts.",
                    ipa="æsk",
                    pos="verb",
                    simple="request information",
                ),
                _w(
                    "tell",
                    "give information",
                    "Tell me what happened.",
                    ipa="tɛl",
                    pos="verb",
                    simple="give information",
                ),
                _w(
                    "say",
                    "speak words",
                    "What did she say?",
                    ipa="seɪ",
                    pos="verb",
                    simple="speak words",
                ),
                _w(
                    "talk",
                    "have a conversation",
                    "We need to talk.",
                    ipa="tɔk",
                    pos="verb",
                    simple="have a conversation",
                ),
                _w(
                    "explain",
                    "make something understandable",
                    "Can you explain this again?",
                    ipa="ɪkˈspleɪn",
                    pos="verb",
                    simple="make it clear",
                ),
                _w(
                    "mention",
                    "briefly talk about something",
                    "She didn't mention the price.",
                    ipa="ˈmɛnʃən",
                    pos="verb",
                    simple="bring up briefly",
                ),
                _w(
                    "mean",
                    "intend or signify",
                    "What does this word mean?",
                    example2="I didn't mean to interrupt.",
                    ipa="min",
                    pos="verb",
                    simple="intend or signify",
                ),
                _w(
                    "listen",
                    "pay attention to sound",
                    "Listen to this song.",
                    example2="She listened carefully.",
                    ipa="ˈlɪsən",
                    pos="verb",
                    simple="pay attention to sound",
                ),
                _w(
                    "hear",
                    "notice sound with your ears",
                    "Did you hear that?",
                    example2="I can't hear you.",
                    ipa="hɪr",
                    pos="verb",
                    simple="notice a sound",
                ),
                _w(
                    "speak",
                    "say words out loud",
                    "Can you speak slower?",
                    example2="He spoke to the manager.",
                    ipa="spik",
                    pos="verb",
                    simple="say words out loud",
                ),
                _w(
                    "answer",
                    "say something back to a question",
                    "Please answer the phone.",
                    example2="She answered my email.",
                    ipa="ˈænsər",
                    pos="verb",
                    simple="respond to a question",
                ),
                _w(
                    "reply",
                    "respond to a message or comment",
                    "I'll reply later today.",
                    example2="He didn't reply.",
                    ipa="rɪˈplaɪ",
                    pos="verb",
                    simple="respond",
                ),
                _w(
                    "write",
                    "put words on paper or a screen",
                    "Write your name here.",
                    example2="She wrote a short note.",
                    ipa="raɪt",
                    pos="verb",
                    simple="put words down",
                ),
                _w(
                    "read",
                    "look at words and understand them",
                    "I read the message twice.",
                    example2="Read this out loud.",
                    ipa="rid",
                    pos="verb",
                    simple="look at words and understand",
                ),
                _w(
                    "call",
                    "phone someone or say their name",
                    "I'll call you tonight.",
                    example2="Call me when you arrive.",
                    ipa="kɔl",
                    pos="verb",
                    simple="phone someone",
                ),
                _w(
                    "discuss",
                    "talk about something with someone",
                    "Let's discuss the plan.",
                    example2="We discussed it after class.",
                    ipa="dɪˈskʌs",
                    pos="verb",
                    simple="talk something through",
                ),
            ],
            domain=DOMAIN,
            sort_order=40,
        ),
        _deck(
            "en",
            "conv-agree",
            "Agree and suggest",
            [
                _w(
                    "agree",
                    "have the same opinion",
                    "I agree with you.",
                    ipa="əˈɡri",
                    pos="verb",
                    simple="have the same opinion",
                ),
                _w(
                    "disagree",
                    "have a different opinion",
                    "I disagree, but I hear you.",
                    ipa="ˌdɪsəˈɡri",
                    pos="verb",
                    simple="have a different opinion",
                ),
                _w(
                    "suggest",
                    "give an idea",
                    "I suggest we leave early.",
                    ipa="səɡˈdʒɛst",
                    pos="verb",
                    simple="give an idea",
                ),
                _w(
                    "promise",
                    "say you will definitely do something",
                    "I promise I'll call.",
                    ipa="ˈprɑmɪs",
                    pos="verb",
                    simple="say you will do it",
                ),
            ],
            domain=DOMAIN,
            sort_order=41,
        ),
    ]
