from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Conversation words"


def conversation_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-actually",
            "Actually and maybe",
            [
                _w(
                    "actually",
                    "in fact",
                    "Actually, I already ate.",
                    ipa="ˈæktʃuəli",
                    pos="adverb",
                    simple="in fact",
                ),
                _w(
                    "probably",
                    "likely",
                    "I'll probably be late.",
                    ipa="ˈprɑbəbli",
                    pos="adverb",
                    simple="likely",
                ),
                _w(
                    "maybe",
                    "possibly",
                    "Maybe we can go tomorrow.",
                    ipa="ˈmeɪbi",
                    pos="adverb",
                    simple="possibly",
                ),
                _w(
                    "definitely",
                    "certainly",
                    "I'll definitely come.",
                    ipa="ˈdɛfənətli",
                    pos="adverb",
                    simple="for sure",
                ),
                _w(
                    "exactly",
                    "completely correct",
                    "That's exactly what I meant.",
                    ipa="ɪɡˈzæktli",
                    pos="adverb",
                    simple="completely correct",
                ),
                _w(
                    "basically",
                    "in simple terms",
                    "Basically, we wait and see.",
                    ipa="ˈbeɪsɪkli",
                    pos="adverb",
                    simple="in simple terms",
                ),
            ],
            domain=DOMAIN,
            sort_order=70,
        ),
        _deck(
            "en",
            "conv-usually",
            "Usually and still",
            [
                _w(
                    "especially",
                    "particularly",
                    "I like fruit, especially mangoes.",
                    ipa="ɪˈspɛʃəli",
                    pos="adverb",
                    simple="particularly",
                ),
                _w(
                    "usually",
                    "most of the time",
                    "I usually wake up at seven.",
                    ipa="ˈjuʒuəli",
                    pos="adverb",
                    simple="most of the time",
                ),
                _w(
                    "already",
                    "before now",
                    "I already sent it.",
                    ipa="ɔlˈrɛdi",
                    pos="adverb",
                    simple="before now",
                ),
                _w(
                    "still",
                    "continuing until now",
                    "Are you still there?",
                    ipa="stɪl",
                    pos="adverb",
                    simple="continuing until now",
                ),
                _w(
                    "yet",
                    "up to now",
                    "Have you eaten yet?",
                    ipa="jɛt",
                    pos="adverb",
                    simple="up to now",
                ),
                _w(
                    "though",
                    "however",
                    "It's late, though I'm not tired.",
                    ipa="ðoʊ",
                    pos="adverb",
                    simple="however",
                ),
                _w(
                    "instead",
                    "as an alternative",
                    "Let's walk instead.",
                    ipa="ɪnˈstɛd",
                    pos="adverb",
                    simple="as an alternative",
                ),
                _w(
                    "anyway",
                    "regardless; used to change the subject",
                    "Anyway, what did you do today?",
                    ipa="ˈɛniˌweɪ",
                    pos="adverb",
                    simple="anyway / changing the subject",
                ),
                _w(
                    "apparently",
                    "according to what you've heard or seen",
                    "Apparently the store is closed.",
                    ipa="əˈpɛrəntli",
                    pos="adverb",
                    simple="from what I heard",
                ),
            ],
            domain=DOMAIN,
            sort_order=71,
        ),
    ]
