from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Daily life"


def daily_life_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "daily-morning",
            "Morning",
            [
                _w("wake up", "to stop sleeping", "I wake up at 7."),
                _w("get up", "to leave bed", "Get up, it's late."),
                _w("shower", "to wash standing under water", "I shower every morning."),
                _w("brush", "to clean with a brush", "Brush your teeth."),
                _w("get dressed", "to put on clothes", "Get dressed quickly."),
                _w("breakfast", "first meal of the day", "Eat breakfast."),
                _w("coffee", "morning drink", "I need coffee."),
                _w("leave", "to go away from a place", "I leave at 8."),
                _w("commute", "daily trip to work or school", "A long commute."),
                _w("early", "before the usual time", "I woke up early."),
                _w("alarm", "clock that rings to wake you", "Set an alarm."),
                _w("tired", "needing rest", "I'm still tired."),
            ],
            domain=DOMAIN,
            sort_order=80,
        ),
        _deck(
            "en",
            "daily-work",
            "Work and school",
            [
                _w("work", "a job or the place you do it", "I go to work."),
                _w("school", "place children learn", "School starts at 8."),
                _w("office", "place people work at desks", "She's at the office."),
                _w("class", "a lesson with a teacher", "Math class."),
                _w("meeting", "people gathering to talk", "A meeting at 10."),
                _w("homework", "school work done at home", "Do your homework."),
                _w("boss", "person in charge at work", "Ask your boss."),
                _w("teacher", "person who teaches", "My teacher is kind."),
                _w("student", "person who studies", "A new student."),
                _w("break", "a short rest", "A lunch break."),
                _w("busy", "having a lot to do", "I'm busy today."),
                _w("finish", "to complete something", "I finish at 5."),
            ],
            domain=DOMAIN,
            sort_order=81,
        ),
        _deck(
            "en",
            "daily-shopping",
            "Shopping",
            [
                _w("shop", "to buy things", "I shop on Saturday."),
                _w("store", "place that sells things", "A grocery store."),
                _w("buy", "to pay money for something", "Buy milk."),
                _w("sell", "to give something for money", "They sell bread."),
                _w("price", "how much something costs", "What's the price?"),
                _w("cheap", "costing little", "A cheap shirt."),
                _w("expensive", "costing a lot", "Too expensive."),
                _w("cash", "money in coins or bills", "I pay cash."),
                _w("card", "plastic used to pay", "Pay by card."),
                _w("bag", "container for carrying things", "A shopping bag."),
                _w("receipt", "proof of what you paid", "Keep the receipt."),
                _w("change", "money you get back", "Here's your change."),
            ],
            domain=DOMAIN,
            sort_order=82,
        ),
        _deck(
            "en",
            "daily-free-time",
            "Free time",
            [
                _w("free time", "time when you are not working", "In my free time I read."),
                _w("rest", "to relax and stop working", "Rest after work."),
                _w("read", "to look at written words", "I read at night."),
                _w("watch", "to look at for a while", "Watch a film."),
                _w("listen", "to hear with attention", "Listen to music."),
                _w("walk", "to go on foot for pleasure", "A walk in the park."),
                _w("exercise", "activity to stay fit", "I exercise on Sunday."),
                _w("hobby", "activity you do for fun", "Cooking is my hobby."),
                _w("friend", "someone you like to spend time with", "Call a friend."),
                _w("weekend", "Saturday and Sunday", "See you this weekend."),
                _w("movie", "a film", "A funny movie."),
                _w("sleep", "to rest with eyes closed", "I need to sleep."),
            ],
            domain=DOMAIN,
            sort_order=83,
        ),
    ]
