from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Describing"


def describing_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-good-bad",
            "Good and bad",
            [
                _w(
                    "good",
                    "high quality or pleasant",
                    "That's a good idea.",
                    ipa="ɡʊd",
                    pos="adjective",
                    simple="nice or well done",
                ),
                _w(
                    "bad",
                    "low quality or unpleasant",
                    "That was a bad movie.",
                    ipa="bæd",
                    pos="adjective",
                    simple="not good",
                ),
                _w(
                    "easy",
                    "not difficult",
                    "This homework is easy.",
                    ipa="ˈizi",
                    pos="adjective",
                    simple="not hard",
                ),
                _w(
                    "hard",
                    "difficult",
                    "The test was hard.",
                    ipa="hɑrd",
                    pos="adjective",
                    simple="difficult",
                ),
                _w(
                    "important",
                    "having great meaning or value",
                    "This is an important meeting.",
                    ipa="ɪmˈpɔrtənt",
                    pos="adjective",
                    simple="matters a lot",
                ),
                _w(
                    "different",
                    "not the same",
                    "We have different opinions.",
                    ipa="ˈdɪfərənt",
                    pos="adjective",
                    simple="not the same",
                ),
                _w(
                    "similar",
                    "almost the same",
                    "Our names are similar.",
                    ipa="ˈsɪmələr",
                    pos="adjective",
                    simple="almost the same",
                ),
                _w(
                    "nice",
                    "pleasant or kind",
                    "That's a nice jacket.",
                    example2="She was nice to me.",
                    ipa="naɪs",
                    pos="adjective",
                    simple="pleasant or kind",
                ),
            ],
            domain=DOMAIN,
            sort_order=60,
        ),
        _deck(
            "en",
            "conv-ready-busy",
            "Ready and busy",
            [
                _w(
                    "weird",
                    "strange or unusual",
                    "That's a weird noise.",
                    ipa="wɪrd",
                    pos="adjective",
                    simple="strange",
                ),
                _w(
                    "serious",
                    "not joking; important",
                    "I'm being serious.",
                    ipa="ˈsɪriəs",
                    pos="adjective",
                    simple="not a joke",
                ),
                _w(
                    "normal",
                    "usual or expected",
                    "That's a normal question.",
                    ipa="ˈnɔrməl",
                    pos="adjective",
                    simple="usual",
                ),
                _w(
                    "possible",
                    "able to happen or be done",
                    "Is it possible to finish today?",
                    ipa="ˈpɑsəbəl",
                    pos="adjective",
                    simple="can happen",
                ),
                _w(
                    "available",
                    "able to be used or free to talk",
                    "Are you available at 3?",
                    ipa="əˈveɪləbəl",
                    pos="adjective",
                    simple="free or ready to use",
                ),
                _w(
                    "ready",
                    "prepared to start",
                    "I'm ready when you are.",
                    ipa="ˈrɛdi",
                    pos="adjective",
                    simple="prepared",
                ),
                _w(
                    "busy",
                    "having a lot to do",
                    "I'm busy this afternoon.",
                    ipa="ˈbɪzi",
                    pos="adjective",
                    simple="having a lot to do",
                ),
                _w(
                    "careful",
                    "paying attention to avoid mistakes or danger",
                    "Be careful on the ice.",
                    ipa="ˈkɛrfəl",
                    pos="adjective",
                    simple="pay attention",
                ),
            ],
            domain=DOMAIN,
            sort_order=61,
        ),
    ]
