from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Everyday actions"


def everyday_actions_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-get-give",
            "Get and give",
            [
                _w(
                    "get",
                    "receive or obtain",
                    "Did you get my message?",
                    ipa="ɡɛt",
                    pos="verb",
                    simple="receive or obtain",
                ),
                _w(
                    "give",
                    "hand something to someone",
                    "Give her the keys.",
                    ipa="ɡɪv",
                    pos="verb",
                    simple="hand something to someone",
                ),
                _w(
                    "take",
                    "carry or move something",
                    "Take an umbrella.",
                    ipa="teɪk",
                    pos="verb",
                    simple="carry or move something",
                ),
                _w(
                    "bring",
                    "take something toward someone or a place",
                    "Bring your laptop to class.",
                    ipa="brɪŋ",
                    pos="verb",
                    simple="take something here",
                ),
                _w(
                    "leave",
                    "go away",
                    "I leave at eight.",
                    ipa="liv",
                    pos="verb",
                    simple="go away",
                ),
                _w(
                    "stay",
                    "remain",
                    "Stay here until I come back.",
                    ipa="steɪ",
                    pos="verb",
                    simple="remain",
                ),
            ],
            domain=DOMAIN,
            sort_order=30,
        ),
        _deck(
            "en",
            "conv-put-keep",
            "Put and keep",
            [
                _w(
                    "keep",
                    "continue having",
                    "You can keep the change.",
                    ipa="kip",
                    pos="verb",
                    simple="continue having",
                ),
                _w(
                    "put",
                    "place something somewhere",
                    "Put the bag on the chair.",
                    ipa="pʊt",
                    pos="verb",
                    simple="place something somewhere",
                ),
                _w(
                    "pick",
                    "choose or take",
                    "Pick a color.",
                    ipa="pɪk",
                    pos="verb",
                    simple="choose or take",
                ),
                _w(
                    "grab",
                    "take quickly",
                    "Grab your coat.",
                    ipa="ɡræb",
                    pos="verb",
                    simple="take quickly",
                ),
                _w(
                    "hold",
                    "keep something in your hand",
                    "Hold my bag, please.",
                    ipa="hoʊld",
                    pos="verb",
                    simple="keep in your hand",
                ),
                _w(
                    "wait",
                    "stay until something happens",
                    "Wait for me outside.",
                    example2="Can you wait a minute?",
                    ipa="weɪt",
                    pos="verb",
                    simple="stay until something happens",
                ),
                _w(
                    "find",
                    "discover or locate something",
                    "I can't find my keys.",
                    example2="Did you find a seat?",
                    ipa="faɪnd",
                    pos="verb",
                    simple="locate something",
                ),
                _w(
                    "lose",
                    "stop having something",
                    "Don't lose the ticket.",
                    example2="I always lose my phone.",
                    ipa="luz",
                    pos="verb",
                    simple="stop having something",
                ),
                _w(
                    "open",
                    "move something so it is not closed",
                    "Open the window, please.",
                    example2="She opened the door.",
                    ipa="ˈoʊpən",
                    pos="verb",
                    simple="make it not closed",
                ),
                _w(
                    "close",
                    "move something so it is shut",
                    "Close the door behind you.",
                    example2="He closed his laptop.",
                    ipa="kloʊz",
                    pos="verb",
                    simple="shut something",
                ),
                _w(
                    "start",
                    "begin something",
                    "Let's start the meeting.",
                    example2="The movie starts at eight.",
                    ipa="stɑrt",
                    pos="verb",
                    simple="begin",
                ),
                _w(
                    "stop",
                    "end an action or motion",
                    "Stop at the light.",
                    example2="Can you stop talking for a second?",
                    ipa="stɑp",
                    pos="verb",
                    simple="end or pause",
                ),
                _w(
                    "help",
                    "make it easier for someone",
                    "Can you help me with this?",
                    example2="She helped him move.",
                    ipa="hɛlp",
                    pos="verb",
                    simple="make it easier for someone",
                ),
                _w(
                    "use",
                    "do something with a tool or object",
                    "Use a pen, not a pencil.",
                    example2="I used your charger.",
                    ipa="juz",
                    pos="verb",
                    simple="do something with it",
                ),
            ],
            domain=DOMAIN,
            sort_order=31,
        ),
    ]
