from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Face and eyes"


def face_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-blink-stare",
            "Blink and stare",
            [
                _w(
                    "blink",
                    "quickly close and open your eyes",
                    "Don't blink or you'll miss it.",
                    ipa="blɪŋk",
                    pos="verb",
                    simple="close and open your eyes quickly",
                ),
                _w(
                    "wink",
                    "close one eye briefly",
                    "She winked at me.",
                    ipa="wɪŋk",
                    pos="verb",
                    simple="close one eye briefly",
                ),
                _w(
                    "stare",
                    "look at something for a long time",
                    "Don't stare at people.",
                    ipa="stɛr",
                    pos="verb",
                    simple="look for a long time",
                ),
                _w(
                    "glance",
                    "look quickly",
                    "He glanced at his phone.",
                    ipa="ɡlæns",
                    pos="verb",
                    simple="look quickly",
                ),
                _w(
                    "peek",
                    "look secretly or briefly",
                    "Don't peek at the gifts.",
                    ipa="pik",
                    pos="verb",
                    simple="look secretly",
                ),
                _w(
                    "squint",
                    "partly close your eyes to see better",
                    "She squinted in the sun.",
                    example2="He squinted at the tiny print.",
                    ipa="skwɪnt",
                    pos="verb",
                    simple="partly close your eyes",
                ),
                _w(
                    "laugh",
                    "make a happy sound when something is funny",
                    "We laughed at the joke.",
                    example2="Don't laugh — I'm serious.",
                    ipa="læf",
                    pos="verb",
                    simple="make a happy sound",
                ),
                _w(
                    "cry",
                    "let tears fall when you are sad or hurt",
                    "The movie made her cry.",
                    example2="It's okay to cry.",
                    ipa="kraɪ",
                    pos="verb",
                    simple="let tears fall",
                ),
                _w(
                    "wince",
                    "briefly tighten your face from pain or discomfort",
                    "He winced when he stood up.",
                    example2="I winced at the loud noise.",
                    ipa="wɪns",
                    pos="verb",
                    simple="flinch from pain",
                ),
            ],
            domain=DOMAIN,
            sort_order=110,
        ),
        _deck(
            "en",
            "conv-smile-frown",
            "Smile and frown",
            [
                _w(
                    "frown",
                    "make an unhappy or concerned expression",
                    "Why are you frowning?",
                    ipa="fraʊn",
                    pos="verb",
                    simple="look unhappy or worried",
                ),
                _w(
                    "smile",
                    "make a happy expression",
                    "She smiled at the joke.",
                    ipa="smaɪl",
                    pos="verb",
                    simple="look happy",
                ),
                _w(
                    "grin",
                    "smile widely",
                    "He grinned when he won.",
                    ipa="ɡrɪn",
                    pos="verb",
                    simple="smile widely",
                ),
                _w(
                    "smirk",
                    "smile in a smug or teasing way",
                    "Don't smirk at me.",
                    ipa="smɜrk",
                    pos="verb",
                    simple="a smug smile",
                ),
                _w(
                    "glare",
                    "look angrily at someone",
                    "She glared at the driver.",
                    ipa="ɡlɛr",
                    pos="verb",
                    simple="look angrily",
                ),
                _w(
                    "nod",
                    "move your head up and down",
                    "He nodded yes.",
                    ipa="nɑd",
                    pos="verb",
                    simple="move your head up and down",
                ),
                _w(
                    "shrug",
                    "raise your shoulders, often to show you don't know",
                    "She shrugged and walked away.",
                    ipa="ʃrʌɡ",
                    pos="verb",
                    simple="raise your shoulders",
                ),
            ],
            domain=DOMAIN,
            sort_order=111,
        ),
    ]
