from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Family"


def family_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "family-immediate",
            "Immediate family",
            [
                _w("parent", "a mother or father", "Each parent signed."),
                _w("mother", "female parent", "My mother called."),
                _w("father", "male parent", "My father cooks."),
                _w("mom", "informal mother", "Mom is home."),
                _w("dad", "informal father", "Dad is reading."),
                _w("child", "a son or daughter", "Their child is six."),
                _w("son", "male child", "Their son is six."),
                _w("daughter", "female child", "Their daughter sings."),
                _w("sibling", "a brother or sister", "I have one sibling."),
                _w("brother", "male sibling", "My brother runs."),
                _w("sister", "female sibling", "My sister reads."),
                _w("parents", "mother and father", "My parents live nearby."),
            ],
            domain=DOMAIN,
            sort_order=20,
        ),
        _deck(
            "en",
            "family-extended",
            "Extended family",
            [
                _w("grandmother", "parent's mother", "Grandmother tells stories."),
                _w("grandfather", "parent's father", "Grandfather smiles."),
                _w("granddaughter", "child's daughter", "Her granddaughter draws."),
                _w("grandson", "child's son", "Her grandson plays."),
                _w("aunt", "parent's sister", "My aunt calls."),
                _w("uncle", "parent's brother", "My uncle visits."),
                _w("niece", "sibling's daughter", "My niece visits."),
                _w("nephew", "sibling's son", "My nephew laughs."),
                _w("cousin", "uncle or aunt's child", "My cousin studies."),
                _w("great-grandmother", "grandparent's mother", "My great-grandmother is 96."),
                _w("great-grandfather", "grandparent's father", "My great-grandfather farmed."),
                _w("great-aunt", "grandparent's sister", "My great-aunt writes."),
                _w("great-uncle", "grandparent's brother", "My great-uncle travels."),
            ],
            domain=DOMAIN,
            sort_order=21,
        ),
        _deck(
            "en",
            "family-marriage",
            "Marriage and partnerships",
            [
                _w("husband", "male spouse", "Her husband cooks."),
                _w("wife", "female spouse", "His wife works."),
                _w("spouse", "husband or wife", "List your spouse."),
                _w("partner", "person you share life with", "My partner and I moved."),
                _w("fiancé", "man engaged to be married", "Her fiancé arrived."),
                _w("fiancée", "woman engaged to be married", "His fiancée smiled."),
                _w("bride", "woman getting married", "The bride entered."),
                _w("groom", "man getting married", "The groom waited."),
                _w("marriage", "legal union of partners", "Their marriage is happy."),
                _w("wedding", "marriage ceremony", "The wedding is in June."),
                _w("divorce", "legal end of a marriage", "They got a divorce."),
                _w("separation", "living apart while married", "They chose a separation."),
                _w("engagement", "agreement to marry", "They announced their engagement."),
            ],
            domain=DOMAIN,
            sort_order=22,
        ),
        _deck(
            "en",
            "family-relationships",
            "Family relationships",
            [
                _w("relative", "a family member", "A relative visited."),
                _w("ancestor", "a person you descend from", "Our ancestors sailed here."),
                _w("descendant", "a person who comes from you", "She is a descendant of poets."),
                _w(
                    "generation",
                    "people born around the same time",
                    "Three generations live here.",
                ),
                _w("in-law", "relative by marriage", "My in-laws are kind."),
                _w("father-in-law", "spouse's father", "My father-in-law arrived."),
                _w("mother-in-law", "spouse's mother", "My mother-in-law helps."),
                _w("blood relative", "related by birth", "He is a blood relative."),
                _w("close relative", "a near family member", "Only close relatives came."),
                _w("distant relative", "a far family member", "A distant relative wrote."),
                _w("kinship", "family relationship", "Kinship matters here."),
                _w("family tree", "chart of relatives", "We drew a family tree."),
            ],
            domain=DOMAIN,
            sort_order=23,
        ),
        _deck(
            "en",
            "family-parenthood",
            "Parenthood",
            [
                _w("parenting", "raising children", "Parenting takes patience."),
                _w("raise", "to bring up a child", "They raise two kids."),
                _w("upbringing", "how a child is raised", "She had a kind upbringing."),
                _w("discipline", "training in behavior", "Fair discipline helps."),
                _w("nurture", "to care for and help grow", "They nurture her talent."),
                _w("adopt", "to take as your child legally", "They want to adopt."),
                _w("adoption", "legal process of adopting", "The adoption went through."),
                _w("foster", "to care for a child temporarily", "They foster a teen."),
                _w("guardian", "adult legally responsible for a child", "Her guardian signed."),
                _w("custody", "legal care of a child", "They share custody."),
                _w("take care of", "to look after someone", "I take care of my sister."),
                _w("protect", "to keep safe", "Parents protect their kids."),
            ],
            domain=DOMAIN,
            sort_order=24,
        ),
        _deck(
            "en",
            "family-birth",
            "Birth and childhood",
            [
                _w("pregnancy", "time before a baby is born", "The pregnancy is healthy."),
                _w("pregnant", "carrying a baby", "She is pregnant."),
                _w("birth", "being born", "The birth was at home."),
                _w("newborn", "a baby just born", "The newborn sleeps a lot."),
                _w("baby", "very young child", "The baby sleeps."),
                _w("infant", "a child in the first year", "The infant cried."),
                _w("toddler", "a child just learning to walk", "The toddler ran."),
                _w("childhood", "the time of being a child", "I remember my childhood."),
                _w("adolescence", "the teen years", "Adolescence can be hard."),
                _w("teenager", "a person aged about 13-19", "The teenager studies."),
                _w("grow up", "to become an adult", "I grew up here."),
                _w("be born", "to come into the world", "She was born in May."),
                _w("give birth", "to have a baby", "She gave birth at dawn."),
            ],
            domain=DOMAIN,
            sort_order=25,
        ),
        _deck(
            "en",
            "family-conflict",
            "Family conflict",
            [
                _w("argue", "to disagree angrily", "They argue about chores."),
                _w("disagree", "to have a different opinion", "We disagree sometimes."),
                _w("fight", "a serious argument", "The fight ended quickly."),
                _w("conflict", "a clash of needs or views", "Family conflict is normal."),
                _w("tension", "strained feeling", "There was tension at dinner."),
                _w("resentment", "bitter leftover anger", "Resentment built up."),
                _w("jealousy", "wanting what another has", "Jealousy hurt them."),
                _w("betrayal", "breaking trust", "The betrayal shocked her."),
                _w("forgive", "to stop blaming", "I forgive you."),
                _w("apologize", "to say you are sorry", "Please apologize."),
                _w("reconcile", "to become friendly again", "They reconciled."),
                _w("fall out", "to stop being friendly", "They fell out last year."),
                _w("make up", "to become friends again", "They made up."),
                _w("get along", "to have a good relationship", "We get along well."),
            ],
            domain=DOMAIN,
            sort_order=26,
        ),
        _deck(
            "en",
            "family-affection",
            "Family affection",
            [
                _w("love", "deep care for someone", "I love my family."),
                _w("care", "kind attention", "She shows care."),
                _w("trust", "belief someone is reliable", "Trust takes time."),
                _w("respect", "regard for someone's worth", "Respect your elders."),
                _w("affection", "warm fondness", "He shows affection."),
                _w("closeness", "feeling emotionally near", "They have closeness."),
                _w("bond", "a strong connection", "A family bond."),
                _w("connection", "a feeling of being linked", "We felt a connection."),
                _w("hug", "to hold someone in your arms", "Give me a hug."),
                _w("kiss", "to touch with the lips", "A kiss on the cheek."),
                _w("comfort", "to soothe someone sad", "I comforted her."),
                _w("encourage", "to give support and hope", "They encourage me."),
            ],
            domain=DOMAIN,
            sort_order=27,
        ),
        _deck(
            "en",
            "family-responsibilities",
            "Family responsibilities",
            [
                _w("provide", "to supply what is needed", "They provide food."),
                _w("provide for", "to support someone with money", "He provides for us."),
                _w("care for", "to look after someone", "We care for grandma."),
                _w("depend on", "to need someone", "Kids depend on parents."),
                _w("responsibility", "a duty you must do", "It is my responsibility."),
                _w("obligation", "something you must do", "A legal obligation."),
                _w("household", "the people who live together", "The whole household ate."),
                _w("childcare", "care of children", "They need childcare."),
                _w("financial support", "money given to help", "She sends financial support."),
                _w("chore", "a regular home task", "Dishes are my chore."),
                _w("allowance", "money given regularly", "A weekly allowance."),
                _w("look after", "to take care of", "I look after the kids."),
            ],
            domain=DOMAIN,
            sort_order=28,
        ),
        _deck(
            "en",
            "family-structure",
            "Family structure",
            [
                _w("single-parent family", "family with one parent", "A single-parent family."),
                _w("nuclear family", "parents and their children", "A nuclear family."),
                _w("blended family", "family joined after remarriage", "A blended family."),
                _w("stepfamily", "family with a step-parent", "They are a stepfamily."),
                _w("stepfather", "mother's new husband", "My stepfather coaches."),
                _w("stepmother", "father's new wife", "My stepmother cooks."),
                _w("stepson", "spouse's son from before", "Her stepson is ten."),
                _w("stepdaughter", "spouse's daughter from before", "His stepdaughter draws."),
                _w("half-brother", "brother who shares one parent", "My half-brother visited."),
                _w("half-sister", "sister who shares one parent", "My half-sister called."),
                _w("adopted child", "child joined by adoption", "Their adopted child is five."),
                _w("only child", "child with no siblings", "I am an only child."),
            ],
            domain=DOMAIN,
            sort_order=29,
        ),
        _deck(
            "en",
            "family-death",
            "Death and family",
            [
                _w("death", "the end of life", "They mourned her death."),
                _w("die", "to stop living", "He died last year."),
                _w("deceased", "no longer living", "The deceased left a note."),
                _w("funeral", "ceremony after a death", "The funeral is Friday."),
                _w("burial", "placing a body in the ground", "The burial was quiet."),
                _w("grief", "deep sadness after loss", "Grief comes in waves."),
                _w("mourn", "to show grief", "They mourn together."),
                _w("widow", "woman whose spouse has died", "The widow spoke."),
                _w("widower", "man whose spouse has died", "The widower moved."),
                _w("memorial", "event to remember someone", "A memorial on Sunday."),
                _w("inherit", "to receive after a death", "She will inherit the house."),
                _w("inheritance", "what is left to someone", "A small inheritance."),
                _w("will", "document about property after death", "He wrote a will."),
                _w("estate", "property left after death", "The estate was divided."),
            ],
            domain=DOMAIN,
            sort_order=30,
        ),
        _deck(
            "en",
            "family-expressions",
            "Family expressions",
            [
                _w("get along with", "to have a good relationship with", "I get along with her."),
                _w("take after", "to resemble a relative", "She takes after her mom."),
                _w("bring up", "to raise a child", "They brought us up here."),
                _w("settle down", "to start a stable life", "They want to settle down."),
                _w("start a family", "to begin having children", "They started a family."),
                _w("have children", "to become a parent", "They have children."),
                _w("get married", "to marry someone", "They got married in May."),
                _w("get divorced", "to end a marriage legally", "They got divorced."),
                _w("be related to", "to share family ties with", "I am related to him."),
                _w("be close to", "to feel emotionally near", "I am close to my sister."),
                _w("fall out with", "to quarrel and stop being friendly", "I fell out with him."),
                _w("make up with", "to become friendly again with", "I made up with her."),
            ],
            domain=DOMAIN,
            sort_order=31,
        ),
    ]
