from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Feelings"


def feelings_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-feelings",
            "Feelings",
            [
                _w(
                    "happy",
                    "feeling good",
                    "She looks happy today.",
                    ipa="ˈhæpi",
                    pos="adjective",
                    simple="feeling good",
                ),
                _w(
                    "sad",
                    "feeling unhappy",
                    "He felt sad after the news.",
                    ipa="sæd",
                    pos="adjective",
                    simple="not happy",
                ),
                _w(
                    "angry",
                    "feeling mad",
                    "Don't be angry with me.",
                    ipa="ˈæŋɡri",
                    pos="adjective",
                    simple="mad",
                ),
                _w(
                    "tired",
                    "needing rest",
                    "I'm too tired to go out.",
                    ipa="ˈtaɪərd",
                    pos="adjective",
                    simple="need rest",
                ),
                _w(
                    "worried",
                    "thinking something bad may happen",
                    "She's worried about the test.",
                    ipa="ˈwɜrid",
                    pos="adjective",
                    simple="thinking something bad may happen",
                ),
                _w(
                    "excited",
                    "very happy and interested",
                    "The kids are excited about the trip.",
                    ipa="ɪkˈsaɪtɪd",
                    pos="adjective",
                    simple="very happy and interested",
                ),
                _w(
                    "annoyed",
                    "slightly angry",
                    "I'm annoyed that the bus is late.",
                    ipa="əˈnɔɪd",
                    pos="adjective",
                    simple="a little angry",
                ),
                _w(
                    "confused",
                    "not understanding",
                    "I'm confused by these instructions.",
                    example2="Wait, now I'm confused.",
                    ipa="kənˈfjuzd",
                    pos="adjective",
                    simple="don't understand",
                ),
                _w(
                    "scared",
                    "afraid that something bad will happen",
                    "I'm scared of the dark.",
                    example2="Don't be scared — I'm here.",
                    ipa="skɛrd",
                    pos="adjective",
                    simple="afraid",
                ),
                _w(
                    "lonely",
                    "unhappy because you are alone",
                    "He felt lonely in the new city.",
                    example2="Call me if you get lonely.",
                    ipa="ˈloʊnli",
                    pos="adjective",
                    simple="sad and alone",
                ),
                _w(
                    "proud",
                    "pleased with yourself or someone you care about",
                    "I'm proud of you.",
                    example2="She was proud of her work.",
                    ipa="praʊd",
                    pos="adjective",
                    simple="pleased with what you did",
                ),
                _w(
                    "bored",
                    "not interested in what is happening",
                    "I'm bored at home.",
                    example2="The class made him bored.",
                    ipa="bɔrd",
                    pos="adjective",
                    simple="not interested",
                ),
                _w(
                    "nervous",
                    "worried about what will happen",
                    "She's nervous about the interview.",
                    example2="I get nervous before I speak.",
                    ipa="ˈnɜrvəs",
                    pos="adjective",
                    simple="worried before something",
                ),
                _w(
                    "calm",
                    "not angry or upset",
                    "Stay calm and breathe.",
                    example2="His voice was calm.",
                    ipa="kɑm",
                    pos="adjective",
                    simple="peaceful, not upset",
                ),
                _w(
                    "surprised",
                    "feeling something unexpected happened",
                    "I was surprised to see you.",
                    example2="She looked surprised.",
                    ipa="sərˈpraɪzd",
                    pos="adjective",
                    simple="not expecting that",
                ),
                _w(
                    "embarrassed",
                    "feeling awkward because of something you did",
                    "I felt embarrassed when I forgot her name.",
                    example2="Don't be embarrassed to ask.",
                    ipa="ɪmˈbɛrəst",
                    pos="adjective",
                    simple="awkward about yourself",
                ),
                _w(
                    "disappointed",
                    "sad because something was worse than you hoped",
                    "We were disappointed by the news.",
                    example2="I'm disappointed you didn't come.",
                    ipa="ˌdɪsəˈpɔɪntɪd",
                    pos="adjective",
                    simple="sad it wasn't what you hoped",
                ),
                _w(
                    "grateful",
                    "thankful for what someone did",
                    "I'm grateful for your help.",
                    example2="She was grateful they waited.",
                    ipa="ˈɡreɪtfəl",
                    pos="adjective",
                    simple="thankful",
                ),
                _w(
                    "upset",
                    "unhappy or worried about something",
                    "He's upset about the mistake.",
                    example2="Don't get upset — we can fix it.",
                    ipa="ʌpˈsɛt",
                    pos="adjective",
                    simple="unhappy or worried",
                ),
                _w(
                    "jealous",
                    "unhappy because someone else has what you want",
                    "Don't be jealous of her success.",
                    example2="He felt jealous of his brother.",
                    ipa="ˈdʒɛləs",
                    pos="adjective",
                    simple="wanting what someone else has",
                ),
            ],
            domain=DOMAIN,
            sort_order=20,
        ),
    ]
