from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Food"


def food_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "food-drinks",
            "Drinks",
            [
                _w("water", "a drink with no flavor", "I drink water."),
                _w("coffee", "a hot drink from beans", "Black coffee."),
                _w("tea", "a hot drink from leaves", "Green tea."),
                _w("milk", "white drink from cows", "A glass of milk."),
                _w("juice", "drink from fruit", "Orange juice."),
                _w("soda", "sweet fizzy drink", "A can of soda."),
                _w("wine", "alcoholic drink from grapes", "A glass of wine."),
                _w("beer", "alcoholic drink from grain", "A cold beer."),
                _w("thirsty", "needing a drink", "I am thirsty."),
                _w("sip", "to drink a little", "She sipped tea."),
                _w("bottle", "container for liquid", "A bottle of water."),
                _w("cup", "small drinking bowl", "A cup of coffee."),
            ],
            domain=DOMAIN,
            sort_order=40,
        ),
        _deck(
            "en",
            "food-meals",
            "Meals",
            [
                _w("breakfast", "first meal of the day", "I eat breakfast."),
                _w("lunch", "midday meal", "Lunch is at noon."),
                _w("dinner", "evening meal", "Dinner is ready."),
                _w("snack", "small food between meals", "A fruit snack."),
                _w("bread", "baked food from flour", "Fresh bread."),
                _w("rice", "cooked grain", "A bowl of rice."),
                _w("egg", "food from a hen", "Boiled eggs."),
                _w("cheese", "food made from milk", "Cheese on bread."),
                _w("soup", "hot liquid food", "Tomato soup."),
                _w("sandwich", "food between bread", "A cheese sandwich."),
                _w("hungry", "needing food", "I am hungry."),
                _w("meal", "food eaten at one time", "A simple meal."),
            ],
            domain=DOMAIN,
            sort_order=41,
        ),
        _deck(
            "en",
            "food-produce",
            "Fruit and vegetables",
            [
                _w("apple", "a round fruit", "A red apple."),
                _w("banana", "a long yellow fruit", "I eat a banana."),
                _w("orange", "a citrus fruit", "Peel the orange."),
                _w("grape", "small fruit in bunches", "Sweet grapes."),
                _w("tomato", "red fruit used as a vegetable", "Slice the tomato."),
                _w("potato", "starchy root vegetable", "Boil the potatoes."),
                _w("onion", "strong-tasting bulb", "Chop an onion."),
                _w("carrot", "orange root vegetable", "A raw carrot."),
                _w("lettuce", "leafy salad plant", "Wash the lettuce."),
                _w("bean", "seed eaten as food", "Black beans."),
                _w("fruit", "sweet plant food", "Eat more fruit."),
                _w("vegetable", "plant food, often savory", "Steam the vegetables."),
            ],
            domain=DOMAIN,
            sort_order=42,
        ),
        _deck(
            "en",
            "food-cooking",
            "Cooking",
            [
                _w("cook", "to prepare food with heat", "I cook dinner."),
                _w("bake", "to cook in an oven", "Bake the bread."),
                _w("boil", "to heat until bubbling", "Boil the water."),
                _w("fry", "to cook in hot oil", "Fry the eggs."),
                _w("cut", "to divide with a knife", "Cut the onion."),
                _w("mix", "to stir together", "Mix the sauce."),
                _w("recipe", "steps for making a dish", "Follow the recipe."),
                _w("ingredient", "one part of a recipe", "List the ingredients."),
                _w("salt", "white seasoning", "Add salt."),
                _w("pepper", "spicy seasoning", "Black pepper."),
                _w("oil", "liquid fat for cooking", "Olive oil."),
                _w("taste", "flavor in the mouth", "Taste the soup."),
            ],
            domain=DOMAIN,
            sort_order=43,
        ),
        _deck(
            "en",
            "food-restaurant",
            "Restaurant",
            [
                _w("restaurant", "place that serves meals", "A small restaurant."),
                _w("menu", "list of dishes", "Look at the menu."),
                _w("waiter", "person who serves food", "The waiter smiled."),
                _w("order", "to ask for food", "I'd like to order."),
                _w("bill", "amount you must pay", "Can I have the bill?"),
                _w("tip", "extra money for service", "Leave a tip."),
                _w("table", "place to sit and eat", "A table for two."),
                _w("reservation", "a booked table", "We have a reservation."),
                _w("delicious", "very good to eat", "This is delicious."),
                _w("spicy", "hot with spice", "The sauce is spicy."),
                _w("vegetarian", "person who does not eat meat", "A vegetarian dish."),
                _w("to go", "food taken away", "Coffee to go."),
            ],
            domain=DOMAIN,
            sort_order=44,
        ),
    ]
