from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Greetings"


def greetings_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "greetings-hello",
            "Hello and goodbye",
            [
                _w(
                    "hello",
                    "a greeting when you meet someone",
                    "Hello, how are you?",
                    ipa="həˈloʊ",
                    pos="interjection",
                    simple="hi",
                ),
                _w(
                    "hi",
                    "an informal hello",
                    "Hi there.",
                    ipa="haɪ",
                    pos="interjection",
                    simple="a casual hello",
                ),
                _w(
                    "hey",
                    "a very casual greeting",
                    "Hey, come in.",
                    ipa="heɪ",
                    pos="interjection",
                    simple="a casual hello",
                ),
                _w(
                    "goodbye",
                    "said when you leave",
                    "Goodbye, see you tomorrow.",
                    ipa="ɡʊdˈbaɪ",
                    pos="interjection",
                    simple="bye",
                ),
                _w(
                    "bye",
                    "an informal goodbye",
                    "Bye for now.",
                    ipa="baɪ",
                    pos="interjection",
                    simple="a short goodbye",
                ),
                _w(
                    "see you later",
                    "said when leaving for a while",
                    "See you later.",
                    ipa="si ju ˈleɪtər",
                    pos="phrase",
                    simple="goodbye for now",
                ),
                _w(
                    "good morning",
                    "a greeting used in the morning",
                    "Good morning, everyone.",
                    ipa="ɡʊd ˈmɔrnɪŋ",
                    pos="phrase",
                    simple="hello in the morning",
                ),
                _w(
                    "good afternoon",
                    "a greeting used in the afternoon",
                    "Good afternoon, come in.",
                    ipa="ɡʊd ˌæftərˈnun",
                    pos="phrase",
                    simple="hello in the afternoon",
                ),
                _w(
                    "good evening",
                    "a greeting used in the evening",
                    "Good evening, welcome.",
                    ipa="ɡʊd ˈivnɪŋ",
                    pos="phrase",
                    simple="hello in the evening",
                ),
                _w(
                    "good night",
                    "said when leaving at night or going to sleep",
                    "Good night, sleep well.",
                    ipa="ɡʊd naɪt",
                    pos="phrase",
                    simple="bye at night",
                ),
                _w(
                    "welcome",
                    "said when someone arrives as a guest",
                    "Welcome home.",
                    ipa="ˈwɛlkəm",
                    pos="interjection",
                    simple="glad you're here",
                ),
                _w(
                    "take care",
                    "a kind way to say goodbye",
                    "Take care, see you soon.",
                    ipa="teɪk kɛr",
                    pos="phrase",
                    simple="a caring goodbye",
                ),
            ],
            domain=DOMAIN,
            sort_order=10,
        ),
        _deck(
            "en",
            "greetings-courtesy",
            "Please and thanks",
            [
                _w(
                    "please",
                    "said to make a request polite",
                    "Please sit down.",
                    ipa="pliz",
                    pos="adverb",
                    simple="a polite ask",
                ),
                _w(
                    "thank you",
                    "said to show you are grateful",
                    "Thank you for your help.",
                    ipa="θæŋk ju",
                    pos="phrase",
                    simple="I appreciate that",
                ),
                _w(
                    "thanks",
                    "a short way to say thank you",
                    "Thanks a lot.",
                    ipa="θæŋks",
                    pos="interjection",
                    simple="short thank you",
                ),
                _w(
                    "you're welcome",
                    "said after someone thanks you",
                    "You're welcome.",
                    ipa="jʊr ˈwɛlkəm",
                    pos="phrase",
                    simple="no problem after thanks",
                ),
                _w(
                    "sorry",
                    "said when you apologize",
                    "Sorry I'm late.",
                    ipa="ˈsɑri",
                    pos="adjective",
                    simple="I apologize",
                ),
                _w(
                    "excuse me",
                    "said to politely interrupt or get past someone",
                    "Excuse me, can I get by?",
                    ipa="ɪkˈskjuz mi",
                    pos="phrase",
                    simple="polite interruption",
                ),
                _w(
                    "pardon",
                    "a polite way to ask someone to repeat something",
                    "Pardon? Could you say that again?",
                    ipa="ˈpɑrdən",
                    pos="interjection",
                    simple="please repeat that",
                ),
                _w(
                    "no problem",
                    "a casual way to say you're welcome or it's okay",
                    "No problem, I can wait.",
                    ipa="noʊ ˈprɑbləm",
                    pos="phrase",
                    simple="it's okay",
                ),
                _w(
                    "of course",
                    "certainly; used to agree readily",
                    "Of course, I'll help you.",
                    ipa="əv kɔrs",
                    pos="phrase",
                    simple="certainly",
                ),
                _w(
                    "bless you",
                    "said to someone after they sneeze",
                    "Bless you! Are you getting a cold?",
                    ipa="blɛs ju",
                    pos="phrase",
                    simple="said after a sneeze",
                ),
                _w(
                    "congratulations",
                    "said to praise someone's success",
                    "Congratulations on your new job!",
                    ipa="kənˌɡrætʃəˈleɪʃənz",
                    pos="interjection",
                    simple="well done",
                ),
                _w(
                    "cheers",
                    "an informal toast, or a casual thanks",
                    "Cheers, everyone!",
                    example2="Thanks for the ride, cheers.",
                    ipa="tʃɪrz",
                    pos="interjection",
                    simple="a toast or casual thanks",
                ),
            ],
            domain=DOMAIN,
            sort_order=11,
        ),
        _deck(
            "en",
            "greetings-meeting",
            "Meeting people",
            [
                _w(
                    "nice to meet you",
                    "said when you meet someone for the first time",
                    "Nice to meet you.",
                    ipa="naɪs tə mit ju",
                    pos="phrase",
                    simple="glad to meet you",
                ),
                _w(
                    "my name is",
                    "used to introduce your own name",
                    "My name is Ana.",
                    ipa="maɪ neɪm ɪz",
                    pos="phrase",
                    simple="introduces your name",
                ),
                _w(
                    "this is",
                    "used to introduce another person",
                    "This is my friend, Sam.",
                    ipa="ðɪs ɪz",
                    pos="phrase",
                    simple="introduces someone",
                ),
                _w(
                    "friend",
                    "a person you know well and like",
                    "A close friend.",
                    ipa="frɛnd",
                    pos="noun",
                    simple="someone you like",
                ),
                _w(
                    "neighbor",
                    "a person who lives near you",
                    "Our neighbor waved hello.",
                    ipa="ˈneɪbər",
                    pos="noun",
                    simple="person who lives nearby",
                ),
                _w(
                    "classmate",
                    "a person in the same class as you",
                    "My classmate helped me study.",
                    ipa="ˈklæsmeɪt",
                    pos="noun",
                    simple="person in your class",
                ),
                _w(
                    "colleague",
                    "a person you work with",
                    "A colleague called me.",
                    ipa="ˈkɑliɡ",
                    pos="noun",
                    simple="person you work with",
                ),
                _w(
                    "stranger",
                    "a person you do not know",
                    "Don't talk to strangers.",
                    ipa="ˈstreɪndʒər",
                    pos="noun",
                    simple="someone you don't know",
                ),
                _w(
                    "introduce",
                    "to make two people known to each other",
                    "Let me introduce you to my boss.",
                    ipa="ˌɪntrəˈdus",
                    pos="verb",
                    simple="to present someone",
                ),
                _w(
                    "handshake",
                    "a greeting made by joining and shaking hands",
                    "They exchanged a handshake.",
                    ipa="ˈhændʃeɪk",
                    pos="noun",
                    simple="greeting by joining hands",
                ),
            ],
            domain=DOMAIN,
            sort_order=12,
        ),
        _deck(
            "en",
            "greetings-how-are-you",
            "How are you",
            [
                _w(
                    "how are you",
                    "asks about someone's well-being",
                    "How are you?",
                    ipa="haʊ ɑr ju",
                    pos="phrase",
                    simple="asks how someone feels",
                ),
                _w(
                    "how are you doing",
                    "a friendly way to ask how someone is",
                    "How are you doing?",
                    ipa="haʊ ɑr ju ˈduɪŋ",
                    pos="phrase",
                    simple="asks how life is going",
                ),
                _w(
                    "fine",
                    "well enough",
                    "I'm fine, thanks.",
                    ipa="faɪn",
                    pos="adjective",
                    simple="okay / well enough",
                ),
                _w(
                    "great",
                    "very good",
                    "I feel great today.",
                    ipa="ɡreɪt",
                    pos="adjective",
                    simple="very good",
                ),
                _w(
                    "okay",
                    "acceptable; all right",
                    "I'm okay, thanks for asking.",
                    ipa="oʊˈkeɪ",
                    pos="adjective",
                    simple="acceptable / fine",
                ),
                _w(
                    "not bad",
                    "fairly well",
                    "Not bad, and you?",
                    ipa="nɑt bæd",
                    pos="phrase",
                    simple="fairly good",
                ),
                _w(
                    "so-so",
                    "neither good nor bad",
                    "I feel so-so today.",
                    ipa="ˈsoʊsoʊ",
                    pos="adjective",
                    simple="neither good nor bad",
                ),
                _w(
                    "and you",
                    "asks the same question back",
                    "I'm well, and you?",
                    ipa="ænd ju",
                    pos="phrase",
                    simple="asks the question back",
                ),
                _w(
                    "what's up",
                    "a casual greeting, or 'what is new'",
                    "What's up?",
                    ipa="wʌts ʌp",
                    pos="phrase",
                    simple="a casual hello",
                ),
            ],
            domain=DOMAIN,
            sort_order=13,
        ),
    ]
