from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Greetings"


def greetings_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "greetings-hello",
            "Hello and goodbye",
            [
                _w("hello", "a greeting", "Hello, how are you?"),
                _w("hi", "informal hello", "Hi there."),
                _w("hey", "casual greeting", "Hey, come in."),
                _w("goodbye", "said when leaving", "Goodbye!"),
                _w("bye", "informal goodbye", "Bye for now."),
                _w("see you", "casual farewell", "See you later."),
                _w("see you later", "said when leaving for a while", "See you later."),
                _w("good morning", "morning greeting", "Good morning."),
                _w("good afternoon", "afternoon greeting", "Good afternoon."),
                _w("good evening", "evening greeting", "Good evening."),
                _w("good night", "evening farewell", "Good night."),
                _w("welcome", "greeting a guest", "Welcome home."),
                _w("take care", "kind farewell", "Take care."),
            ],
            domain=DOMAIN,
            sort_order=10,
        ),
        _deck(
            "en",
            "greetings-courtesy",
            "Courtesy",
            [
                _w("please", "polite request", "Please sit down."),
                _w("thank you", "polite gratitude", "Thank you."),
                _w("thanks", "short for thank you", "Thanks a lot."),
                _w("you're welcome", "reply to thanks", "You're welcome."),
                _w("sorry", "apology", "Sorry I'm late."),
                _w("excuse me", "polite interruption", "Excuse me."),
                _w("pardon", "polite request to repeat", "Pardon?"),
                _w("no problem", "it's okay", "No problem."),
                _w("of course", "certainly", "Of course."),
                _w("bless you", "said after a sneeze", "Bless you."),
                _w("congratulations", "praise for success", "Congratulations!"),
                _w("cheers", "toast or informal thanks", "Cheers."),
            ],
            domain=DOMAIN,
            sort_order=11,
        ),
        _deck(
            "en",
            "greetings-meeting",
            "Meeting people",
            [
                _w("nice to meet you", "said when meeting someone", "Nice to meet you."),
                _w("my name is", "introduces your name", "My name is Ana."),
                _w("I am", "says who you are", "I am a teacher."),
                _w("this is", "introduces another person", "This is my friend."),
                _w("friend", "someone you like", "A close friend."),
                _w("neighbor", "person who lives nearby", "Our neighbor waved."),
                _w("classmate", "person in your class", "My classmate helped."),
                _w("colleague", "person you work with", "A colleague called."),
                _w("stranger", "someone you do not know", "Don't talk to strangers."),
                _w("introduce", "to present someone", "Let me introduce you."),
                _w("handshake", "greeting by joining hands", "They shook hands."),
                _w("smile", "a happy facial expression", "She gave a smile."),
            ],
            domain=DOMAIN,
            sort_order=12,
        ),
        _deck(
            "en",
            "greetings-how-are-you",
            "How are you",
            [
                _w("how are you", "asks about well-being", "How are you?"),
                _w("how are you doing", "asks how life is going", "How are you doing?"),
                _w("fine", "well enough", "I'm fine."),
                _w("good", "well or pleasant", "I'm good, thanks."),
                _w("great", "very good", "I feel great."),
                _w("okay", "acceptable; all right", "I'm okay."),
                _w("tired", "needing rest", "I'm tired today."),
                _w("busy", "having a lot to do", "I'm busy this week."),
                _w("not bad", "fairly well", "Not bad, and you?"),
                _w("so-so", "neither good nor bad", "I feel so-so."),
                _w("and you", "asks the same question back", "I'm well, and you?"),
                _w("what's up", "casual hello or 'what is new'", "What's up?"),
            ],
            domain=DOMAIN,
            sort_order=13,
        ),
    ]
