from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Hands"


def hands_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-drop-catch",
            "Drop and catch",
            [
                _w(
                    "grip",
                    "hold something tightly",
                    "Grip the handle.",
                    ipa="ɡrɪp",
                    pos="verb",
                    simple="hold tightly",
                ),
                _w(
                    "pick up",
                    "lift something",
                    "Pick up your clothes.",
                    ipa="pɪk ʌp",
                    pos="verb",
                    simple="lift something",
                ),
                _w(
                    "drop",
                    "let something fall",
                    "Don't drop the glass.",
                    ipa="drɑp",
                    pos="verb",
                    simple="let something fall",
                ),
                _w(
                    "throw",
                    "send something through the air",
                    "Throw me the keys.",
                    ipa="θroʊ",
                    pos="verb",
                    simple="send through the air",
                ),
                _w(
                    "toss",
                    "throw lightly",
                    "Toss it in the bag.",
                    ipa="tɔs",
                    pos="verb",
                    simple="throw lightly",
                ),
                _w(
                    "catch",
                    "stop and hold something thrown",
                    "Catch the ball.",
                    ipa="kætʃ",
                    pos="verb",
                    simple="stop and hold something thrown",
                ),
            ],
            domain=DOMAIN,
            sort_order=130,
        ),
        _deck(
            "en",
            "conv-push-pull",
            "Push and pull",
            [
                _w(
                    "push",
                    "move something away from you",
                    "Push the door open.",
                    ipa="pʊʃ",
                    pos="verb",
                    simple="move something away",
                ),
                _w(
                    "pull",
                    "move something toward you",
                    "Pull the chair closer.",
                    ipa="pʊl",
                    pos="verb",
                    simple="move something toward you",
                ),
                _w(
                    "drag",
                    "pull something along a surface",
                    "Don't drag the bag on the floor.",
                    ipa="dræɡ",
                    pos="verb",
                    simple="pull along a surface",
                ),
                _w(
                    "lift",
                    "raise something",
                    "Lift with your legs.",
                    ipa="lɪft",
                    pos="verb",
                    simple="raise something",
                ),
                _w(
                    "carry",
                    "move something while holding it",
                    "Can you carry this box?",
                    ipa="ˈkɛri",
                    pos="verb",
                    simple="move something while holding it",
                ),
            ],
            domain=DOMAIN,
            sort_order=131,
        ),
        _deck(
            "en",
            "conv-tap-wave",
            "Tap and wave",
            [
                _w(
                    "tap",
                    "touch or hit lightly",
                    "Tap the screen.",
                    ipa="tæp",
                    pos="verb",
                    simple="touch lightly",
                ),
                _w(
                    "pat",
                    "touch repeatedly and gently",
                    "She patted the dog.",
                    ipa="pæt",
                    pos="verb",
                    simple="touch gently again and again",
                ),
                _w(
                    "poke",
                    "push with your finger",
                    "Don't poke me.",
                    ipa="poʊk",
                    pos="verb",
                    simple="push with a finger",
                ),
                _w(
                    "pinch",
                    "squeeze between your fingers",
                    "Don't pinch your brother.",
                    ipa="pɪntʃ",
                    pos="verb",
                    simple="squeeze between fingers",
                ),
                _w(
                    "scratch",
                    "rub with your fingernails",
                    "Don't scratch the mosquito bite.",
                    ipa="skrætʃ",
                    pos="verb",
                    simple="rub with your nails",
                ),
                _w(
                    "rub",
                    "move your hand back and forth over something",
                    "Rub the stain gently.",
                    ipa="rʌb",
                    pos="verb",
                    simple="move your hand back and forth",
                ),
                _w(
                    "squeeze",
                    "press something tightly",
                    "Squeeze the bottle.",
                    ipa="skwiz",
                    pos="verb",
                    simple="press tightly",
                ),
                _w(
                    "clap",
                    "hit your hands together",
                    "Clap if you agree.",
                    ipa="klæp",
                    pos="verb",
                    simple="hit your hands together",
                ),
                _w(
                    "snap",
                    "make a clicking sound with your fingers",
                    "She snapped her fingers.",
                    ipa="snæp",
                    pos="verb",
                    simple="click with your fingers",
                ),
                _w(
                    "wave",
                    "move your hand to greet someone",
                    "Wave goodbye.",
                    ipa="weɪv",
                    pos="verb",
                    simple="move your hand to greet",
                ),
                _w(
                    "point",
                    "direct your finger toward something",
                    "Don't point at people.",
                    ipa="pɔɪnt",
                    pos="verb",
                    simple="aim your finger",
                ),
            ],
            domain=DOMAIN,
            sort_order=132,
        ),
    ]
