from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Hello"


def hello_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-hello",
            "Hello",
            [
                _w(
                    "hello",
                    "a greeting when you meet someone",
                    "Hello, how are you?",
                    ipa="həˈloʊ",
                    pos="interjection",
                    simple="hi",
                ),
                _w(
                    "hi",
                    "an informal hello",
                    "Hi there.",
                    ipa="haɪ",
                    pos="interjection",
                    simple="a casual hello",
                ),
                _w(
                    "hey",
                    "a very casual greeting",
                    "Hey, come in.",
                    ipa="heɪ",
                    pos="interjection",
                    simple="a casual hello",
                ),
                _w(
                    "goodbye",
                    "said when you leave",
                    "Goodbye, see you tomorrow.",
                    ipa="ɡʊdˈbaɪ",
                    pos="interjection",
                    simple="bye",
                ),
                _w(
                    "bye",
                    "an informal goodbye",
                    "Bye for now.",
                    ipa="baɪ",
                    pos="interjection",
                    simple="a short goodbye",
                ),
                _w(
                    "see you",
                    "a casual way to say goodbye",
                    "See you later.",
                    ipa="si ju",
                    pos="phrase",
                    simple="goodbye for now",
                ),
                _w(
                    "good morning",
                    "a greeting used in the morning",
                    "Good morning, everyone.",
                    ipa="ɡʊd ˈmɔrnɪŋ",
                    pos="phrase",
                    simple="hello in the morning",
                ),
                _w(
                    "good night",
                    "said when leaving at night or going to sleep",
                    "Good night, sleep well.",
                    ipa="ɡʊd naɪt",
                    pos="phrase",
                    simple="bye at night",
                ),
            ],
            domain=DOMAIN,
            sort_order=10,
        ),
        _deck(
            "en",
            "conv-please",
            "Please and thanks",
            [
                _w(
                    "please",
                    "said to make a request polite",
                    "Please sit down.",
                    ipa="pliz",
                    pos="adverb",
                    simple="a polite ask",
                ),
                _w(
                    "thank you",
                    "said to show you are grateful",
                    "Thank you for your help.",
                    ipa="θæŋk ju",
                    pos="phrase",
                    simple="I appreciate that",
                ),
                _w(
                    "thanks",
                    "a short way to say thank you",
                    "Thanks a lot.",
                    ipa="θæŋks",
                    pos="interjection",
                    simple="short thank you",
                ),
                _w(
                    "you're welcome",
                    "said after someone thanks you",
                    "You're welcome.",
                    ipa="jʊr ˈwɛlkəm",
                    pos="phrase",
                    simple="no problem after thanks",
                ),
                _w(
                    "sorry",
                    "said when you apologize",
                    "Sorry I'm late.",
                    ipa="ˈsɑri",
                    pos="adjective",
                    simple="I apologize",
                ),
                _w(
                    "excuse me",
                    "said to politely interrupt or get past someone",
                    "Excuse me, can I get by?",
                    ipa="ɪkˈskjuz mi",
                    pos="phrase",
                    simple="polite interruption",
                ),
                _w(
                    "no problem",
                    "a casual way to say you're welcome or it's okay",
                    "No problem, I can wait.",
                    ipa="noʊ ˈprɑbləm",
                    pos="phrase",
                    simple="it's okay",
                ),
                _w(
                    "welcome",
                    "said when someone arrives as a guest",
                    "Welcome home.",
                    ipa="ˈwɛlkəm",
                    pos="interjection",
                    simple="glad you're here",
                ),
            ],
            domain=DOMAIN,
            sort_order=11,
        ),
    ]
