from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Home"


def home_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "home-rooms",
            "Rooms",
            [
                _w("house", "a building people live in", "A small house."),
                _w("apartment", "a home in a larger building", "A city apartment."),
                _w("room", "a space inside a home", "A quiet room."),
                _w("kitchen", "room for cooking", "She's in the kitchen."),
                _w("bedroom", "room for sleeping", "The bedroom is dark."),
                _w("bathroom", "room with a toilet and sink", "The bathroom is free."),
                _w("living room", "room for sitting together", "TV in the living room."),
                _w("hallway", "passage between rooms", "Shoes in the hallway."),
                _w("balcony", "outdoor platform on a building", "Sit on the balcony."),
                _w("garden", "outdoor plant space", "A small garden."),
                _w("garage", "place to keep a car", "The car is in the garage."),
                _w("upstairs", "on a higher floor", "The kids are upstairs."),
            ],
            domain=DOMAIN,
            sort_order=50,
        ),
        _deck(
            "en",
            "home-furniture",
            "Furniture",
            [
                _w("table", "flat surface on legs", "Set the table."),
                _w("chair", "seat for one person", "Pull up a chair."),
                _w("sofa", "long soft seat", "Sit on the sofa."),
                _w("bed", "furniture for sleeping", "Make the bed."),
                _w("desk", "table for writing", "A wooden desk."),
                _w("lamp", "light you can move", "Turn on the lamp."),
                _w("shelf", "board for storing things", "Books on the shelf."),
                _w("closet", "space for clothes", "Hang it in the closet."),
                _w("mirror", "glass that shows your face", "Look in the mirror."),
                _w("curtain", "cloth over a window", "Open the curtains."),
                _w("carpet", "thick floor covering", "A red carpet."),
                _w("pillow", "soft support for the head", "A soft pillow."),
            ],
            domain=DOMAIN,
            sort_order=51,
        ),
        _deck(
            "en",
            "home-chores",
            "Kitchen and chores",
            [
                _w("clean", "to make free of dirt", "Clean the floor."),
                _w("wash", "to clean with water", "Wash the dishes."),
                _w("dishes", "plates and bowls after a meal", "Do the dishes."),
                _w("laundry", "clothes to be washed", "Do the laundry."),
                _w("vacuum", "to clean with a vacuum", "Vacuum the rug."),
                _w("sweep", "to clean with a broom", "Sweep the kitchen."),
                _w("trash", "things you throw away", "Take out the trash."),
                _w("sink", "basin with a tap", "Wash it in the sink."),
                _w("stove", "appliance for cooking", "The pot is on the stove."),
                _w("fridge", "cold box for food", "Milk is in the fridge."),
                _w("broom", "tool for sweeping", "Get the broom."),
                _w("soap", "used for washing", "Use soap and water."),
            ],
            domain=DOMAIN,
            sort_order=52,
        ),
        _deck(
            "en",
            "home-living",
            "Living at home",
            [
                _w("home", "the place you live", "I'm going home."),
                _w("rent", "money paid to live somewhere", "We pay rent."),
                _w("landlord", "person who rents out a home", "Call the landlord."),
                _w("neighbor", "person who lives nearby", "Our neighbor waved."),
                _w("key", "metal tool that opens a lock", "I lost my key."),
                _w("lock", "device that keeps a door shut", "Lock the door."),
                _w("doorbell", "button that rings at the door", "Ring the doorbell."),
                _w("quiet", "with little noise", "Keep it quiet."),
                _w("messy", "not tidy", "The room is messy."),
                _w("tidy", "neat and in order", "Keep your room tidy."),
                _w("move in", "to start living somewhere", "We move in Monday."),
                _w("move out", "to leave a home", "They moved out."),
            ],
            domain=DOMAIN,
            sort_order=53,
        ),
    ]
