from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Hotel"


def hotel_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "hotel-arrival",
            "Arrival",
            [
                _w("hotel", "place that rents rooms to guests", "A downtown hotel."),
                _w("reservation", "a booked room", "I have a reservation."),
                _w("check in", "to register as a guest", "We check in at 3."),
                _w("reception", "front desk of a hotel", "Ask at reception."),
                _w("receptionist", "person at the front desk", "The receptionist smiled."),
                _w("passport", "travel ID document", "Show your passport."),
                _w("guest", "person staying at a hotel", "A hotel guest."),
                _w("lobby", "entrance hall", "Wait in the lobby."),
                _w("elevator", "lift between floors", "Take the elevator."),
                _w("floor", "level of a building", "Third floor."),
                _w("key card", "plastic card that opens a room", "Your key card."),
                _w("night", "one overnight stay", "Two nights, please."),
            ],
            domain=DOMAIN,
            sort_order=60,
        ),
        _deck(
            "en",
            "hotel-room",
            "The room",
            [
                _w("room", "a hotel bedroom", "A double room."),
                _w("single room", "room for one person", "A single room, please."),
                _w("double room", "room for two people", "A double room."),
                _w("bed", "furniture for sleeping", "A king bed."),
                _w("bathroom", "room with a shower or bath", "A private bathroom."),
                _w("shower", "place to wash standing up", "A hot shower."),
                _w("towel", "cloth for drying", "Clean towels."),
                _w("wifi", "wireless internet", "The wifi password."),
                _w("air conditioning", "system that cools a room", "Turn on the air conditioning."),
                _w("view", "what you see from a window", "A sea view."),
                _w("quiet room", "room with little noise", "A quiet room, please."),
                _w("safe", "box that locks valuables", "Put it in the safe."),
            ],
            domain=DOMAIN,
            sort_order=61,
        ),
        _deck(
            "en",
            "hotel-services",
            "Hotel services",
            [
                _w("breakfast", "morning meal at a hotel", "Breakfast is included."),
                _w("included", "already in the price", "Wifi is included."),
                _w("pool", "place to swim", "The hotel pool."),
                _w("gym", "room for exercise", "The gym opens at 6."),
                _w("spa", "place for rest and treatments", "Book the spa."),
                _w("room service", "food brought to your room", "Call room service."),
                _w("housekeeping", "staff who clean rooms", "Housekeeping at 11."),
                _w("laundry", "clothes-washing service", "Hotel laundry."),
                _w("concierge", "staff who help with plans", "Ask the concierge."),
                _w("parking", "place to leave a car", "Is parking free?"),
                _w("late checkout", "leaving later than usual", "Can I have late checkout?"),
                _w("wake-up call", "phone call to wake you", "A wake-up call at 7."),
            ],
            domain=DOMAIN,
            sort_order=62,
        ),
        _deck(
            "en",
            "hotel-problems",
            "Problems and checkout",
            [
                _w("check out", "to leave and pay", "We check out at 11."),
                _w("bill", "amount you must pay", "The hotel bill."),
                _w("receipt", "proof of payment", "I need a receipt."),
                _w("complaint", "statement that something is wrong", "I have a complaint."),
                _w("noisy", "too loud", "The room is noisy."),
                _w("broken", "not working", "The shower is broken."),
                _w("dirty", "not clean", "The towels are dirty."),
                _w("too small", "not big enough", "The bed is too small."),
                _w("change rooms", "to move to another room", "Can we change rooms?"),
                _w("refund", "money given back", "I'd like a refund."),
                _w("lost", "cannot be found", "I lost my key card."),
                _w("help", "assistance", "I need help."),
            ],
            domain=DOMAIN,
            sort_order=63,
        ),
    ]
