from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Household actions"


def household_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-pour-wipe",
            "Pour and wipe",
            [
                _w(
                    "pour",
                    "make liquid flow from a container",
                    "Pour the milk slowly.",
                    ipa="pɔr",
                    pos="verb",
                    simple="make liquid flow out",
                ),
                _w(
                    "spill",
                    "accidentally cause liquid to fall out",
                    "Don't spill the coffee.",
                    ipa="spɪl",
                    pos="verb",
                    simple="accidentally let liquid fall",
                ),
                _w(
                    "wipe",
                    "clean by rubbing",
                    "Wipe the table.",
                    ipa="waɪp",
                    pos="verb",
                    simple="clean by rubbing",
                ),
                _w(
                    "scrub",
                    "clean by rubbing hard",
                    "Scrub the pan.",
                    ipa="skrʌb",
                    pos="verb",
                    simple="clean by rubbing hard",
                ),
                _w(
                    "rinse",
                    "wash quickly with water",
                    "Rinse the dishes.",
                    ipa="rɪns",
                    pos="verb",
                    simple="wash quickly with water",
                ),
                _w(
                    "soak",
                    "leave something in liquid",
                    "Soak the beans overnight.",
                    ipa="soʊk",
                    pos="verb",
                    simple="leave in liquid",
                ),
                _w(
                    "sweep",
                    "clean with a broom",
                    "Sweep the floor.",
                    ipa="swip",
                    pos="verb",
                    simple="clean with a broom",
                ),
                _w(
                    "stir",
                    "move liquid or food around",
                    "Stir the soup.",
                    ipa="stɜr",
                    pos="verb",
                    simple="mix by moving around",
                ),
            ],
            domain=DOMAIN,
            sort_order=150,
        ),
        _deck(
            "en",
            "conv-chop-fold",
            "Chop and fold",
            [
                _w(
                    "chop",
                    "cut into pieces",
                    "Chop the onions.",
                    ipa="tʃɑp",
                    pos="verb",
                    simple="cut into pieces",
                ),
                _w(
                    "slice",
                    "cut into thin pieces",
                    "Slice the bread.",
                    ipa="slaɪs",
                    pos="verb",
                    simple="cut into thin pieces",
                ),
                _w(
                    "peel",
                    "remove the outer layer",
                    "Peel the orange.",
                    ipa="pil",
                    pos="verb",
                    simple="remove the skin",
                ),
                _w(
                    "tear",
                    "pull something apart",
                    "Tear the paper in half.",
                    ipa="tɛr",
                    pos="verb",
                    simple="pull apart",
                ),
                _w(
                    "rip",
                    "tear something forcefully",
                    "Don't rip the page.",
                    ipa="rɪp",
                    pos="verb",
                    simple="tear hard",
                ),
                _w(
                    "fold",
                    "bend something over itself",
                    "Fold the towel.",
                    ipa="foʊld",
                    pos="verb",
                    simple="bend over itself",
                ),
                _w(
                    "unwrap",
                    "remove a covering",
                    "Unwrap the gift.",
                    ipa="ʌnˈræp",
                    pos="verb",
                    simple="take the covering off",
                ),
            ],
            domain=DOMAIN,
            sort_order=151,
        ),
        _deck(
            "en",
            "conv-plug-lock",
            "Plug and lock",
            [
                _w(
                    "plug in",
                    "connect to electricity",
                    "Plug in your phone.",
                    ipa="plʌɡ ɪn",
                    pos="verb",
                    simple="connect to electricity",
                ),
                _w(
                    "unplug",
                    "disconnect from electricity",
                    "Unplug the toaster.",
                    ipa="ʌnˈplʌɡ",
                    pos="verb",
                    simple="disconnect from electricity",
                ),
                _w(
                    "lock",
                    "secure something",
                    "Lock the door.",
                    ipa="lɑk",
                    pos="verb",
                    simple="secure with a lock",
                ),
                _w(
                    "unlock",
                    "open a lock",
                    "Unlock the car.",
                    ipa="ʌnˈlɑk",
                    pos="verb",
                    simple="open a lock",
                ),
                _w(
                    "flush",
                    "make a toilet empty with water",
                    "Don't forget to flush.",
                    ipa="flʌʃ",
                    pos="verb",
                    simple="empty the toilet",
                ),
            ],
            domain=DOMAIN,
            sort_order=152,
        ),
    ]
