from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Body movement"


def movement_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-walk-run",
            "Walk and run",
            [
                _w(
                    "walk",
                    "move on your feet",
                    "Let's walk to the store.",
                    ipa="wɔk",
                    pos="verb",
                    simple="move on your feet",
                ),
                _w(
                    "run",
                    "move quickly on your feet",
                    "Don't run in the hallway.",
                    ipa="rʌn",
                    pos="verb",
                    simple="move quickly on your feet",
                ),
                _w(
                    "jog",
                    "run slowly",
                    "I jog in the morning.",
                    ipa="dʒɑɡ",
                    pos="verb",
                    simple="run slowly",
                ),
                _w(
                    "sprint",
                    "run very fast",
                    "He sprinted to the bus.",
                    ipa="sprɪnt",
                    pos="verb",
                    simple="run very fast",
                ),
                _w(
                    "jump",
                    "push yourself off the ground",
                    "Jump over the puddle.",
                    ipa="dʒʌmp",
                    pos="verb",
                    simple="push off the ground",
                ),
                _w(
                    "hop",
                    "make a small jump",
                    "The kid hopped on one foot.",
                    ipa="hɑp",
                    pos="verb",
                    simple="a small jump",
                ),
                _w(
                    "skip",
                    "move with alternating steps and hops",
                    "The children skipped down the path.",
                    ipa="skɪp",
                    pos="verb",
                    simple="step and hop",
                ),
            ],
            domain=DOMAIN,
            sort_order=120,
        ),
        _deck(
            "en",
            "conv-crawl-squat",
            "Crawl and squat",
            [
                _w(
                    "crawl",
                    "move on your hands and knees",
                    "The baby crawled to the toy.",
                    ipa="krɔl",
                    pos="verb",
                    simple="move on hands and knees",
                ),
                _w(
                    "climb",
                    "move upward",
                    "We climbed the stairs.",
                    ipa="klaɪm",
                    pos="verb",
                    simple="move upward",
                ),
                _w(
                    "bend",
                    "curve your body",
                    "Bend your knees.",
                    ipa="bɛnd",
                    pos="verb",
                    simple="curve your body",
                ),
                _w(
                    "stretch",
                    "extend your arms or body",
                    "Stretch before you run.",
                    ipa="strɛtʃ",
                    pos="verb",
                    simple="extend your body",
                ),
                _w(
                    "twist",
                    "turn part of your body",
                    "Don't twist your ankle.",
                    ipa="twɪst",
                    pos="verb",
                    simple="turn part of your body",
                ),
                _w(
                    "lean",
                    "move your body toward something",
                    "Don't lean on the door.",
                    ipa="lin",
                    pos="verb",
                    simple="move toward something",
                ),
                _w(
                    "kneel",
                    "rest on your knees",
                    "He knelt to tie his shoe.",
                    ipa="nil",
                    pos="verb",
                    simple="go down onto your knees",
                ),
                _w(
                    "squat",
                    "lower your body by bending your knees",
                    "Squat if you need to pick that up.",
                    ipa="skwɑt",
                    pos="verb",
                    simple="lower yourself by bending your knees",
                ),
                _w(
                    "duck",
                    "quickly lower your head or body",
                    "Duck! The ball is coming.",
                    ipa="dʌk",
                    pos="verb",
                    simple="quickly lower your head",
                ),
            ],
            domain=DOMAIN,
            sort_order=121,
        ),
        _deck(
            "en",
            "conv-stumble-fall",
            "Stumble and fall",
            [
                _w(
                    "stumble",
                    "almost fall while walking",
                    "I stumbled on the step.",
                    ipa="ˈstʌmbəl",
                    pos="verb",
                    simple="almost fall while moving",
                ),
                _w(
                    "trip",
                    "catch your foot and nearly or actually fall",
                    "Don't trip on the cord.",
                    ipa="trɪp",
                    pos="verb",
                    simple="catch your foot",
                ),
                _w(
                    "slip",
                    "accidentally slide",
                    "Be careful not to slip.",
                    ipa="slɪp",
                    pos="verb",
                    simple="accidentally slide",
                ),
                _w(
                    "fall",
                    "drop to the ground",
                    "She fell off the bike.",
                    ipa="fɔl",
                    pos="verb",
                    simple="drop to the ground",
                ),
                _w(
                    "roll",
                    "turn over repeatedly",
                    "The ball rolled under the couch.",
                    ipa="roʊl",
                    pos="verb",
                    simple="turn over again and again",
                ),
            ],
            domain=DOMAIN,
            sort_order=122,
        ),
    ]
