from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Numbers and time"


def numbers_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "numbers-count",
            "Numbers",
            [
                _w("zero", "0", "The score is zero."),
                _w("one", "1", "I have one."),
                _w("two", "2", "Two books."),
                _w("three", "3", "Three chairs."),
                _w("four", "4", "Four doors."),
                _w("five", "5", "Five apples."),
                _w("ten", "10", "Ten dollars."),
                _w("twenty", "20", "Twenty students."),
                _w("hundred", "100", "A hundred people."),
                _w("thousand", "1,000", "A thousand years."),
                _w("first", "number 1 in order", "The first train."),
                _w("second", "number 2 in order", "The second door."),
                _w("half", "one of two equal parts", "Half the pie."),
            ],
            domain=DOMAIN,
            sort_order=90,
        ),
        _deck(
            "en",
            "numbers-clock",
            "Clock time",
            [
                _w("time", "hours and minutes", "What time is it?"),
                _w("hour", "60 minutes", "Wait one hour."),
                _w("minute", "60 seconds", "Wait a minute."),
                _w("o'clock", "exactly on the hour", "It's three o'clock."),
                _w("morning", "early part of the day", "In the morning."),
                _w("afternoon", "after noon", "This afternoon."),
                _w("evening", "late part of the day", "This evening."),
                _w("night", "dark part of the day", "At night."),
                _w("now", "at this moment", "Do it now."),
                _w("later", "after now", "Later tonight."),
                _w("early", "before the usual time", "An early train."),
                _w("late", "after the usual time", "Sorry I'm late."),
            ],
            domain=DOMAIN,
            sort_order=91,
        ),
        _deck(
            "en",
            "numbers-days",
            "Days and months",
            [
                _w("today", "this day", "Today is Monday."),
                _w("tomorrow", "the next day", "See you tomorrow."),
                _w("yesterday", "the day before today", "Yesterday was cold."),
                _w("Monday", "first weekday", "I work on Monday."),
                _w("Friday", "end of the work week", "Friday night."),
                _w("Sunday", "last day of the week", "I rest on Sunday."),
                _w("week", "seven days", "This week."),
                _w("month", "about 30 days", "Next month."),
                _w("year", "12 months", "Next year."),
                _w("January", "first month", "Born in January."),
                _w("June", "sixth month", "School ends in June."),
                _w("December", "last month", "Snow in December."),
            ],
            domain=DOMAIN,
            sort_order=92,
        ),
        _deck(
            "en",
            "numbers-duration",
            "Duration",
            [
                _w("second", "a very short time", "Wait a second."),
                _w("day", "24 hours", "A long day."),
                _w("weekend", "Saturday and Sunday", "This weekend."),
                _w("season", "one of four parts of the year", "Summer is my season."),
                _w("always", "at all times", "She always smiles."),
                _w("often", "many times", "I often walk."),
                _w("sometimes", "not always", "I sometimes cook."),
                _w("never", "at no time", "I never smoke."),
                _w("soon", "in a short time", "See you soon."),
                _w("already", "before now", "I already ate."),
                _w("still", "continuing up to now", "Are you still here?"),
                _w("yet", "up to now, in questions/negatives", "Not yet."),
            ],
            domain=DOMAIN,
            sort_order=93,
        ),
    ]
