from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Numbers and time"


def numbers_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "numbers-count",
            "Numbers",
            [
                _w(
                    "zero",
                    "the number 0",
                    "The score is zero.",
                    ipa="ˈzɪroʊ",
                    pos="noun",
                    simple="0",
                ),
                _w("one", "the number 1", "I have one brother.", ipa="wʌn", pos="noun", simple="1"),
                _w("two", "the number 2", "Two books.", ipa="tu", pos="noun", simple="2"),
                _w("three", "the number 3", "Three chairs.", ipa="θri", pos="noun", simple="3"),
                _w("four", "the number 4", "Four doors.", ipa="fɔr", pos="noun", simple="4"),
                _w("five", "the number 5", "Five apples.", ipa="faɪv", pos="noun", simple="5"),
                _w("ten", "the number 10", "Ten dollars.", ipa="tɛn", pos="noun", simple="10"),
                _w(
                    "twenty",
                    "the number 20",
                    "Twenty students.",
                    ipa="ˈtwɛnti",
                    pos="noun",
                    simple="20",
                ),
                _w(
                    "hundred",
                    "the number 100",
                    "A hundred people came.",
                    ipa="ˈhʌndrəd",
                    pos="noun",
                    simple="100",
                ),
                _w(
                    "thousand",
                    "the number 1,000",
                    "A thousand years.",
                    ipa="ˈθaʊzənd",
                    pos="noun",
                    simple="1,000",
                ),
                _w(
                    "first",
                    "number 1 in a sequence",
                    "The first train leaves at six.",
                    ipa="fɜrst",
                    pos="adjective",
                    simple="number 1 in order",
                ),
                _w(
                    "second",
                    "number 2 in a sequence",
                    "The second door on the left.",
                    ipa="ˈsɛkənd",
                    pos="adjective",
                    simple="number 2 in order",
                ),
                _w(
                    "half",
                    "one of two equal parts",
                    "Half the pie is gone.",
                    ipa="hæf",
                    pos="noun",
                    simple="one of two equal parts",
                ),
            ],
            domain=DOMAIN,
            sort_order=20,
        ),
        _deck(
            "en",
            "numbers-clock",
            "Clock time",
            [
                _w(
                    "time",
                    "hours and minutes; a point in the day",
                    "What time is it?",
                    ipa="taɪm",
                    pos="noun",
                    simple="hours and minutes",
                ),
                _w(
                    "hour",
                    "a period of 60 minutes",
                    "Wait one hour.",
                    ipa="aʊər",
                    pos="noun",
                    simple="60 minutes",
                ),
                _w(
                    "minute",
                    "a period of 60 seconds",
                    "Wait a minute.",
                    ipa="ˈmɪnɪt",
                    pos="noun",
                    simple="60 seconds",
                ),
                _w(
                    "o'clock",
                    "used to say the exact hour",
                    "It's three o'clock.",
                    ipa="əˈklɑk",
                    pos="adverb",
                    simple="exactly on the hour",
                ),
                _w(
                    "morning",
                    "the early part of the day",
                    "In the morning.",
                    ipa="ˈmɔrnɪŋ",
                    pos="noun",
                    simple="early part of the day",
                ),
                _w(
                    "afternoon",
                    "the part of the day after noon",
                    "This afternoon.",
                    ipa="ˌæftərˈnun",
                    pos="noun",
                    simple="after noon",
                ),
                _w(
                    "evening",
                    "the late part of the day",
                    "This evening.",
                    ipa="ˈivnɪŋ",
                    pos="noun",
                    simple="late part of the day",
                ),
                _w(
                    "night",
                    "the dark part of the day",
                    "At night.",
                    ipa="naɪt",
                    pos="noun",
                    simple="dark part of the day",
                ),
                _w(
                    "now",
                    "at this moment",
                    "Do it now.",
                    ipa="naʊ",
                    pos="adverb",
                    simple="at this moment",
                ),
                _w(
                    "later",
                    "at a time after now",
                    "Later tonight.",
                    ipa="ˈleɪtər",
                    pos="adverb",
                    simple="after now",
                ),
                _w(
                    "early",
                    "before the usual or expected time",
                    "An early train.",
                    ipa="ˈɜrli",
                    pos="adjective",
                    simple="before the usual time",
                ),
                _w(
                    "late",
                    "after the usual or expected time",
                    "Sorry I'm late.",
                    ipa="leɪt",
                    pos="adjective",
                    simple="after the usual time",
                ),
            ],
            domain=DOMAIN,
            sort_order=21,
        ),
        _deck(
            "en",
            "numbers-days",
            "Days and months",
            [
                _w(
                    "today",
                    "this current day",
                    "Today is Monday.",
                    ipa="təˈdeɪ",
                    pos="noun",
                    simple="this day",
                ),
                _w(
                    "tomorrow",
                    "the day after today",
                    "See you tomorrow.",
                    ipa="təˈmɔroʊ",
                    pos="noun",
                    simple="the next day",
                ),
                _w(
                    "yesterday",
                    "the day before today",
                    "Yesterday was cold.",
                    ipa="ˈjɛstərdeɪ",
                    pos="noun",
                    simple="the day before today",
                ),
                _w(
                    "Monday",
                    "the first weekday",
                    "I work on Monday.",
                    ipa="ˈmʌndeɪ",
                    pos="noun",
                    simple="first weekday",
                ),
                _w(
                    "Friday",
                    "the last day of the work week",
                    "Friday night.",
                    ipa="ˈfraɪdeɪ",
                    pos="noun",
                    simple="end of the work week",
                ),
                _w(
                    "Sunday",
                    "the last day of the week",
                    "I rest on Sunday.",
                    ipa="ˈsʌndeɪ",
                    pos="noun",
                    simple="last day of the week",
                ),
                _w(
                    "week",
                    "a period of seven days",
                    "This week.",
                    ipa="wik",
                    pos="noun",
                    simple="seven days",
                ),
                _w(
                    "month",
                    "a period of about 30 days",
                    "Next month.",
                    ipa="mʌnθ",
                    pos="noun",
                    simple="about 30 days",
                ),
                _w(
                    "year",
                    "a period of 12 months",
                    "Next year.",
                    ipa="jɪr",
                    pos="noun",
                    simple="12 months",
                ),
                _w(
                    "January",
                    "the first month of the year",
                    "Born in January.",
                    ipa="ˈdʒænjuɛri",
                    pos="noun",
                    simple="first month",
                ),
                _w(
                    "June",
                    "the sixth month of the year",
                    "School ends in June.",
                    ipa="dʒun",
                    pos="noun",
                    simple="sixth month",
                ),
                _w(
                    "December",
                    "the last month of the year",
                    "Snow in December.",
                    ipa="dɪˈsɛmbər",
                    pos="noun",
                    simple="last month",
                ),
            ],
            domain=DOMAIN,
            sort_order=22,
        ),
        _deck(
            "en",
            "numbers-duration",
            "Duration",
            [
                _w(
                    "second",
                    "a very short unit of time",
                    "Wait a second.",
                    ipa="ˈsɛkənd",
                    pos="noun",
                    simple="a very short time",
                ),
                _w(
                    "day",
                    "a period of 24 hours",
                    "A long day.",
                    ipa="deɪ",
                    pos="noun",
                    simple="24 hours",
                ),
                _w(
                    "weekend",
                    "Saturday and Sunday",
                    "This weekend.",
                    ipa="ˈwikɛnd",
                    pos="noun",
                    simple="Saturday and Sunday",
                ),
                _w(
                    "season",
                    "one of the four parts of the year",
                    "Summer is my favorite season.",
                    ipa="ˈsizən",
                    pos="noun",
                    simple="one of four parts of the year",
                ),
                _w(
                    "always",
                    "at all times; every time",
                    "She always smiles.",
                    ipa="ˈɔlweɪz",
                    pos="adverb",
                    simple="at all times",
                ),
                _w(
                    "often",
                    "many times",
                    "I often walk to work.",
                    ipa="ˈɔfən",
                    pos="adverb",
                    simple="many times",
                ),
                _w(
                    "sometimes",
                    "occasionally; not always",
                    "I sometimes cook at home.",
                    ipa="ˈsʌmtaɪmz",
                    pos="adverb",
                    simple="not always",
                ),
                _w(
                    "never",
                    "at no time; not ever",
                    "I never smoke.",
                    ipa="ˈnɛvər",
                    pos="adverb",
                    simple="at no time",
                ),
                _w(
                    "soon",
                    "in a short time from now",
                    "See you soon.",
                    ipa="sun",
                    pos="adverb",
                    simple="in a short time",
                ),
            ],
            domain=DOMAIN,
            sort_order=23,
        ),
    ]
