from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Body reactions"


def reactions_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-shiver-sweat",
            "Shiver and sweat",
            [
                _w(
                    "shiver",
                    "shake slightly from cold or fear",
                    "I shivered in the wind.",
                    ipa="ˈʃɪvər",
                    pos="verb",
                    simple="shake from cold or fear",
                ),
                _w(
                    "tremble",
                    "shake because of fear, cold, or emotion",
                    "Her hands trembled.",
                    ipa="ˈtrɛmbəl",
                    pos="verb",
                    simple="shake from emotion or cold",
                ),
                _w(
                    "sweat",
                    "produce moisture from your skin",
                    "I sweat when I run.",
                    ipa="swɛt",
                    pos="verb",
                    simple="produce moisture from your skin",
                ),
                _w(
                    "blush",
                    "become red in the face",
                    "He blushed at the compliment.",
                    ipa="blʌʃ",
                    pos="verb",
                    simple="face turns red",
                ),
                _w(
                    "itch",
                    "have a feeling that makes you want to scratch",
                    "My arm itches.",
                    ipa="ɪtʃ",
                    pos="verb",
                    simple="feeling that makes you want to scratch",
                ),
                _w(
                    "ache",
                    "hurt continuously",
                    "My legs ache after the hike.",
                    ipa="eɪk",
                    pos="verb",
                    simple="hurt for a while",
                ),
                _w(
                    "cramp",
                    "experience sudden muscle tightening",
                    "I cramped in the pool.",
                    ipa="kræmp",
                    pos="verb",
                    simple="sudden muscle tightness",
                ),
            ],
            domain=DOMAIN,
            sort_order=140,
        ),
        _deck(
            "en",
            "conv-breathe-sleep",
            "Breathe and sleep",
            [
                _w(
                    "breathe",
                    "take air in and out",
                    "Breathe slowly.",
                    ipa="brið",
                    pos="verb",
                    simple="take air in and out",
                ),
                _w(
                    "inhale",
                    "breathe in",
                    "Inhale through your nose.",
                    ipa="ɪnˈheɪl",
                    pos="verb",
                    simple="breathe in",
                ),
                _w(
                    "exhale",
                    "breathe out",
                    "Exhale slowly.",
                    ipa="ɛksˈheɪl",
                    pos="verb",
                    simple="breathe out",
                ),
                _w(
                    "doze",
                    "sleep lightly",
                    "He dozed on the couch.",
                    ipa="doʊz",
                    pos="verb",
                    simple="sleep lightly",
                ),
                _w(
                    "nap",
                    "sleep briefly",
                    "I need a nap.",
                    ipa="næp",
                    pos="verb",
                    simple="sleep for a short time",
                ),
                _w(
                    "oversleep",
                    "sleep longer than intended",
                    "Don't oversleep tomorrow.",
                    ipa="ˌoʊvərˈslip",
                    pos="verb",
                    simple="sleep too long",
                ),
                _w(
                    "wake up",
                    "stop sleeping",
                    "I wake up at seven.",
                    ipa="weɪk ʌp",
                    pos="verb",
                    simple="stop sleeping",
                ),
                _w(
                    "dizzy",
                    "feeling like you might fall because your head is spinning",
                    "I felt dizzy after I stood up.",
                    example2="Sit down if you get dizzy.",
                    ipa="ˈdɪzi",
                    pos="adjective",
                    simple="head spinning",
                ),
                _w(
                    "faint",
                    "pass out for a short time",
                    "She fainted in the heat.",
                    example2="I thought I might faint.",
                    ipa="feɪnt",
                    pos="verb",
                    simple="pass out",
                ),
            ],
            domain=DOMAIN,
            sort_order=141,
        ),
    ]
