from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "SAT"


def sat_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "sat-core",
            "SAT",
            [
                _w("abundant", "plentiful", "Abundant rain."),
                _w("benevolent", "kind; generous", "A benevolent leader."),
                _w("concise", "short and clear", "A concise answer."),
                _w("diligent", "hard-working", "A diligent student."),
                _w("eloquent", "fluent and persuasive", "An eloquent speech."),
                _w("frugal", "thrifty", "A frugal meal."),
                _w("genuine", "real; sincere", "A genuine smile."),
                _w("hypothesis", "a testable idea", "Test the hypothesis."),
                _w("illuminate", "to light up or explain", "The lamp illuminates the room."),
                _w("pragmatic", "practical", "A pragmatic plan."),
                _w("reticent", "reserved; quiet", "He was reticent."),
                _w("tenacious", "persistent", "A tenacious grip."),
                _w("candid", "honest and direct", "A candid reply."),
                _w("vivid", "bright and clear", "A vivid memory."),
                _w("precise", "exact", "A precise measurement."),
                _w("skeptical", "doubting", "A skeptical look."),
                _w("modest", "not boastful", "A modest answer."),
                _w("durable", "long-lasting", "A durable bag."),
                _w("evident", "obvious", "The answer is evident."),
                _w("feasible", "possible to do", "A feasible plan."),
            ],
            domain=DOMAIN,
            kind="sat",
            sort_order=100,
        ),
        _deck(
            "en",
            "sat-advanced",
            "SAT words",
            [
                _w("capricious", "changing on a whim", "A capricious breeze."),
                _w("ephemeral", "short-lived", "Ephemeral fame."),
                _w("juxtapose", "to place side by side", "The film juxtaposes two lives."),
                _w("ostentatious", "showy", "An ostentatious house."),
                _w("prosaic", "ordinary; dull", "A prosaic routine."),
                _w("superfluous", "extra; not needed", "Superfluous details."),
                _w("ubiquitous", "found everywhere", "Ubiquitous phones."),
                _w("verbose", "wordy", "A verbose email."),
                _w("wary", "cautious", "Be wary of ice."),
                _w("zeal", "great energy for a cause", "She worked with zeal."),
                _w("lament", "to mourn or regret", "They lament the loss."),
                _w("ambivalent", "having mixed feelings", "She felt ambivalent."),
                _w("austere", "severe; without luxury", "An austere room."),
                _w("cryptic", "mysterious", "A cryptic note."),
                _w("dogmatic", "stubbornly sure", "A dogmatic claim."),
                _w("enigma", "a puzzle", "The code is an enigma."),
                _w("furtive", "secretive", "A furtive glance."),
                _w("impartial", "fair; not biased", "An impartial judge."),
                _w("novel", "new and unusual", "A novel idea."),
                _w("opaque", "not transparent; unclear", "An opaque explanation."),
            ],
            domain=DOMAIN,
            kind="sat",
            sort_order=101,
        ),
    ]
