from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Thinking"


def thinking_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "conv-know-think",
            "Know and think",
            [
                _w(
                    "know",
                    "have information",
                    "I know the answer.",
                    ipa="noʊ",
                    pos="verb",
                    simple="have information",
                ),
                _w(
                    "think",
                    "use your mind",
                    "Let me think about it.",
                    ipa="θɪŋk",
                    pos="verb",
                    simple="use your mind",
                ),
                _w(
                    "believe",
                    "think something is true",
                    "I believe you.",
                    ipa="bɪˈliv",
                    pos="verb",
                    simple="think it's true",
                ),
                _w(
                    "remember",
                    "keep something in your mind",
                    "Do you remember her name?",
                    ipa="rɪˈmɛmbər",
                    pos="verb",
                    simple="keep in your mind",
                ),
                _w(
                    "forget",
                    "fail to remember",
                    "Don't forget your keys.",
                    ipa="fərˈɡɛt",
                    pos="verb",
                    simple="not remember",
                ),
                _w(
                    "understand",
                    "know what something means",
                    "I understand the question.",
                    example2="Do you understand now?",
                    ipa="ˌʌndərˈstænd",
                    pos="verb",
                    simple="know what it means",
                ),
                _w(
                    "learn",
                    "get new knowledge or a skill",
                    "I want to learn Spanish.",
                    example2="She learned it quickly.",
                    ipa="lɜrn",
                    pos="verb",
                    simple="get new knowledge",
                ),
                _w(
                    "wonder",
                    "want to know something",
                    "I wonder where they went.",
                    example2="She wondered if he was okay.",
                    ipa="ˈwʌndər",
                    pos="verb",
                    simple="want to know",
                ),
                _w(
                    "imagine",
                    "form a picture in your mind",
                    "Imagine you are on a beach.",
                    example2="I can't imagine living there.",
                    ipa="ɪˈmædʒɪn",
                    pos="verb",
                    simple="picture it in your mind",
                ),
                _w(
                    "hope",
                    "want something to happen",
                    "I hope you feel better.",
                    example2="We hope it doesn't rain.",
                    ipa="hoʊp",
                    pos="verb",
                    simple="want it to happen",
                ),
                _w(
                    "doubt",
                    "feel unsure that something is true",
                    "I doubt that's true.",
                    example2="She doubted the story.",
                    ipa="daʊt",
                    pos="verb",
                    simple="not sure it's true",
                ),
                _w(
                    "focus",
                    "give all your attention",
                    "Focus on the question.",
                    example2="He couldn't focus in class.",
                    ipa="ˈfoʊkəs",
                    pos="verb",
                    simple="pay full attention",
                ),
                _w(
                    "plan",
                    "decide how you will do something",
                    "Let's plan the weekend.",
                    example2="She planned every step.",
                    ipa="plæn",
                    pos="verb",
                    simple="decide how to do it",
                ),
                _w(
                    "choose",
                    "pick one option",
                    "Choose a seat.",
                    example2="You can choose the movie.",
                    ipa="tʃuz",
                    pos="verb",
                    simple="pick one",
                ),
            ],
            domain=DOMAIN,
            sort_order=50,
        ),
        _deck(
            "en",
            "conv-notice-decide",
            "Notice and decide",
            [
                _w(
                    "realize",
                    "suddenly understand",
                    "I realize I was wrong.",
                    ipa="ˈriəˌlaɪz",
                    pos="verb",
                    simple="suddenly understand",
                ),
                _w(
                    "notice",
                    "become aware of something",
                    "Did you notice the sign?",
                    ipa="ˈnoʊtɪs",
                    pos="verb",
                    simple="become aware",
                ),
                _w(
                    "guess",
                    "answer without being certain",
                    "Guess who called.",
                    ipa="ɡɛs",
                    pos="verb",
                    simple="answer without being sure",
                ),
                _w(
                    "decide",
                    "make a choice",
                    "We need to decide now.",
                    ipa="dɪˈsaɪd",
                    pos="verb",
                    simple="make a choice",
                ),
            ],
            domain=DOMAIN,
            sort_order=51,
        ),
    ]
