from app.content.vocab_catalog import CatalogDeck, _deck, _w

DOMAIN = "Travel"


def travel_decks() -> list[CatalogDeck]:
    return [
        _deck(
            "en",
            "travel-around",
            "Getting around",
            [
                _w("travel", "to go from one place to another", "I travel for work."),
                _w("trip", "a journey", "A weekend trip."),
                _w("bus", "large road vehicle for passengers", "Take the bus."),
                _w("train", "vehicles on rails", "The train is late."),
                _w("taxi", "car you pay to ride in", "Call a taxi."),
                _w("subway", "underground city train", "Take the subway."),
                _w("car", "road vehicle for a few people", "We rented a car."),
                _w("walk", "to go on foot", "We can walk."),
                _w("map", "drawing of a place", "Look at the map."),
                _w("ticket", "proof you paid to travel", "Buy a ticket."),
                _w("station", "place trains or buses stop", "The train station."),
                _w("stop", "place a bus or train pauses", "Next stop is mine."),
            ],
            domain=DOMAIN,
            sort_order=70,
        ),
        _deck(
            "en",
            "travel-airport",
            "Airport",
            [
                _w("airport", "place planes take off and land", "We're at the airport."),
                _w("plane", "aircraft that flies", "The plane is boarding."),
                _w("flight", "a trip by plane", "The flight is delayed."),
                _w("passport", "travel ID document", "Show your passport."),
                _w("boarding pass", "ticket to get on a plane", "Here's my boarding pass."),
                _w("gate", "door where you board", "Gate 12."),
                _w("luggage", "bags you travel with", "Check your luggage."),
                _w("carry-on", "bag you take on the plane", "One carry-on."),
                _w("security", "airport safety check", "Go through security."),
                _w("delay", "when something is late", "A two-hour delay."),
                _w("arrival", "coming to a place", "Arrival at 6."),
                _w("departure", "leaving a place", "Departure at 9."),
            ],
            domain=DOMAIN,
            sort_order=71,
        ),
        _deck(
            "en",
            "travel-directions",
            "Directions",
            [
                _w("left", "opposite of right", "Turn left."),
                _w("right", "opposite of left", "Turn right."),
                _w("straight", "ahead, not turning", "Go straight."),
                _w("near", "not far", "The bank is near."),
                _w("far", "a long way", "It's far from here."),
                _w("next to", "beside", "Next to the park."),
                _w("across from", "on the other side of", "Across from the hotel."),
                _w("corner", "where two streets meet", "On the corner."),
                _w("block", "distance between streets", "Walk two blocks."),
                _w("north", "toward the top of a map", "Go north."),
                _w("south", "toward the bottom of a map", "Go south."),
                _w("lost", "not knowing where you are", "I am lost."),
            ],
            domain=DOMAIN,
            sort_order=72,
        ),
        _deck(
            "en",
            "travel-tickets",
            "Tickets and places",
            [
                _w("ticket", "proof you paid to enter or travel", "A train ticket."),
                _w("one-way", "travel in one direction only", "A one-way ticket."),
                _w("round trip", "going and coming back", "A round-trip ticket."),
                _w("city", "large town", "A busy city."),
                _w("town", "smaller than a city", "A quiet town."),
                _w("country", "a nation", "Which country?"),
                _w("beach", "sand by the sea", "A sunny beach."),
                _w("museum", "place that shows art or history", "Visit the museum."),
                _w("park", "public green space", "Walk in the park."),
                _w("hotel", "place to stay overnight", "Book a hotel."),
                _w("tourist", "person visiting for pleasure", "Many tourists."),
                _w("souvenir", "thing you buy to remember a trip", "A small souvenir."),
            ],
            domain=DOMAIN,
            sort_order=73,
        ),
    ]
