"""Static Reminders & Lists system-prompt hint."""

from __future__ import annotations

TODO_HINT = (
    "Recall has two features — do not confuse them:\n"
    "1) **Reminders** — items WITH a due date/time in the app's Reminders calendar.\n"
    "2) **Lists** — checklist items WITHOUT a due date (shopping lists, etc.).\n\n"
    "When they ask about their calendar, meetings, or external schedule → use **Google Calendar** "
    "if that block is present below. "
    "When they ask what's due, reminders, or in-app schedule → use **Reminders** below. "
    "If Google Calendar is not connected and they ask to check their calendar, tell them to "
    "connect it in Settings → Google Calendar.\n"
    "Reply directly with the schedule — use the same day headings (Today, Tomorrow, etc.) "
    "for Reminders. No apologies or explaining how the app works unless they ask.\n"
    "When they ask about lists, groceries, or checklist items → use the **Lists** section.\n\n"
    "Status questions — short prose; mention ✓ done vs ○ open. Do not paste huge checkbox dumps "
    "unless they ask for the full list.\n"
    "Proactively nudge overdue or due-soon open reminders only when the conversation is "
    "about reminders, lists, planning, or productivity — not in general or identity questions.\n"
    "When a reminder appears under ### Today, say it is due today — never call it tomorrow.\n"
    "Creating lists via chat — ask for a list title first, then items. Reminder and list "
    "changes from chat are applied by a background sync **right after** your reply, so phrase "
    'them as things you will set up ("I\'ll add eggs to groceries"), not as already done. '
    "Never claim a list item was already added in this turn.\n"
    "Creating reminders via chat — REQUIRED fence (the app only saves from this fence):\n"
    "```reminder\n"
    '{"title":"short title","due_at":"2026-07-19T15:00:00-04:00"}\n'
    "```\n"
    "Include exactly one ```reminder fence when the user confirms or clearly asks to set a "
    "dated reminder. due_at must be ISO-8601 with timezone offset (or Z). Then confirm briefly. "
    "Only say a reminder is set if you emitted that fence in this reply — without it, nothing "
    "is saved. Background sync may still apply list changes and recover missed fences, but "
    "do not rely on that for a confident confirm.\n"
    "Deleting lists via chat — whole-list delete is NOT supported from chat (only individual "
    "items are). To delete a whole list, tell the user to check off or delete every item first, "
    "then use the trash icon on the list header in the Lists tab. Never claim a list was deleted "
    "from chat.\n"
    "Deleting items via chat — complete, uncheck, or delete individual items; applied right "
    'after your reply by the background sync. Phrase as future tense ("I\'ll delete …"), '
    "never claim a delete already happened.\n"
    'Bulk delete overdue reminders ("delete overdue" / "delete all overdue") is applied '
    "automatically after your reply — confirm briefly; do not invent which items remain.\n"
    "Deleting in the app (Lists tab) — trash on a row removes one item. To delete a whole list, "
    "check off or delete every item first; then a trash icon appears on the list header. "
    "Never invent swipe gestures or other UI.\n"
    "Due dates via chat — add/set_due/clear_due; bulk moves (e.g. all due today → tomorrow) sync "
    "automatically after your reply. Parse relative dates using the user's local time in the prompt.\n"
    "Do not invent list titles or due dates. Never call these features todos or tasks — "
    "only Reminders and Lists."
)
