/** A searchable, independently curated physics formula reference. */

export type PhysicsEducationLevel = "middle_school" | "high_school" | "undergraduate";
export type PhysicsFormulaRow = {
  id: string;
  name: string;
  equation: string;
  topicId: string;
  topic: string;
  level: PhysicsEducationLevel;
  note?: string;
};
export type PhysicsTopic = {
  id: string;
  title: string;
  level: PhysicsEducationLevel;
};

type FormulaSeed = readonly [name: string, equation: string, note?: string];
type TopicSeed = PhysicsTopic & { formulas: readonly FormulaSeed[] };

const TOPIC_SEEDS: readonly TopicSeed[] = [
  {
    id: "measurement",
    title: "Measurement and uncertainty",
    level: "middle_school",
    formulas: [
      ["Change in position", String.raw`\Delta x=x_f-x_i`],
      ["Arithmetic mean", String.raw`\bar{x}=\frac{1}{N}\sum_{i=1}^{N}x_i`],
      ["Sample standard deviation", String.raw`s=\sqrt{\frac{\sum_i(x_i-\bar{x})^2}{N-1}}`],
      ["Standard error of the mean", String.raw`\sigma_{\bar{x}}=\frac{s}{\sqrt{N}}`],
      ["Absolute uncertainty", String.raw`\delta x=|x_{measured}-x_{reference}|`],
      ["Fractional uncertainty", String.raw`u_r=\frac{\delta x}{|x|}`],
      ["Percent uncertainty", String.raw`u_{\%}=100\frac{\delta x}{|x|}\%`],
      ["Uncertainty in a sum", String.raw`\delta z=\sqrt{(\delta x)^2+(\delta y)^2},\quad z=x+y`, "For independent random uncertainties; correlated errors require covariance terms."],
      ["Uncertainty in a product", String.raw`\frac{\delta z}{|z|}=\sqrt{\left(\frac{\delta x}{x}\right)^2+\left(\frac{\delta y}{y}\right)^2},\quad z=xy`, "For independent random uncertainties and small relative errors."],
      ["Uncertainty in a power", String.raw`\frac{\delta z}{|z|}=|n|\frac{\delta x}{|x|},\quad z=x^n`],
      ["Dimensional form of force", String.raw`[F]=MLT^{-2}`],
      ["Unit conversion", String.raw`q_{new}=q_{old}\frac{u_{old}}{u_{new}}`],
      ["Radians and arc length", String.raw`\theta=\frac{s}{r}`],
    ],
  },
  {
    id: "vectors",
    title: "Vectors and coordinates",
    level: "high_school",
    formulas: [
      ["Vector magnitude in two dimensions", String.raw`|\vec{A}|=\sqrt{A_x^2+A_y^2}`],
      ["Vector magnitude in three dimensions", String.raw`|\vec{A}|=\sqrt{A_x^2+A_y^2+A_z^2}`],
      ["Cartesian component", String.raw`A_x=A\cos\theta`],
      ["Vertical component", String.raw`A_y=A\sin\theta`],
      ["Vector from components", String.raw`\vec{A}=A_x\hat{i}+A_y\hat{j}+A_z\hat{k}`],
      ["Unit vector", String.raw`\hat{A}=\frac{\vec{A}}{|\vec{A}|}`],
      ["Vector addition", String.raw`\vec{R}=\vec{A}+\vec{B}`],
      ["Dot product", String.raw`\vec{A}\cdot\vec{B}=AB\cos\theta`],
      ["Dot product by components", String.raw`\vec{A}\cdot\vec{B}=A_xB_x+A_yB_y+A_zB_z`],
      ["Cross-product magnitude", String.raw`|\vec{A}\times\vec{B}|=AB\sin\theta`],
      ["Cross product by determinant", String.raw`\vec{A}\times\vec{B}=\begin{vmatrix}\hat{i}&\hat{j}&\hat{k}\\A_x&A_y&A_z\\B_x&B_y&B_z\end{vmatrix}`],
      ["Position vector", String.raw`\vec{r}=x\hat{i}+y\hat{j}+z\hat{k}`],
      ["Displacement vector", String.raw`\Delta\vec{r}=\vec{r}_f-\vec{r}_i`],
    ],
  },
  {
    id: "linear-motion",
    title: "One-dimensional motion",
    level: "middle_school",
    formulas: [
      ["Average speed", String.raw`v_{avg}=\frac{d_{total}}{\Delta t}`],
      ["Average velocity", String.raw`\bar{v}=\frac{\Delta x}{\Delta t}`],
      ["Instantaneous velocity", String.raw`v=\frac{dx}{dt}`],
      ["Average acceleration", String.raw`a_{avg}=\frac{v_f-v_i}{\Delta t}`],
      ["Instantaneous acceleration", String.raw`a=\frac{dv}{dt}`],
      ["Constant-acceleration velocity", String.raw`v_f=v_i+at`],
      ["Constant-acceleration position", String.raw`x_f=x_i+v_it+\frac{1}{2}at^2`],
      ["Velocity-position relation", String.raw`v_f^2=v_i^2+2a(x_f-x_i)`],
      ["Average velocity at constant acceleration", String.raw`\bar{v}=\frac{v_i+v_f}{2}`],
      ["Displacement from average velocity", String.raw`\Delta x=\frac{v_i+v_f}{2}t`],
      ["Free-fall velocity", String.raw`v_y=v_{0y}-gt`],
      ["Free-fall displacement", String.raw`\Delta y=v_{0y}t-\frac{1}{2}gt^2`],
      ["Distance at constant speed", String.raw`d=vt`],
    ],
  },
  {
    id: "projectile-motion",
    title: "Two-dimensional motion and projectiles",
    level: "high_school",
    formulas: [
      ["Horizontal launch speed component", String.raw`v_{0x}=v_0\cos\theta`],
      ["Vertical launch speed component", String.raw`v_{0y}=v_0\sin\theta`],
      ["Horizontal position", String.raw`x=x_0+v_{0x}t`],
      ["Vertical position", String.raw`y=y_0+v_{0y}t-\frac{1}{2}gt^2`],
      ["Horizontal velocity", String.raw`v_x=v_{0x}`],
      ["Vertical velocity", String.raw`v_y=v_{0y}-gt`],
      ["Projectile trajectory", String.raw`y-y_0=(x-x_0)\tan\theta-\frac{g(x-x_0)^2}{2v_0^2\cos^2\theta}`, "Assumes uniform gravity and negligible air resistance."],
      ["Time to peak", String.raw`t_{peak}=\frac{v_0\sin\theta}{g}`],
      ["Maximum height", String.raw`H=\frac{v_0^2\sin^2\theta}{2g}`],
      ["Flight time at equal launch and landing heights", String.raw`T=\frac{2v_0\sin\theta}{g}`],
      ["Range at equal launch and landing heights", String.raw`R=\frac{v_0^2\sin(2\theta)}{g}`],
      ["Horizontal-launch flight time", String.raw`t=\sqrt{\frac{2h}{g}}`, "Assumes a level landing surface, uniform gravity, and negligible air resistance."],
      ["Horizontal-launch range", String.raw`R=v_0\sqrt{\frac{2h}{g}}`, "Assumes a level landing surface, uniform gravity, and negligible air resistance."],
    ],
  },
  {
    id: "newtons-laws",
    title: "Newton’s laws and forces",
    level: "middle_school",
    formulas: [
      ["Newton’s second law", String.raw`\sum\vec{F}=m\vec{a}`],
      ["Weight near a planet’s surface", String.raw`W=mg`],
      ["Newton’s third law", String.raw`\vec{F}_{AB}=-\vec{F}_{BA}`],
      ["Net force from components", String.raw`F_{net,x}=\sum_iF_{i,x}`],
      ["Normal force on a level surface", String.raw`N=mg`, "For a horizontal surface with no vertical acceleration or other vertical forces."],
      ["Normal force on an incline", String.raw`N=mg\cos\theta`, "For an incline with no acceleration perpendicular to its surface."],
      ["Component of weight down an incline", String.raw`F_{g,\parallel}=mg\sin\theta`],
      ["Component of weight perpendicular to an incline", String.raw`F_{g,\perp}=mg\cos\theta`],
      ["Tension for a hanging mass at rest", String.raw`T=mg`, "For a stationary mass (or one moving at constant velocity)."],
      ["Apparent weight in an upward elevator", String.raw`N=m(g+a)`, "The elevator's acceleration is upward; a is its magnitude."],
      ["Apparent weight in a downward elevator", String.raw`N=m(g-a)`, "The elevator accelerates downward with magnitude a < g."],
      ["Spring force magnitude", String.raw`F_s=k|x|`],
      ["Hooke’s law with sign", String.raw`F_s=-kx`],
    ],
  },
  {
    id: "friction-drag-circular",
    title: "Friction, drag, and circular motion",
    level: "high_school",
    formulas: [
      ["Static friction limit", String.raw`f_s\leq\mu_sN`],
      ["Maximum static friction", String.raw`f_{s,max}=\mu_sN`],
      ["Kinetic friction", String.raw`f_k=\mu_kN`],
      ["Centripetal acceleration", String.raw`a_c=\frac{v^2}{r}`],
      ["Centripetal force", String.raw`F_c=\frac{mv^2}{r}`],
      ["Angular speed from period", String.raw`\omega=\frac{2\pi}{T}`],
      ["Tangential speed", String.raw`v=r\omega`],
      ["Centripetal acceleration from angular speed", String.raw`a_c=r\omega^2`],
      ["Banked turn without friction", String.raw`\tan\theta=\frac{v^2}{rg}`],
      ["Flat-road maximum speed", String.raw`v_{max}=\sqrt{\mu_srg}`],
      ["Linear drag at low speed", String.raw`F_D=bv`],
      ["Quadratic drag", String.raw`F_D=\frac{1}{2}C_D\rho Av^2`],
      ["Terminal speed with linear drag", String.raw`v_t=\frac{mg}{b}`, "For downward motion when drag force has magnitude bv and balances weight."],
    ],
  },
  {
    id: "work-energy",
    title: "Work, energy, power, and machines",
    level: "middle_school",
    formulas: [
      ["Work by a constant force", String.raw`W=Fd\cos\theta`],
      ["Kinetic energy", String.raw`K=\frac{1}{2}mv^2`],
      ["Gravitational potential energy near Earth", String.raw`U_g=mgh`],
      ["Elastic potential energy", String.raw`U_s=\frac{1}{2}kx^2`],
      ["Work-energy theorem", String.raw`W_{net}=\Delta K`],
      ["Mechanical energy", String.raw`E_{mech}=K+U`],
      ["Conservation of mechanical energy", String.raw`K_i+U_i=K_f+U_f`],
      ["Power from work", String.raw`P_{avg}=\frac{W}{\Delta t}`],
      ["Instantaneous mechanical power", String.raw`P=\vec{F}\cdot\vec{v}`],
      ["Efficiency", String.raw`\eta=\frac{W_{out}}{W_{in}}\times100\%`],
      ["Mechanical advantage from forces", String.raw`MA=\frac{F_{out}}{F_{in}}`],
      ["Ideal inclined-plane advantage", String.raw`MA=\frac{L}{h}`, "Ideal machine: no friction or energy loss."],
      ["Ideal pulley advantage", String.raw`MA=n_{support}`, "Ideal, massless pulley and rope; n counts rope segments supporting the load."],
      ["Ideal wheel-and-axle advantage", String.raw`MA=\frac{R}{r}`, "Ideal machine: R is the wheel radius and r is the axle radius."],
      ["Ideal gear advantage", String.raw`MA=\frac{N_{out}}{N_{in}}`, "N counts gear teeth; ideal gears mesh without slipping."],
      ["Ideal screw advantage", String.raw`MA=\frac{2\pi L}{p}`, "L is the handle arm and p is the thread pitch; friction is neglected."],
      ["Ideal wedge advantage", String.raw`MA=\frac{L}{w}`, "L is wedge length and w is its thickness; friction is neglected."],
    ],
  },
  {
    id: "momentum-collisions",
    title: "Momentum, impulse, and collisions",
    level: "high_school",
    formulas: [
      ["Linear momentum", String.raw`\vec{p}=m\vec{v}`],
      ["Impulse", String.raw`\vec{J}=\vec{F}_{avg}\Delta t`],
      ["Impulse-momentum theorem", String.raw`\vec{J}=\Delta\vec{p}`],
      ["Momentum conservation", String.raw`\sum_i\vec{p}_i=\sum_f\vec{p}_f`],
      ["Center-of-mass position", String.raw`\vec{r}_{cm}=\frac{\sum_i m_i\vec{r}_i}{\sum_i m_i}`],
      ["Center-of-mass velocity", String.raw`\vec{v}_{cm}=\frac{\sum_i m_i\vec{v}_i}{\sum_i m_i}`],
      ["Center-of-mass acceleration", String.raw`M\vec{a}_{cm}=\sum\vec{F}_{ext}`],
      ["Perfectly inelastic final speed", String.raw`v_f=\frac{m_1v_{1i}+m_2v_{2i}}{m_1+m_2}`],
      ["Elastic-collision relative speed", String.raw`v_{1i}-v_{2i}=-(v_{1f}-v_{2f})`],
      ["Coefficient of restitution", String.raw`e=\frac{v_{2f}-v_{1f}}{v_{1i}-v_{2i}}`],
      ["Rocket thrust", String.raw`F_T=u\frac{dm}{dt}`],
      ["Rocket equation", String.raw`\Delta v=u\ln\frac{m_i}{m_f}`],
    ],
  },
  {
    id: "rotational-kinematics",
    title: "Rotational kinematics",
    level: "high_school",
    formulas: [
      ["Angular displacement", String.raw`\Delta\theta=\theta_f-\theta_i`],
      ["Average angular velocity", String.raw`\omega_{avg}=\frac{\Delta\theta}{\Delta t}`],
      ["Angular velocity", String.raw`\omega=\frac{d\theta}{dt}`],
      ["Average angular acceleration", String.raw`\alpha_{avg}=\frac{\omega_f-\omega_i}{\Delta t}`],
      ["Angular acceleration", String.raw`\alpha=\frac{d\omega}{dt}`],
      ["Angular velocity at constant acceleration", String.raw`\omega_f=\omega_i+\alpha t`],
      ["Angular position at constant acceleration", String.raw`\theta_f=\theta_i+\omega_it+\frac{1}{2}\alpha t^2`],
      ["Angular velocity-position relation", String.raw`\omega_f^2=\omega_i^2+2\alpha\Delta\theta`],
      ["Arc length", String.raw`s=r\theta`],
      ["Tangential acceleration", String.raw`a_t=r\alpha`],
      ["Radial acceleration", String.raw`a_r=r\omega^2`],
      ["Rotational frequency", String.raw`f=\frac{\omega}{2\pi}`],
    ],
  },
  {
    id: "rotational-dynamics",
    title: "Torque and rotational dynamics",
    level: "undergraduate",
    formulas: [
      ["Torque magnitude", String.raw`\tau=rF\sin\theta`],
      ["Vector torque", String.raw`\vec{\tau}=\vec{r}\times\vec{F}`],
      ["Rotational Newton’s second law", String.raw`\sum\tau=I\alpha`],
      ["Moment of inertia for point masses", String.raw`I=\sum_i m_ir_i^2`],
      ["Rotational kinetic energy", String.raw`K_{rot}=\frac{1}{2}I\omega^2`],
      ["Rotational work", String.raw`W=\int_{\theta_i}^{\theta_f}\tau\,d\theta`],
      ["Rotational power", String.raw`P=\tau\omega`],
      ["Parallel-axis theorem", String.raw`I=I_{cm}+Md^2`],
      ["Perpendicular-axis theorem", String.raw`I_z=I_x+I_y`],
      ["Uniform solid disk inertia", String.raw`I=\frac{1}{2}MR^2`],
      ["Uniform rod about its center", String.raw`I=\frac{1}{12}ML^2`],
      ["Uniform rod about one end", String.raw`I=\frac{1}{3}ML^2`],
      ["Thin hoop inertia", String.raw`I=MR^2`],
    ],
  },
  {
    id: "angular-momentum-rolling",
    title: "Angular momentum and rolling",
    level: "undergraduate",
    formulas: [
      ["Angular momentum of a rigid body", String.raw`L=I\omega`],
      ["Angular momentum of a particle", String.raw`\vec{L}=\vec{r}\times\vec{p}`],
      ["Torque and angular momentum", String.raw`\vec{\tau}_{net}=\frac{d\vec{L}}{dt}`],
      ["Angular momentum conservation", String.raw`\vec{L}_i=\vec{L}_f`],
      ["Rolling without slipping", String.raw`v_{cm}=R\omega`],
      ["Rolling acceleration constraint", String.raw`a_{cm}=R\alpha`],
      ["Total rolling kinetic energy", String.raw`K=\frac{1}{2}Mv_{cm}^2+\frac{1}{2}I_{cm}\omega^2`],
      ["Rolling body down an incline", String.raw`a_{cm}=\frac{g\sin\theta}{1+I_{cm}/(MR^2)}`],
      ["Angular impulse", String.raw`\Delta L=\tau_{avg}\Delta t`],
      ["Gyroscopic precession rate", String.raw`\Omega_p=\frac{\tau}{L}`],
      ["Rotational collision conservation", String.raw`I_i\omega_i=I_f\omega_f`],
      ["Areal velocity", String.raw`\frac{dA}{dt}=\frac{L}{2m}`],
      ["Angular momentum of a circular orbit", String.raw`L=mrv`],
    ],
  },
  {
    id: "statics-elasticity",
    title: "Equilibrium and elasticity",
    level: "high_school",
    formulas: [
      ["Translational equilibrium", String.raw`\sum\vec{F}=0`],
      ["Rotational equilibrium", String.raw`\sum\vec{\tau}=0`],
      ["Lever balance", String.raw`F_1d_1=F_2d_2`],
      ["Center of gravity", String.raw`\vec{r}_{cg}=\frac{\sum_i m_i\vec{r}_i}{\sum_i m_i}`],
      ["Normal stress", String.raw`\sigma=\frac{F_\perp}{A}`],
      ["Longitudinal strain", String.raw`\epsilon=\frac{\Delta L}{L_0}`],
      ["Young’s modulus", String.raw`Y=\frac{\sigma}{\epsilon}`],
      ["Shear stress", String.raw`\tau=\frac{F_{\parallel}}{A}`],
      ["Shear strain", String.raw`\gamma=\frac{\Delta x}{h}`],
      ["Shear modulus", String.raw`G=\frac{\tau}{\gamma}`],
      ["Bulk modulus", String.raw`B=-\frac{\Delta P}{\Delta V/V}`],
      ["Poisson ratio", String.raw`\nu=-\frac{\epsilon_{transverse}}{\epsilon_{longitudinal}}`],
      ["Elastic potential energy density", String.raw`u=\frac{1}{2}\sigma\epsilon`],
    ],
  },
  {
    id: "gravitation-orbits",
    title: "Gravitation and orbits",
    level: "high_school",
    formulas: [
      ["Newton’s law of gravitation", String.raw`F=G\frac{m_1m_2}{r^2}`],
      ["Gravitational field strength", String.raw`g=\frac{GM}{r^2}`],
      ["Gravitational potential energy", String.raw`U=-\frac{GMm}{r}`],
      ["Gravitational potential", String.raw`\Phi_g=-\frac{GM}{r}`],
      ["Circular-orbit speed", String.raw`v=\sqrt{\frac{GM}{r}}`],
      ["Circular-orbit period", String.raw`T=2\pi\sqrt{\frac{r^3}{GM}}`],
      ["Kepler’s third law", String.raw`T^2=\frac{4\pi^2}{GM}a^3`],
      ["Escape speed", String.raw`v_{esc}=\sqrt{\frac{2GM}{r}}`],
      ["Gravitational potential energy near a surface", String.raw`\Delta U=mg\Delta h`],
      ["Orbital kinetic energy", String.raw`K=\frac{GMm}{2r}`],
      ["Total energy of a circular orbit", String.raw`E=-\frac{GMm}{2r}`],
      ["Geostationary orbital radius", String.raw`r=\left(\frac{GMT^2}{4\pi^2}\right)^{1/3}`],
    ],
  },
  {
    id: "fluids",
    title: "Fluids, pressure, and buoyancy",
    level: "middle_school",
    formulas: [
      ["Density", String.raw`\rho=\frac{m}{V}`],
      ["Pressure", String.raw`P=\frac{F}{A}`],
      ["Hydrostatic pressure increase", String.raw`\Delta P=\rho gh`],
      ["Absolute pressure at depth", String.raw`P=P_0+\rho gh`],
      ["Pascal’s principle", String.raw`\frac{F_1}{A_1}=\frac{F_2}{A_2}`],
      ["Buoyant force", String.raw`F_B=\rho_f gV_{displaced}`],
      ["Floating condition", String.raw`F_B=W,\quad \rho_{obj}\leq\rho_f`, "For a freely floating object in static equilibrium."],
      ["Fraction submerged", String.raw`\frac{V_{sub}}{V_{obj}}=\frac{\rho_{obj}}{\rho_f}`],
      ["Volume flow rate", String.raw`Q=\frac{dV}{dt}`],
      ["Continuity for incompressible flow", String.raw`A_1v_1=A_2v_2`],
      ["Mass continuity", String.raw`\rho_1A_1v_1=\rho_2A_2v_2`],
      ["Bernoulli equation", String.raw`P+\frac{1}{2}\rho v^2+\rho gy=constant`],
      ["Poiseuille flow rate", String.raw`Q=\frac{\pi r^4\Delta P}{8\eta L}`],
      ["Standard atmospheric pressure near sea level", String.raw`P_{atm}\approx101.3\,\mathrm{kPa}`, "Rounded reference value; the standard atmosphere is exactly 101325 Pa."],
    ],
  },
  {
    id: "oscillations",
    title: "Oscillations and springs",
    level: "high_school",
    formulas: [
      ["Hooke’s law", String.raw`F=-kx`],
      ["Simple-harmonic displacement", String.raw`x(t)=A\cos(\omega t+\phi)`],
      ["Simple-harmonic velocity", String.raw`v(t)=-A\omega\sin(\omega t+\phi)`],
      ["Simple-harmonic acceleration", String.raw`a(t)=-\omega^2x(t)`],
      ["Spring angular frequency", String.raw`\omega=\sqrt{\frac{k}{m}}`],
      ["Mass-spring period", String.raw`T=2\pi\sqrt{\frac{m}{k}}`],
      ["Simple-pendulum period", String.raw`T=2\pi\sqrt{\frac{L}{g}}`],
      ["Physical-pendulum period", String.raw`T=2\pi\sqrt{\frac{I}{mgd}}`],
      ["Energy in simple harmonic motion", String.raw`E=\frac{1}{2}kA^2`],
      ["Potential energy in a spring", String.raw`U=\frac{1}{2}kx^2`],
      ["Maximum speed in SHM", String.raw`v_{max}=A\omega`],
      ["Maximum acceleration in SHM", String.raw`a_{max}=A\omega^2`],
      ["Damped oscillator envelope", String.raw`A(t)=A_0e^{-bt/(2m)}`],
    ],
  },
  {
    id: "mechanical-waves",
    title: "Mechanical waves",
    level: "high_school",
    formulas: [
      ["Wave speed", String.raw`v=f\lambda`],
      ["Frequency and period", String.raw`f=\frac{1}{T}`],
      ["Angular frequency", String.raw`\omega=2\pi f`],
      ["Wave number", String.raw`k=\frac{2\pi}{\lambda}`],
      ["Traveling wave", String.raw`y(x,t)=A\sin(kx-\omega t+\phi)`],
      ["Wave speed on a string", String.raw`v=\sqrt{\frac{T}{\mu}}`],
      ["Average wave power on a string", String.raw`P_{avg}=\frac{1}{2}\mu\omega^2A^2v`],
      ["Wave intensity", String.raw`I=\frac{P}{A}`],
      ["Standing-wave string frequencies", String.raw`f_n=\frac{nv}{2L}`],
      ["Standing-wave nodes", String.raw`x_n=\frac{n\lambda}{2}`],
      ["Beat frequency", String.raw`f_{beat}=|f_1-f_2|`],
      ["Wave equation", String.raw`\frac{\partial^2y}{\partial x^2}=\frac{1}{v^2}\frac{\partial^2y}{\partial t^2}`],
      ["Energy density of a sinusoidal wave", String.raw`u=\frac{1}{2}\mu\omega^2A^2`],
    ],
  },
  {
    id: "sound",
    title: "Sound",
    level: "high_school",
    formulas: [
      ["Sound level", String.raw`\beta=10\log_{10}\left(\frac{I}{I_0}\right)`],
      ["Spherical sound intensity", String.raw`I=\frac{P}{4\pi r^2}`],
      ["Speed of sound in air at 20 °C", String.raw`v_{sound}\approx343\,\mathrm{m/s}`, "Approximate value for dry air near room temperature."],
      ["Sound pressure level", String.raw`L_p=20\log_{10}\left(\frac{p_{rms}}{p_0}\right)`],
      ["Doppler shift for a moving observer", String.raw`f'=f\frac{v+v_o}{v}`],
      ["Doppler shift for a moving source", String.raw`f'=f\frac{v}{v-v_s}`],
      ["General Doppler equation", String.raw`f'=f\frac{v\pm v_o}{v\mp v_s}`],
      ["Echo distance", String.raw`d=\frac{vt}{2}`],
      ["Open-open pipe harmonics", String.raw`f_n=\frac{nv}{2L}`],
      ["Open-closed pipe harmonics", String.raw`f_n=\frac{(2n-1)v}{4L}`],
      ["Sonic boom Mach angle", String.raw`\sin\theta=\frac{v_{sound}}{v_s}`],
      ["Speed of sound in an ideal gas", String.raw`v=\sqrt{\frac{\gamma RT}{M}}`],
      ["Intensity from displacement amplitude", String.raw`I=\frac{1}{2}\rho v\omega^2s_m^2`],
    ],
  },
  {
    id: "heat-temperature",
    title: "Temperature and heat transfer",
    level: "middle_school",
    formulas: [
      ["Celsius to kelvin", String.raw`T_K=T_C+273.15`],
      ["Celsius to Fahrenheit", String.raw`T_F=\frac{9}{5}T_C+32`],
      ["Fahrenheit to Celsius", String.raw`T_C=\frac{5}{9}(T_F-32)`],
      ["Heat from temperature change", String.raw`Q=mc\Delta T`],
      ["Heat during a phase change", String.raw`Q=mL`],
      ["Thermal energy balance", String.raw`Q_{lost}+Q_{gained}=0`],
      ["Linear thermal expansion", String.raw`\Delta L=\alpha L_0\Delta T`],
      ["Area thermal expansion", String.raw`\Delta A=2\alpha A_0\Delta T`],
      ["Volume thermal expansion", String.raw`\Delta V=\beta V_0\Delta T`],
      ["Heat conduction rate", String.raw`\frac{Q}{t}=\frac{kA(T_h-T_c)}{L}`],
      ["Thermal resistance", String.raw`R_{th}=\frac{L}{kA}`],
      ["Newton cooling law", String.raw`T(t)=T_{env}+(T_0-T_{env})e^{-t/\tau}`],
      ["Radiated power", String.raw`P=\epsilon\sigma A(T^4-T_{env}^4)`],
    ],
  },
  {
    id: "kinetic-theory",
    title: "Kinetic theory and ideal gases",
    level: "high_school",
    formulas: [
      ["Ideal gas law", String.raw`PV=nRT`, "Applies to an ideal-gas model; real gases approach it at low density."],
      ["Molecular ideal gas law", String.raw`PV=Nk_BT`],
      ["Combined gas law", String.raw`\frac{P_1V_1}{T_1}=\frac{P_2V_2}{T_2}`],
      ["Boyle’s law", String.raw`P_1V_1=P_2V_2`],
      ["Charles’s law", String.raw`\frac{V_1}{T_1}=\frac{V_2}{T_2}`],
      ["Gay-Lussac’s law", String.raw`\frac{P_1}{T_1}=\frac{P_2}{T_2}`],
      ["Avogadro’s law", String.raw`\frac{V_1}{n_1}=\frac{V_2}{n_2}`],
      ["Number density", String.raw`n_V=\frac{N}{V}`],
      ["Mean translational kinetic energy", String.raw`\langle K\rangle=\frac{3}{2}k_BT`],
      ["RMS molecular speed", String.raw`v_{rms}=\sqrt{\frac{3RT}{M}}`],
      ["Most probable molecular speed", String.raw`v_{mp}=\sqrt{\frac{2RT}{M}}`],
      ["Mean molecular speed", String.raw`\bar{v}=\sqrt{\frac{8RT}{\pi M}}`],
      ["Ideal-gas pressure from molecular motion", String.raw`P=\frac{1}{3}\rho v_{rms}^2`],
    ],
  },
  {
    id: "thermodynamics",
    title: "Thermodynamics and heat engines",
    level: "undergraduate",
    formulas: [
      ["First law with work done by the system", String.raw`\Delta U=Q-W`],
      ["Work at constant pressure", String.raw`W=P\Delta V`],
      ["Work by a gas", String.raw`W=\int_{V_i}^{V_f}P\,dV`],
      ["Internal energy of a monatomic ideal gas", String.raw`U=\frac{3}{2}nRT`],
      ["Internal energy of a diatomic ideal gas", String.raw`U=\frac{5}{2}nRT`],
      ["Molar heat capacity at constant volume", String.raw`C_V=\frac{1}{n}\left(\frac{\partial Q}{\partial T}\right)_V`],
      ["Molar heat capacity at constant pressure", String.raw`C_P=\frac{1}{n}\left(\frac{\partial Q}{\partial T}\right)_P`],
      ["Mayer relation", String.raw`C_P-C_V=R`],
      ["Adiabatic ideal-gas relation", String.raw`PV^\gamma=constant`],
      ["Adiabatic temperature-volume relation", String.raw`TV^{\gamma-1}=constant`],
      ["Carnot efficiency", String.raw`\eta_C=1-\frac{T_C}{T_H}`, "Maximum efficiency for a reversible engine operating between absolute temperatures."],
      ["Heat-engine efficiency", String.raw`\eta=\frac{W_{out}}{Q_H}=1-\frac{Q_C}{Q_H}`],
      ["Otto-cycle efficiency", String.raw`\eta_O=1-r^{1-\gamma}`],
    ],
  },
  {
    id: "electrostatics",
    title: "Electric charge and Coulomb’s law",
    level: "high_school",
    formulas: [
      ["Quantization of charge", String.raw`q=ne`],
      ["Coulomb’s law magnitude", String.raw`F=k_e\frac{|q_1q_2|}{r^2}`],
      ["Coulomb force vector", String.raw`\vec{F}_{12}=k_e\frac{q_1q_2}{r^2}\hat{r}_{12}`],
      ["Superposition of electric forces", String.raw`\vec{F}_{net}=\sum_i\vec{F}_i`],
      ["Charge density per length", String.raw`\lambda=\frac{dq}{dl}`],
      ["Charge density per area", String.raw`\sigma=\frac{dq}{dA}`],
      ["Charge density per volume", String.raw`\rho_q=\frac{dq}{dV}`],
      ["Charge conservation", String.raw`Q_{initial}=Q_{final}`],
      ["Electric dipole moment", String.raw`\vec{p}=q\vec{d}`],
      ["Dipole torque", String.raw`\vec{\tau}=\vec{p}\times\vec{E}`],
      ["Dipole potential energy", String.raw`U=-\vec{p}\cdot\vec{E}`],
      ["Electrostatic force from potential energy", String.raw`\vec{F}=-\nabla U`],
      ["Coulomb constant", String.raw`k_e=\frac{1}{4\pi\epsilon_0}`],
    ],
  },
  {
    id: "electric-fields-gauss",
    title: "Electric fields and Gauss’s law",
    level: "high_school",
    formulas: [
      ["Electric field definition", String.raw`\vec{E}=\frac{\vec{F}}{q}`],
      ["Point-charge electric field", String.raw`E=k_e\frac{|q|}{r^2}`],
      ["Force on a charge in an electric field", String.raw`\vec{F}=q\vec{E}`],
      ["Uniform field between plates", String.raw`E=\frac{\Delta V}{d}`],
      ["Electric flux", String.raw`\Phi_E=\int\vec{E}\cdot d\vec{A}`],
      ["Gauss’s law", String.raw`\oint\vec{E}\cdot d\vec{A}=\frac{Q_{enc}}{\epsilon_0}`],
      ["Field of an infinite line charge", String.raw`E=\frac{\lambda}{2\pi\epsilon_0r}`],
      ["Field of an infinite sheet", String.raw`E=\frac{\sigma}{2\epsilon_0}`],
      ["Field between oppositely charged plates", String.raw`E=\frac{\sigma}{\epsilon_0}`],
      ["Field outside a spherical charge", String.raw`E=k_e\frac{Q}{r^2}`],
      ["Field inside a uniformly charged sphere", String.raw`E=k_e\frac{Qr}{R^3}`],
      ["Electric field from potential", String.raw`\vec{E}=-\nabla V`],
      ["Electric displacement field", String.raw`\vec{D}=\epsilon_0\vec{E}+\vec{P}`],
    ],
  },
  {
    id: "electric-potential",
    title: "Electric potential and energy",
    level: "high_school",
    formulas: [
      ["Potential difference", String.raw`\Delta V=-\int_A^B\vec{E}\cdot d\vec{l}`],
      ["Electric potential energy", String.raw`U=qV`],
      ["Potential of a point charge", String.raw`V=k_e\frac{q}{r}`],
      ["Potential from multiple point charges", String.raw`V=\sum_i k_e\frac{q_i}{r_i}`],
      ["Potential energy of two charges", String.raw`U=k_e\frac{q_1q_2}{r}`],
      ["Work by an electric field", String.raw`W_E=-\Delta U`],
      ["Electron-volt conversion", String.raw`1\,eV=e\cdot1\,V`],
      ["Potential energy of a dipole", String.raw`U=-\vec{p}\cdot\vec{E}`],
      ["Potential of a continuous distribution", String.raw`V=k_e\int\frac{dq}{r}`],
      ["Potential outside a charged sphere", String.raw`V=k_e\frac{Q}{r}`],
      ["Potential inside a charged conducting shell", String.raw`V=k_e\frac{Q}{R}`],
      ["Potential energy of a system of charges", String.raw`U=\frac{1}{2}\sum_iq_iV_i`],
      ["Electric field in one dimension", String.raw`E_x=-\frac{dV}{dx}`],
    ],
  },
  {
    id: "capacitance",
    title: "Capacitance and dielectrics",
    level: "high_school",
    formulas: [
      ["Capacitance", String.raw`C=\frac{Q}{\Delta V}`],
      ["Parallel-plate capacitance", String.raw`C=\epsilon_0\frac{A}{d}`],
      ["Capacitance with dielectric", String.raw`C=\kappa\epsilon_0\frac{A}{d}`],
      ["Isolated spherical capacitance", String.raw`C=4\pi\epsilon_0R`],
      ["Capacitors in parallel", String.raw`C_{eq}=\sum_iC_i`],
      ["Capacitors in series", String.raw`\frac{1}{C_{eq}}=\sum_i\frac{1}{C_i}`],
      ["Energy stored in a capacitor", String.raw`U=\frac{1}{2}C(\Delta V)^2`],
      ["Capacitor energy from charge", String.raw`U=\frac{Q^2}{2C}`],
      ["Electric energy density", String.raw`u_E=\frac{1}{2}\epsilon E^2`],
      ["RC time constant", String.raw`\tau=RC`],
      ["Charging capacitor voltage", String.raw`V_C(t)=V_0(1-e^{-t/RC})`],
      ["Discharging capacitor voltage", String.raw`V_C(t)=V_0e^{-t/RC}`],
    ],
  },
  {
    id: "current-resistance",
    title: "Current, resistance, and resistivity",
    level: "middle_school",
    formulas: [
      ["Electric current", String.raw`I=\frac{dQ}{dt}`],
      ["Charge flow", String.raw`Q=It`],
      ["Ohm’s law", String.raw`V=IR`],
      ["Resistance from resistivity", String.raw`R=\rho\frac{L}{A}`],
      ["Conductivity", String.raw`\sigma=\frac{1}{\rho}`],
      ["Current density", String.raw`J=\frac{I}{A}`],
      ["Microscopic Ohm’s law", String.raw`\vec{J}=\sigma\vec{E}`],
      ["Drift current", String.raw`I=nqAv_d`],
      ["Drift speed", String.raw`v_d=\frac{I}{nqA}`],
      ["Temperature dependence of resistance", String.raw`R=R_0[1+\alpha(T-T_0)]`],
      ["Power dissipated in a resistor", String.raw`P=I^2R`],
    ],
  },
  {
    id: "dc-circuits",
    title: "DC circuits and electrical power",
    level: "middle_school",
    formulas: [
      ["Electrical power", String.raw`P=IV`],
      ["Electrical energy", String.raw`E=Pt`],
      ["Resistors in series", String.raw`R_{eq}=\sum_iR_i`],
      ["Resistors in parallel", String.raw`\frac{1}{R_{eq}}=\sum_i\frac{1}{R_i}`],
      ["Kirchhoff’s current law", String.raw`\sum I_{in}=\sum I_{out}`],
      ["Kirchhoff’s voltage law", String.raw`\sum_{loop}\Delta V=0`],
      ["Terminal voltage of a source", String.raw`V_{term}=\mathcal{E}-Ir`],
      ["RC charging current", String.raw`I(t)=\frac{\mathcal{E}}{R}e^{-t/RC}`],
      ["Cells in series", String.raw`\mathcal{E}_{eq}=\sum_i\mathcal{E}_i`],
      ["Energy cost", String.raw`Cost=E_{kWh}\times rate`],
      ["Kilowatt-hour conversion", String.raw`1\,kWh=3.6\times10^6\,J`],
    ],
  },
  {
    id: "magnetic-forces",
    title: "Magnetic forces",
    level: "high_school",
    formulas: [
      ["Magnetic force on a charge", String.raw`\vec{F}=q\vec{v}\times\vec{B}`],
      ["Magnetic force magnitude", String.raw`F=|q|vB\sin\theta`],
      ["Force on a current-carrying wire", String.raw`\vec{F}=I\vec{L}\times\vec{B}`],
      ["Magnetic force on a wire magnitude", String.raw`F=ILB\sin\theta`],
      ["Cyclotron radius", String.raw`r=\frac{mv}{|q|B}`],
      ["Cyclotron angular frequency", String.raw`\omega_c=\frac{|q|B}{m}`],
      ["Cyclotron period", String.raw`T=\frac{2\pi m}{|q|B}`],
      ["Velocity selector", String.raw`v=\frac{E}{B}`],
      ["Hall voltage", String.raw`V_H=\frac{IB}{nqt}`],
      ["Magnetic dipole moment of a loop", String.raw`\vec{\mu}=NI A\hat{n}`],
      ["Torque on a magnetic dipole", String.raw`\vec{\tau}=\vec{\mu}\times\vec{B}`],
      ["Potential energy of a magnetic dipole", String.raw`U=-\vec{\mu}\cdot\vec{B}`],
    ],
  },
  {
    id: "magnetic-fields",
    title: "Magnetic fields and their sources",
    level: "high_school",
    formulas: [
      ["Biot–Savart law", String.raw`d\vec{B}=\frac{\mu_0}{4\pi}\frac{I\,d\vec{l}\times\hat{r}}{r^2}`],
      ["Field around a long straight wire", String.raw`B=\frac{\mu_0I}{2\pi r}`],
      ["Field at the center of a circular loop", String.raw`B=\frac{\mu_0NI}{2R}`],
      ["Ampère’s law", String.raw`\oint\vec{B}\cdot d\vec{l}=\mu_0I_{enc}`],
      ["Field inside a long solenoid", String.raw`B=\mu_0nI`],
      ["Field inside a toroid", String.raw`B=\frac{\mu_0NI}{2\pi r}`],
      ["Force per length between parallel currents", String.raw`\frac{F}{L}=\frac{\mu_0I_1I_2}{2\pi r}`],
      ["Magnetic flux", String.raw`\Phi_B=\int\vec{B}\cdot d\vec{A}`],
      ["Magnetic Gauss law", String.raw`\oint\vec{B}\cdot d\vec{A}=0`],
      ["Magnetic field of a dipole on its axis", String.raw`B_{axis}=\frac{\mu_0}{4\pi}\frac{2\mu}{r^3}`],
      ["Magnetic field of a dipole on its equator", String.raw`B_{eq}=\frac{\mu_0}{4\pi}\frac{\mu}{r^3}`],
      ["Magnetization and field", String.raw`\vec{B}=\mu_0(\vec{H}+\vec{M})`],
    ],
  },
  {
    id: "induction",
    title: "Electromagnetic induction",
    level: "high_school",
    formulas: [
      ["Faraday’s law", String.raw`\mathcal{E}=-N\frac{d\Phi_B}{dt}`],
      ["Motional emf", String.raw`\mathcal{E}=BLv`],
      ["Lenz’s law direction", String.raw`\mathcal{E}_{ind}=-\frac{d\Phi_B}{dt}`],
      ["Magnetic flux through a flat loop", String.raw`\Phi_B=BA\cos\theta`],
      ["Self-inductance", String.raw`\mathcal{E}_L=-L\frac{dI}{dt}`],
      ["Inductance of a solenoid", String.raw`L=\mu_0\frac{N^2A}{l}`],
      ["Energy stored in an inductor", String.raw`U_B=\frac{1}{2}LI^2`],
      ["Magnetic energy density", String.raw`u_B=\frac{B^2}{2\mu_0}`],
      ["RL time constant", String.raw`\tau=\frac{L}{R}`],
      ["RL current growth", String.raw`I(t)=\frac{\mathcal{E}}{R}(1-e^{-tR/L})`],
      ["RL current decay", String.raw`I(t)=I_0e^{-tR/L}`],
      ["Mutual inductance", String.raw`\mathcal{E}_2=-M\frac{dI_1}{dt}`],
    ],
  },
  {
    id: "ac-circuits",
    title: "AC circuits and transformers",
    level: "undergraduate",
    formulas: [
      ["Sinusoidal voltage", String.raw`V(t)=V_0\sin(\omega t)`],
      ["RMS voltage", String.raw`V_{rms}=\frac{V_0}{\sqrt{2}}`],
      ["RMS current", String.raw`I_{rms}=\frac{I_0}{\sqrt{2}}`],
      ["Inductive reactance", String.raw`X_L=\omega L`],
      ["Capacitive reactance", String.raw`X_C=\frac{1}{\omega C}`],
      ["Series RLC impedance magnitude", String.raw`|Z|=\sqrt{R^2+(X_L-X_C)^2}`, "Magnitude for a series circuit; complex impedance is Z = R + i(X_L − X_C)."],
      ["AC Ohm’s law", String.raw`I_{rms}=\frac{V_{rms}}{Z}`],
      ["RLC phase angle", String.raw`\tan\phi=\frac{X_L-X_C}{R}`],
      ["Average AC power", String.raw`P_{avg}=V_{rms}I_{rms}\cos\phi`],
      ["Resonance angular frequency", String.raw`\omega_0=\frac{1}{\sqrt{LC}}`],
      ["Ideal transformer voltage ratio", String.raw`\frac{V_s}{V_p}=\frac{N_s}{N_p}`],
      ["Ideal transformer current ratio", String.raw`\frac{I_s}{I_p}=\frac{N_p}{N_s}`],
    ],
  },
  {
    id: "em-waves",
    title: "Electromagnetic waves",
    level: "high_school",
    formulas: [
      ["Speed of electromagnetic waves", String.raw`c=\frac{1}{\sqrt{\epsilon_0\mu_0}}`],
      ["Speed of light in vacuum", String.raw`c=2.99792458\times10^8\,\mathrm{m/s}`, "Exact in vacuum; c is defined to be 299792458 m/s."],
      ["Electric and magnetic field ratio", String.raw`E=cB`],
      ["Poynting vector", String.raw`\vec{S}=\frac{1}{\mu_0}\vec{E}\times\vec{B}`],
      ["Average plane-wave intensity", String.raw`I=\frac{1}{2}c\epsilon_0E_0^2`],
      ["Intensity from magnetic amplitude", String.raw`I=\frac{cB_0^2}{2\mu_0}`],
      ["Radiation pressure on absorber", String.raw`P_{rad}=\frac{I}{c}`],
      ["Radiation pressure on reflector", String.raw`P_{rad}=\frac{2I}{c}`],
      ["Displacement current", String.raw`I_d=\epsilon_0\frac{d\Phi_E}{dt}`],
      ["Ampère–Maxwell law", String.raw`\oint\vec{B}\cdot d\vec{l}=\mu_0I+\mu_0\epsilon_0\frac{d\Phi_E}{dt}`],
      ["Plane-wave equation", String.raw`\nabla^2\vec{E}=\frac{1}{c^2}\frac{\partial^2\vec{E}}{\partial t^2}`],
      ["Momentum density of a wave", String.raw`g=\frac{S}{c^2}`],
      ["Energy flux", String.raw`S=uc`],
    ],
  },
  {
    id: "geometric-optics",
    title: "Geometric optics and lenses",
    level: "middle_school",
    formulas: [
      ["Law of reflection", String.raw`\theta_i=\theta_r`],
      ["Index of refraction", String.raw`n=\frac{c}{v}`],
      ["Snell’s law", String.raw`n_1\sin\theta_1=n_2\sin\theta_2`],
      ["Critical angle", String.raw`\sin\theta_c=\frac{n_2}{n_1},\quad n_1>n_2`],
      ["Thin-lens equation", String.raw`\frac{1}{f}=\frac{1}{d_o}+\frac{1}{d_i}`],
      ["Spherical-mirror equation", String.raw`\frac{1}{f}=\frac{1}{d_o}+\frac{1}{d_i}`],
      ["Lens magnification", String.raw`m=-\frac{d_i}{d_o}`],
      ["Image-height relation", String.raw`\frac{h_i}{h_o}=m`],
      ["Spherical mirror focal length", String.raw`f=\frac{R}{2}`],
      ["Lens power", String.raw`P=\frac{1}{f}`],
      ["Thin lenses in contact", String.raw`P_{eq}=\sum_iP_i`],
      ["Apparent depth", String.raw`d_{apparent}=d_{real}\frac{n_{observer}}{n_{object}}`],
    ],
  },
  {
    id: "interference-diffraction",
    title: "Interference and diffraction",
    level: "high_school",
    formulas: [
      ["Constructive interference", String.raw`\Delta r=m\lambda`],
      ["Destructive interference", String.raw`\Delta r=(m+\frac{1}{2})\lambda`],
      ["Double-slit maxima", String.raw`d\sin\theta=m\lambda`],
      ["Double-slit minima", String.raw`d\sin\theta=(m+\frac{1}{2})\lambda`],
      ["Small-angle fringe position", String.raw`y_m\approx\frac{m\lambda L}{d}`],
      ["Fringe spacing", String.raw`\Delta y=\frac{\lambda L}{d}`],
      ["Single-slit minima", String.raw`a\sin\theta=m\lambda`],
      ["Diffraction-grating maxima", String.raw`d\sin\theta=m\lambda`],
      ["Rayleigh criterion for a circular aperture", String.raw`\theta_{min}=1.22\frac{\lambda}{D}`, "Diffraction-limited angular resolution; D is the aperture diameter."],
      ["Thin-film path difference", String.raw`\Delta r=2nt\cos\theta`, "The interference condition also depends on any phase reversal at the film boundaries."],
      ["Malus’s law", String.raw`I=I_0\cos^2\theta`],
      ["Brewster’s angle", String.raw`\tan\theta_B=\frac{n_2}{n_1}`],
    ],
  },
  {
    id: "special-relativity",
    title: "Special relativity",
    level: "undergraduate",
    formulas: [
      ["Lorentz factor", String.raw`\gamma=\frac{1}{\sqrt{1-v^2/c^2}}`],
      ["Time dilation", String.raw`\Delta t=\gamma\Delta\tau`],
      ["Length contraction", String.raw`L=\frac{L_0}{\gamma}`],
      ["Relativistic momentum", String.raw`p=\gamma mv`],
      ["Total relativistic energy", String.raw`E=\gamma mc^2`],
      ["Rest energy", String.raw`E_0=mc^2`],
      ["Relativistic kinetic energy", String.raw`K=(\gamma-1)mc^2`],
      ["Energy-momentum relation", String.raw`E^2=(pc)^2+(mc^2)^2`],
      ["Relativistic velocity addition", String.raw`u'=\frac{u-v}{1-uv/c^2}`],
      ["Lorentz transformation of position", String.raw`x'=\gamma(x-vt)`],
      ["Lorentz transformation of time", String.raw`t'=\gamma(t-vx/c^2)`],
      ["Spacetime interval", String.raw`\Delta s^2=c^2\Delta t^2-\Delta x^2-\Delta y^2-\Delta z^2`],
    ],
  },
  {
    id: "photons-matter-waves",
    title: "Photons and matter waves",
    level: "undergraduate",
    formulas: [
      ["Photon energy", String.raw`E=hf`],
      ["Photon energy from wavelength", String.raw`E=\frac{hc}{\lambda}`],
      ["Photon momentum", String.raw`p=\frac{h}{\lambda}`],
      ["Photoelectric equation", String.raw`K_{max}=hf-\phi`],
      ["Stopping potential", String.raw`eV_s=K_{max}`],
      ["Threshold frequency", String.raw`f_0=\frac{\phi}{h}`],
      ["de Broglie wavelength", String.raw`\lambda=\frac{h}{p}`],
      ["Compton wavelength shift", String.raw`\Delta\lambda=\frac{h}{m_ec}(1-\cos\theta)`],
      ["Compton wavelength", String.raw`\lambda_C=\frac{h}{m_ec}`],
      ["Pair-production threshold", String.raw`E_{\gamma}\geq2m_ec^2`],
      ["Photon number from energy", String.raw`N=\frac{E_{total}}{hf}`],
      ["Radiation momentum transfer", String.raw`\Delta p=\frac{E}{c}`],
    ],
  },
  {
    id: "quantum-mechanics",
    title: "Quantum mechanics",
    level: "undergraduate",
    formulas: [
      ["Time-dependent Schrödinger equation", String.raw`i\hbar\frac{\partial\Psi}{\partial t}=\hat{H}\Psi`],
      ["Time-independent Schrödinger equation", String.raw`\hat{H}\psi=E\psi`],
      ["Born probability density", String.raw`\rho(x)=|\psi(x)|^2`],
      ["Wavefunction normalization", String.raw`\int_{-\infty}^{\infty}|\psi(x)|^2dx=1`],
      ["Expectation value", String.raw`\langle A\rangle=\int\psi^*\hat{A}\psi\,d\tau`],
      ["Position-momentum uncertainty", String.raw`\Delta x\Delta p\geq\frac{\hbar}{2}`],
      ["Energy-time uncertainty", String.raw`\Delta E\Delta t\geq\frac{\hbar}{2}`],
      ["Particle in a one-dimensional box", String.raw`E_n=\frac{n^2\pi^2\hbar^2}{2mL^2}`],
      ["Quantum harmonic oscillator levels", String.raw`E_n=(n+\frac{1}{2})\hbar\omega`],
      ["Tunneling probability approximation", String.raw`T\approx e^{-2\kappa L}`],
      ["Evanescent decay constant", String.raw`\kappa=\frac{\sqrt{2m(U-E)}}{\hbar}`],
      ["Probability current density", String.raw`j=\frac{\hbar}{2mi}(\psi^*\nabla\psi-\psi\nabla\psi^*)`],
    ],
  },
  {
    id: "atomic-physics",
    title: "Atomic physics and spectra",
    level: "undergraduate",
    formulas: [
      ["Bohr orbit radius", String.raw`r_n=\frac{n^2a_0}{Z}`],
      ["Hydrogen energy levels", String.raw`E_n=-\frac{13.6\,eV}{n^2}`],
      ["Hydrogen transition energy", String.raw`\Delta E=13.6\,eV\left(\frac{1}{n_f^2}-\frac{1}{n_i^2}\right)`],
      ["Rydberg formula", String.raw`\frac{1}{\lambda}=R_\infty Z^2\left(\frac{1}{n_f^2}-\frac{1}{n_i^2}\right)`],
      ["Bohr angular momentum quantization", String.raw`L=n\hbar`],
      ["Bohr radius", String.raw`a_0=\frac{4\pi\epsilon_0\hbar^2}{m_ee^2}`],
      ["Fine-structure constant", String.raw`\alpha=\frac{e^2}{4\pi\epsilon_0\hbar c}`],
      ["Photon frequency from a transition", String.raw`f=\frac{|\Delta E|}{h}`],
      ["Lyman series limit", String.raw`\frac{1}{\lambda}=R_\infty`],
      ["Zeeman energy shift", String.raw`\Delta E=\mu_B g_Jm_JB`],
      ["Bohr magneton", String.raw`\mu_B=\frac{e\hbar}{2m_e}`],
      ["Spectral line width and lifetime", String.raw`\Delta E\Delta t\gtrsim\hbar`],
    ],
  },
  {
    id: "nuclear-physics",
    title: "Nuclear physics and radioactivity",
    level: "undergraduate",
    formulas: [
      ["Radioactive decay", String.raw`N(t)=N_0e^{-\lambda t}`],
      ["Activity", String.raw`A=\lambda N`],
      ["Half-life", String.raw`t_{1/2}=\frac{\ln2}{\lambda}`],
      ["Mean lifetime", String.raw`\tau=\frac{1}{\lambda}`],
      ["Remaining fraction", String.raw`\frac{N}{N_0}=e^{-\lambda t}`],
      ["Mass defect", String.raw`\Delta m=Zm_p+Nm_n-m_{nucleus}`],
      ["Nuclear binding energy", String.raw`E_b=\Delta mc^2`],
      ["Binding energy per nucleon", String.raw`\frac{E_b}{A}`],
      ["Q-value of a nuclear reaction", String.raw`Q=(m_i-m_f)c^2`],
      ["Nuclear radius", String.raw`R=R_0A^{1/3}`],
      ["Alpha-decay energy", String.raw`Q_\alpha=(m_P-m_D-m_\alpha)c^2`],
      ["Attenuation through matter", String.raw`I=I_0e^{-\mu x}`],
    ],
  },
  {
    id: "particle-physics",
    title: "Particle physics",
    level: "undergraduate",
    formulas: [
      ["Relativistic invariant mass", String.raw`m^2c^4=E^2-p^2c^2`],
      ["Center-of-mass energy", String.raw`E_{cm}=\sqrt{(E_1+E_2)^2-c^2|\vec{p}_1+\vec{p}_2|^2}`],
      ["Particle wavelength", String.raw`\lambda=\frac{h}{p}`],
      ["Decay probability", String.raw`P(t)=1-e^{-t/\tau}`],
      ["Particle decay length", String.raw`L=\beta\gamma c\tau`],
      ["Lorentz-invariant Mandelstam s", String.raw`s=(p_1+p_2)^2`],
      ["Energy threshold for fixed-target production", String.raw`E_{beam,min}=\frac{(\sum_fm_f)^2-\sum_im_i^2}{2m_{target}}c^2`],
      ["Cross section from event rate", String.raw`R=\mathcal{L}\sigma`],
      ["Mean free path", String.raw`\ell=\frac{1}{n\sigma}`],
      ["Branching ratio", String.raw`B_i=\frac{\Gamma_i}{\Gamma_{total}}`],
      ["Lifetime-width relation", String.raw`\tau=\frac{\hbar}{\Gamma}`],
      ["Relativistic kinetic energy", String.raw`K=E-mc^2`],
    ],
  },
  {
    id: "condensed-matter",
    title: "Condensed matter and semiconductors",
    level: "undergraduate",
    formulas: [
      ["Bragg diffraction", String.raw`2d\sin\theta=n\lambda`],
      ["Crystal plane spacing for cubic lattice", String.raw`d_{hkl}=\frac{a}{\sqrt{h^2+k^2+l^2}}`],
      ["Fermi energy of a free-electron gas", String.raw`E_F=\frac{\hbar^2}{2m}(3\pi^2n)^{2/3}`],
      ["Fermi wave number", String.raw`k_F=(3\pi^2n)^{1/3}`],
      ["Density of states in three dimensions", String.raw`g(E)\propto\sqrt{E}`],
      ["Drude conductivity", String.raw`\sigma=\frac{ne^2\tau}{m}`],
      ["Hall coefficient", String.raw`R_H=\frac{1}{nq}`],
      ["Semiconductor conductivity", String.raw`\sigma=q(n\mu_n+p\mu_p)`],
      ["Intrinsic carrier concentration", String.raw`n_i^2=np`],
      ["Band-gap photon threshold", String.raw`\lambda_g=\frac{hc}{E_g}`],
      ["Debye temperature", String.raw`\Theta_D=\frac{\hbar\omega_D}{k_B}`],
      ["Critical field near transition temperature", String.raw`B_c(T)=B_c(0)[1-(T/T_c)^2]`],
    ],
  },
  {
    id: "statistical-physics",
    title: "Statistical physics and entropy",
    level: "undergraduate",
    formulas: [
      ["Boltzmann entropy", String.raw`S=k_B\ln\Omega`],
      ["Microstate probability", String.raw`P_i=\frac{e^{-E_i/(k_BT)}}{Z}`],
      ["Partition function", String.raw`Z=\sum_i e^{-E_i/(k_BT)}`],
      ["Helmholtz free energy", String.raw`F=-k_BT\ln Z`],
      ["Mean energy from partition function", String.raw`U=-\frac{\partial\ln Z}{\partial\beta}`],
      ["Inverse thermal energy", String.raw`\beta=\frac{1}{k_BT}`],
      ["Boltzmann population ratio", String.raw`\frac{N_2}{N_1}=e^{-\Delta E/(k_BT)}`],
      ["Gibbs entropy", String.raw`S=-k_B\sum_i p_i\ln p_i`],
      ["Multiplicity of two-level system", String.raw`\Omega=\frac{N!}{N_1!N_2!}`],
      ["Stirling approximation", String.raw`\ln N!\approx N\ln N-N`],
      ["Equipartition energy", String.raw`\langle E\rangle=\frac{f}{2}k_BT`],
      ["Entropy change for reversible heat", String.raw`dS=\frac{\delta Q_{rev}}{T}`],
    ],
  },
  {
    id: "astrophysics-cosmology",
    title: "Astrophysics and cosmology",
    level: "undergraduate",
    formulas: [
      ["Hubble–Lemaître law", String.raw`v=H_0d`],
      ["Light-year conversion", String.raw`1\,\mathrm{ly}=9.46073047258\times10^{15}\,\mathrm{m}`, "Uses the Julian year."],
      ["Luminosity and flux", String.raw`F=\frac{L}{4\pi d^2}`],
      ["Distance modulus", String.raw`m-M=5\log_{10}(d/10\,pc)`],
      ["Parallax distance", String.raw`d(pc)=\frac{1}{p(arcsec)}`],
      ["Stefan–Boltzmann luminosity", String.raw`L=4\pi R^2\sigma T^4`],
      ["Wien displacement law", String.raw`\lambda_{max}T=b_W`],
      ["Kepler orbit mass estimate", String.raw`M=\frac{4\pi^2a^3}{GT^2}`],
      ["Redshift", String.raw`z=\frac{\lambda_{obs}-\lambda_{emit}}{\lambda_{emit}}`],
      ["Low-speed redshift relation", String.raw`v\approx cz`],
      ["Critical density", String.raw`\rho_c=\frac{3H^2}{8\pi G}`],
      ["Schwarzschild radius", String.raw`r_s=\frac{2GM}{c^2}`],
    ],
  },
  {
    id: "mathematical-methods",
    title: "Mathematical methods and fields",
    level: "undergraduate",
    formulas: [
      ["Gradient", String.raw`\nabla f=\hat{i}\frac{\partial f}{\partial x}+\hat{j}\frac{\partial f}{\partial y}+\hat{k}\frac{\partial f}{\partial z}`],
      ["Divergence", String.raw`\nabla\cdot\vec{A}=\frac{\partial A_x}{\partial x}+\frac{\partial A_y}{\partial y}+\frac{\partial A_z}{\partial z}`],
      ["Curl", String.raw`\nabla\times\vec{A}=\begin{vmatrix}\hat{i}&\hat{j}&\hat{k}\\\partial_x&\partial_y&\partial_z\\A_x&A_y&A_z\end{vmatrix}`],
      ["Laplacian", String.raw`\nabla^2f=\frac{\partial^2f}{\partial x^2}+\frac{\partial^2f}{\partial y^2}+\frac{\partial^2f}{\partial z^2}`],
      ["Divergence theorem", String.raw`\int_V\nabla\cdot\vec{A}\,dV=\oint_{\partial V}\vec{A}\cdot d\vec{A}`],
      ["Stokes’ theorem", String.raw`\int_S(\nabla\times\vec{A})\cdot d\vec{A}=\oint_{\partial S}\vec{A}\cdot d\vec{l}`],
      ["Fourier series", String.raw`f(x)=\frac{a_0}{2}+\sum_{n=1}^{\infty}[a_n\cos(nx)+b_n\sin(nx)]`],
      ["Fourier transform", String.raw`\tilde{f}(k)=\int_{-\infty}^{\infty}f(x)e^{-ikx}\,dx`],
      ["Complex impedance", String.raw`Z=R+i(X_L-X_C)`],
      ["Second-order oscillator equation", String.raw`m\ddot{x}+b\dot{x}+kx=F(t)`],
      ["Diffusion equation", String.raw`\frac{\partial u}{\partial t}=D\nabla^2u`],
      ["Wave equation", String.raw`\frac{\partial^2u}{\partial t^2}=v^2\nabla^2u`],
    ],
  },
];

export const PHYSICS_TOPICS: readonly PhysicsTopic[] = TOPIC_SEEDS.map(
  ({ formulas: _formulas, ...topic }) => topic,
);

export const PHYSICS_FORMULAS: readonly PhysicsFormulaRow[] = TOPIC_SEEDS.flatMap((topic) =>
  topic.formulas.map(([name, equation, note], index) => ({
    id: `${topic.id}-${index + 1}`,
    name,
    equation,
    topicId: topic.id,
    topic: topic.title,
    level: topic.level,
    ...(note ? { note } : {}),
  })),
);

export const PHYSICS_FORMULA_COUNT = 540;

export type PhysicsConstant = {
  id: string;
  name: string;
  symbol: string;
  value: string;
  unit: string;
  note?: string;
};

// Fundamental-constant values follow NIST CODATA 2022 where applicable.
// Standardized conversion factors and the cosmological Hubble parameter are
// labeled separately because they are not all CODATA fundamental constants.
export const PHYSICS_CONSTANTS: readonly PhysicsConstant[] = [
  { id: "c", name: "Speed of light in vacuum", symbol: "c", value: "2.99792458 × 10⁸", unit: "m/s" },
  { id: "h", name: "Planck constant", symbol: "h", value: "6.62607015 × 10⁻³⁴", unit: "J·s" },
  { id: "hbar", name: "Reduced Planck constant", symbol: "\\hbar", value: "1.054571817 × 10⁻³⁴", unit: "J·s" },
  { id: "e", name: "Elementary charge", symbol: "e", value: "1.602176634 × 10⁻¹⁹", unit: "C" },
  { id: "electron-mass", name: "Electron mass", symbol: "m_e", value: "9.1093837139 × 10⁻³¹", unit: "kg" },
  { id: "proton-mass", name: "Proton mass", symbol: "m_p", value: "1.67262192595 × 10⁻²⁷", unit: "kg" },
  { id: "neutron-mass", name: "Neutron mass", symbol: "m_n", value: "1.67492750056 × 10⁻²⁷", unit: "kg" },
  { id: "proton-electron-ratio", name: "Proton-electron mass ratio", symbol: "m_p/m_e", value: "1836.152673426", unit: "dimensionless" },
  { id: "G", name: "Newtonian gravitational constant", symbol: "G", value: "6.67430 × 10⁻¹¹", unit: "N·m²/kg²" },
  { id: "coulomb-constant", name: "Coulomb constant", symbol: "k_e", value: "8.9875517862 × 10⁹", unit: "N·m²/C²" },
  { id: "epsilon0", name: "Vacuum permittivity", symbol: "\\epsilon_0", value: "8.8541878188 × 10⁻¹²", unit: "F/m" },
  { id: "mu0", name: "Vacuum permeability", symbol: "\\mu_0", value: "1.25663706127 × 10⁻⁶", unit: "N/A²" },
  { id: "boltzmann", name: "Boltzmann constant", symbol: "k_B", value: "1.380649 × 10⁻²³", unit: "J/K" },
  { id: "avogadro", name: "Avogadro constant", symbol: "N_A", value: "6.02214076 × 10²³", unit: "mol⁻¹" },
  { id: "gas-constant", name: "Molar gas constant", symbol: "R", value: "8.314462618", unit: "J/(mol·K)" },
  { id: "faraday", name: "Faraday constant", symbol: "F", value: "96485.33212", unit: "C/mol" },
  { id: "stefan-boltzmann", name: "Stefan–Boltzmann constant", symbol: "\\sigma", value: "5.670374419 × 10⁻⁸", unit: "W/(m²·K⁴)" },
  { id: "fine-structure", name: "Fine-structure constant", symbol: "\\alpha", value: "7.2973525643 × 10⁻³", unit: "dimensionless" },
  { id: "rydberg", name: "Rydberg constant", symbol: "R_\\infty", value: "1.0973731568157 × 10⁷", unit: "m⁻¹" },
  { id: "bohr-radius", name: "Bohr radius", symbol: "a_0", value: "5.29177210544 × 10⁻¹¹", unit: "m" },
  { id: "bohr-magneton", name: "Bohr magneton", symbol: "\\mu_B", value: "9.2740100657 × 10⁻²⁴", unit: "J/T" },
  { id: "classical-electron-radius", name: "Classical electron radius", symbol: "r_e", value: "2.8179403205 × 10⁻¹⁵", unit: "m" },
  { id: "compton-wavelength", name: "Electron Compton wavelength", symbol: "\\lambda_C", value: "2.42631023538 × 10⁻¹²", unit: "m" },
  { id: "thomson-cross-section", name: "Thomson cross-section", symbol: "\\sigma_T", value: "6.6524587051 × 10⁻²⁹", unit: "m²" },
  { id: "standard-gravity", name: "Standard gravity", symbol: "g_0", value: "9.80665", unit: "m/s²", note: "Conventional standard value; local gravity varies." },
  { id: "standard-atmosphere", name: "Standard atmosphere", symbol: "atm", value: "101325", unit: "Pa", note: "Exact unit conversion." },
  { id: "electron-volt", name: "Electron volt", symbol: "eV", value: "1.602176634 × 10⁻¹⁹", unit: "J", note: "Exact unit conversion." },
  { id: "astronomical-unit", name: "Astronomical unit", symbol: "AU", value: "149597870700", unit: "m", note: "Exact unit definition." },
  { id: "light-year", name: "Light-year", symbol: "ly", value: "9.46073047258 × 10¹⁵", unit: "m", note: "Uses the Julian year." },
  { id: "parsec", name: "Parsec", symbol: "pc", value: "3.08567758149 × 10¹⁶", unit: "m" },
  { id: "solar-mass", name: "Solar mass", symbol: "M_\\odot", value: "1.98847 × 10³⁰", unit: "kg", note: "Nominal rounded reference value." },
  { id: "hubble-constant", name: "Hubble parameter (approx.)", symbol: "H_0", value: "70", unit: "km/(s·Mpc)", note: "Cosmological estimate; measured values depend on method." },
];

const SUPERSCRIPT_DIGITS: Readonly<Record<string, string>> = {
  "⁰": "0",
  "¹": "1",
  "²": "2",
  "³": "3",
  "⁴": "4",
  "⁵": "5",
  "⁶": "6",
  "⁷": "7",
  "⁸": "8",
  "⁹": "9",
  "⁻": "-",
};

export function physicsConstantEquation(constant: PhysicsConstant): string {
  const match = constant.value.match(/^(.+?) × 10([⁰¹²³⁴⁵⁶⁷⁸⁹⁻]+)$/);
  if (!match) return `${constant.symbol} = ${constant.value}`;
  const exponent = Array.from(match[2]!).map((char) => SUPERSCRIPT_DIGITS[char]).join("");
  return `${constant.symbol} = ${match[1]} \\times 10^{${exponent}}`;
}

const LATEX_SYMBOL_ALIASES: readonly (readonly [string, string])[] = [
  ["\\alpha", "alpha α"],
  ["\\beta", "beta β"],
  ["\\gamma", "gamma γ"],
  ["\\delta", "delta δ"],
  ["\\epsilon", "epsilon ε"],
  ["\\eta", "eta η"],
  ["\\lambda", "lambda λ"],
  ["\\mu", "mu μ"],
  ["\\nu", "nu ν"],
  ["\\omega", "omega ω"],
  ["\\phi", "phi φ"],
  ["\\pi", "pi π"],
  ["\\rho", "rho ρ"],
  ["\\sigma", "sigma σ"],
  ["\\tau", "tau τ"],
  ["\\theta", "theta θ"],
  ["\\hbar", "hbar ħ"],
  ["\\Delta", "delta Δ"],
  ["\\nabla", "nabla ∇"],
];

function normalizeSearchText(value: string): string {
  let searchable = value.toLocaleLowerCase();
  for (const [latex, aliases] of LATEX_SYMBOL_ALIASES) {
    searchable = searchable.replaceAll(latex.toLocaleLowerCase(), ` ${aliases.toLocaleLowerCase()} `);
  }
  return searchable.replaceAll("\\", " ").replace(/[{}_^]/g, " ");
}

export function searchPhysicsFormulas(
  query: string,
  level: PhysicsEducationLevel | "all" = "all",
  topicId: string | "all" = "all",
): readonly PhysicsFormulaRow[] {
  const terms = normalizeSearchText(query).trim().split(/\s+/).filter(Boolean);
  return PHYSICS_FORMULAS.filter((formula) => {
    if (level !== "all" && formula.level !== level) return false;
    if (topicId !== "all" && formula.topicId !== topicId) return false;
    if (!terms.length) return true;
    const searchable = normalizeSearchText(
      `${formula.name} ${formula.equation} ${formula.topic} ${formula.level}`,
    );
    return terms.every((term) => searchable.includes(term.replace(/[{}_^]/g, "")));
  });
}

export function searchPhysicsConstants(query: string): readonly PhysicsConstant[] {
  const terms = normalizeSearchText(query).trim().split(/\s+/).filter(Boolean);
  return PHYSICS_CONSTANTS.filter((constant) => {
    if (!terms.length) return true;
    const searchable = normalizeSearchText(
      `${constant.name} ${constant.symbol} ${constant.value} ${constant.unit} ${constant.note ?? ""}`,
    );
    return terms.every((term) => searchable.includes(term.replace(/[{}_^]/g, "")));
  });
}
