// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    ignores: ["dist/*", "vendor/**", ".expo/**"],
  },
  {
    rules: {
      // Expo SDK 56 enables React Compiler hook rules that flag common RN patterns.
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react/no-unescaped-entities": "off",
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    ignores: [
      "**/__tests__/**",
      "**/*.test.ts",
      "**/*.test.tsx",
      "lib/type.ts",
      "lib/graphic.ts",
      "lib/vendor/**",
      "lib/math/**",
      "components/CodeBlock.tsx",
      "components/rich/MathText.tsx",
      "components/rich/AnswerBlock.tsx",
      "components/rich/CircularClockBlock.tsx",
      "components/rich/InteractiveFunctionPlot.tsx",
      "components/rich/InequalityGraphChart.tsx",
      "components/rich/FunctionGraphBlock.tsx",
      "components/rich/GeometryBlock.tsx",
      "components/rich/geometry/**",
      "components/rich/NumberLineChart.tsx",
      "components/rich/CartesianAxes.tsx",
      "components/rich/SimulationBlock.tsx",
      "components/rich/Molecule3DBlock.tsx",
      "components/rich/MoleculeCard.tsx",
      "components/rich/ChemistryBlock.tsx",
      "components/rich/ChartBlock.tsx",
      "components/rich/MermaidBlock.tsx",
      "components/chat/MathKeyboardBar.tsx",
      "components/chat/MathConverterUnitSheet.tsx",
      "components/chat/MathConverterPad.tsx",
      "components/chat/MathDraftPreview.tsx",
      "features/learning/screens/LessonPlayScreen.tsx",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Property[key.name='fontSize'][value.raw=/^\\d/]",
          message:
            "Use a Type role from lib/type.ts. Raw font sizes belong in that file, or in domain graphics.",
        },
      ],
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    ignores: [
      "**/__tests__/**",
      "**/*.test.ts",
      "**/*.test.tsx",
      "lib/graphic.ts",
      "lib/math/**",
      "lib/type.ts",
      "components/rich/CartesianAxes.tsx",
      "components/rich/GeometryBlock.tsx",
      "components/rich/NumberLineChart.tsx",
      "components/rich/SimulationBlock.tsx",
      "components/rich/geometry/**",
      "features/learning/screens/LessonPlayScreen.tsx",
      "lib/radius.ts",
      "lib/shadow.ts",
      "lib/space.ts",
      "lib/theme.ts",
      "lib/vendor/**",
      // Still use a spacing or radius number that is not on the scale.
      // New files are checked. These stay listed until they move onto Space / Radius.
      "app/login.tsx",
      "app/onboarding.tsx",
      "app/settings/index.tsx",
      "components/ActionBanner.tsx",
      "components/ActionSheetRow.tsx",
      "components/AddFab.tsx",
      "components/ChatMessageImage.tsx",
      "components/ChatMessagePdf.tsx",
      "components/CodeBlock.tsx",
      "components/CopyBlock.tsx",
      "components/CountBadge.tsx",
      "components/FallbackMarkdown.tsx",
      "components/HtmlPreviewModal.tsx",
      "components/LinkPreviewCard.tsx",
      "components/MarkdownTable.tsx",
      "components/MessageBubble.tsx",
      "components/PlacesListBlock.tsx",
      "components/SearchSourcesStack.tsx",
      "components/SettingsProposalCard.tsx",
      "components/SkeletonLoader.tsx",
      "components/UpgradeSheet.tsx",
      "components/UserMessageContent.tsx",
      "components/chat/ChatComposer.tsx",
      "components/chat/ChatInlineError.tsx",
      "components/chat/ChatMessageList.tsx",
      "components/chat/ChatScrollFab.tsx",
      "components/chat/MathConverterPad.tsx",
      "components/chat/MathConverterUnitSheet.tsx",
      "components/chat/MathDraftPreview.tsx",
      "components/chat/MathKeyboardBar.tsx",
      "components/drawer/ConversationRow.tsx",
      "components/drawer/conversationListStyles.ts",
      "components/markdown/markdownContentStyles.ts",
      "components/mathScanner/MathScannerChrome.tsx",
      "components/mathScanner/MathScannerCropOverlay.tsx",
      "components/mathScanner/ScannerSubjectSwitcher.tsx",
      "components/rich/AnswerBlock.tsx",
      "components/rich/CardShell.tsx",
      "components/rich/ChartBlock.tsx",
      "components/rich/ChemistryBlock.tsx",
      "components/rich/CircularClockBlock.tsx",
      "components/rich/CollapsibleBlock.tsx",
      "components/rich/ComparisonBlock.tsx",
      "components/rich/FunctionGraphBlock.tsx",
      "components/rich/InequalityGraphChart.tsx",
      "components/rich/InteractiveFunctionPlot.tsx",
      "components/rich/KeyValueBlock.tsx",
      "components/rich/MathSvgView.tsx",
      "components/rich/MathText.tsx",
      "components/rich/MermaidBlock.tsx",
      "components/rich/Molecule3DBlock.tsx",
      "components/rich/MoleculeCard.tsx",
      "components/rich/QuoteBlock.tsx",
      "components/rich/StepList.tsx",
      "components/rich/VisualCard.tsx",
      "components/settings/SettingsPickerSheet.tsx",
      "components/settings/SettingsProfileSheet.tsx",
      "components/settings/SettingsSkeleton.tsx",
      "components/settings/settingsStyles.ts",
      "features/attachments/components/AttachmentLightboxChrome.tsx",
      "features/attachments/components/ComposerAttachmentPreview.tsx",
      "features/attachments/components/GalleryLibraryHeader.tsx",
      "features/attachments/screens/GalleryScreen.tsx",
      "features/home/components/HomeStarters.tsx",
      "features/images/components/ImageGenPlaceholder.tsx",
      "features/integrations/components/CalendarProposalCard.tsx",
      "features/integrations/components/EmailCard.tsx",
      "features/job-search/components/JobMatchReasons.tsx",
      "features/job-search/components/JobStageFilter.tsx",
      "features/job-search/components/SearchProfileFields.tsx",
      "features/job-search/components/SearchableMultiSelect.tsx",
      "features/job-search/screens/JobMatchDetailScreen.tsx",
      "features/job-search/screens/MyJobScreen.tsx",
      "features/learning/components/LearningPathList.tsx",
      "features/learning/components/LearningProjectCard.tsx",
      "features/learning/components/LessonOptionsSheet.tsx",
      "features/learning/components/StepPicker.tsx",
      "features/learning/screens/LearningCreateScreen.tsx",
      "features/learning/screens/LearningListScreen.tsx",
      "features/learning/screens/LessonMapScreen.tsx",
      "features/memory/components/MemoryRows.tsx",
      "features/search/components/DrawerSearchResults.tsx",
      "features/speech/components/LiveTalkButton.tsx",
      "features/speech/components/LiveTalkComposerControls.tsx",
      "features/speech/components/LiveTalkOrb.tsx",
      "features/speech/components/VoiceMicButton.tsx",
      "features/suggestions/components/SuggestionChips.tsx",
      "features/todos/components/CalendarNudgeCard.tsx",
      "features/todos/components/todosStyles.ts",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Property[key.name='fontSize'][value.raw=/^\\d/]",
          message:
            "Use a Type role from lib/type.ts. Raw font sizes belong in that file, or in domain graphics.",
        },
        {
          selector:
            "Property[key.name=/^(padding|margin|gap|paddingHorizontal|paddingVertical|marginHorizontal|marginVertical|paddingTop|paddingBottom|paddingLeft|paddingRight|marginTop|marginBottom|marginLeft|marginRight|rowGap|columnGap)$/][value.raw=/^([3-9]|[1-9]\\d+)$/]",
          message: "Use a Space token from lib/space.ts. 0, 1, and 2 may stay raw.",
        },
        {
          selector:
            "Property[key.name=/^(borderRadius|borderTopLeftRadius|borderTopRightRadius|borderBottomLeftRadius|borderBottomRightRadius|borderTopStartRadius|borderTopEndRadius|borderBottomStartRadius|borderBottomEndRadius)$/][value.raw=/^([3-9]|[1-9]\\d+)$/]",
          message: "Use a Radius token from lib/radius.ts. 0, 1, and 2 may stay raw.",
        },
        {
          selector:
            "Property[key.name=/^(color|backgroundColor|borderColor|shadowColor|tintColor)$/][value.raw=/^['\"]#/]",
          message: "Use a theme color. Neutral shadow ink is SHADOW_COLOR in lib/shadow.ts.",
        },
      ],
    },
  },
]);
