import type { ModelInfo } from "@/lib/api";

/** Mirrors backend ``model_catalog.selectable_models()`` when /models cannot be reached. */
export const MODEL_CATALOG_FALLBACK: ModelInfo[] = [
  {
    id: "free-chat",
    label: "DeepSeek Chat",
    tier: "fast",
    plan_access: "free",
    description: "Fast everyday chat — cheap and capable.",
    available: true,
    input_price_per_m: 0.14,
    output_price_per_m: 0.28,
  },
  {
    id: "smart-chat",
    label: "DeepSeek R1",
    tier: "smart",
    plan_access: "pro",
    description: "Stronger reasoning for hard questions and code.",
    available: true,
    input_price_per_m: 0.7,
    output_price_per_m: 2.5,
  },
  {
    id: "minimax-m2",
    label: "Minimax M2",
    tier: "standard",
    plan_access: "pro",
    description: "Minimax flagship model.",
    available: true,
    input_price_per_m: null,
    output_price_per_m: null,
  },
  {
    id: "glm-4-flash",
    label: "GLM-4 Flash",
    tier: "standard",
    plan_access: "free",
    description: "Zhipu GLM — fast multilingual model.",
    available: true,
    input_price_per_m: null,
    output_price_per_m: null,
  },
  {
    id: "qwen-plus",
    label: "Qwen Plus",
    tier: "standard",
    plan_access: "pro",
    description: "Alibaba Qwen — strong general assistant.",
    available: true,
    input_price_per_m: null,
    output_price_per_m: null,
  },
  {
    id: "gemini-flash",
    label: "Gemini 2.5 Flash",
    tier: "fast",
    plan_access: "free",
    description: "Google Gemini — fast multimodal model.",
    available: true,
    input_price_per_m: null,
    output_price_per_m: null,
  },
  {
    id: "llama-70b",
    label: "Llama 3.3 70B",
    tier: "standard",
    plan_access: "pro",
    description: "Meta Llama — open-weight instruct model.",
    available: true,
    input_price_per_m: null,
    output_price_per_m: null,
  },
  {
    id: "max-chat",
    label: "OpenRouter Auto",
    tier: "max",
    plan_access: "pro",
    description: "OpenRouter picks the best model for each request.",
    available: true,
    input_price_per_m: null,
    output_price_per_m: null,
  },
];
