// TODO(mvp): Move to a versioned server endpoint (GET /terms) so updates don't
// require an app-store submission. Same plan as the privacy policy.
export const TERMS_OF_SERVICE = `# Terms of Service

**Last updated: June 2026**

## Using Recall

- Recall is a personal AI chat app that remembers your preferences and context across chats.
- You agree to provide accurate information and to use the app for lawful, personal purposes.
- You are responsible for the content you share with the app.

## Your Account

- You sign in with Google. Keep your Google account secure — you are responsible for activity under it.
- You can export or delete your account and data at any time from Settings.

## AI Responses

- AI responses are generated by third-party models and may be inaccurate or incomplete. They are not professional advice.
- Do not rely on Recall for medical, legal, financial, or safety-critical decisions.
- You are responsible for reviewing AI output before acting on it.

## Acceptable Use

- Do not use Recall to generate unlawful, harmful, harassing, or abusive content.
- Do not attempt to extract provider API keys, reverse-engineer the service, or overload it.
- We may suspend accounts that violate these terms.

## Privacy

- Our handling of your data is described in the Privacy Policy, which is part of these terms.

## Changes

- We may update these terms. Material changes will be surfaced in the app. Continued use after changes means you accept the updated terms.

## Contact

- Questions about these terms can be sent to the contact listed in the Privacy Policy.
`;
