"""How questions write units, mapped to the names Pint reads."""

from __future__ import annotations

_UNIT_ALIASES = {
    "m/s2": "m/s**2",
    "m/s^2": "m/s**2",
    "deg": "deg",
    "degrees": "deg",
    "°": "deg",
    "miles per hour": "mph",
    "miles": "mile",
    "ohms": "ohm",
    "volts": "volt",
    "amps": "ampere",
    "amperes": "ampere",
    # Pint is case-sensitive and unforgiving about the symbols people type:
    # bare "pa" is a petayear, "t" a tonne, "c" the speed of light, and "w",
    # "n", "j", "hz" are not units at all. Every extractor regex here is
    # IGNORECASE, so the lowercase spellings do arrive.
    "w": "watt",
    "watts": "watt",
    "kw": "kilowatt",
    "kilowatts": "kilowatt",
    "c/m": "coulomb / meter",
    "c/m^2": "coulomb / meter ** 2",
    "c/m2": "coulomb / meter ** 2",
    "uc/m": "microcoulomb / meter",
    "uc/m^2": "microcoulomb / meter ** 2",
    "c": "coulomb",
    "coulombs": "coulomb",
    "uc": "microcoulomb",
    "microcoulomb": "microcoulomb",
    "microcoulombs": "microcoulomb",
    "f": "farad",
    "farads": "farad",
    "uf": "microfarad",
    "µf": "microfarad",
    "nf": "nanofarad",
    "pf": "picofarad",
    "j": "joule",
    "joules": "joule",
    "ev": "electron_volt",
    "kev": "kiloelectron_volt",
    "mev": "megaelectron_volt",
    "rad/s": "radian / second",
    "rad/s^2": "radian / second ** 2",
    "rad/s2": "radian / second ** 2",
    "rads/s": "radian / second",
    "n*m": "newton * meter",
    "n·m": "newton * meter",
    "kg*m^2/s": "kilogram * meter ** 2 / second",
    "kg m^2/s": "kilogram * meter ** 2 / second",
    "radians/s": "radian / second",
    "rad/sec": "radian / second",
    "hz": "hertz",
    "khz": "kilohertz",
    "mhz": "megahertz",
    "pa": "pascal",
    "kpa": "kilopascal",
    "mpa": "megapascal",
    "k": "kelvin",
    "kelvins": "kelvin",
    "\u00b0c": "degC",
    "celsius": "degC",
    "j/kg/k": "joule / kilogram / kelvin",
    "j/(kg k)": "joule / kilogram / kelvin",
    "j/kgk": "joule / kilogram / kelvin",
    "j/kg": "joule / kilogram",
    "kj/kg": "kilojoule / kilogram",
    "kg/m": "kilogram / meter",
    "g/m": "gram / meter",
    "n/m": "newton / meter",
    "pa*s": "pascal * second",
    "pa·s": "pascal * second",
    "w/m^2": "watt / meter**2",
    "w/m2": "watt / meter**2",
    "w/m/k": "watt / meter / kelvin",
    "1/k": "1 / kelvin",
    "/k": "1 / kelvin",
    "1/°c": "1 / kelvin",
    "/°c": "1 / kelvin",
    "m^3": "m**3",
    "m3": "m**3",
    "cm^3": "cm**3",
    "cm3": "cm**3",
    "litres": "liter",
    "litre": "liter",
    "liters": "liter",
    "moles": "mole",
    "m^2": "m**2",
    "m2": "m**2",
    "cm^2": "cm**2",
    "cm2": "cm**2",
    "mm^2": "mm**2",
    "kg/m^3": "kg/m**3",
    "kg/m3": "kg/m**3",
    "g/cm^3": "g/cm**3",
    "g/cm3": "g/cm**3",
    "kg*m^2": "kg * m**2",
    "kg m^2": "kg * m**2",
    "kgm^2": "kg * m**2",
    "rad": "radian",
    "radians": "radian",
    "t": "tesla",
    "tesla": "tesla",
    "teslas": "tesla",
    "mt": "millitesla",
    "wb": "weber",
    "weber": "weber",
    "webers": "weber",
    "n": "newton",
    "newtons": "newton",
    "gpa": "gigapascal",
    "nm": "nanometer",
    "nanometer": "nanometer",
    "nanometers": "nanometer",
    "um": "micrometer",
    "µm": "micrometer",
    "micrometer": "micrometer",
    "micrometers": "micrometer",
}
