export {
  MATH_KEYBOARD_GROUPS,
  MATH_KEYBOARD_SYMBOLS,
  MATH_PAD_KEYS,
  MATH_SYMBOL_ROW_SIZE,
  SYMBOL_A11Y,
  converterResultSpec,
  isCursorInsideInlineMath,
  mathGroupCanToggleDigits,
  spliceBackspace,
  spliceMathInsert,
  symbolA11yLabel,
  symbolsInGroup,
  type MathKeyboardGroup,
  type MathKeyboardSymbol,
  type TextSelection,
} from "@/lib/math/keyboardCatalog";
export {
  MATH_NUMPAD_ROWS,
  autoAdvanceFracDen,
  autoAdvanceNextEmptySlot,
  caretForInsert,
  caretInGroup,
  findEditSlots,
  findFracSlots,
  findLognSlots,
  findNrootSlots,
  fracTapAdvancesToDen,
  innermostSlot,
  nextEditSlotCaret,
  prevEditSlotCaret,
  readBraceGroup,
  readDelimGroup,
  symbolRowsForGroup,
  tapAdvancesToNextSlot,
  type LatexGroup,
  type PadCell,
} from "@/lib/math/keyboardSlots";
