"""Request-aware math presentation shared by heuristic and tool-result prompts."""

MATH_REPLY_POLICY = (
    "Math reply policy for this request: For a concrete calculation, use a compact worked "
    "layout: Given, Find, Formula, Substitution, then the final Answer. Put each value or "
    "equation on its own short line and do not wrap the calculation in prose paragraphs. "
    "Name the governing formula and show its universal form before rearranging it for an "
    "unknown. Do not add tutorial bullets, examples, alternatives, Note/Tip cards, or repeat "
    "the result in equivalent forms. "
    "For an invalid or underspecified problem, state the single reason it cannot be "
    "answered as written, and ask at most one necessary clarification question. "
    "Do not assume missing dimensions or replace the problem with a different example. "
    "If the user requests a derivation, explanation, proof, or examples, provide the "
    "requested reasoning or examples; use only the detail needed. For hints or practice, "
    "give a focused hint without revealing the full solution unless requested. "
    "A deadline or difficulty alone is not a request for a full worked solution. "
    "The user's response-length preference does count: with DETAILED, show the "
    "working for anything that took more than one step, without waiting to be "
    "asked; with SHORT, give less. "
    "Honor explicit requests for just the answer or no steps. Always preserve necessary "
    "domains, excluded endpoints or values, all solution branches, units, constants of "
    "integration, and every requested part of the problem. When steps are shown, one "
    "transformation per numbered step: operation label, then the formula alone on the "
    "next `$...$` line. Copy verified formulas; do not recompute them. Inverse "
    "operations are for equations, not a universal teaching method."
)
