"""Verified circuit operations."""

from __future__ import annotations

from app.modules.physics.catalog.spec import FormulaSpec, FormulaVariant, formula, var

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "voltage",
        "circuit",
        "Ohm's law",
        "V",
        base_latex="V = IR",
        variables=(
            var("I", "I", "ampere"),
            var("R", "R", "ohm"),
        ),
    ),
    formula(
        "current",
        "circuit",
        "Ohm's law",
        "I",
        base_latex="V = IR",
        variables=(
            var("R", "R", "ohm"),
            var("V", "V", "volt"),
        ),
    ),
    formula(
        "resistance",
        "circuit",
        "Ohm's law",
        "R",
        base_latex="V = IR",
        variables=(
            var("I", "I", "ampere"),
            var("V", "V", "volt"),
        ),
    ),
    formula(
        "electrical_power",
        "circuit",
        "Electrical-power formula",
        "P",
        base_latex="P = VI",
        variables=(
            var("I", "I", "ampere"),
            var("R", "R", "ohm"),
            var("V", "V", "volt"),
        ),
    ),
    formula(
        "series_resistance",
        "circuit",
        "Series-resistance law",
        "R_s",
        variables=(
            var("R1", "R_1", "ohm"),
            var("R2", "R_2", "ohm"),
            var("R3", "R_3", "ohm"),
        ),
    ),
    formula(
        "parallel_resistance",
        "circuit",
        "Parallel-resistance law",
        "R_p",
        variables=(
            var("R1", "R_1", "ohm"),
            var("R2", "R_2", "ohm"),
            var("R3", "R_3", "ohm"),
        ),
    ),
    formula(
        "charge",
        "circuit",
        "Charge-current relation",
        "Q",
        variables=(
            var("I", "I", "ampere"),
            var("t", "t", "second"),
        ),
    ),
    formula(
        "electrical_energy",
        "circuit",
        "Electrical-energy formula",
        "E",
        variables=(
            var("power", "P", "watt"),
            var("t", "t", "second"),
        ),
    ),
    formula(
        "capacitance",
        "circuit",
        "Capacitance formula",
        "C",
        variables=(
            var("Q", "Q", "coulomb"),
            var("V", "V", "volt"),
        ),
    ),
    formula(
        "parallel_plate_capacitance",
        "circuit",
        "Parallel-plate capacitance",
        "C",
        base_latex="C = \\frac{\\epsilon_0A}{d}",
        variables=(
            var("area", "A", "meter ** 2"),
            var("d", "d", "meter"),
        ),
    ),
    formula(
        "capacitor_energy",
        "circuit",
        "Capacitor energy",
        "U",
        base_latex="U = \\frac{1}{2}CV^2",
        variables=(
            var("V", "V", "volt"),
            var("capacitance", "C", "farad"),
        ),
    ),
    formula(
        "rc_time_constant",
        "circuit",
        "RC time constant",
        "\\tau",
        base_latex="\\tau = RC",
        variables=(
            var("R", "R", "ohm"),
            var("capacitance", "C", "farad"),
        ),
    ),
    formula(
        "terminal_voltage",
        "circuit",
        "Terminal-voltage equation",
        "V_{terminal}",
        variables=(
            var("E_emf", r"\mathcal{E}", "volt"),
            var("I", "I", "ampere"),
            var("r_int", "r", "ohm"),
        ),
    ),
    formula(
        "kirchhoff_junction",
        "circuit",
        "Kirchhoff's junction rule",
        "I",
        base_latex=r"\sum I_{\mathrm{in}} = \sum I_{\mathrm{out}}",
        assumptions=("one junction and steady current",),
        variables=(
            var("i_enter", r"I_{\mathrm{in}}", "ampere"),
            var("i_leave", r"I_{\mathrm{out}}", "ampere"),
        ),
    ),
    formula(
        "kirchhoff_loop",
        "circuit",
        "Kirchhoff's loop rule",
        "I",
        base_latex=r"\sum \Delta V = 0",
        assumptions=("one battery and one series loop",),
        variables=(
            var("R1", "R_1", "ohm"),
            var("R2", "R_2", "ohm"),
            var("R3", "R_3", "ohm"),
            var("R4", "R_4", "ohm"),
            var("V", "V", "volt"),
        ),
    ),
    formula(
        "inductor_emf",
        "circuit",
        "Inductor emf",
        r"|\mathcal{E}|",
        base_latex=r"|\mathcal{E}| = L\frac{|\Delta I|}{\Delta t}",
        assumptions=("magnitude; the minus sign is direction",),
        variables=(
            var("delta_i", r"\Delta I", "ampere"),
            var("dt", r"\Delta t", "second"),
            var("inductance", "L", "henry"),
        ),
    ),
    formula(
        "inductor_energy",
        "circuit",
        "Inductor energy",
        "U",
        base_latex=r"U = \frac{1}{2}LI^2",
        variables=(
            var("I", "I", "ampere"),
            var("inductance", "L", "henry"),
        ),
    ),
    formula(
        "rl_time_constant",
        "circuit",
        "RL time constant",
        r"\tau",
        base_latex=r"\tau = \frac{L}{R}",
        variables=(
            var("R", "R", "ohm"),
            var("inductance", "L", "henry"),
        ),
    ),
    formula(
        "rl_growth",
        "circuit",
        "RL current growth",
        "I",
        base_latex=r"I = \frac{V}{R}(1-e^{-tR/L})",
        assumptions=("current is zero before the switch closes",),
        variables=(
            var("R", "R", "ohm"),
            var("V", "V", "volt"),
            var("inductance", "L", "henry"),
            var("t", "t", "second"),
        ),
    ),
    formula(
        "rl_decay",
        "circuit",
        "RL current decay",
        "I",
        base_latex=r"I = I_0 e^{-Rt/L}",
        assumptions=("the source is removed at t = 0",),
        variables=(
            var("I0", "I_0", "ampere"),
            var("R", "R", "ohm"),
            var("inductance", "L", "henry"),
            var("t", "t", "second"),
        ),
    ),
    formula(
        "rms_voltage",
        "circuit",
        "RMS voltage",
        "V_{rms}",
        base_latex=r"V_{\mathrm{rms}} = \frac{V_0}{\sqrt{2}}",
        assumptions=("sinusoidal voltage",),
        variables=(
            var("V", "V", "volt"),
            var("to_peak", "to_peak", dimensionless=True, visible=False),
        ),
        variants=(
            FormulaVariant(
                present=frozenset({"to_peak"}),
                latex=r"V_0 = V_{\mathrm{rms}}\sqrt{2}",
                result_symbol="V_0",
            ),
        ),
    ),
    formula(
        "rms_current",
        "circuit",
        "RMS current",
        "I_{rms}",
        base_latex=r"I_{\mathrm{rms}} = \frac{I_0}{\sqrt{2}}",
        assumptions=("sinusoidal current",),
        variables=(
            var("I", "I", "ampere"),
            var("to_peak", "to_peak", dimensionless=True, visible=False),
        ),
        variants=(
            FormulaVariant(
                present=frozenset({"to_peak"}),
                latex=r"I_0 = I_{\mathrm{rms}}\sqrt{2}",
                result_symbol="I_0",
            ),
        ),
    ),
    formula(
        "inductive_reactance",
        "circuit",
        "Inductive reactance",
        "X_L",
        base_latex=r"X_L = 2\pi f L",
        variables=(
            var("freq", "f", "hertz"),
            var("inductance", "L", "henry"),
        ),
    ),
    formula(
        "capacitive_reactance",
        "circuit",
        "Capacitive reactance",
        "X_C",
        base_latex=r"X_C = \frac{1}{2\pi f C}",
        variables=(
            var("capacitance", "C", "farad"),
            var("freq", "f", "hertz"),
        ),
    ),
    formula(
        "series_impedance",
        "circuit",
        "Series impedance",
        "Z",
        base_latex=r"Z = \sqrt{R^2+(X_L-X_C)^2}",
        assumptions=("series RLC",),
        variables=(
            var("R", "R", "ohm"),
            var("capacitance", "C", "farad"),
            var("freq", "f", "hertz"),
            var("inductance", "L", "henry"),
            var("reactance_c", "X_C", "ohm"),
            var("reactance_l", "X_L", "ohm"),
        ),
    ),
    formula(
        "lc_resonance",
        "circuit",
        "LC resonance",
        "f",
        base_latex=r"f = \frac{1}{2\pi\sqrt{LC}}",
        variables=(
            var("capacitance", "C", "farad"),
            var("inductance", "L", "henry"),
        ),
    ),
    formula(
        "ac_average_power",
        "circuit",
        "Average AC power",
        "P",
        base_latex="P = I^2 R",
        assumptions=("average power in the resistor",),
        variables=(
            var("I", "I", "ampere"),
            var("R", "R", "ohm"),
        ),
    ),
)
