"""Verified circuit operations."""

from __future__ import annotations

from app.modules.physics.catalog.spec import FormulaSpec, formula

SPECS: tuple[FormulaSpec, ...] = (
    formula("voltage", "circuit", "Ohm's law", "V", base_latex="V = IR"),
    formula("current", "circuit", "Ohm's law", "I", base_latex="V = IR"),
    formula("resistance", "circuit", "Ohm's law", "R", base_latex="V = IR"),
    formula("electrical_power", "circuit", "Electrical-power formula", "P", base_latex="P = VI"),
    formula("series_resistance", "circuit", "Series-resistance law", "R_s"),
    formula("parallel_resistance", "circuit", "Parallel-resistance law", "R_p"),
    formula("charge", "circuit", "Charge-current relation", "Q"),
    formula("electrical_energy", "circuit", "Electrical-energy formula", "E"),
    formula("capacitance", "circuit", "Capacitance formula", "C"),
    formula(
        "parallel_plate_capacitance",
        "circuit",
        "Parallel-plate capacitance",
        "C",
        base_latex="C = \\frac{\\epsilon_0A}{d}",
    ),
    formula(
        "capacitor_energy", "circuit", "Capacitor energy", "U", base_latex="U = \\frac{1}{2}CV^2"
    ),
    formula("rc_time_constant", "circuit", "RC time constant", "\\tau", base_latex="\\tau = RC"),
    formula("terminal_voltage", "circuit", "Terminal-voltage equation", "V_{terminal}"),
    formula(
        "kirchhoff_junction",
        "circuit",
        "Kirchhoff's junction rule",
        "I",
        base_latex=r"\sum I_{\mathrm{in}} = \sum I_{\mathrm{out}}",
        assumptions=("one junction and steady current",),
    ),
    formula(
        "kirchhoff_loop",
        "circuit",
        "Kirchhoff's loop rule",
        "I",
        base_latex=r"\sum \Delta V = 0",
        assumptions=("one battery and one series loop",),
    ),
    formula(
        "inductor_emf",
        "circuit",
        "Inductor emf",
        r"|\mathcal{E}|",
        base_latex=r"|\mathcal{E}| = L\frac{|\Delta I|}{\Delta t}",
        assumptions=("magnitude; the minus sign is direction",),
    ),
    formula(
        "inductor_energy",
        "circuit",
        "Inductor energy",
        "U",
        base_latex=r"U = \frac{1}{2}LI^2",
    ),
    formula(
        "rl_time_constant",
        "circuit",
        "RL time constant",
        r"\tau",
        base_latex=r"\tau = \frac{L}{R}",
    ),
    formula(
        "rl_growth",
        "circuit",
        "RL current growth",
        "I",
        base_latex=r"I = \frac{V}{R}(1-e^{-tR/L})",
        assumptions=("current is zero before the switch closes",),
    ),
    formula(
        "rl_decay",
        "circuit",
        "RL current decay",
        "I",
        base_latex=r"I = I_0 e^{-Rt/L}",
        assumptions=("the source is removed at t = 0",),
    ),
    formula(
        "rms_voltage",
        "circuit",
        "RMS voltage",
        "V_{rms}",
        base_latex=r"V_{\mathrm{rms}} = \frac{V_0}{\sqrt{2}}",
        assumptions=("sinusoidal voltage",),
    ),
    formula(
        "rms_current",
        "circuit",
        "RMS current",
        "I_{rms}",
        base_latex=r"I_{\mathrm{rms}} = \frac{I_0}{\sqrt{2}}",
        assumptions=("sinusoidal current",),
    ),
    formula(
        "inductive_reactance",
        "circuit",
        "Inductive reactance",
        "X_L",
        base_latex=r"X_L = 2\pi f L",
    ),
    formula(
        "capacitive_reactance",
        "circuit",
        "Capacitive reactance",
        "X_C",
        base_latex=r"X_C = \frac{1}{2\pi f C}",
    ),
    formula(
        "series_impedance",
        "circuit",
        "Series impedance",
        "Z",
        base_latex=r"Z = \sqrt{R^2+(X_L-X_C)^2}",
        assumptions=("series RLC",),
    ),
    formula(
        "lc_resonance",
        "circuit",
        "LC resonance",
        "f",
        base_latex=r"f = \frac{1}{2\pi\sqrt{LC}}",
    ),
    formula(
        "ac_average_power",
        "circuit",
        "Average AC power",
        "P",
        base_latex="P = I^2 R",
        assumptions=("average power in the resistor",),
    ),
)
