"""One-expression laws the area catalogs had not named.

Each binding declines unless the question states that law's inputs and asks
for its result. A missing dielectric, atomic number, or third mass still
declines rather than answering the narrower law.
"""

from __future__ import annotations

from app.services.law_binding.spec import Binding, FormulaSpec, formula, var

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "drift_speed",
        "circuit",
        "Drift speed",
        "v_d",
        base_latex=r"v_d = \frac{I}{n e A}",
        assumptions=("one carrier density",),
        expression="I/(number_density*e_charge*area)",
        variables=(
            var("I", "I", "ampere"),
            var(
                "number_density",
                "n",
                "1 / meter ** 3",
                words=("density", "number density", "carrier"),
                needs_words=True,
            ),
            var("area", "A", "meter ** 2", words=("area",), needs_words=True),
        ),
        binding=Binding(
            asks=("drift speed", "drift velocity"),
            result=("meter / second",),
            inputs=(frozenset({"I", "area", "number_density"}),),
            cues=("drift",),
            excludes=("hall",),
            nonnegative=True,
        ),
    ),
    formula(
        "wire_force_per_length",
        "magnetism",
        "Force per length between parallel wires",
        "F/L",
        base_latex=r"\frac{F}{L} = \frac{\mu_0 I_1 I_2}{2\pi d}",
        assumptions=("two long parallel wires",),
        expression="mu_0*i1*i2/(2*pi*wire_separation)",
        variables=(
            var("i1", "I_1", "ampere"),
            var("i2", "I_2", "ampere"),
            var(
                "wire_separation",
                "d",
                "meter",
                words=("apart", "separation", "between"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("force per unit length", "force per meter", "force per metre"),
            result=("newton / meter",),
            inputs=(frozenset({"i1", "i2", "wire_separation"}),),
            cues=("parallel wire", "parallel wires"),
            interchangeable=("i1", "i2"),
            nonnegative=True,
        ),
    ),
    formula(
        "ideal_gas_sound_speed",
        "waves",
        "Speed of sound in an ideal gas",
        "v",
        base_latex=r"v = \sqrt{\frac{\gamma P}{\rho}}",
        assumptions=("an ideal gas",),
        expression="sqrt(gamma_gas*pres/rho)",
        variables=(
            var("gamma_gas", r"\gamma", dimensionless=True, words=("gamma",), needs_words=True),
            var("pres", "P", "pascal"),
            var("rho", r"\rho", "kilogram / meter ** 3", words=("density",), needs_words=True),
        ),
        binding=Binding(
            asks=("speed of sound",),
            result=("meter / second",),
            inputs=(frozenset({"gamma_gas", "pres", "rho"}),),
            cues=("speed of sound",),
            excludes=("string",),
            nonnegative=True,
        ),
    ),
    formula(
        "transformer_current",
        "circuit",
        "Ideal transformer current",
        "I_s",
        base_latex=r"\frac{I_s}{I_p} = \frac{N_p}{N_s}",
        assumptions=("an ideal transformer",),
        expression="i_primary*turns_primary/turns_secondary",
        variables=(
            var("turns_primary", "N_p", dimensionless=True, words=("primary",)),
            var("turns_secondary", "N_s", dimensionless=True, words=("secondary",)),
            var("i_primary", "I_p", "ampere", words=("primary",), needs_words=True),
        ),
        binding=Binding(
            asks=("secondary current", "output current"),
            result=("ampere",),
            inputs=(frozenset({"i_primary", "turns_primary", "turns_secondary"}),),
            cues=("transformer",),
            nonnegative=True,
        ),
    ),
    formula(
        "dielectric_parallel_plate",
        "circuit",
        "Parallel-plate capacitance with a dielectric",
        "C",
        base_latex=r"C = \frac{\kappa\varepsilon_0 A}{d}",
        assumptions=("a linear dielectric filling the gap",),
        expression="dielectric_constant*epsilon_0*area/d",
        variables=(
            var(
                "dielectric_constant",
                r"\kappa",
                dimensionless=True,
                words=("dielectric", "kappa"),
                needs_words=True,
            ),
            var("area", "A", "meter ** 2", words=("area",), needs_words=True),
            var(
                "d",
                "d",
                "meter",
                words=("separation", "spacing", "apart"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("capacitance",),
            result=("farad",),
            inputs=(frozenset({"area", "d", "dielectric_constant"}),),
            cues=("parallel plate", "parallel-plate"),
            excludes=("vacuum",),
            nonnegative=True,
        ),
    ),
    formula(
        "net_blackbody_power",
        "modern",
        "Net blackbody power",
        "P",
        base_latex=r"P = \varepsilon\sigma A(T^4 - T_0^4)",
        assumptions=("the surroundings are a black enclosure",),
        expression="emissivity*sigma*area*(temp**4 - temp_env**4)",
        variables=(
            var(
                "emissivity",
                r"\varepsilon",
                dimensionless=True,
                words=("emissivity",),
                needs_words=True,
            ),
            var("area", "A", "meter ** 2", words=("area",), needs_words=True),
            var(
                "temp",
                "T",
                "kelvin",
                words=("body", "surface"),
                needs_words=True,
            ),
            var(
                "temp_env",
                "T_0",
                "kelvin",
                words=("surroundings", "ambient", "environment"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("net radiated power", "net power"),
            result=("watt",),
            inputs=(frozenset({"area", "emissivity", "temp", "temp_env"}),),
            cues=("blackbody", "stefan"),
            nonnegative=False,
        ),
    ),
    formula(
        "adiabatic_temperature",
        "thermal",
        "Adiabatic temperature-volume relation",
        "T_2",
        base_latex=r"T_1 V_1^{\gamma-1} = T_2 V_2^{\gamma-1}",
        assumptions=("a reversible adiabatic process with gamma stated",),
        expression="temp_initial*(vol1/vol2)**(gamma_gas-1)",
        variables=(
            var("gamma_gas", r"\gamma", dimensionless=True, words=("gamma",), needs_words=True),
            var("temp_initial", "T_1", "kelvin", words=("initial",), needs_words=True),
            var("vol1", "V_1", "meter ** 3", words=("initial",), needs_words=True),
            var("vol2", "V_2", "meter ** 3", words=("final",), needs_words=True),
        ),
        binding=Binding(
            asks=("final temperature", "temperature"),
            result=("kelvin",),
            inputs=(frozenset({"gamma_gas", "temp_initial", "vol1", "vol2"}),),
            cues=("adiabatic",),
            excludes=("pressure",),
            nonnegative=True,
        ),
    ),
    formula(
        "mayer_cp",
        "thermal",
        "Mayer's relation",
        "C_p",
        base_latex=r"C_p - C_v = R",
        assumptions=("an ideal gas, molar heat capacities",),
        expression="cv_molar+R_gas",
        variables=(
            var(
                "cv_molar",
                "C_v",
                "joule / mole / kelvin",
                words=("cv", "constant volume"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("molar heat capacity at constant pressure", "cp"),
            result=("joule / mole / kelvin",),
            inputs=(frozenset({"cv_molar"}),),
            cues=("mayer",),
            nonnegative=True,
        ),
    ),
    formula(
        "mayer_cv",
        "thermal",
        "Mayer's relation",
        "C_v",
        base_latex=r"C_p - C_v = R",
        assumptions=("an ideal gas, molar heat capacities",),
        expression="cp_molar-R_gas",
        variables=(
            var(
                "cp_molar",
                "C_p",
                "joule / mole / kelvin",
                words=("cp", "constant pressure"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("molar heat capacity at constant volume",),
            result=("joule / mole / kelvin",),
            inputs=(frozenset({"cp_molar"}),),
            cues=("mayer",),
            nonnegative=True,
        ),
    ),
    formula(
        "series_phase_tangent",
        "circuit",
        "Series-circuit phase",
        r"\tan\phi",
        base_latex=r"\tan\phi = \frac{X_L - X_C}{R}",
        assumptions=("a series combination",),
        expression="(reactance_l-reactance_c)/R",
        variables=(
            var(
                "reactance_l",
                "X_L",
                "ohm",
                words=("inductive",),
                needs_words=True,
            ),
            var(
                "reactance_c",
                "X_C",
                "ohm",
                words=("capacitive",),
                needs_words=True,
            ),
            var("R", "R", "ohm", words=("resistance",), needs_words=True),
        ),
        binding=Binding(
            asks=("tangent of the phase angle", "phase tangent"),
            result=("dimensionless",),
            inputs=(frozenset({"R", "reactance_c", "reactance_l"}),),
            cues=("phase",),
            nonnegative=False,
        ),
    ),
    formula(
        "average_power_phase",
        "circuit",
        "Average AC power with phase",
        "P",
        base_latex=r"P = V_{\mathrm{rms}} I_{\mathrm{rms}}\cos\phi",
        assumptions=("the phase angle is stated",),
        expression="v_rms*i_rms*cos(angle_phase)",
        variables=(
            var("v_rms", "V_{rms}", "volt", words=("voltage",), needs_words=True),
            var("i_rms", "I_{rms}", "ampere", words=("current",), needs_words=True),
            var(
                "angle_phase",
                r"\phi",
                dimensionless=True,
                words=("phase",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("average power",),
            result=("watt",),
            inputs=(frozenset({"angle_phase", "i_rms", "v_rms"}),),
            cues=("phase angle", "power factor"),
            nonnegative=True,
        ),
    ),
    formula(
        "hydrogenlike_energy",
        "modern",
        "Hydrogen-like energy level",
        "E_n",
        base_latex=r"E_n = -\frac{13.6\,Z^2}{n^2}\,\mathrm{eV}",
        assumptions=("infinite nuclear mass",),
        expression="-13.6*e_charge*atomic_number**2/quantum_n**2",
        variables=(
            var(
                "atomic_number",
                "Z",
                dimensionless=True,
                words=("atomic number", "z"),
                needs_words=True,
            ),
            var("quantum_n", "n", dimensionless=True, words=("n",), needs_words=True),
        ),
        binding=Binding(
            asks=("energy",),
            result=("joule",),
            inputs=(frozenset({"atomic_number", "quantum_n"}),),
            cues=("hydrogen-like", "hydrogenic"),
            excludes=("transition", "wavelength"),
            nonnegative=False,
        ),
    ),
    formula(
        "mutual_inductance_emf",
        "circuit",
        "Mutual inductance",
        r"|\mathcal{E}|",
        base_latex=r"|\mathcal{E}| = M\frac{|\Delta I|}{\Delta t}",
        assumptions=("the mutual inductance is stated",),
        expression="mutual_inductance*sqrt(delta_current**2)/current_dt",
        variables=(
            var(
                "mutual_inductance",
                "M",
                "henry",
                words=("mutual",),
                needs_words=True,
            ),
            var(
                "delta_current",
                r"\Delta I",
                "ampere",
                words=("changes", "change", "current"),
                needs_words=True,
            ),
            var(
                "current_dt",
                r"\Delta t",
                "second",
                words=("during", "in", "over"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("induced emf", "emf"),
            result=("volt",),
            inputs=(frozenset({"current_dt", "delta_current", "mutual_inductance"}),),
            cues=("mutual",),
            nonnegative=True,
        ),
    ),
    formula(
        "dipole_field_axis",
        "magnetism",
        "Electric dipole field on axis",
        "E",
        base_latex=r"E = \frac{1}{4\pi\varepsilon_0}\frac{2p}{r^3}",
        assumptions=("a point on the dipole axis, far from the charges"),
        expression="2*k_e*dipole_moment/dipole_distance**3",
        variables=(
            var(
                "dipole_moment",
                "p",
                "coulomb * meter",
                words=("dipole moment", "moment"),
                needs_words=True,
            ),
            var(
                "dipole_distance",
                "r",
                "meter",
                words=("distance", "axis"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("electric field", "field"),
            result=("volt / meter",),
            inputs=(frozenset({"dipole_distance", "dipole_moment"}),),
            cues=("dipole",),
            excludes=("torque",),
            nonnegative=True,
        ),
    ),
    formula(
        "center_of_mass_three",
        "momentum",
        "Center of mass of three masses",
        "x_{cm}",
        base_latex=r"x_{cm} = \frac{m_1x_1 + m_2x_2 + m_3x_3}{m_1 + m_2 + m_3}",
        expression="(m1*x1+m2*x2+m3*x3)/(m1+m2+m3)",
        variables=(
            var("m1", "m_1", "kilogram"),
            var("m2", "m_2", "kilogram"),
            var("m3", "m_3", "kilogram"),
            var("x1", "x_1", "meter"),
            var("x2", "x_2", "meter"),
            var("x3", "x_3", "meter"),
        ),
        binding=Binding(
            asks=("center of mass", "centre of mass"),
            result=("meter",),
            inputs=(frozenset({"m1", "m2", "m3", "x1", "x2", "x3"}),),
            cues=("center of mass", "centre of mass"),
            nonnegative=False,
        ),
    ),
    formula(
        "thin_film_constructive",
        "optics",
        "Thin-film constructive interference",
        "t",
        base_latex=r"2nt = \left(m+\frac{1}{2}\right)\lambda",
        assumptions=("normal incidence, a phase change at exactly one surface"),
        expression="(order+0.5)*wavelength/(2*n_index)",
        variables=(
            var("order", "m", dimensionless=True, words=("order",), needs_words=True),
            var("wavelength", r"\lambda", "meter", words=("wavelength",), needs_words=True),
            var("n_index", "n", dimensionless=True, words=("index",), needs_words=True),
        ),
        binding=Binding(
            asks=("thickness",),
            result=("meter",),
            inputs=(frozenset({"n_index", "order", "wavelength"}),),
            cues=("constructive",),
            excludes=("destructive",),
            nonnegative=True,
        ),
    ),
    formula(
        "thin_film_destructive",
        "optics",
        "Thin-film destructive interference",
        "t",
        base_latex=r"2nt = m\lambda",
        assumptions=("normal incidence, a phase change at exactly one surface"),
        expression="order*wavelength/(2*n_index)",
        variables=(
            var("order", "m", dimensionless=True, words=("order",), needs_words=True),
            var("wavelength", r"\lambda", "meter", words=("wavelength",), needs_words=True),
            var("n_index", "n", dimensionless=True, words=("index",), needs_words=True),
        ),
        binding=Binding(
            asks=("thickness",),
            result=("meter",),
            inputs=(frozenset({"n_index", "order", "wavelength"}),),
            cues=("destructive",),
            excludes=("constructive",),
            nonnegative=True,
        ),
    ),
    formula(
        "vis_viva",
        "gravitation",
        "Vis-viva equation",
        "v",
        base_latex=r"v = \sqrt{GM\left(\frac{2}{r}-\frac{1}{a}\right)}",
        assumptions=("a Kepler orbit about a fixed central mass"),
        expression="sqrt(G_grav*M*(2/orbit_radius-1/semi_major))",
        variables=(
            var("M", "M", "kilogram", fallback="body_mass"),
            var(
                "orbit_radius",
                "r",
                "meter",
                words=("distance", "radius"),
                needs_words=True,
            ),
            var(
                "semi_major",
                "a",
                "meter",
                words=("semi-major", "semimajor"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("orbital speed", "speed"),
            result=("meter / second",),
            inputs=(frozenset({"M", "orbit_radius", "semi_major"}),),
            cues=("vis-viva", "vis viva", "semi-major", "semimajor"),
            nonnegative=True,
        ),
    ),
    formula(
        "fermi_energy",
        "modern",
        "Fermi energy",
        "E_F",
        base_latex=r"E_F = \frac{\hbar^2}{2m_e}(3\pi^2 n)^{2/3}",
        assumptions=("a three-dimensional free-electron gas"),
        expression="(hbar**2/(2*m_e))*(3*pi**2*number_density)**(2/3)",
        variables=(
            var(
                "number_density",
                "n",
                "1 / meter ** 3",
                words=("density",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("fermi energy", "energy"),
            result=("joule",),
            inputs=(frozenset({"number_density"}),),
            cues=("fermi",),
            nonnegative=True,
        ),
    ),
    formula(
        "planck_spectral_radiance",
        "modern",
        "Planck's law",
        r"B_\lambda",
        base_latex=r"B_\lambda = \frac{2hc^2}{\lambda^5}\frac{1}{e^{hc/\lambda kT}-1}",
        assumptions=("spectral radiance per steradian, wavelength form"),
        expression=(
            "2*h_planck*c_light**2/wavelength**5/(exp(h_planck*c_light/(wavelength*k_B*temp))-1)"
        ),
        variables=(
            var("wavelength", r"\lambda", "meter", words=("wavelength",), needs_words=True),
            var("temp", "T", "kelvin", words=("temperature",), needs_words=True),
        ),
        binding=Binding(
            asks=("spectral radiance",),
            result=("watt / meter ** 3",),
            inputs=(frozenset({"temp", "wavelength"}),),
            cues=("planck", "blackbody distribution"),
            excludes=("photon",),
            nonnegative=True,
        ),
    ),
    formula(
        "skin_depth",
        "magnetism",
        "Skin depth",
        r"\delta",
        base_latex=r"\delta = \frac{1}{\sqrt{\pi f \mu_0 \sigma}}",
        assumptions=("a good nonmagnetic conductor"),
        expression="1/sqrt(pi*freq*mu_0*conductivity)",
        variables=(
            var("freq", "f", "hertz", words=("frequency",), needs_words=True),
            var(
                "conductivity",
                r"\sigma",
                "siemens / meter",
                words=("conductivity",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("skin depth",),
            result=("meter",),
            inputs=(frozenset({"conductivity", "freq"}),),
            cues=("skin depth", "skin effect"),
            excludes=("relative permeability", "resistivity"),
            nonnegative=True,
        ),
    ),
    formula(
        "skin_depth_resistivity",
        "magnetism",
        "Skin depth",
        r"\delta",
        base_latex=r"\delta = \sqrt{\frac{\rho}{\pi f \mu_0}}",
        assumptions=("a good nonmagnetic conductor"),
        expression="sqrt(resistivity/(pi*freq*mu_0))",
        variables=(
            var("freq", "f", "hertz", words=("frequency",), needs_words=True),
            var(
                "resistivity",
                r"\rho",
                "ohm * meter",
                words=("resistivity",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("skin depth",),
            result=("meter",),
            inputs=(frozenset({"freq", "resistivity"}),),
            cues=("skin depth", "skin effect"),
            excludes=("conductivity", "relative permeability"),
            nonnegative=True,
        ),
    ),
    formula(
        "skin_depth_permeability",
        "magnetism",
        "Skin depth",
        r"\delta",
        base_latex=r"\delta = \frac{1}{\sqrt{\pi f \mu_0 \mu_r \sigma}}",
        assumptions=("a good conductor of stated relative permeability"),
        expression="1/sqrt(pi*freq*mu_0*relative_permeability*conductivity)",
        variables=(
            var("freq", "f", "hertz", words=("frequency",), needs_words=True),
            var(
                "conductivity",
                r"\sigma",
                "siemens / meter",
                words=("conductivity",),
                needs_words=True,
            ),
            var(
                "relative_permeability",
                r"\mu_r",
                dimensionless=True,
                words=("relative permeability", "relative"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("skin depth",),
            result=("meter",),
            inputs=(frozenset({"conductivity", "freq", "relative_permeability"}),),
            cues=("skin depth", "skin effect"),
            nonnegative=True,
        ),
    ),
    formula(
        "coaxial_capacitance",
        "circuit",
        "Coaxial capacitance",
        "C",
        base_latex=r"C = \frac{2\pi\varepsilon_0 L}{\ln(b/a)}",
        assumptions=("vacuum between the conductors"),
        expression="2*pi*epsilon_0*cable_length/log(outer_radius/inner_radius)",
        variables=(
            var("cable_length", "L", "meter", words=("long", "length"), needs_words=True),
            var("inner_radius", "a", "meter", words=("inner",), needs_words=True),
            var("outer_radius", "b", "meter", words=("outer",), needs_words=True),
        ),
        binding=Binding(
            asks=("capacitance",),
            result=("farad",),
            inputs=(frozenset({"cable_length", "inner_radius", "outer_radius"}),),
            cues=("coaxial",),
            nonnegative=True,
        ),
    ),
    formula(
        "spherical_capacitance",
        "circuit",
        "Spherical capacitor",
        "C",
        base_latex=r"C = 4\pi\varepsilon_0\frac{ab}{b-a}",
        assumptions=("vacuum between concentric spheres"),
        expression="4*pi*epsilon_0*inner_radius*outer_radius/(outer_radius-inner_radius)",
        variables=(
            var("inner_radius", "a", "meter", words=("inner",), needs_words=True),
            var("outer_radius", "b", "meter", words=("outer",), needs_words=True),
        ),
        binding=Binding(
            asks=("capacitance",),
            result=("farad",),
            inputs=(frozenset({"inner_radius", "outer_radius"}),),
            cues=("spherical capacitor",),
            nonnegative=True,
        ),
    ),
    formula(
        "quality_factor_bandwidth",
        "circuit",
        "Quality factor",
        "Q",
        base_latex=r"Q = \frac{f_0}{\Delta f}",
        assumptions=("the bandwidth is the full width"),
        expression="resonant_freq/bandwidth",
        variables=(
            var(
                "resonant_freq",
                "f_0",
                "hertz",
                words=("resonant", "frequency"),
                needs_words=True,
            ),
            var("bandwidth", r"\Delta f", "hertz", words=("bandwidth",), needs_words=True),
        ),
        binding=Binding(
            asks=("quality factor",),
            result=("dimensionless",),
            inputs=(frozenset({"bandwidth", "resonant_freq"}),),
            cues=("quality factor", "q factor"),
            nonnegative=True,
        ),
    ),
    formula(
        "quality_factor_rlc",
        "circuit",
        "Series RLC quality factor",
        "Q",
        base_latex=r"Q = \frac{1}{R}\sqrt{\frac{L}{C}}",
        assumptions=("a series combination at resonance"),
        expression="sqrt(inductance/capacitance)/R",
        variables=(
            var("R", "R", "ohm", words=("resistance",), needs_words=True),
            var("inductance", "L", "henry", words=("inductance",), needs_words=True),
            var("capacitance", "C", "farad", words=("capacitance",), needs_words=True),
        ),
        binding=Binding(
            asks=("quality factor",),
            result=("dimensionless",),
            inputs=(frozenset({"R", "capacitance", "inductance"}),),
            cues=("quality factor", "q factor"),
            excludes=("bandwidth",),
            nonnegative=True,
        ),
    ),
    formula(
        "tunnel_probability",
        "modern",
        "Tunneling probability",
        "T",
        base_latex=r"T \approx \exp\left(-\frac{2L}{\hbar}\sqrt{2m(U-E)}\right)",
        assumptions=("a rectangular barrier with E < U; the prefactor is omitted"),
        expression="exp(-2*barrier_width*sqrt(2*m*(barrier_height-particle_energy))/hbar)",
        variables=(
            var("m", "m", "kilogram", fallback="particle_mass"),
            var(
                "barrier_height",
                "U",
                "joule",
                words=("barrier", "height"),
                needs_words=True,
            ),
            var(
                "particle_energy",
                "E",
                "joule",
                words=("energy", "kinetic"),
                needs_words=True,
            ),
            var(
                "barrier_width",
                "L",
                "meter",
                words=("wide", "width", "thick"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("tunneling probability", "transmission probability"),
            result=("dimensionless",),
            inputs=(frozenset({"barrier_height", "barrier_width", "m", "particle_energy"}),),
            cues=("tunnel",),
            nonnegative=True,
            at_most=1.0,
        ),
    ),
)
