"""Closed formulas the school-to-early-graduate catalog did not yet name.

Each one is a single expression with the inputs the question has to state.
A missing axis, sign, or direction still declines.
"""

from __future__ import annotations

from app.services.law_binding.spec import Binding, FormulaSpec, FormulaVariant, formula, var

_RISE = ("by", "rise", "change", "increase", "raised", "heated", "cooled", "difference")
_DELTA_TEMP = var("delta_temp", r"\Delta T", "kelvin", words=_RISE, needs_words=True)
_ALPHA = var(
    "alpha",
    r"\alpha",
    "1 / kelvin",
    words=("linear expansivity", "linear expansion", "coefficient of linear"),
    needs_words=True,
)

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "area_expansion",
        "thermal",
        "Area thermal expansion",
        r"\Delta A",
        base_latex=r"\Delta A = 2\alpha A_0\Delta T",
        assumptions=("the linear expansivity is the same in both directions",),
        expression="2*alpha*area0*delta_temp",
        variables=(
            var("area0", "A_0", "meter ** 2", words=("area",), needs_words=True),
            _ALPHA,
            _DELTA_TEMP,
        ),
        binding=Binding(
            asks=("change in area", "increase in area", "area expansion"),
            result=("meter ** 2",),
            inputs=(frozenset({"alpha", "area0", "delta_temp"}),),
            cues=("area",),
            excludes=("volume",),
            nonnegative=True,
        ),
    ),
    formula(
        "volume_expansion",
        "thermal",
        "Volume thermal expansion",
        r"\Delta V",
        base_latex=r"\Delta V = \beta V_0\Delta T",
        expression="beta*volume0*delta_temp",
        variables=(
            var("volume0", "V_0", "meter ** 3", words=("volume",), needs_words=True),
            var(
                "beta",
                r"\beta",
                "1 / kelvin",
                words=("volume expansivity", "cubical expansivity", "volume expansion"),
                needs_words=True,
            ),
            _ALPHA,
            _DELTA_TEMP,
        ),
        variants=(
            FormulaVariant(
                present=frozenset({"alpha"}),
                absent=frozenset({"beta"}),
                latex=r"\Delta V = 3\alpha V_0\Delta T",
                expression="3*alpha*volume0*delta_temp",
                assumptions=("the volume expansivity is three times the linear one",),
            ),
        ),
        binding=Binding(
            asks=("change in volume", "increase in volume", "volume expansion"),
            result=("meter ** 3",),
            inputs=(
                frozenset({"beta", "delta_temp", "volume0"}),
                frozenset({"alpha", "delta_temp", "volume0"}),
            ),
            cues=("volume",),
            excludes=("area",),
            nonnegative=True,
        ),
    ),
    formula(
        "isothermal_work",
        "thermal",
        "Isothermal work of an ideal gas",
        "W",
        base_latex=r"W = nRT\ln\frac{V_2}{V_1}",
        assumptions=("the temperature is constant", "the gas is ideal"),
        expression="moles*R_gas*temp*log(vol_final/vol_initial)",
        variables=(
            var("moles", "n", "mole"),
            var("temp", "T", "kelvin", words=("at",), needs_words=True),
            var("vol_initial", "V_1", "meter ** 3", words=("from",), needs_words=True),
            var("vol_final", "V_2", "meter ** 3", words=("to",), needs_words=True),
        ),
        binding=Binding(
            asks=("work", "work done"),
            result=("joule",),
            inputs=(frozenset({"moles", "temp", "vol_final", "vol_initial"}),),
            cues=("isothermal", "isothermally"),
            negative_detail="done on the gas",
        ),
    ),
    formula(
        "mean_free_path",
        "thermal",
        "Mean free path",
        r"\lambda",
        base_latex=r"\lambda = \frac{1}{\sqrt{2}\pi d^2 n}",
        assumptions=("the molecules are hard spheres",),
        expression="1/(sqrt(2)*pi*diameter**2*number_density)",
        variables=(
            var("diameter", "d", "meter", words=("diameter",), needs_words=True),
            var("number_density", "n", "1 / meter ** 3", words=("density",), needs_words=True),
        ),
        binding=Binding(
            asks=("mean free path",),
            result=("meter",),
            inputs=(frozenset({"diameter", "number_density"}),),
            cues=("mean free path",),
            nonnegative=True,
        ),
    ),
    formula(
        "rocket_delta_v",
        "kinematics",
        "Rocket equation",
        r"\Delta v",
        base_latex=r"\Delta v = v_e\ln\frac{m_0}{m}",
        assumptions=("the exhaust speed is constant", "no external force"),
        expression="v_exhaust*log(m_initial/m_final)",
        variables=(
            var(
                "v_exhaust",
                "v_e",
                "meter / second",
                words=("exhaust", "exhausts", "ejected"),
                needs_words=True,
            ),
            var("m_initial", "m_0", "kilogram", words=("from", "initial"), needs_words=True),
            var("m_final", "m", "kilogram", words=("to", "final"), needs_words=True),
        ),
        binding=Binding(
            asks=("change in speed", "speed change", "delta v"),
            result=("meter / second",),
            inputs=(frozenset({"m_final", "m_initial", "v_exhaust"}),),
            cues=("rocket",),
            nonnegative=True,
        ),
    ),
    formula(
        "loop_magnetic_field",
        "magnetism",
        "Magnetic field at the center of a loop",
        "B",
        base_latex=r"B = \frac{\mu_0 I}{2R}",
        assumptions=("the point is at the center of a single circular loop",),
        expression="mu_0*I/(2*r)",
        variables=(
            var("I", "I", "ampere"),
            var("r", "R", "meter", words=("radius",), needs_words=True),
        ),
        binding=Binding(
            asks=("magnetic field", "flux density"),
            result=("tesla",),
            inputs=(frozenset({"I", "r"}),),
            cues=("circular loop", "current loop"),
            excludes=("solenoid", "toroid", "straight wire", "long wire"),
            nonnegative=True,
        ),
    ),
    formula(
        "toroid_field",
        "magnetism",
        "Magnetic field inside a toroid",
        "B",
        base_latex=r"B = \frac{\mu_0 N I}{2\pi r}",
        assumptions=("the field is inside a tightly wound toroid",),
        expression="mu_0*turns*I/(2*pi*r)",
        variables=(
            var("turns", "N", dimensionless=True),
            var("I", "I", "ampere"),
            var("r", "r", "meter", words=("radius",), needs_words=True),
        ),
        binding=Binding(
            asks=("magnetic field", "flux density"),
            result=("tesla",),
            inputs=(frozenset({"I", "r", "turns"}),),
            cues=("toroid",),
            nonnegative=True,
        ),
    ),
    formula(
        "solenoid_inductance",
        "magnetism",
        "Solenoid self-inductance",
        "L",
        base_latex=r"L = \frac{\mu_0 N^2 A}{\ell}",
        assumptions=("a long solenoid in air",),
        expression="mu_0*turns**2*area/solenoid_length",
        variables=(
            var("turns", "N", dimensionless=True),
            var(
                "area",
                "A",
                "meter ** 2",
                words=("area", "cross-section", "cross sectional"),
                needs_words=True,
            ),
            var(
                "solenoid_length",
                r"\ell",
                "meter",
                words=("length", "long"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("inductance", "self-inductance", "self inductance"),
            result=("henry",),
            inputs=(frozenset({"area", "solenoid_length", "turns"}),),
            cues=("solenoid",),
            excludes=("mutual",),
            nonnegative=True,
        ),
    ),
    formula(
        "cyclotron_frequency",
        "magnetism",
        "Cyclotron frequency",
        "f",
        base_latex=r"f = \frac{qB}{2\pi m}",
        assumptions=("the frequency of revolution, not the angular frequency",),
        expression="Q*b_field/(2*pi*m)",
        variables=(
            var("Q", "q", "coulomb", fallback="particle_charge"),
            var("b_field", "B", "tesla"),
            var("m", "m", "kilogram", fallback="particle_mass"),
        ),
        binding=Binding(
            asks=("cyclotron frequency", "frequency"),
            result=("hertz",),
            inputs=(frozenset({"Q", "b_field", "m"}),),
            cues=("cyclotron",),
            excludes=("angular",),
            nonnegative=True,
        ),
    ),
    formula(
        "hall_voltage",
        "magnetism",
        "Hall voltage",
        "V_H",
        base_latex=r"V_H = \frac{IB}{n e t}",
        assumptions=("the carriers of one sign drift across the strip",),
        expression="I*b_field/(number_density*e_charge*thickness)",
        variables=(
            var("I", "I", "ampere"),
            var("b_field", "B", "tesla"),
            var("number_density", "n", "1 / meter ** 3", words=("density",), needs_words=True),
            var("thickness", "t", "meter", words=("thick", "thickness"), needs_words=True),
        ),
        binding=Binding(
            asks=("hall voltage", "voltage"),
            result=("volt",),
            inputs=(frozenset({"I", "b_field", "number_density", "thickness"}),),
            cues=("hall",),
            nonnegative=True,
        ),
    ),
    formula(
        "electric_energy_density",
        "magnetism",
        "Electric energy density",
        "u",
        base_latex=r"u = \frac{1}{2}\varepsilon_0 E^2",
        expression="epsilon_0*e_field**2/2",
        variables=(var("e_field", "E", "volt / meter"),),
        binding=Binding(
            asks=("energy density", "electric energy density"),
            result=("joule / meter ** 3",),
            inputs=(frozenset({"e_field"}),),
            cues=("electric",),
            excludes=("magnetic",),
            nonnegative=True,
        ),
    ),
    formula(
        "magnetic_energy_density",
        "magnetism",
        "Magnetic energy density",
        "u",
        base_latex=r"u = \frac{B^2}{2\mu_0}",
        expression="b_field**2/(2*mu_0)",
        variables=(var("b_field", "B", "tesla"),),
        binding=Binding(
            asks=("energy density", "magnetic energy density"),
            result=("joule / meter ** 3",),
            inputs=(frozenset({"b_field"}),),
            cues=("magnetic",),
            excludes=("electric",),
            nonnegative=True,
        ),
    ),
    formula(
        "em_wave_intensity",
        "waves",
        "Electromagnetic-wave intensity",
        "I",
        base_latex=r"I = \frac{1}{2}c\varepsilon_0 E_0^2",
        assumptions=("a sinusoidal wave in vacuum",),
        expression="c_light*epsilon_0*e_field**2/2",
        variables=(var("e_field", "E_0", "volt / meter", words=("peak", "amplitude")),),
        binding=Binding(
            asks=("intensity",),
            result=("watt / meter ** 2",),
            inputs=(frozenset({"e_field"}),),
            cues=("electromagnetic", "em wave"),
            excludes=("sound",),
            nonnegative=True,
        ),
    ),
    formula(
        "rayleigh_angle",
        "optics",
        "Rayleigh criterion",
        r"\theta",
        base_latex=r"\theta = 1.22\frac{\lambda}{D}",
        assumptions=("a circular aperture",),
        expression="1.22*wavelength/aperture_diameter",
        variables=(
            var("wavelength", r"\lambda", "meter", words=("wavelength",), needs_words=True),
            var(
                "aperture_diameter",
                "D",
                "meter",
                words=("diameter",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("angle", "angular separation", "rayleigh criterion"),
            result=("radian",),
            inputs=(frozenset({"aperture_diameter", "wavelength"}),),
            cues=("rayleigh",),
            nonnegative=True,
        ),
    ),
    formula(
        "lens_power_sum",
        "optics",
        "Thin lenses in contact",
        "P",
        base_latex=r"P = P_1 + P_2",
        assumptions=("the lenses are thin and in contact",),
        expression="p1+p2",
        variables=(
            var("p1", "P_1", "1 / meter"),
            var("p2", "P_2", "1 / meter"),
        ),
        binding=Binding(
            asks=("power", "lens power", "total power"),
            result=("1 / meter",),
            inputs=(frozenset({"p1", "p2"}),),
            cues=("in contact",),
            interchangeable=("p1", "p2"),
            excludes=("telescope",),
            nonnegative=True,
        ),
    ),
    formula(
        "telescope_magnification",
        "optics",
        "Telescope angular magnification",
        "M",
        base_latex=r"M = \frac{f_o}{f_e}",
        assumptions=("the magnitude for an astronomical telescope in normal adjustment",),
        expression="focal_obj/focal_eye",
        variables=(
            var("focal_obj", "f_o", "meter", words=("objective",), needs_words=True),
            var("focal_eye", "f_e", "meter", words=("eyepiece",), needs_words=True),
        ),
        binding=Binding(
            asks=("magnification",),
            result=("dimensionless",),
            inputs=(frozenset({"focal_eye", "focal_obj"}),),
            cues=("telescope",),
            excludes=("microscope",),
            nonnegative=True,
        ),
    ),
    formula(
        "reduced_mass",
        "force",
        "Reduced mass",
        r"\mu",
        base_latex=r"\mu = \frac{m_1 m_2}{m_1 + m_2}",
        expression="m1*m2/(m1+m2)",
        variables=(
            var("m1", "m_1", "kilogram"),
            var("m2", "m_2", "kilogram"),
        ),
        binding=Binding(
            asks=("reduced mass",),
            result=("kilogram",),
            inputs=(frozenset({"m1", "m2"}),),
            cues=("reduced mass",),
            interchangeable=("m1", "m2"),
            nonnegative=True,
        ),
    ),
    formula(
        "restitution",
        "momentum",
        "Coefficient of restitution",
        "e",
        base_latex=r"e = \frac{v_{\mathrm{sep}}}{v_{\mathrm{app}}}",
        assumptions=("one dimension",),
        expression="v_sep/v_app",
        variables=(
            var(
                "v_app",
                r"v_{\mathrm{app}}",
                "meter / second",
                words=("approach", "before"),
                needs_words=True,
            ),
            var(
                "v_sep",
                r"v_{\mathrm{sep}}",
                "meter / second",
                words=("separate", "separation", "after", "rebound"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("coefficient of restitution", "restitution"),
            result=("dimensionless",),
            inputs=(frozenset({"v_app", "v_sep"}),),
            cues=("restitution",),
            nonnegative=True,
        ),
    ),
    formula(
        "torsional_period",
        "spring",
        "Torsional-pendulum period",
        "T",
        base_latex=r"T = 2\pi\sqrt{I/\kappa}",
        expression="2*pi*sqrt(inertia/kappa)",
        variables=(
            var("inertia", "I", "kilogram * meter ** 2"),
            var(
                "kappa",
                r"\kappa",
                "newton * meter / radian",
                words=("torsion",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("period",),
            result=("second",),
            inputs=(frozenset({"inertia", "kappa"}),),
            cues=("torsional",),
            nonnegative=True,
        ),
    ),
    formula(
        "rod_center_inertia",
        "rotation",
        "Thin rod about its center",
        "I",
        base_latex=r"I = \frac{1}{12}mL^2",
        assumptions=("the axis is perpendicular to the rod through its center",),
        expression="m*rod_length**2/12",
        variables=(
            var("m", "m", "kilogram"),
            var("rod_length", "L", "meter"),
        ),
        binding=Binding(
            asks=("moment of inertia",),
            result=("kilogram * meter ** 2",),
            inputs=(frozenset({"m", "rod_length"}),),
            cues=("rod",),
            excludes=("end",),
            nonnegative=True,
        ),
    ),
    formula(
        "rod_end_inertia",
        "rotation",
        "Thin rod about one end",
        "I",
        base_latex=r"I = \frac{1}{3}mL^2",
        assumptions=("the axis is perpendicular to the rod through one end",),
        expression="m*rod_length**2/3",
        variables=(
            var("m", "m", "kilogram"),
            var("rod_length", "L", "meter"),
        ),
        binding=Binding(
            asks=("moment of inertia",),
            result=("kilogram * meter ** 2",),
            inputs=(frozenset({"m", "rod_length"}),),
            cues=("rod",),
            excludes=("center", "centre"),
            nonnegative=True,
        ),
    ),
    formula(
        "gravitational_frequency_shift",
        "gravitation",
        "Gravitational frequency shift",
        r"\frac{\Delta f}{f}",
        base_latex=r"\frac{\Delta f}{f} = \frac{gh}{c^2}",
        assumptions=("a weak uniform field",),
        expression="g*h/c_light**2",
        variables=(
            var("g", "g", "meter / second ** 2"),
            var("h", "h", "meter", words=("above", "height"), needs_words=True),
        ),
        binding=Binding(
            asks=("fractional frequency shift", "frequency shift"),
            result=("dimensionless",),
            inputs=(frozenset({"g", "h"}),),
            cues=("gravitational",),
            nonnegative=True,
        ),
    ),
    formula(
        "decay_elapsed",
        "modern",
        "Radioactive decay time",
        "t",
        base_latex=r"t = \frac{1}{\lambda}\ln\frac{N_0}{N}",
        expression="log(n_initial/n_final)/decay_const",
        variables=(
            var("n_initial", "N_0", dimensionless=True, words=("from",), needs_words=True),
            var("n_final", "N", dimensionless=True, words=("to",), needs_words=True),
            var(
                "decay_const",
                r"\lambda",
                "1 / second",
                words=("decay constant",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("time", "time elapsed", "age"),
            result=("second",),
            inputs=(frozenset({"decay_const", "n_final", "n_initial"}),),
            cues=("decay",),
            nonnegative=True,
        ),
    ),
    formula(
        "microscope_magnification",
        "optics",
        "Compound microscope magnification",
        "M",
        base_latex=r"M = \frac{L D}{f_o f_e}",
        assumptions=("normal adjustment, and the magnitude",),
        expression="tube_length*near_point/(focal_obj*focal_eye)",
        variables=(
            var("tube_length", "L", "meter", words=("tube",), needs_words=True),
            var(
                "near_point",
                "D",
                "meter",
                words=("near point", "least distance"),
                needs_words=True,
            ),
            var("focal_obj", "f_o", "meter", words=("objective",), needs_words=True),
            var("focal_eye", "f_e", "meter", words=("eyepiece",), needs_words=True),
        ),
        binding=Binding(
            asks=("magnification",),
            result=("dimensionless",),
            inputs=(frozenset({"focal_eye", "focal_obj", "near_point", "tube_length"}),),
            cues=("microscope",),
            excludes=("telescope",),
            nonnegative=True,
        ),
    ),
    formula(
        "lens_maker",
        "optics",
        "Lens-maker equation",
        "f",
        base_latex=r"\frac{1}{f} = (n-1)\left(\frac{1}{R_1}-\frac{1}{R_2}\right)",
        assumptions=("a thin lens in air",),
        expression="1/((n_index-1)*(1/r1-1/r2))",
        variants=(
            FormulaVariant(
                latex=r"\frac{1}{f} = (n-1)\left(\frac{1}{R_1}+\frac{1}{R_2}\right)",
                present=frozenset({"convex"}),
                absent=frozenset({"concave"}),
                expression="1/((n_index-1)*(1/r1+1/r2))",
            ),
            FormulaVariant(
                latex=r"\frac{1}{f} = -(n-1)\left(\frac{1}{R_1}+\frac{1}{R_2}\right)",
                present=frozenset({"concave"}),
                expression="-1/((n_index-1)*(1/r1+1/r2))",
            ),
        ),
        variables=(
            var(
                "n_index",
                "n",
                dimensionless=True,
                words=("refractive index", "index of refraction"),
                needs_words=True,
            ),
            var("r1", "R_1", "meter", words=("first", "r1"), needs_words=False),
            var("r2", "R_2", "meter", words=("second", "r2"), needs_words=False),
            var(
                "convex",
                "",
                dimensionless=True,
                visible=False,
                implied=(("biconvex", 1.0), ("double convex", 1.0), ("convex lens", 1.0)),
            ),
            var(
                "concave",
                "",
                dimensionless=True,
                visible=False,
                implied=(("biconcave", 1.0), ("double concave", 1.0), ("concave lens", 1.0)),
            ),
        ),
        binding=Binding(
            asks=("focal length",),
            result=("meter",),
            inputs=(
                frozenset({"n_index", "r1", "r2"}),
                frozenset({"concave", "n_index", "r1", "r2"}),
                frozenset({"convex", "n_index", "r1", "r2"}),
            ),
            cues=("lens maker", "lensmaker", "radii", "radius of curvature", "biconvex"),
            excludes=("telescope", "microscope", "mirror"),
            interchangeable=("r1", "r2"),
            nonnegative=False,
        ),
    ),
    formula(
        "springs_parallel",
        "spring",
        "Springs in parallel",
        "k",
        base_latex="k = k_1 + k_2",
        expression="k1+k2",
        variables=(
            var("k1", "k_1", "newton / meter"),
            var("k2", "k_2", "newton / meter"),
        ),
        binding=Binding(
            asks=("spring constant", "equivalent spring constant", "effective spring constant"),
            result=("newton / meter",),
            inputs=(frozenset({"k1", "k2"}),),
            cues=("in parallel",),
            excludes=("series",),
            interchangeable=("k1", "k2"),
            nonnegative=True,
        ),
    ),
    formula(
        "springs_series",
        "spring",
        "Springs in series",
        "k",
        base_latex=r"\frac{1}{k} = \frac{1}{k_1}+\frac{1}{k_2}",
        expression="1/(1/k1+1/k2)",
        variables=(
            var("k1", "k_1", "newton / meter"),
            var("k2", "k_2", "newton / meter"),
        ),
        binding=Binding(
            asks=("spring constant", "equivalent spring constant", "effective spring constant"),
            result=("newton / meter",),
            inputs=(frozenset({"k1", "k2"}),),
            cues=("in series",),
            excludes=("parallel",),
            interchangeable=("k1", "k2"),
            nonnegative=True,
        ),
    ),
    formula(
        "magnetic_moment",
        "magnetism",
        "Magnetic moment of a current loop",
        r"\mu",
        base_latex=r"\mu = IA",
        expression="loop_current*loop_area",
        variables=(
            var("loop_current", "I", "ampere", words=("current",), needs_words=True),
            var("loop_area", "A", "meter ** 2", words=("area",), needs_words=True),
        ),
        binding=Binding(
            asks=("magnetic moment",),
            result=("ampere * meter ** 2",),
            inputs=(frozenset({"loop_area", "loop_current"}),),
            cues=("magnetic moment",),
            nonnegative=True,
        ),
    ),
    formula(
        "magnetic_moment_torque",
        "magnetism",
        "Torque on a magnetic moment",
        r"\tau",
        base_latex=r"\tau = \mu B\sin\theta",
        assumptions=("the angle between the moment and the field is stated",),
        expression="moment*b_field*sin(angle)",
        variables=(
            var(
                "moment",
                r"\mu",
                "ampere * meter ** 2",
                words=("magnetic moment",),
                needs_words=True,
            ),
            var("b_field", "B", "tesla", words=("field",), needs_words=True),
            var(
                "angle",
                r"\theta",
                dimensionless=True,
                words=("angle", "degree", "degrees"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("torque",),
            result=("newton * meter",),
            inputs=(frozenset({"angle", "b_field", "moment"}),),
            cues=("magnetic moment",),
            nonnegative=True,
        ),
    ),
)
