"""One-expression laws past the undergraduate core.

Each one answers only when the question states that formula's inputs. A
differential equation, a Lagrangian, or a field theory is not in this list.
"""

from __future__ import annotations

from app.services.law_binding.spec import Binding, FormulaSpec, formula, var

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "bulk_sound_speed",
        "waves",
        "Speed of sound from the bulk modulus",
        "v",
        base_latex=r"v = \sqrt{\frac{B}{\rho}}",
        expression="sqrt(bulk_modulus/rho)",
        variables=(
            var("bulk_modulus", "B", "pascal", words=("bulk",), needs_words=True),
            var("rho", r"\rho", "kilogram / meter ** 3", words=("density",), needs_words=True),
        ),
        binding=Binding(
            asks=("speed of sound",),
            result=("meter / second",),
            inputs=(frozenset({"bulk_modulus", "rho"}),),
            cues=("bulk",),
            nonnegative=True,
        ),
    ),
    formula(
        "quadratic_drag_force",
        "fluids",
        "Quadratic drag force",
        "F_D",
        base_latex=r"F_D = \frac{1}{2}C_D\rho A v^2",
        expression="0.5*drag_coefficient*rho*area*v**2",
        variables=(
            var(
                "drag_coefficient",
                "C_D",
                dimensionless=True,
                words=("coefficient",),
                needs_words=True,
            ),
            var("rho", r"\rho", "kilogram / meter ** 3"),
            var("area", "A", "meter ** 2"),
            var("v", "v", "meter / second"),
        ),
        binding=Binding(
            asks=("drag force", "drag"),
            result=("newton",),
            inputs=(frozenset({"area", "drag_coefficient", "rho", "v"}),),
            cues=("drag coefficient",),
            nonnegative=True,
        ),
    ),
    formula(
        "hubble_law",
        "gravitation",
        "Hubble's law",
        "v",
        base_latex=r"v = H_0 d",
        expression="hubble_constant*galaxy_distance",
        variables=(
            var(
                "hubble_constant",
                "H_0",
                "1 / second",
                words=("hubble",),
                needs_words=True,
            ),
            var(
                "galaxy_distance",
                "d",
                "meter",
                words=("distance", "away"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("recessional speed", "recession speed", "speed"),
            result=("meter / second",),
            inputs=(frozenset({"galaxy_distance", "hubble_constant"}),),
            cues=("hubble",),
            excludes=("critical density",),
            nonnegative=True,
        ),
    ),
    formula(
        "critical_density",
        "gravitation",
        "Critical density",
        r"\rho_c",
        base_latex=r"\rho_c = \frac{3H^2}{8\pi G}",
        expression="3*hubble_constant**2/(8*pi*G_grav)",
        variables=(
            var(
                "hubble_constant",
                "H",
                "1 / second",
                words=("hubble",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("critical density",),
            result=("kilogram / meter ** 3",),
            inputs=(frozenset({"hubble_constant"}),),
            cues=("critical density",),
            nonnegative=True,
        ),
    ),
    formula(
        "plasma_frequency",
        "magnetism",
        "Plasma frequency",
        r"\omega_p",
        base_latex=r"\omega_p = \sqrt{\frac{n e^2}{\varepsilon_0 m_e}}",
        assumptions=("electrons in a cold plasma"),
        expression="sqrt(number_density*e_charge**2/(epsilon_0*m_e))",
        variables=(
            var(
                "number_density",
                "n",
                "1 / meter ** 3",
                words=("density",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("plasma frequency", "angular frequency"),
            result=("radian / second",),
            inputs=(frozenset({"number_density"}),),
            cues=("plasma frequency",),
            nonnegative=True,
        ),
    ),
    formula(
        "debye_length",
        "magnetism",
        "Debye length",
        r"\lambda_D",
        base_latex=r"\lambda_D = \sqrt{\frac{\varepsilon_0 k_B T}{n e^2}}",
        assumptions=("one mobile species"),
        expression="sqrt(epsilon_0*k_B*temp/(number_density*e_charge**2))",
        variables=(
            var(
                "number_density",
                "n",
                "1 / meter ** 3",
                words=("density",),
                needs_words=True,
            ),
            var("temp", "T", "kelvin", words=("temperature",), needs_words=True),
        ),
        binding=Binding(
            asks=("debye length", "length"),
            result=("meter",),
            inputs=(frozenset({"number_density", "temp"}),),
            cues=("debye",),
            nonnegative=True,
        ),
    ),
    formula(
        "alfven_speed",
        "magnetism",
        "Alfvén speed",
        "v_A",
        base_latex=r"v_A = \frac{B}{\sqrt{\mu_0\rho}}",
        expression="b_field/sqrt(mu_0*rho)",
        variables=(
            var("b_field", "B", "tesla"),
            var("rho", r"\rho", "kilogram / meter ** 3", words=("density",), needs_words=True),
        ),
        binding=Binding(
            asks=("alfven speed", "speed"),
            result=("meter / second",),
            inputs=(frozenset({"b_field", "rho"}),),
            cues=("alfven", "alven"),
            nonnegative=True,
        ),
    ),
    formula(
        "stellar_luminosity",
        "modern",
        "Stellar luminosity",
        "L",
        base_latex=r"L = 4\pi R^2\sigma T^4",
        assumptions=("a black spherical star"),
        expression="4*pi*star_radius**2*sigma*temp**4",
        variables=(
            var("star_radius", "R", "meter", words=("radius",), needs_words=True),
            var("temp", "T", "kelvin", words=("temperature",), needs_words=True),
        ),
        binding=Binding(
            asks=("luminosity",),
            result=("watt",),
            inputs=(frozenset({"star_radius", "temp"}),),
            cues=("star", "stellar"),
            nonnegative=True,
        ),
    ),
    formula(
        "luminosity_flux",
        "modern",
        "Flux from a point source",
        "F",
        base_latex=r"F = \frac{L}{4\pi r^2}",
        expression="luminosity/(4*pi*star_distance**2)",
        variables=(
            var("luminosity", "L", "watt", words=("luminosity",), needs_words=True),
            var(
                "star_distance",
                "r",
                "meter",
                words=("distance", "away"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("radiant flux", "flux"),
            result=("watt / meter ** 2",),
            inputs=(frozenset({"luminosity", "star_distance"}),),
            cues=("luminosity",),
            nonnegative=True,
        ),
    ),
    formula(
        "nuclear_radius",
        "modern",
        "Nuclear radius",
        "R",
        base_latex=r"R = R_0 A^{1/3}",
        assumptions=(r"R_0 = 1.2\,\mathrm{fm}"),
        expression="1.2e-15*mass_number**(1/3)",
        variables=(
            var(
                "mass_number",
                "A",
                dimensionless=True,
                words=("mass number", "nucleon"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("nuclear radius", "radius"),
            result=("meter",),
            inputs=(frozenset({"mass_number"}),),
            cues=("nuclear radius",),
            nonnegative=True,
        ),
    ),
    formula(
        "drude_conductivity",
        "modern",
        "Drude conductivity",
        r"\sigma",
        base_latex=r"\sigma = \frac{n e^2 \tau}{m_e}",
        assumptions=("electrons"),
        expression="number_density*e_charge**2*scattering_time/m_e",
        variables=(
            var(
                "number_density",
                "n",
                "1 / meter ** 3",
                words=("density",),
                needs_words=True,
            ),
            var(
                "scattering_time",
                r"\tau",
                "second",
                words=("scattering", "relaxation"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("conductivity",),
            result=("siemens / meter",),
            inputs=(frozenset({"number_density", "scattering_time"}),),
            cues=("drude",),
            nonnegative=True,
        ),
    ),
    formula(
        "hall_coefficient",
        "magnetism",
        "Hall coefficient",
        "R_H",
        base_latex=r"R_H = -\frac{1}{ne}",
        assumptions=("electrons; the sign is negative"),
        expression="-1/(number_density*e_charge)",
        variables=(
            var(
                "number_density",
                "n",
                "1 / meter ** 3",
                words=("density",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("hall coefficient",),
            result=("meter ** 3 / coulomb",),
            inputs=(frozenset({"number_density"}),),
            cues=("hall coefficient",),
            nonnegative=False,
        ),
    ),
    formula(
        "hawking_temperature",
        "modern",
        "Hawking temperature",
        "T_H",
        base_latex=r"T_H = \frac{\hbar c^3}{8\pi G M k_B}",
        expression="hbar*c_light**3/(8*pi*G_grav*M*k_B)",
        variables=(var("M", "M", "kilogram", fallback="body_mass"),),
        binding=Binding(
            asks=("hawking temperature", "temperature"),
            result=("kelvin",),
            inputs=(frozenset({"M"}),),
            cues=("hawking",),
            nonnegative=True,
        ),
    ),
    formula(
        "bekenstein_entropy",
        "modern",
        "Bekenstein-Hawking entropy",
        "S",
        base_latex=r"S = \frac{k_B c^3 A}{4 G \hbar}",
        expression="k_B*c_light**3*area/(4*G_grav*hbar)",
        variables=(var("area", "A", "meter ** 2", words=("area",), needs_words=True),),
        binding=Binding(
            asks=("entropy",),
            result=("joule / kelvin",),
            inputs=(frozenset({"area"}),),
            cues=("bekenstein", "black hole entropy", "black-hole entropy"),
            nonnegative=True,
        ),
    ),
    formula(
        "gravitational_time_factor",
        "gravitation",
        "Gravitational time dilation",
        r"d\tau/dt",
        base_latex=r"\frac{d\tau}{dt} = \sqrt{1-\frac{2GM}{rc^2}}",
        assumptions=("the Schwarzschild factor, outside the horizon"),
        expression="sqrt(1-2*G_grav*M/(radial_distance*c_light**2))",
        variables=(
            var("M", "M", "kilogram", fallback="body_mass"),
            var(
                "radial_distance",
                "r",
                "meter",
                words=("distance", "radius"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("time-dilation factor", "dilation factor"),
            result=("dimensionless",),
            inputs=(frozenset({"M", "radial_distance"}),),
            cues=("gravitational",),
            excludes=("velocity", "speed of light"),
            nonnegative=True,
            at_most=1.0,
        ),
    ),
    formula(
        "fermi_dirac_occupation",
        "modern",
        "Fermi-Dirac occupation",
        "f",
        base_latex=r"f = \frac{1}{e^{(E-\mu)/k_B T}+1}",
        expression="1/(exp((state_energy-chemical_potential)/(k_B*temp))+1)",
        variables=(
            var("state_energy", "E", "joule", words=("energy",), needs_words=True),
            var(
                "chemical_potential",
                r"\mu",
                "joule",
                words=("chemical potential", "potential"),
                needs_words=True,
            ),
            var("temp", "T", "kelvin", words=("temperature",), needs_words=True),
        ),
        binding=Binding(
            asks=("occupation number", "occupation"),
            result=("dimensionless",),
            inputs=(frozenset({"chemical_potential", "state_energy", "temp"}),),
            cues=("fermi-dirac", "fermi dirac"),
            nonnegative=True,
            at_most=1.0,
        ),
    ),
    formula(
        "bose_einstein_occupation",
        "modern",
        "Bose-Einstein occupation",
        "f",
        base_latex=r"f = \frac{1}{e^{(E-\mu)/k_B T}-1}",
        assumptions=("E is above the chemical potential"),
        expression="1/(exp((state_energy-chemical_potential)/(k_B*temp))-1)",
        variables=(
            var("state_energy", "E", "joule", words=("energy",), needs_words=True),
            var(
                "chemical_potential",
                r"\mu",
                "joule",
                words=("chemical potential", "potential"),
                needs_words=True,
            ),
            var("temp", "T", "kelvin", words=("temperature",), needs_words=True),
        ),
        binding=Binding(
            asks=("occupation number", "occupation"),
            result=("dimensionless",),
            inputs=(frozenset({"chemical_potential", "state_energy", "temp"}),),
            cues=("bose",),
            nonnegative=True,
        ),
    ),
)
