"""Verified magnetism operations."""

from __future__ import annotations

from app.modules.physics.catalog.spec import FormulaSpec, formula

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "magnetic_force_wire",
        "magnetism",
        "Magnetic force on a wire",
        "F",
        base_latex="F = BIL",
        assumptions=("current is perpendicular to the field",),
    ),
    formula(
        "magnetic_force_charge",
        "magnetism",
        "Lorentz magnetic-force law",
        "F",
        base_latex="F = qvB",
        assumptions=("velocity is perpendicular to the field",),
    ),
    formula(
        "electric_force",
        "magnetism",
        "Coulomb's law",
        "F_e",
        base_latex="F_e = k_e \\frac{\\lvert q_1q_2\\rvert}{r^2}",
    ),
    formula(
        "magnetic_flux",
        "magnetism",
        "Magnetic-flux formula",
        "\\Phi",
        base_latex=r"\Phi = BA",
        assumptions=("area is perpendicular to the field",),
    ),
    formula(
        "gauss_outside",
        "magnetism",
        "Gauss's law outside a sphere",
        "E",
        base_latex=r"E = k\frac{|Q|}{r^2}",
        assumptions=("spherical symmetry, outside the charge",),
    ),
    formula(
        "gauss_inside_shell",
        "magnetism",
        "Gauss's law inside a shell",
        "E",
        base_latex="E = 0",
        assumptions=("thin spherical shell",),
    ),
    formula(
        "gauss_inside_sphere",
        "magnetism",
        "Gauss's law inside a uniform sphere",
        "E",
        base_latex=r"E = k\frac{|Q|r}{R^3}",
        assumptions=("charge is spread uniformly through the sphere",),
    ),
    formula(
        "gauss_line",
        "magnetism",
        "Gauss's law for a line",
        "E",
        base_latex=r"E = \frac{2k|\lambda|}{r}",
        assumptions=("infinite straight line",),
    ),
    formula(
        "gauss_plane",
        "magnetism",
        "Gauss's law for a sheet",
        "E",
        base_latex=r"E = \frac{|\sigma|}{2\epsilon_0}",
        assumptions=("infinite nonconducting sheet",),
    ),
    formula(
        "faraday_emf",
        "magnetism",
        "Faraday's law",
        r"|\mathcal{E}|",
        base_latex=r"|\mathcal{E}| = N\frac{|\Delta\Phi|}{\Delta t}",
        assumptions=("magnitude; the minus sign is direction",),
    ),
    formula(
        "electric_field",
        "magnetism",
        "Electric field of a point charge",
        "E",
        base_latex="E = k_e\\frac{\\lvert Q\\rvert}{r^2}",
    ),
    formula(
        "electric_potential",
        "magnetism",
        "Electric potential of a point charge",
        "V",
        base_latex="V = k_e\\frac{Q}{r}",
    ),
    formula(
        "electric_potential_energy",
        "magnetism",
        "Electric potential-energy equation",
        "U",
        base_latex="U = k_e\\frac{q_1q_2}{r}",
    ),
    formula(
        "charged_particle_radius",
        "magnetism",
        "Charged-particle magnetic radius",
        "r",
        base_latex="r = \\frac{mv}{\\lvert q\\rvert B}",
    ),
    formula(
        "motional_emf",
        "magnetism",
        "Motional-emf equation",
        "\\mathcal{E}",
        base_latex="\\mathcal{E} = BLv",
    ),
    formula(
        "magnetic_field_wire",
        "magnetism",
        "Magnetic field of a straight wire",
        "B",
        base_latex="B = \\frac{\\mu_0I}{2\\pi r}",
    ),
)
