"""Laws that are one expression. The catalog evaluates them; they have no solver.

Each binding declines unless the question states that law's inputs and asks
for its result. A speed range, a differential equation, or a wave function
does not belong here.
"""

from __future__ import annotations

from app.services.law_binding.spec import Binding, FormulaSpec, FormulaVariant, formula, var

_G = var("g", "g", "meter / second ** 2", fallback="gravity")

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "machine_advantage_forces",
        "energy",
        "Mechanical advantage from force",
        "MA",
        base_latex=r"MA = \frac{F_{out}}{F_{in}}",
        expression="F_out/F_in",
        variables=(
            var("F_out", "F_{out}", "newton", words=("output", "out"), needs_words=True),
            var("F_in", "F_{in}", "newton", words=("input", "in"), needs_words=True),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"F_in", "F_out"}),),
            cues=("input force", "output force", "force in", "force out"),
            nonnegative=True,
        ),
    ),
    formula(
        "machine_advantage_inclined_plane",
        "energy",
        "Ideal mechanical advantage of an inclined plane",
        "MA",
        base_latex=r"MA = \frac{L}{h}",
        assumptions=("friction is neglected",),
        expression="incline_length/incline_height",
        variables=(
            var("incline_length", "L", "meter", words=("length", "long"), needs_words=True),
            var("incline_height", "h", "meter", words=("height", "rise"), needs_words=True),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"incline_height", "incline_length"}),),
            cues=("inclined plane", "ramp"),
            nonnegative=True,
        ),
    ),
    formula(
        "machine_advantage_pulley",
        "energy",
        "Ideal mechanical advantage of a pulley system",
        "MA",
        base_latex=r"MA = n",
        assumptions=("the rope and pulleys are ideal",),
        expression="supporting_strands",
        variables=(
            var(
                "supporting_strands",
                "n",
                dimensionless=True,
                words=("supporting strands", "supporting rope", "strands"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"supporting_strands"}),),
            cues=("pulley",),
            nonnegative=True,
        ),
    ),
    formula(
        "machine_advantage_wheel_axle",
        "energy",
        "Ideal mechanical advantage of a wheel and axle",
        "MA",
        base_latex=r"MA = \frac{R}{r}",
        assumptions=("friction is neglected",),
        expression="wheel_radius/axle_radius",
        variables=(
            var(
                "wheel_radius",
                "R",
                "meter",
                words=("wheel radius", "wheel"),
                needs_words=True,
            ),
            var(
                "axle_radius",
                "r",
                "meter",
                words=("axle radius", "axle"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"axle_radius", "wheel_radius"}),),
            cues=("wheel and axle",),
            nonnegative=True,
        ),
    ),
    formula(
        "machine_advantage_gears",
        "energy",
        "Ideal mechanical advantage of gears",
        "MA",
        base_latex=r"MA = \frac{N_{out}}{N_{in}}",
        assumptions=("the gears mesh without slip",),
        expression="output_teeth/input_teeth",
        variables=(
            var(
                "output_teeth",
                "N_{out}",
                dimensionless=True,
                words=("output", "driven"),
                needs_words=True,
            ),
            var(
                "input_teeth",
                "N_{in}",
                dimensionless=True,
                words=("input", "driving"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"input_teeth", "output_teeth"}),),
            cues=("gear", "gears"),
            nonnegative=True,
        ),
    ),
    formula(
        "machine_advantage_screw",
        "energy",
        "Ideal mechanical advantage of a screw",
        "MA",
        base_latex=r"MA = \frac{2\pi L}{p}",
        assumptions=("friction is neglected",),
        expression="2*pi*screw_handle_length/thread_pitch",
        variables=(
            var(
                "screw_handle_length",
                "L",
                "meter",
                words=("handle length", "handle"),
                needs_words=True,
            ),
            var(
                "thread_pitch",
                "p",
                "meter",
                words=("thread pitch", "pitch"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"screw_handle_length", "thread_pitch"}),),
            cues=("screw",),
            nonnegative=True,
        ),
    ),
    formula(
        "machine_advantage_wedge",
        "energy",
        "Ideal mechanical advantage of a wedge",
        "MA",
        base_latex=r"MA = \frac{L}{w}",
        assumptions=("friction is neglected",),
        expression="wedge_length/wedge_width",
        variables=(
            var(
                "wedge_length",
                "L",
                "meter",
                words=("wedge length", "length", "long"),
                needs_words=True,
            ),
            var(
                "wedge_width",
                "w",
                "meter",
                words=("wedge width", "width", "wide", "thickness"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("mechanical advantage",),
            result=("dimensionless",),
            inputs=(frozenset({"wedge_length", "wedge_width"}),),
            cues=("wedge",),
            nonnegative=True,
        ),
    ),
    formula(
        "physical_pendulum_period",
        "spring",
        "Physical-pendulum period",
        "T",
        base_latex=r"T = 2\pi\sqrt{\frac{I}{mgd}}",
        assumptions=("the swing is a small angle",),
        expression="2*pi*sqrt(inertia/(m*g*L))",
        variables=(
            var("inertia", "I", "kilogram * meter ** 2"),
            var("m", "m", "kilogram"),
            var("L", "d", "meter"),
            _G,
        ),
        binding=Binding(
            asks=("period",),
            result=("second",),
            inputs=(frozenset({"g", "inertia", "L", "m"}),),
            cues=("physical pendulum", "compound pendulum", "bar pendulum"),
            nonnegative=True,
        ),
    ),
    formula(
        "conical_pendulum_period",
        "spring",
        "Conical-pendulum period",
        "T",
        base_latex=r"T = 2\pi\sqrt{\frac{L\cos\theta}{g}}",
        expression="2*pi*sqrt(L*cos(angle_cone)/g)",
        variables=(
            var("L", "L", "meter"),
            var("angle_cone", r"\theta", dimensionless=True),
            _G,
        ),
        binding=Binding(
            asks=("period",),
            result=("second",),
            inputs=(frozenset({"angle_cone", "g", "L"}),),
            cues=("conical pendulum",),
            nonnegative=True,
        ),
    ),
    formula(
        "loop_entry_speed",
        "circular",
        "Speed to complete a vertical loop",
        "v",
        base_latex=r"v = \sqrt{5gr}",
        assumptions=("the track is entered at the bottom", "the car just keeps contact at the top"),
        expression="sqrt(5*g*r)",
        variables=(var("r", "r", "meter"), _G),
        binding=Binding(
            asks=("speed", "minimum speed", "velocity"),
            result=("meter / second",),
            inputs=(frozenset({"g", "r"}),),
            cues=("just completes", "just complete"),
            excludes=("at the top",),
            nonnegative=True,
        ),
    ),
    formula(
        "sound_level",
        "waves",
        "Sound-intensity level",
        r"\beta",
        base_latex=r"\beta = 10\log_{10}\frac{I}{I_0}",
        expression="10*log(intensity/i_ref)/log(10)",
        variables=(
            var(
                "intensity",
                "I",
                "watt / meter ** 2",
                words=("intensity",),
                needs_words=True,
            ),
            var(
                "i_ref",
                "I_0",
                "watt / meter ** 2",
                words=("reference",),
                implied=(
                    ("threshold of hearing", 1.0e-12),
                    ("hearing threshold", 1.0e-12),
                    ("decibel", 1.0e-12),
                    ("decibels", 1.0e-12),
                ),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("sound level", "intensity level"),
            result=("dimensionless",),
            inputs=(frozenset({"i_ref", "intensity"}),),
            cues=("decibel", "sound level"),
            shown_unit="dB",
        ),
    ),
    formula(
        "shear_modulus",
        "materials",
        "Shear-modulus formula",
        "G",
        base_latex=r"G = \frac{\tau}{\gamma}",
        expression="shear_stress/shear_strain",
        variables=(
            var("shear_stress", r"\tau", "pascal", words=("shear stress",), needs_words=True),
            var(
                "shear_strain",
                r"\gamma",
                dimensionless=True,
                words=("shear strain",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("shear modulus",),
            result=("pascal",),
            inputs=(frozenset({"shear_strain", "shear_stress"}),),
            cues=("shear modulus",),
            nonnegative=True,
        ),
    ),
    formula(
        "bulk_modulus",
        "materials",
        "Bulk-modulus formula",
        "B",
        base_latex=r"B = \frac{\Delta P}{\Delta V/V}",
        assumptions=("the volume change is a decrease",),
        expression="delta_pres*volume/dV",
        variants=(
            FormulaVariant(
                latex=r"B = \frac{\Delta P}{\Delta V/V}",
                present=frozenset({"volume_strain"}),
                absent=frozenset({"volume", "dV"}),
                expression="delta_pres/volume_strain",
            ),
        ),
        variables=(
            var("delta_pres", r"\Delta P", "pascal"),
            var("volume", "V", "meter ** 3", words=("original",), needs_words=True),
            var("dV", r"\Delta V", "meter ** 3", words=("change", "decrease"), needs_words=True),
            var(
                "volume_strain",
                r"\Delta V/V",
                dimensionless=True,
                words=("volume strain", "volumetric strain"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("bulk modulus",),
            result=("pascal",),
            inputs=(
                frozenset({"dV", "delta_pres", "volume"}),
                frozenset({"delta_pres", "volume_strain"}),
            ),
            cues=("bulk modulus",),
            nonnegative=True,
        ),
    ),
    formula(
        "poisson_ratio",
        "materials",
        "Poisson's ratio",
        r"\nu",
        base_latex=r"\nu = \frac{\varepsilon_{lat}}{\varepsilon_{axial}}",
        expression="lateral_strain/axial_strain",
        variables=(
            var(
                "lateral_strain",
                r"\varepsilon_{lat}",
                dimensionless=True,
                words=("lateral",),
                needs_words=True,
            ),
            var(
                "axial_strain",
                r"\varepsilon_{axial}",
                dimensionless=True,
                words=("axial", "longitudinal"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("poisson's ratio", "poissons ratio", "poisson ratio"),
            result=("dimensionless",),
            inputs=(frozenset({"axial_strain", "lateral_strain"}),),
            cues=("poisson",),
            nonnegative=True,
            at_most=0.5,
        ),
    ),
    formula(
        "gear_output_speed",
        "rotation",
        "Gear train",
        r"\omega_2",
        base_latex=r"\omega_2 = \omega_1\frac{N_1}{N_2}",
        assumptions=("the teeth mesh without slip",),
        expression="omega*teeth_driving/teeth_driven",
        variables=(
            var("omega", r"\omega_1", "radian / second"),
            var(
                "teeth_driving",
                "N_1",
                dimensionless=True,
                words=("driving", "input"),
                needs_words=True,
            ),
            var(
                "teeth_driven",
                "N_2",
                dimensionless=True,
                words=("driven", "output"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("angular speed", "angular velocity"),
            result=("radian / second",),
            inputs=(frozenset({"omega", "teeth_driven", "teeth_driving"}),),
            cues=("gear",),
            nonnegative=True,
        ),
    ),
    formula(
        "gear_ratio",
        "rotation",
        "Gear train",
        r"\frac{\omega_2}{\omega_1}",
        base_latex=r"\frac{\omega_2}{\omega_1} = \frac{N_1}{N_2}",
        assumptions=("the teeth mesh without slip",),
        expression="teeth_driving/teeth_driven",
        variables=(
            var(
                "teeth_driving",
                "N_1",
                dimensionless=True,
                words=("driving", "input"),
                needs_words=True,
            ),
            var(
                "teeth_driven",
                "N_2",
                dimensionless=True,
                words=("driven", "output"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("gear ratio",),
            result=("dimensionless",),
            inputs=(frozenset({"teeth_driven", "teeth_driving"}),),
            cues=("gear",),
            nonnegative=True,
        ),
    ),
    formula(
        "newton_cooling",
        "thermal",
        "Newton's law of cooling",
        "T",
        base_latex=r"T = T_e + (T_0 - T_e)e^{-t/\tau}",
        expression="temp_env + (temp - temp_env)*exp(-t/cool_time)",
        variables=(
            var(
                "temp",
                "T_0",
                "kelvin",
                words=("starts", "initial", "object"),
                needs_words=True,
            ),
            var(
                "temp_env",
                "T_e",
                "kelvin",
                words=("room", "ambient", "surrounding", "environment", "outside"),
                needs_words=True,
            ),
            var("t", "t", "second", words=("after", "later"), needs_words=True),
            var("cool_time", r"\tau", "second", words=("time constant",), needs_words=True),
        ),
        binding=Binding(
            asks=("temperature",),
            result=("kelvin",),
            inputs=(frozenset({"cool_time", "t", "temp", "temp_env"}),),
            cues=("law of cooling",),
            nonnegative=True,
        ),
    ),
    formula(
        "radiation_pressure_absorbed",
        "waves",
        "Radiation pressure",
        "P",
        base_latex=r"P = \frac{I}{c}",
        assumptions=("the surface absorbs the wave",),
        expression="intensity/c_light",
        variables=(var("intensity", "I", "watt / meter ** 2"),),
        binding=Binding(
            asks=("radiation pressure", "pressure"),
            result=("pascal",),
            inputs=(frozenset({"intensity"}),),
            cues=("radiation pressure",),
            excludes=("reflected", "reflection"),
            nonnegative=True,
        ),
    ),
    formula(
        "radiation_pressure_reflected",
        "waves",
        "Radiation pressure",
        "P",
        base_latex=r"P = \frac{2I}{c}",
        assumptions=("the surface reflects the wave",),
        expression="2*intensity/c_light",
        variables=(var("intensity", "I", "watt / meter ** 2"),),
        binding=Binding(
            asks=("radiation pressure", "pressure"),
            result=("pascal",),
            inputs=(frozenset({"intensity"}),),
            cues=("radiation pressure",),
            excludes=("absorbed", "absorption"),
            nonnegative=True,
        ),
    ),
    formula(
        "otto_efficiency",
        "thermal",
        "Otto-cycle efficiency",
        r"\eta",
        base_latex=r"\eta = 1 - r^{1-\gamma}",
        expression="1 - compression_ratio**(1 - gamma)",
        variables=(
            var(
                "compression_ratio",
                "r",
                dimensionless=True,
                words=("compression ratio", "compression"),
                needs_words=True,
            ),
            var("gamma", r"\gamma", dimensionless=True, words=("gamma",), needs_words=True),
        ),
        binding=Binding(
            asks=("efficiency",),
            result=("dimensionless",),
            inputs=(frozenset({"compression_ratio", "gamma"}),),
            cues=("otto",),
            excludes=("diesel", "carnot"),
            nonnegative=True,
            at_most=1.0,
        ),
    ),
)
