"""Verified optics operations."""

from __future__ import annotations

from app.modules.physics.catalog.spec import Binding, FormulaSpec, FormulaVariant, formula, var

SPECS: tuple[FormulaSpec, ...] = (
    formula(
        "image_distance",
        "optics",
        "Thin-lens and mirror equation",
        "v",
        base_latex="\\frac{1}{f} = \\frac{1}{u} + \\frac{1}{v}",
        variables=(
            var("d_obj", "u", "meter"),
            var("focal", "f", "meter"),
        ),
    ),
    formula(
        "magnification",
        "optics",
        "Magnification formula",
        "m",
        variables=(
            var("h_img", "h_i", "meter"),
            var("h_obj", "h_o", "meter"),
        ),
    ),
    formula(
        "refractive_index",
        "optics",
        "Snell's law",
        "n",
        variables=(
            var("angle", r"\theta", dimensionless=True),
            var("angle2", r"\theta_2", dimensionless=True),
            var("v_wave", "v", "meter / second"),
        ),
    ),
    formula(
        "critical_angle",
        "optics",
        "Critical-angle equation",
        "\\theta_c",
        variables=(var("n1", "n_1", dimensionless=True),),
    ),
    formula(
        "lens_power",
        "optics",
        "Lens-power formula",
        "P",
        base_latex="P = \\frac{1}{f}",
        variables=(var("focal", "f", "meter"),),
        binding=Binding(
            asks=("power",),
            result=("1 / meter",),
            inputs=(frozenset({"focal"}),),
            cues=("lens",),
        ),
    ),
    formula(
        "double_slit_fringe_spacing",
        "optics",
        "Double-slit interference",
        "\\Delta y",
        base_latex="\\Delta y = \\frac{\\lambda L}{d}",
        variables=(
            var("L", "L", "meter"),
            var("d", "d", "meter"),
            var("wavelength", r"\lambda", "meter"),
        ),
    ),
    formula(
        "diffraction_central_width",
        "optics",
        "Single-slit diffraction",
        "w",
        base_latex="w = \\frac{2\\lambda L}{a}",
        variables=(
            var("L", "L", "meter"),
            var("d", "a", "meter"),
            var("wavelength", r"\lambda", "meter"),
        ),
    ),
    formula(
        "malus_intensity",
        "optics",
        "Malus's law",
        "I",
        base_latex="I = I_0\\cos^2\\theta",
        variables=(
            var("angle", r"\theta", dimensionless=True),
            var("intensity0", "I_0", "watt / meter ** 2"),
        ),
    ),
    formula(
        "brewster_angle",
        "optics",
        "Brewster's law",
        "\\theta_B",
        base_latex="\\tan\\theta_B = \\frac{n_2}{n_1}",
        variables=(
            var("n1", "n_1", dimensionless=True),
            var("n2", "n_2", dimensionless=True),
        ),
    ),
    formula(
        "snell_refraction_angle",
        "optics",
        "Snell's law",
        r"\theta_2",
        base_latex=r"n_1 \sin\theta_1 = n_2 \sin\theta_2",
        expression="asin(n1*sin(angle)/n2)*180/pi",
        variables=(
            var("angle", r"\theta_1", dimensionless=True),
            var(
                "n1",
                "n_1",
                dimensionless=True,
                words=("from", "leaves", "travelling in", "traveling in"),
                implied=(("from air", 1.0), ("in air", 1.0), ("from a vacuum", 1.0)),
            ),
            var("n2", "n_2", dimensionless=True, words=("into", "enters", "entering")),
        ),
        binding=Binding(
            asks=("angle of refraction", "refraction angle", "refracted angle"),
            result=("degree",),
            inputs=(frozenset({"angle", "n1", "n2"}),),
            nonnegative=True,
        ),
    ),
    formula(
        "grating_angle",
        "optics",
        "Diffraction-grating equation",
        r"\theta",
        base_latex=r"d\sin\theta = n\lambda",
        expression="asin(order*wavelength*line_density)*180/pi",
        variants=(
            FormulaVariant(
                present=frozenset({"d"}),
                expression="asin(order*wavelength/d)*180/pi",
            ),
        ),
        variables=(
            var("d", "d", "meter", words=("spacing", "separation", "lines are")),
            var("line_density", "N", "1 / meter"),
            var(
                "order",
                "n",
                dimensionless=True,
                words=("order",),
                implied=(
                    ("first order", 1.0),
                    ("first-order", 1.0),
                    ("second order", 2.0),
                    ("second-order", 2.0),
                    ("third order", 3.0),
                    ("third-order", 3.0),
                ),
            ),
            var("wavelength", r"\lambda", "meter", words=("wavelength",)),
        ),
        binding=Binding(
            asks=("angle",),
            result=("degree",),
            inputs=(
                frozenset({"line_density", "order", "wavelength"}),
                frozenset({"d", "order", "wavelength"}),
            ),
            cues=("grating",),
            nonnegative=True,
        ),
    ),
    formula(
        "mirror_focal_length",
        "optics",
        "Spherical-mirror focal length",
        "f",
        base_latex=r"f = \frac{R}{2}",
        assumptions=("a spherical mirror, rays near the axis",),
        expression="radius_curvature/2",
        variables=(var("radius_curvature", "R", "meter"),),
        binding=Binding(
            asks=("focal length",),
            result=("meter",),
            inputs=(frozenset({"radius_curvature"}),),
            cues=("mirror",),
            # A convex mirror's focal length is negative; its sign is the
            # convention the question has not stated.
            excludes=("convex", "diverging"),
            nonnegative=True,
        ),
    ),
    formula(
        "magnification_distances",
        "optics",
        "Magnification equation",
        "m",
        base_latex=r"m = -\frac{v}{u}",
        assumptions=("real distances are positive; a negative m is an inverted image",),
        expression="-d_img/d_obj",
        variables=(
            var("d_img", "v", "meter", words=("image",)),
            var("d_obj", "u", "meter", words=("object",)),
        ),
        binding=Binding(
            asks=("magnification",),
            result=("dimensionless",),
            inputs=(frozenset({"d_img", "d_obj"}),),
            # A virtual image's distance carries the other sign.
            excludes=("virtual",),
        ),
    ),
    formula(
        "bragg_wavelength",
        "optics",
        "Bragg's law",
        r"\lambda",
        base_latex=r"n\lambda = 2d\sin\theta",
        expression="2*d*sin(angle_bragg)/order",
        variables=(
            var("angle_bragg", r"\theta", dimensionless=True),
            var("d", "d", "meter", words=("spacing", "separation", "apart", "planes")),
            var(
                "order",
                "n",
                dimensionless=True,
                words=("order",),
                needs_words=True,
                implied=(
                    ("first order", 1.0),
                    ("first-order", 1.0),
                    ("second order", 2.0),
                    ("second-order", 2.0),
                    ("third order", 3.0),
                    ("third-order", 3.0),
                ),
            ),
        ),
        binding=Binding(
            asks=("wavelength",),
            result=("meter",),
            inputs=(frozenset({"angle_bragg", "d", "order"}),),
            cues=("bragg",),
            nonnegative=True,
        ),
    ),
    formula(
        "bragg_spacing",
        "optics",
        "Bragg's law",
        "d",
        base_latex=r"n\lambda = 2d\sin\theta",
        expression="order*wavelength/(2*sin(angle_bragg))",
        variables=(
            var("angle_bragg", r"\theta", dimensionless=True),
            var(
                "order",
                "n",
                dimensionless=True,
                words=("order",),
                needs_words=True,
                implied=(
                    ("first order", 1.0),
                    ("first-order", 1.0),
                    ("second order", 2.0),
                    ("second-order", 2.0),
                    ("third order", 3.0),
                    ("third-order", 3.0),
                ),
            ),
            var("wavelength", r"\lambda", "meter", words=("wavelength",), needs_words=True),
        ),
        binding=Binding(
            asks=("spacing", "separation", "plane spacing", "interplanar spacing"),
            result=("meter",),
            inputs=(frozenset({"angle_bragg", "order", "wavelength"}),),
            cues=("bragg",),
            nonnegative=True,
        ),
    ),
)
