"""One-number laws a question can state in full.

Each one answers only when that formula's inputs are written down. A
differential equation, an operator identity, or a field theory is not here.
"""

from __future__ import annotations

from app.services.law_binding.spec import Binding, FormulaSpec, VariableSpec, formula, var

_MOLECULES = ("molecules", "particles")
_N = var(
    "molecule_count",
    "N",
    dimensionless=True,
    words=("molecules", "particles", "molecule"),
    needs_words=True,
)
_TEMP = var("temp", "T", "kelvin")
_VOLUME = var("volume", "V", "meter ** 3")
_PRESSURE = var("pres", "P", "pascal")
_CHARGE = var("Q", "Q", "coulomb")
_VOLTAGE = var("V", "V", "volt")
_CAPACITANCE = var("capacitance", "C", "farad")
_POWER = var("power", "P", "watt")
_AREA = var("area", "A", "meter ** 2")
_DENSITY = var("rho", r"\rho", "kilogram / meter ** 3", words=("density",), needs_words=True)
_FIELD_E = var("e_field", "E", "volt / meter")
_FIELD_B = var("b_field", "B", "tesla")
_LEVEL = var(
    "quantum_n",
    "n",
    dimensionless=True,
    words=("n =", "principal"),
    needs_words=True,
)
_BOOST = "sqrt(1 - v**2/c_light**2)"


def _molecule_gas(
    operation: str,
    symbol: str,
    expression: str,
    asks: tuple[str, ...],
    result: str,
    variables: tuple[VariableSpec, ...],
    inputs: frozenset[str],
) -> FormulaSpec:
    return formula(
        operation,
        "thermal",
        "Ideal-gas law",
        symbol,
        base_latex=r"PV = N k_B T",
        assumptions=("an ideal gas",),
        expression=expression,
        variables=variables,
        binding=Binding(
            asks=asks,
            result=(result,),
            inputs=(inputs,),
            cues=_MOLECULES,
            excludes=("particle in a box", "infinite box"),
            nonnegative=True,
        ),
    )


def _lorentz(
    operation: str,
    symbol: str,
    base: str,
    expression: str,
    asks: tuple[str, ...],
) -> FormulaSpec:
    return formula(
        operation,
        "modern",
        "Lorentz transformation",
        symbol,
        base_latex=base,
        assumptions=("a boost along one axis",),
        expression=expression,
        variables=(
            var("event_x", "x", "meter", words=("coordinate", "position"), needs_words=True),
            var("t", "t", "second", words=("time",), needs_words=True),
            var("v", "v", "meter / second"),
        ),
        binding=Binding(
            asks=asks,
            result=("meter" if operation.endswith("coordinate") else "second",),
            inputs=(frozenset({"event_x", "t", "v"}),),
            cues=("lorentz transformation",),
            nonnegative=False,
        ),
    )


SPECS: tuple[FormulaSpec, ...] = (
    _molecule_gas(
        "molecule_gas_pressure",
        "P",
        "molecule_count*k_B*temp/volume",
        ("pressure",),
        "pascal",
        (_N, _TEMP, _VOLUME),
        frozenset({"molecule_count", "temp", "volume"}),
    ),
    _molecule_gas(
        "molecule_gas_volume",
        "V",
        "molecule_count*k_B*temp/pres",
        ("volume",),
        "meter ** 3",
        (_N, _TEMP, _PRESSURE),
        frozenset({"molecule_count", "pres", "temp"}),
    ),
    _molecule_gas(
        "molecule_gas_count",
        "N",
        "pres*volume/(k_B*temp)",
        ("number of molecules", "number of particles"),
        "dimensionless",
        (_PRESSURE, _VOLUME, _TEMP),
        frozenset({"pres", "temp", "volume"}),
    ),
    _molecule_gas(
        "molecule_gas_temperature",
        "T",
        "pres*volume/(molecule_count*k_B)",
        ("temperature",),
        "kelvin",
        (_N, _PRESSURE, _VOLUME),
        frozenset({"molecule_count", "pres", "volume"}),
    ),
    formula(
        "ideal_gas_density",
        "thermal",
        "Ideal-gas density",
        r"\rho",
        base_latex=r"\rho = \frac{PM}{RT}",
        assumptions=("an ideal gas",),
        expression="pres*molar_mass/(R_gas*temp)",
        variables=(
            _PRESSURE,
            var("molar_mass", "M", "kilogram / mole", words=("molar",), needs_words=True),
            _TEMP,
        ),
        binding=Binding(
            asks=("density",),
            result=("kilogram / meter ** 3",),
            inputs=(frozenset({"molar_mass", "pres", "temp"}),),
            cues=("molar mass",),
            nonnegative=True,
        ),
    ),
    formula(
        "capacitor_energy_charge",
        "circuit",
        "Capacitor energy",
        "U",
        base_latex=r"U = \frac{Q^2}{2C}",
        expression="Q**2/(2*capacitance)",
        variables=(_CHARGE, _CAPACITANCE),
        binding=Binding(
            asks=("stored energy", "energy"),
            result=("joule",),
            inputs=(frozenset({"Q", "capacitance"}),),
            cues=("capacitor",),
            excludes=("voltage", "volt"),
            nonnegative=True,
        ),
    ),
    formula(
        "capacitor_energy_charge_voltage",
        "circuit",
        "Capacitor energy",
        "U",
        base_latex=r"U = \frac{1}{2}QV",
        expression="Q*V/2",
        variables=(_CHARGE, _VOLTAGE),
        binding=Binding(
            asks=("stored energy", "energy"),
            result=("joule",),
            inputs=(frozenset({"Q", "V"}),),
            cues=("capacitor",),
            excludes=("capacitance", "farad"),
            nonnegative=True,
        ),
    ),
    formula(
        "plane_wave_intensity",
        "waves",
        "Plane-wave intensity",
        "I",
        base_latex=r"I = \frac{P}{A}",
        assumptions=("the power is spread uniformly over the area",),
        expression="power/area",
        variables=(_POWER, _AREA),
        binding=Binding(
            asks=("intensity",),
            result=("watt / meter ** 2",),
            inputs=(frozenset({"area", "power"}),),
            cues=("plane wave",),
            excludes=("spherical", "radius", "electromagnetic"),
            nonnegative=True,
        ),
    ),
    formula(
        "em_wave_electric_field",
        "waves",
        "Electromagnetic wave",
        "E",
        base_latex=r"E = cB",
        assumptions=("a plane wave in vacuum",),
        expression="c_light*b_field",
        variables=(_FIELD_B,),
        binding=Binding(
            asks=("electric field",),
            result=("volt / meter",),
            inputs=(frozenset({"b_field"}),),
            cues=("electromagnetic wave",),
            nonnegative=True,
        ),
    ),
    formula(
        "em_wave_magnetic_field",
        "waves",
        "Electromagnetic wave",
        "B",
        base_latex=r"B = \frac{E}{c}",
        assumptions=("a plane wave in vacuum",),
        expression="e_field/c_light",
        variables=(_FIELD_E,),
        binding=Binding(
            asks=("magnetic field",),
            result=("tesla",),
            inputs=(frozenset({"e_field"}),),
            cues=("electromagnetic wave",),
            nonnegative=True,
        ),
    ),
    formula(
        "poynting_magnitude",
        "waves",
        "Poynting vector",
        "S",
        base_latex=r"S = \frac{EB}{\mu_0}",
        assumptions=("perpendicular fields",),
        expression="e_field*b_field/mu_0",
        variables=(_FIELD_E, _FIELD_B),
        binding=Binding(
            asks=("poynting magnitude",),
            result=("watt / meter ** 2",),
            inputs=(frozenset({"b_field", "e_field"}),),
            cues=("poynting",),
            nonnegative=True,
        ),
    ),
    formula(
        "rod_wave_speed",
        "waves",
        "Longitudinal speed in a thin rod",
        "v",
        base_latex=r"v = \sqrt{\frac{Y}{\rho}}",
        assumptions=("a thin rod",),
        expression="sqrt(young_modulus/rho)",
        variables=(
            var("young_modulus", "Y", "pascal", words=("young",), needs_words=True),
            _DENSITY,
        ),
        binding=Binding(
            asks=("wave speed", "speed"),
            result=("meter / second",),
            inputs=(frozenset({"rho", "young_modulus"}),),
            cues=("young",),
            nonnegative=True,
        ),
    ),
    formula(
        "shear_wave_speed",
        "waves",
        "Shear-wave speed",
        "v",
        base_latex=r"v = \sqrt{\frac{G}{\rho}}",
        assumptions=("a shear wave in bulk material",),
        expression="sqrt(shear_wave_modulus/rho)",
        variables=(
            var(
                "shear_wave_modulus",
                "G",
                "pascal",
                words=("shear modulus",),
                needs_words=True,
            ),
            _DENSITY,
        ),
        binding=Binding(
            asks=("shear-wave speed", "wave speed"),
            result=("meter / second",),
            inputs=(frozenset({"rho", "shear_wave_modulus"}),),
            cues=("shear-wave", "shear wave"),
            nonnegative=True,
        ),
    ),
    _lorentz(
        "lorentz_coordinate",
        "x'",
        r"x' = \gamma(x - vt)",
        f"(event_x - v*t)/{_BOOST}",
        ("transformed coordinate",),
    ),
    _lorentz(
        "lorentz_time",
        "t'",
        r"t' = \gamma(t - vx/c^2)",
        f"(t - v*event_x/c_light**2)/{_BOOST}",
        ("transformed time",),
    ),
    formula(
        "bohr_angular_momentum",
        "modern",
        "Bohr angular momentum",
        "L",
        base_latex=r"L = n\hbar",
        assumptions=("the Bohr model",),
        expression="quantum_n*hbar",
        variables=(
            var(
                "quantum_n",
                "n",
                dimensionless=True,
                words=("n =", "level"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("angular momentum",),
            result=("kilogram * meter ** 2 / second",),
            inputs=(frozenset({"quantum_n"}),),
            cues=("bohr",),
            excludes=("squared", "z component"),
            nonnegative=True,
        ),
    ),
    formula(
        "orbital_angular_momentum_squared",
        "modern",
        "Orbital angular-momentum eigenvalue",
        "L^2",
        base_latex=r"L^2 = \hbar^2 \ell(\ell+1)",
        assumptions=("one orbital angular-momentum eigenvalue",),
        expression="hbar**2*orbital_l*(orbital_l+1)",
        variables=(
            var(
                "orbital_l",
                r"\ell",
                dimensionless=True,
                words=("orbital", "azimuthal"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("angular momentum squared",),
            result=("kilogram ** 2 * meter ** 4 / second ** 2",),
            inputs=(frozenset({"orbital_l"}),),
            cues=("orbital quantum", "azimuthal"),
            nonnegative=True,
        ),
    ),
    formula(
        "angular_momentum_z",
        "modern",
        "Angular-momentum z component",
        "L_z",
        base_latex=r"L_z = m\hbar",
        assumptions=("the z component",),
        expression="magnetic_quantum*hbar",
        variables=(
            var(
                "magnetic_quantum",
                "m",
                dimensionless=True,
                words=("magnetic quantum",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("z component of angular momentum",),
            result=("kilogram * meter ** 2 / second",),
            inputs=(frozenset({"magnetic_quantum"}),),
            cues=("magnetic quantum",),
            excludes=("zeeman",),
            nonnegative=False,
        ),
    ),
    formula(
        "hydrogenlike_radius",
        "modern",
        "Hydrogen-like Bohr radius",
        "r_n",
        base_latex=r"r_n = \frac{n^2 a_0}{Z}",
        assumptions=("a hydrogen-like atom, infinite nuclear mass",),
        expression="quantum_n**2*a_0/atomic_number",
        variables=(
            _LEVEL,
            var(
                "atomic_number",
                "Z",
                dimensionless=True,
                words=("atomic number", "z ="),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("orbit radius", "orbital radius", "radius"),
            result=("meter",),
            inputs=(frozenset({"atomic_number", "quantum_n"}),),
            cues=("hydrogen-like", "hydrogenic", "atomic number"),
            nonnegative=True,
        ),
    ),
    formula(
        "zeeman_shift",
        "modern",
        "Normal Zeeman shift",
        r"\Delta E",
        base_latex=r"\Delta E = \frac{e\hbar B m_l}{2 m_e}",
        assumptions=("the normal Zeeman effect",),
        expression="e_charge*hbar*b_field*magnetic_quantum/(2*m_e)",
        variables=(
            _FIELD_B,
            var(
                "magnetic_quantum",
                "m_l",
                dimensionless=True,
                words=("magnetic quantum",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("zeeman shift",),
            result=("joule",),
            inputs=(frozenset({"b_field", "magnetic_quantum"}),),
            cues=("zeeman",),
            nonnegative=False,
        ),
    ),
    formula(
        "pair_production_threshold",
        "modern",
        "Pair-production threshold",
        "E",
        base_latex=r"E = 2mc^2",
        assumptions=("a particle and its antiparticle created at rest",),
        expression="2*m*c_light**2",
        variables=(var("m", "m", "kilogram", fallback="particle_mass"),),
        binding=Binding(
            asks=("threshold energy", "pair-production threshold"),
            result=("joule",),
            inputs=(frozenset({"m"}),),
            cues=("pair production", "pair-production"),
            nonnegative=True,
        ),
    ),
    formula(
        "numerical_aperture",
        "optics",
        "Numerical aperture",
        "NA",
        base_latex=r"\mathrm{NA} = n\sin\theta",
        assumptions=("the half-angle of the acceptance cone",),
        expression="n_index*sin(angle_aperture)",
        variables=(
            var("n_index", "n", dimensionless=True, words=("index",), needs_words=True),
            var("angle_aperture", r"\theta", dimensionless=True),
        ),
        binding=Binding(
            asks=("numerical aperture",),
            result=("dimensionless",),
            inputs=(frozenset({"angle_aperture", "n_index"}),),
            cues=("numerical aperture",),
            nonnegative=True,
        ),
    ),
    formula(
        "grating_resolving_power",
        "optics",
        "Grating resolving power",
        "R",
        base_latex=r"R = mN",
        assumptions=("a diffraction grating",),
        expression="order*n_lines",
        variables=(
            var(
                "order",
                "m",
                dimensionless=True,
                words=("order",),
                needs_words=True,
                # "second order" states m the same way the grating angle already reads it.
                implied=(
                    ("first order", 1.0),
                    ("first-order", 1.0),
                    ("second order", 2.0),
                    ("second-order", 2.0),
                    ("third order", 3.0),
                    ("third-order", 3.0),
                ),
            ),
            var(
                "n_lines",
                "N",
                dimensionless=True,
                words=("lines", "slits", "rulings"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("resolving power",),
            result=("dimensionless",),
            inputs=(frozenset({"n_lines", "order"}),),
            cues=("resolving power",),
            nonnegative=True,
        ),
    ),
    formula(
        "bcs_gap",
        "modern",
        "BCS gap",
        r"\Delta",
        base_latex=r"\Delta = 1.764\,k_B T_c",
        assumptions=("the weak-coupling approximation",),
        expression="1.764*k_B*temp",
        variables=(var("temp", "T_c", "kelvin", words=("critical",), needs_words=True),),
        binding=Binding(
            asks=("energy gap", "gap"),
            result=("joule",),
            inputs=(frozenset({"temp"}),),
            cues=("bcs",),
            nonnegative=True,
        ),
    ),
    formula(
        "hawking_power",
        "modern",
        "Hawking power",
        "P",
        base_latex=r"P = \frac{\hbar c^6}{15360\pi G^2 M^2}",
        assumptions=("a Schwarzschild black hole",),
        expression="hbar*c_light**6/(15360*pi*G_grav**2*M**2)",
        variables=(var("M", "M", "kilogram", fallback="body_mass"),),
        binding=Binding(
            asks=("hawking power", "hawking luminosity"),
            result=("watt",),
            inputs=(frozenset({"M"}),),
            cues=("hawking power", "hawking luminosity"),
            nonnegative=True,
        ),
    ),
    formula(
        "friedmann_hubble",
        "gravitation",
        "Friedmann equation",
        "H",
        base_latex=r"H = \sqrt{\frac{8\pi G\rho}{3} - \frac{kc^2}{a^2} + \frac{\Lambda c^2}{3}}",
        assumptions=("the Hubble parameter from the stated density, curvature, scale, and Lambda",),
        expression=(
            "sqrt(8*pi*G_grav*rho/3 - curvature*c_light**2/scale_factor**2"
            " + lambda_cosmo*c_light**2/3)"
        ),
        variables=(
            _DENSITY,
            var(
                "curvature",
                "k",
                dimensionless=True,
                words=("curvature",),
                needs_words=True,
            ),
            var("scale_factor", "a", "meter", words=("scale",), needs_words=True),
            var(
                "lambda_cosmo",
                r"\Lambda",
                "1 / meter ** 2",
                words=("cosmological",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("hubble parameter",),
            result=("1 / second",),
            inputs=(frozenset({"curvature", "lambda_cosmo", "rho", "scale_factor"}),),
            cues=("friedmann",),
            nonnegative=True,
        ),
    ),
    formula(
        "virial_kinetic_energy",
        "gravitation",
        "Virial theorem",
        "K",
        base_latex=r"2K + U = 0",
        assumptions=("a self-gravitating system in equilibrium",),
        expression="-potential_energy/2",
        variables=(var("potential_energy", "U", "joule", words=("potential",), needs_words=True),),
        binding=Binding(
            asks=("kinetic energy",),
            result=("joule",),
            inputs=(frozenset({"potential_energy"}),),
            cues=("virial",),
            nonnegative=False,
        ),
    ),
    formula(
        "virial_potential_energy",
        "gravitation",
        "Virial theorem",
        "U",
        base_latex=r"2K + U = 0",
        assumptions=("a self-gravitating system in equilibrium",),
        expression="-2*kinetic_energy",
        variables=(var("kinetic_energy", "K", "joule", words=("kinetic",), needs_words=True),),
        binding=Binding(
            asks=("potential energy",),
            result=("joule",),
            inputs=(frozenset({"kinetic_energy"}),),
            cues=("virial",),
            nonnegative=False,
        ),
    ),
    formula(
        "higgs_mass",
        "modern",
        "Higgs mass",
        "m_H",
        base_latex=r"m_H = \frac{v\sqrt{2\lambda}}{c^2}",
        assumptions=("the Mexican-hat potential, mass in kilograms",),
        expression="vacuum_expectation*sqrt(2*self_coupling)/c_light**2",
        variables=(
            var(
                "vacuum_expectation",
                "v",
                "joule",
                words=("vacuum", "expectation"),
                needs_words=True,
            ),
            var(
                "self_coupling",
                r"\lambda",
                dimensionless=True,
                words=("coupling",),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("higgs mass",),
            result=("kilogram",),
            inputs=(frozenset({"self_coupling", "vacuum_expectation"}),),
            cues=("higgs",),
            nonnegative=True,
        ),
    ),
    formula(
        "strong_coupling",
        "modern",
        "One-loop strong coupling",
        r"\alpha_s",
        base_latex=r"\alpha_s = \frac{12\pi}{(33-2n_f)\ln(Q^2/\Lambda^2)}",
        assumptions=("one-loop running with the stated flavor count",),
        expression="12*pi/((33-2*n_flavors)*log((momentum_scale/lambda_qcd)**2))",
        variables=(
            var(
                "momentum_scale",
                "Q",
                "joule",
                words=("momentum",),
                needs_words=True,
            ),
            var(
                "lambda_qcd",
                r"\Lambda",
                "joule",
                words=("lambda",),
                needs_words=True,
            ),
            var(
                "n_flavors",
                "n_f",
                dimensionless=True,
                words=("flavor", "flavour"),
                needs_words=True,
            ),
        ),
        binding=Binding(
            asks=("strong coupling",),
            result=("dimensionless",),
            inputs=(frozenset({"lambda_qcd", "momentum_scale", "n_flavors"}),),
            cues=("qcd",),
            nonnegative=True,
        ),
    ),
)
