#!/usr/bin/env node
/**
 * Builds ui/icons/glyphs.generated.ts from ui/icons/manifest.json and the
 * Lucide drawings in the lucide-static dev dependency (ISC License).
 *
 *   pnpm icons
 *
 * Only the icons named in the manifest ship in the app bundle. The script
 * fails when a manifest entry points at a Lucide id that does not exist, so a
 * Lucide rename surfaces here instead of as a blank icon on a device.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const lucideDir = join(root, "node_modules", "lucide-static");
const iconNodes = JSON.parse(readFileSync(join(lucideDir, "icon-nodes.json"), "utf8"));
const { version } = JSON.parse(readFileSync(join(lucideDir, "package.json"), "utf8"));
const { icons } = JSON.parse(readFileSync(join(root, "ui", "icons", "manifest.json"), "utf8"));

const ALLOWED_TAGS = new Set(["path", "circle", "line", "rect", "polyline", "polygon", "ellipse"]);
const missing = [];
const entries = [];

for (const name of Object.keys(icons).sort()) {
  const lucideId = icons[name];
  const nodes = iconNodes[lucideId];
  if (!nodes) {
    missing.push(`${name} -> ${lucideId}`);
    continue;
  }
  for (const [tag] of nodes) {
    if (!ALLOWED_TAGS.has(tag)) {
      missing.push(`${name} -> ${lucideId} uses unsupported <${tag}>`);
    }
  }
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(nodes)},`);
}

if (missing.length > 0) {
  console.error("Icon manifest entries without a usable Lucide drawing:");
  for (const line of missing) console.error(`  ${line}`);
  process.exit(1);
}

const out = `// Generated by scripts/generate-icons.mjs from ui/icons/manifest.json.
// Do not edit by hand: change the manifest and run \`pnpm icons\`.
// Drawings: Lucide v${version} (https://lucide.dev), ISC License,
// Copyright (c) Lucide Contributors.

export type GlyphNode = readonly [
  "path" | "circle" | "line" | "rect" | "polyline" | "polygon" | "ellipse",
  Readonly<Record<string, string>>,
];

export const GLYPHS = {
${entries.join("\n")}
} as const satisfies Record<string, readonly GlyphNode[]>;

export type LucideIconName = keyof typeof GLYPHS;
`;

writeFileSync(join(root, "ui", "icons", "glyphs.generated.ts"), out);
console.log(`Wrote ${entries.length} icons (Lucide ${version}).`);
