#!/usr/bin/env node
/**
 * Vendor CDN-served JS/CSS/font assets into local .ts string exports so the
 * sandboxed WebView renderers (KaTeX, MathJax, Mermaid, Vega, pdf.js) work
 * fully offline — no runtime CDN fetch, tighter CSP, faster first render.
 *
 * Pinned versions are intentional; bump here and re-run to upgrade.
 *
 * Output: apps/mobile/lib/vendor/*.ts  (committed; this script regenerates them)
 *
 * Usage: node scripts/vendor-cdn.mjs
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const VENDOR_DIR = join(process.cwd(), "apps/mobile/lib/vendor");
const TMP_DIR = join("/tmp", "recall-vendor-dl");
mkdirSync(VENDOR_DIR, { recursive: true });
mkdirSync(TMP_DIR, { recursive: true });

const VERSIONS = {
  katex: "0.17.0",
  // Pinned exactly to the committed bundle version (MathJax's internal
  // version is 3.2.1). A floating "3" would silently pull whatever 3.x
  // jsDelivr serves on the next vendor regen. Bump deliberately.
  mathjax: "3.2.1",
  mermaid: "10",
  vega: "5",
  vegaLite: "5",
  vegaEmbed: "6",
  pdfjs: "3.11.174",
  smilesDrawer: "2.1.7",
};

async function download(url, dest) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url} -> ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(dest, buf);
  return buf;
}

/** Write a .ts file exporting a JS/text asset as a JSON-stringified literal. */
function writeStringTs(name, content, comment) {
  const header = `// AUTO-GENERATED by scripts/vendor-cdn.mjs — do not edit by hand.\n// ${comment}\n// Size: ${(content.length / 1024).toFixed(0)} KB\n\n`;
  writeFileSync(join(VENDOR_DIR, `${name}.ts`), `${header}export const ${toConst(name)}: string = ${JSON.stringify(content)};\n`);
}

function toConst(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

async function main() {
  // 1. KaTeX fonts (woff2 only) — base64-embed into the CSS string.
  const katexBase = `https://cdn.jsdelivr.net/npm/katex@${VERSIONS.katex}/dist`;
  const cssResp = await fetch(`${katexBase}/katex.min.css`);
  if (!cssResp.ok) throw new Error(`katex css ${cssResp.status}`);
  let katexCss = await cssResp.text();

  const fontFiles = [...katexCss.matchAll(/url\(fonts\/([A-Za-z0-9_-]+\.woff2)\)/g)].map((m) => m[1]);
  const uniqueFonts = [...new Set(fontFiles)];
  console.log(`KaTeX: ${uniqueFonts.length} woff2 fonts to inline`);
  for (const f of uniqueFonts) {
    const buf = await download(`${katexBase}/fonts/${f}`, join(TMP_DIR, f));
    const b64 = buf.toString("base64");
    katexCss = katexCss.replaceAll(`url(fonts/${f})`, `url(data:font/woff2;base64,${b64})`);
  }
  // Strip remaining woff/ttf references (woff2 is universal in modern WebViews).
  katexCss = katexCss.replace(/,\s*url\(fonts\/[A-Za-z0-9_-]+\.(woff|ttf)\)[^,)]*/g, "");
  katexCss = katexCss.replace(/url\(fonts\/[A-Za-z0-9_-]+\.(woff|ttf)\)[^,)]*/g, "");
  writeStringTs("katexCss", katexCss, `KaTeX ${VERSIONS.katex} min CSS with ${uniqueFonts.length} woff2 fonts inlined as data URIs.`);

  // 2. MathJax tex-svg (self-contained, no font fetches).
  const mathjaxUrl = `https://cdn.jsdelivr.net/npm/mathjax@${VERSIONS.mathjax}/es5/tex-svg.js`;
  const mathjaxBuf = await download(mathjaxUrl, join(TMP_DIR, "tex-svg.js"));
  writeStringTs("mathjaxTexSvgJs", mathjaxBuf.toString("utf8"), `MathJax ${VERSIONS.mathjax} tex-svg.js — SVG output, no runtime font fetches.`);

  // 3. Mermaid
  const mermaidBuf = await download(`https://cdn.jsdelivr.net/npm/mermaid@${VERSIONS.mermaid}/dist/mermaid.min.js`, join(TMP_DIR, "mermaid.min.js"));
  writeStringTs("mermaidMinJs", mermaidBuf.toString("utf8"), `Mermaid ${VERSIONS.mermaid} min.`);

  // 4. Vega stack
  const vegaBuf = await download(`https://cdn.jsdelivr.net/npm/vega@${VERSIONS.vega}`, join(TMP_DIR, "vega.min.js"));
  writeStringTs("vegaMinJs", vegaBuf.toString("utf8"), `Vega ${VERSIONS.vega} min.`);
  const vegaLiteBuf = await download(`https://cdn.jsdelivr.net/npm/vega-lite@${VERSIONS.vegaLite}`, join(TMP_DIR, "vega-lite.min.js"));
  writeStringTs("vegaLiteMinJs", vegaLiteBuf.toString("utf8"), `Vega-Lite ${VERSIONS.vegaLite} min.`);
  const vegaEmbedBuf = await download(`https://cdn.jsdelivr.net/npm/vega-embed@${VERSIONS.vegaEmbed}`, join(TMP_DIR, "vega-embed.min.js"));
  writeStringTs("vegaEmbedMinJs", vegaEmbedBuf.toString("utf8"), `Vega-Embed ${VERSIONS.vegaEmbed} min.`);

  // 5. pdf.js (main + worker)
  const pdfBase = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${VERSIONS.pdfjs}`;
  const pdfMainBuf = await download(`${pdfBase}/pdf.min.js`, join(TMP_DIR, "pdf.min.js"));
  writeStringTs("pdfMinJs", pdfMainBuf.toString("utf8"), `pdf.js ${VERSIONS.pdfjs} main.`);
  const pdfWorkerBuf = await download(`${pdfBase}/pdf.worker.min.js`, join(TMP_DIR, "pdf.worker.min.js"));
  writeStringTs("pdfWorkerMinJs", pdfWorkerBuf.toString("utf8"), `pdf.js ${VERSIONS.pdfjs} worker (loaded via Blob URL at runtime).`);

  // 6. SmilesDrawer (chemistry) — browserify bundle; WebView loads via require(1) shim.
  const smilesUrl =
    `https://cdn.jsdelivr.net/npm/smiles-drawer@${VERSIONS.smilesDrawer}/dist/smiles-drawer.min.js`;
  const smilesBuf = await download(smilesUrl, join(TMP_DIR, "smiles-drawer.min.js"));
  const smilesJs = smilesBuf
    .toString("utf8")
    .replace(/\n?\/\/# sourceMappingURL=.*$/m, "");
  writeStringTs(
    "smilesDrawerMinJs",
    smilesJs,
    `smiles-drawer ${VERSIONS.smilesDrawer} min (browserify — load via require(1) shim).`,
  );

  // Manifest for traceability
  const allJs = [
    ["mathjaxTexSvgJs", mathjaxBuf.toString("utf8")],
    ["mermaidMinJs", mermaidBuf.toString("utf8")],
    ["vegaMinJs", vegaBuf.toString("utf8")],
    ["vegaLiteMinJs", vegaLiteBuf.toString("utf8")],
    ["vegaEmbedMinJs", vegaEmbedBuf.toString("utf8")],
    ["pdfMinJs", pdfMainBuf.toString("utf8")],
    ["pdfWorkerMinJs", pdfWorkerBuf.toString("utf8")],
    ["smilesDrawerMinJs", smilesJs],
  ];
  for (const [name, src] of allJs) {
    if (/<\/script>/i.test(src)) {
      throw new Error(
        `Vendored JS ${name} contains a "</script>" sequence — the inline-` +
        `script rendering path would break. Inspect the upgrade and handle it ` +
        `(e.g. split the sequence) before re-running.`,
      );
    }
  }
  const manifest = {
    generatedAt: new Date().toISOString(),
    versions: VERSIONS,
    sha256: {
      katexCss: sha(katexCss),
      mathjaxTexSvgJs: sha(mathjaxBuf),
      mermaidMinJs: sha(mermaidBuf),
      vegaMinJs: sha(vegaBuf),
      vegaLiteMinJs: sha(vegaLiteBuf),
      vegaEmbedMinJs: sha(vegaEmbedBuf),
      pdfMinJs: sha(pdfMainBuf),
      pdfWorkerMinJs: sha(pdfWorkerBuf),
      smilesDrawerMinJs: sha(smilesJs),
    },
  };
  writeFileSync(join(VENDOR_DIR, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  console.log("Vendor generation complete:", VENDOR_DIR);
}

function sha(buf) {
  return createHash("sha256").update(buf).digest("hex").slice(0, 16);
}

main().catch((e) => { console.error(e); process.exit(1); });
