/**
 * Cross-sector occupation list for the My Job role picker.
 *
 * My Job must work for every kind of work, not just software — this list is
 * the picker's corpus. Grouped by sector for maintainability; exported flat,
 * deduped, and sorted.
 */

import { matchOption, rankedOptions } from "@/lib/jobSearch/optionSearch";

const SECTORS: string[][] = [
  // Technology
  [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full-Stack Developer",
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "Web Developer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Cloud Engineer",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "QA Engineer",
    "Test Automation Engineer",
    "Security Engineer",
    "Cybersecurity Analyst",
    "Network Engineer",
    "Systems Administrator",
    "Database Administrator",
    "IT Support Specialist",
    "Help Desk Technician",
    "IT Manager",
    "Engineering Manager",
    "Technical Program Manager",
    "Solutions Architect",
    "Business Analyst",
    "Data Analyst",
    "Business Intelligence Analyst",
    "UX Designer",
    "UI Designer",
    "Product Designer",
    "UX Researcher",
    "Product Manager",
    "Technical Writer",
    "Salesforce Developer",
    "SAP Consultant",
    "Embedded Systems Engineer",
    "Firmware Engineer",
    "Robotics Engineer",
    "Game Developer",
    "Blockchain Developer",
    "WordPress Developer",
    "Shopify Developer",
    "Cloud Architect",
    "Scrum Master",
    "Data Architect",
    "Platform Engineer",
    "QA Analyst",
    "Penetration Tester",
    "IT Support Manager",
    "Computer Support Specialist",
    "ERP Consultant",
    "CRM Administrator",
    "Bioinformatics Analyst",
    "Quantitative Analyst",
    "Growth Engineer",
    "DevSecOps Engineer",
    "Software Developer",
    "Programmer",
    "Web Designer",
  ],
  // Healthcare & care
  [
    "Registered Nurse",
    "Nurse Practitioner",
    "Physician Assistant",
    "Physician",
    "Surgeon",
    "Dentist",
    "Dental Hygienist",
    "Dental Assistant",
    "Pharmacist",
    "Pharmacy Technician",
    "Physical Therapist",
    "Occupational Therapist",
    "Speech Therapist",
    "Radiologic Technologist",
    "Medical Assistant",
    "Medical Receptionist",
    "Caregiver",
    "Home Health Aide",
    "Nursing Assistant",
    "Midwife",
    "Paramedic",
    "EMT",
    "Phlebotomist",
    "Lab Technician",
    "Veterinarian",
    "Veterinary Technician",
    "Psychologist",
    "Therapist",
    "Counselor",
    "Social Worker",
    "Nutritionist",
    "Dietitian",
    "Optometrist",
    "Chiropractor",
    "Massage Therapist",
    "Medical Biller",
    "Health Services Administrator",
    "Clinical Research Coordinator",
    "Public Health Specialist",
    "Anesthesiologist",
    "Radiologist",
    "Pediatrician",
    "Family Physician",
    "Psychiatrist",
    "Occupational Health Nurse",
    "Surgical Technologist",
    "Respiratory Therapist",
    "Dialysis Technician",
    "Medical Transcriptionist",
    "Nursing Home Administrator",
    "Behavioral Health Technician",
    "Substance Abuse Counselor",
    "School Nurse",
    "Hospice Nurse",
    "Medical Laboratory Scientist",
    "Doctor",
    "Nurse",
    "Optician",
    "Orderly",
  ],
  // Trades & construction
  [
    "Electrician",
    "Plumber",
    "Carpenter",
    "HVAC Technician",
    "Welder",
    "Mason",
    "Roofer",
    "Painter",
    "Construction Worker",
    "Construction Manager",
    "General Contractor",
    "Heavy Equipment Operator",
    "Crane Operator",
    "Landscaper",
    "Groundskeeper",
    "Locksmith",
    "Glazier",
    "Drywall Installer",
    "Insulation Worker",
    "Sheet Metal Worker",
    "Ironworker",
    "Elevator Mechanic",
    "Solar Installer",
    "Home Inspector",
    "Building Inspector",
    "Surveyor",
    "Construction Estimator",
    "Handyman",
    "Tile Setter",
    "Concrete Finisher",
    "Pipefitter",
    "Boilermaker",
    "Millwright",
    "Cabinet Maker",
    "Fence Installer",
    "Garage Door Technician",
    "Water Damage Technician",
    "Restoration Technician",
    "Pest Control Technician",
    "Septic Technician",
    "Well Driller",
    "Scaffolder",
    "Demolition Worker",
  ],
  // Hospitality, food & travel
  [
    "Chef",
    "Cook",
    "Line Cook",
    "Sous Chef",
    "Baker",
    "Pastry Chef",
    "Barista",
    "Bartender",
    "Server",
    "Waiter",
    "Waitress",
    "Host",
    "Dishwasher",
    "Restaurant Manager",
    "Food Runner",
    "Catering Manager",
    "Hotel Manager",
    "Front Desk Agent",
    "Housekeeper",
    "Concierge",
    "Event Planner",
    "Tour Guide",
    "Flight Attendant",
    "Travel Agent",
    "Bar Manager",
    "Sommelier",
    "Food Service Manager",
    "Banquet Server",
    "Room Attendant",
    "Bellhop",
    "Valet",
    "Casino Dealer",
    "Cruise Ship Staff",
    "Ski Instructor",
    "Lifeguard Supervisor",
    "Camp Counselor",
  ],
  // Retail & sales
  [
    "Sales Associate",
    "Retail Associate",
    "Cashier",
    "Store Manager",
    "Assistant Store Manager",
    "Merchandiser",
    "Retail Buyer",
    "Account Executive",
    "Sales Representative",
    "Sales Manager",
    "Business Development Representative",
    "Real Estate Agent",
    "Real Estate Broker",
    "Insurance Agent",
    "Car Salesperson",
    "Customer Service Representative",
    "Call Center Agent",
    "Account Manager",
    "Sales Engineer",
    "Pharmaceutical Sales Representative",
    "Inside Sales Representative",
    "Regional Sales Manager",
    "E-commerce Manager",
    "Visual Merchandiser",
    "Loss Prevention Officer",
    "Leasing Consultant",
    "Property Manager",
    "Mortgage Loan Officer",
    "Financial Sales Agent",
    "Realtor",
  ],
  // Education
  [
    "Teacher",
    "Elementary School Teacher",
    "Middle School Teacher",
    "High School Teacher",
    "Kindergarten Teacher",
    "Preschool Teacher",
    "Special Education Teacher",
    "Substitute Teacher",
    "Tutor",
    "Professor",
    "Lecturer",
    "Teaching Assistant",
    "School Counselor",
    "School Principal",
    "Librarian",
    "Instructional Designer",
    "Coach",
    "Corporate Trainer",
    "Curriculum Developer",
    "Admissions Officer",
    "Education Administrator",
    "Early Childhood Educator",
    "ESL Teacher",
    "Math Teacher",
    "Science Teacher",
    "English Teacher",
    "Music Teacher",
    "Art Teacher",
    "Physical Education Teacher",
    "Guidance Counselor",
    "Speech Language Pathologist",
    "Daycare Worker",
    "After School Coordinator",
  ],
  // Finance, legal & insurance
  [
    "Accountant",
    "Bookkeeper",
    "Financial Analyst",
    "Financial Advisor",
    "Auditor",
    "Tax Preparer",
    "Investment Banker",
    "Loan Officer",
    "Bank Teller",
    "Underwriter",
    "Actuary",
    "Payroll Specialist",
    "Controller",
    "Finance Manager",
    "Lawyer",
    "Attorney",
    "Paralegal",
    "Legal Assistant",
    "Compliance Officer",
    "Claims Adjuster",
    "Insurance Underwriter",
    "Risk Manager",
    "Credit Analyst",
    "Mortgage Broker",
    "Insurance Claims Examiner",
    "Insurance Sales Agent",
    "Tax Accountant",
    "Forensic Accountant",
    "Budget Analyst",
    "Portfolio Manager",
    "Court Clerk",
    "Legal Secretary",
    "Contract Manager",
    "Notary Public",
    "Mediator",
    "Judge",
    "Banker",
  ],
  // Creative, media & marketing
  [
    "Graphic Designer",
    "Photographer",
    "Videographer",
    "Video Editor",
    "Copywriter",
    "Content Writer",
    "Journalist",
    "Editor",
    "Social Media Manager",
    "Marketing Manager",
    "Marketing Coordinator",
    "SEO Specialist",
    "Content Strategist",
    "Brand Manager",
    "Art Director",
    "Illustrator",
    "Animator",
    "Musician",
    "Actor",
    "Fashion Designer",
    "Interior Designer",
    "Architect",
    "Producer",
    "Public Relations Specialist",
    "Translator",
    "Interpreter",
    "Podcast Producer",
    "UX Writer",
    "Motion Designer",
    "Digital Marketing Specialist",
    "Email Marketing Manager",
    "E-commerce Specialist",
    "Community Manager",
    "Video Producer",
    "Sound Engineer",
    "Lighting Technician",
    "Stage Manager",
    "Costume Designer",
    "Set Designer",
    "Tattoo Artist",
    "Floral Designer",
    "Wedding Planner",
    "Writer",
    "Artist",
    "Singer",
    "Dancer",
    "DJ",
    "Professional Athlete",
    "Referee",
  ],
  // Science & engineering (non-software)
  [
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Chemical Engineer",
    "Aerospace Engineer",
    "Biomedical Engineer",
    "Industrial Engineer",
    "Environmental Engineer",
    "Structural Engineer",
    "Manufacturing Engineer",
    "Process Engineer",
    "Quality Engineer",
    "Materials Scientist",
    "Chemist",
    "Biologist",
    "Physicist",
    "Geologist",
    "Research Scientist",
    "Lab Assistant",
    "Statistician",
    "Economist",
    "Environmental Scientist",
    "Marine Biologist",
    "Forensic Scientist",
    "Agricultural Scientist",
    "Petroleum Engineer",
    "Mining Engineer",
    "Nuclear Engineer",
    "Optical Engineer",
    "Acoustical Engineer",
    "Hydrologist",
    "Meteorologist",
    "Epidemiologist",
    "Microbiologist",
    "Zoologist",
    "Botanist",
    "Food Scientist",
    "Scientist",
  ],
  // Manufacturing, logistics & transport
  [
    "Warehouse Worker",
    "Warehouse Manager",
    "Forklift Operator",
    "Machine Operator",
    "Assembler",
    "Production Worker",
    "Quality Inspector",
    "Maintenance Technician",
    "Mechanic",
    "Diesel Mechanic",
    "Auto Mechanic",
    "Machinist",
    "CNC Operator",
    "Truck Driver",
    "Delivery Driver",
    "Bus Driver",
    "Courier",
    "Dispatcher",
    "Logistics Coordinator",
    "Supply Chain Analyst",
    "Inventory Manager",
    "Shipping Clerk",
    "Package Handler",
    "Postal Worker",
    "Pilot",
    "Air Traffic Controller",
    "Train Conductor",
    "Ship Captain",
    "Fleet Manager",
    "Delivery Van Driver",
    "School Bus Driver",
    "Taxi Driver",
    "Rideshare Driver",
    "Tow Truck Driver",
    "Crane Truck Operator",
    "Freight Broker",
    "Customs Broker",
    "Import Export Coordinator",
    "Distribution Center Manager",
    "Package Delivery Driver",
    "Mail Carrier",
    "Driver",
    "Chauffeur",
  ],
  // Office & administration
  [
    "Administrative Assistant",
    "Executive Assistant",
    "Receptionist",
    "Office Manager",
    "Data Entry Clerk",
    "Virtual Assistant",
    "Human Resources Manager",
    "HR Generalist",
    "Recruiter",
    "Talent Acquisition Specialist",
    "Operations Manager",
    "General Manager",
    "Program Manager",
    "Project Manager",
    "Management Consultant",
    "Personal Assistant",
    "Scheduler",
    "Office Clerk",
    "Facilities Manager",
    "Chief of Staff",
    "Executive Director",
    "Nonprofit Program Manager",
    "Grant Writer",
    "Fundraising Manager",
    "Volunteer Coordinator",
    "Customer Success Manager",
    "Onboarding Specialist",
    "Benefits Administrator",
    "Training Coordinator",
    "Secretary",
    "File Clerk",
  ],
  // Public service & safety
  [
    "Police Officer",
    "Firefighter",
    "Correctional Officer",
    "Security Guard",
    "Security Officer",
    "Urban Planner",
    "Civil Servant",
    "Park Ranger",
    "Probation Officer",
    "Detective",
    "Border Patrol Agent",
    "Customs Officer",
    "Emergency Management Specialist",
    "911 Dispatcher",
    "Animal Control Officer",
    "Code Enforcement Officer",
    "Public Works Director",
    "City Planner",
    "Transit Operator",
    "Court Officer",
    "Juvenile Counselor",
    "Victim Advocate",
    "Soldier",
    "Military Officer",
    "Intelligence Analyst",
    "Diplomat",
    "Pastor",
    "Priest",
    "Imam",
    "Rabbi",
    "Chaplain",
  ],
  // Beauty, fitness & personal services
  [
    "Hair Stylist",
    "Barber",
    "Esthetician",
    "Nail Technician",
    "Makeup Artist",
    "Personal Trainer",
    "Yoga Instructor",
    "Fitness Instructor",
    "Tattoo Artist",
    "Spa Therapist",
    "Pilates Instructor",
    "CrossFit Coach",
    "Swim Instructor",
    "Dance Instructor",
    "Nutrition Coach",
    "Wellness Coach",
    "Electrologist",
    "Permanent Makeup Artist",
  ],
  // Agriculture & outdoors
  [
    "Farmer",
    "Farm Worker",
    "Rancher",
    "Agricultural Technician",
    "Gardener",
    "Greenhouse Worker",
    "Forester",
    "Fisherman",
    "Vineyard Worker",
    "Beekeeper",
    "Dairy Farmer",
    "Poultry Farmer",
    "Crop Consultant",
    "Soil Scientist",
    "Arborist",
    "Logger",
    "Fish Hatchery Technician",
  ],
  // Home & everyday services
  [
    "Cleaner",
    "Janitor",
    "Nanny",
    "Babysitter",
    "Dog Walker",
    "Pet Sitter",
    "Mover",
    "Lifeguard",
    "Pest Control Technician",
    "Pool Technician",
    "Appliance Repair Technician",
    "Auto Detailer",
    "Carpet Cleaner",
    "Window Cleaner",
    "Pressure Washer",
    "Junk Removal Specialist",
    "Professional Organizer",
    "Home Stager",
    "Elderly Companion",
    "Personal Shopper",
    "Au Pair",
  ],
];

/** Flat, deduped, alphabetized occupation list. */
export const JOB_TITLES: string[] = Array.from(
  new Map(SECTORS.flat().map((title) => [title.toLowerCase(), title])).values(),
).sort((a, b) => a.localeCompare(b));

/** Ranked search over JOB_TITLES; already-selected titles excluded. */
export function searchJobTitles(
  query: string,
  exclude: readonly string[] = [],
  limit?: number,
): string[] {
  return rankedOptions(JOB_TITLES, query, exclude, limit);
}

/** Exact (case-insensitive) match against the list → canonical casing. */
export function matchJobTitle(text: string): string | null {
  return matchOption(JOB_TITLES, text);
}
