/**
 * Cross-sector skills list for the My Job skills picker — same idea as
 * jobTitles.ts: every kind of work, not just software. Grouped by sector
 * for maintainability; exported flat, deduped, and sorted.
 */

import { matchOption, rankedOptions } from "@/lib/jobSearch/optionSearch";

const SKILL_GROUPS: string[][] = [
  // Workplace fundamentals
  [
    "Customer Service",
    "Communication",
    "Teamwork",
    "Leadership",
    "Problem Solving",
    "Time Management",
    "Project Management",
    "Public Speaking",
    "Negotiation",
    "Conflict Resolution",
    "Training",
    "Mentoring",
    "Scheduling",
    "Inventory Management",
    "Quality Assurance",
    "Data Entry",
    "Report Writing",
    "Budgeting",
    "Event Planning",
    "Risk Management",
  ],
  // Office & business tools
  [
    "Microsoft Excel",
    "Microsoft Word",
    "Microsoft PowerPoint",
    "Google Workspace",
    "QuickBooks",
    "Salesforce",
    "SAP",
    "HubSpot",
    "Slack",
    "Notion",
    "Jira",
    "Trello",
    "Zoom",
    "CRM Software",
    "Payroll Software",
    "Bookkeeping",
    "Accounting",
    "Financial Analysis",
    "Auditing",
    "Tax Preparation",
  ],
  // Technology
  [
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "SQL",
    "React",
    "React Native",
    "Node.js",
    "FastAPI",
    "Django",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Linux",
    "Git",
    "Data Analysis",
    "Machine Learning",
    "Data Visualization",
    "Tableau",
    "Power BI",
    "Figma",
    "Cybersecurity",
    "Network Administration",
    "Technical Support",
    "WordPress",
    "Shopify",
  ],
  // Healthcare & care
  [
    "Patient Care",
    "CPR",
    "First Aid",
    "Phlebotomy",
    "Medication Administration",
    "Vital Signs",
    "Electronic Health Records",
    "Medical Terminology",
    "Medical Billing",
    "Wound Care",
    "Physical Therapy",
    "Occupational Therapy",
    "Counseling",
    "Case Management",
    "Childcare",
    "Elderly Care",
    "Special Needs Care",
  ],
  // Trades & construction
  [
    "Welding",
    "Carpentry",
    "Plumbing",
    "Electrical Wiring",
    "HVAC",
    "Blueprint Reading",
    "Drywall",
    "Roofing",
    "Painting",
    "Masonry",
    "Heavy Equipment Operation",
    "Forklift Operation",
    "OSHA Safety",
    "Power Tools",
    "Landscaping",
    "Irrigation",
    "Solar Installation",
    "Auto Repair",
    "Diesel Engines",
    "CNC Machining",
  ],
  // Food & hospitality
  [
    "Cooking",
    "Baking",
    "Food Safety",
    "HACCP",
    "Menu Planning",
    "Knife Skills",
    "Bartending",
    "Barista Skills",
    "Catering",
    "Food Costing",
    "Housekeeping",
    "Front Desk Operations",
    "Reservations Systems",
  ],
  // Retail & sales
  [
    "Cash Handling",
    "POS Systems",
    "Merchandising",
    "Cold Calling",
    "Lead Generation",
    "Upselling",
    "Stock Management",
    "Loss Prevention",
    "Client Relations",
    "B2B Sales",
    "Retail Sales",
  ],
  // Creative & marketing
  [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe Premiere",
    "Video Editing",
    "Photography",
    "Copywriting",
    "Content Writing",
    "Social Media Marketing",
    "SEO",
    "Email Marketing",
    "Graphic Design",
    "Branding",
    "UI Design",
    "UX Research",
    "Animation",
  ],
  // Education & language
  [
    "Lesson Planning",
    "Classroom Management",
    "Curriculum Design",
    "Tutoring",
    "ESL Teaching",
    "Translation",
    "Interpretation",
    "Spanish",
    "French",
    "German",
    "Mandarin",
    "Arabic",
    "Amharic",
    "Portuguese",
    "Russian",
    "Hindi",
    "Sign Language",
  ],
  // Logistics & driving
  [
    "Commercial Driving (CDL)",
    "Defensive Driving",
    "Route Planning",
    "Warehouse Operations",
    "Order Picking",
    "Pallet Jack",
    "Supply Chain Management",
    "Customs Clearance",
    "Dispatching",
  ],
  // Personal services
  [
    "Hair Cutting",
    "Hair Coloring",
    "Skincare",
    "Nail Art",
    "Makeup Artistry",
    "Fitness Training",
    "Yoga Instruction",
    "Massage Therapy",
    "Pet Grooming",
    "Pet Training",
  ],
];

/** Flat, deduped, alphabetized skills list. */
export const SKILLS: string[] = Array.from(
  new Map(SKILL_GROUPS.flat().map((skill) => [skill.toLowerCase(), skill])).values(),
).sort((a, b) => a.localeCompare(b));

/** Ranked typeahead over SKILLS; already-selected skills excluded. */
export function searchSkills(
  query: string,
  exclude: readonly string[] = [],
  limit?: number,
): string[] {
  return rankedOptions(SKILLS, query, exclude, limit);
}

/** Exact (case-insensitive) skill match → canonical casing. */
export function matchSkill(text: string): string | null {
  return matchOption(SKILLS, text);
}
