"""The phrases a physics question asks with, each mapped to the dimension of its answer."""

from __future__ import annotations

from app.modules.physics.givens import ANGLE

_DIMENSIONLESS = "dimensionless"
_UNKNOWN = ""
# A price is no physical result: a question for the cost of running a heater
# is not answered by its energy in joules.
_MONEY = "money"

# Asked phrase -> Pint expression. ANGLE, dimensionless and money stand for
# themselves; an empty string marks a phrase that is a quantity of no single
# dimension, so the reading is abandoned rather than guessed.
_QUANTITIES: dict[str, str] = {
    # Time
    "how long": "second",
    "time of flight": "second",
    "flight time": "second",
    "time taken": "second",
    "time constant": "second",
    "half-life": "second",
    "half life": "second",
    "period": "second",
    "duration": "second",
    "time": "second",
    # Length
    "how far": "meter",
    "how high": "meter",
    "how deep": "meter",
    "distance": "meter",
    "displacement": "meter",
    "height": "meter",
    "range": "meter",
    "length": "meter",
    "wavelength": "meter",
    "radius": "meter",
    "depth": "meter",
    "extension": "meter",
    "compression": "meter",
    "focal length": "meter",
    "separation": "meter",
    "position": "meter",
    # Motion
    "how fast": "meter / second",
    "speed": "meter / second",
    "velocity": "meter / second",
    "velocities": "meter / second",
    "speeds": "meter / second",
    "acceleration": "meter / second ** 2",
    "deceleration": "meter / second ** 2",
    "retardation": "meter / second ** 2",
    "gravitational field strength": "meter / second ** 2",
    "angular velocity": "radian / second",
    "angular speed": "radian / second",
    "angular frequency": "radian / second",
    "angular acceleration": "radian / second ** 2",
    "angular displacement": ANGLE,
    "angular momentum": "kilogram * meter ** 2 / second",
    "center of mass": "meter",
    "centre of mass": "meter",
    "moment of inertia": "kilogram * meter ** 2",
    "momentum": "kilogram * meter / second",
    "impulse": "kilogram * meter / second",
    # Force and energy
    "force": "newton",
    "forces": "newton",
    "tension": "newton",
    "weight": "newton",
    "thrust": "newton",
    "upthrust": "newton",
    "buoyant force": "newton",
    "normal force": "newton",
    "friction": "newton",
    "drag": "newton",
    "torque": "newton * meter",
    "moment": "newton * meter",
    "energy": "joule",
    "work": "joule",
    "work done": "joule",
    "work function": "joule",
    "heat": "joule",
    "kinetic energy": "joule",
    "potential energy": "joule",
    "heat energy": "joule",
    "latent heat energy": "joule",
    "mass energy": "joule",
    "rest energy": "joule",
    "energy equivalent": "joule",
    "ke": "joule",
    "pe": "joule",
    "gpe": "joule",
    "rate of heat": "watt",
    "heat conduction rate": "watt",
    "conduction rate": "watt",
    "mass flow rate": "kilogram / second",
    "flow rate": "meter ** 3 / second",
    "surface tension": "newton / meter",
    "power": "watt",
    "lens power": "1 / meter",
    "optical power": "1 / meter",
    "pressure": "pascal",
    "stress": "pascal",
    "young modulus": "pascal",
    "young's modulus": "pascal",
    "youngs modulus": "pascal",
    "bulk modulus": "pascal",
    "shear modulus": "pascal",
    "modulus": "pascal",
    "mass": "kilogram",
    "density": "kilogram / meter ** 3",
    "volume": "meter ** 3",
    "area": "meter ** 2",
    "spring constant": "newton / meter",
    "stiffness": "newton / meter",
    # Waves and thermal
    "frequency": "hertz",
    "frequencies": "hertz",
    "pitch": "hertz",
    "temperature": "kelvin",
    "specific heat capacity": "joule / kilogram / kelvin",
    "specific heat": "joule / kilogram / kelvin",
    "latent heat": "joule / kilogram",
    "entropy": "joule / kelvin",
    "number of moles": "mole",
    "moles": "mole",
    # Electricity and magnetism
    "current": "ampere",
    "voltage": "volt",
    "electric potential": "volt",
    "electric potential energy": "joule",
    "potential difference": "volt",
    "emf": "volt",
    "e.m.f.": "volt",
    "terminal voltage": "volt",
    "resistance": "ohm",
    "impedance": "ohm",
    "reactance": "ohm",
    "resistivity": "ohm * meter",
    "charge": "coulomb",
    "capacitance": "farad",
    "inductance": "henry",
    "magnetic field": "tesla",
    "flux density": "tesla",
    "magnetic flux": "weber",
    "electric field": "volt / meter",
    "activity": "1 / second",
    "decay constant": "1 / second",
    # Pure numbers and angles
    "angle": ANGLE,
    "efficiency": _DIMENSIONLESS,
    "refractive index": _DIMENSIONLESS,
    "index of refraction": _DIMENSIONLESS,
    "coefficient of friction": _DIMENSIONLESS,
    "coefficient of static friction": _DIMENSIONLESS,
    "coefficient of kinetic friction": _DIMENSIONLESS,
    "coefficient of performance": _DIMENSIONLESS,
    "coefficient": _DIMENSIONLESS,
    "reynolds number": _DIMENSIONLESS,
    "magnification": _DIMENSIONLESS,
    "lorentz factor": _DIMENSIONLESS,
    "fraction": _DIMENSIONLESS,
    "ratio": _DIMENSIONLESS,
    "strain": _DIMENSIONLESS,
    "cost": _MONEY,
    "price": _MONEY,
    # Not a bare "bill": that is also a name ("Bill's weight").
    "electricity bill": _MONEY,
    "energy bill": _MONEY,
    # Quantities of no single dimension: stop reading rather than guess.
    "field strength": _UNKNOWN,
    "field": _UNKNOWN,
    "component": _UNKNOWN,
    "components": _UNKNOWN,
    "value": _UNKNOWN,
    "answer": _UNKNOWN,
}
