"""The unit spellings the givens scanner reads, each mapped to a Pint expression.

A closed table, not free-form Pint parsing: Pint reads prose as units ("at" is a
technical atmosphere, "in" an inch, "a" a year).
"""

from __future__ import annotations

# Spelling -> Pint expression. Single letters are case-sensitive SI symbols;
# a lowercase "a" is an article and "v" a variable. Longer spellings below are
# matched without case.
_SYMBOLS: dict[str, str] = {
    "m": "meter",
    "g": "gram",
    "s": "second",
    "h": "hour",
    "N": "newton",
    "J": "joule",
    "W": "watt",
    "A": "ampere",
    "V": "volt",
    "C": "coulomb",
    "F": "farad",
    "H": "henry",
    "T": "tesla",
    "K": "kelvin",
    "L": "liter",
    "Ω": "ohm",
    "°": "degree",
    "%": "percent",
    "mA": "milliampere",
    "MW": "megawatt",
    "mW": "milliwatt",
    "mV": "millivolt",
    "MV": "megavolt",
    "kV": "kilovolt",
    "mH": "millihenry",
    "mT": "millitesla",
    "uC": "microcoulomb",
    "µC": "microcoulomb",
    "μC": "microcoulomb",
    "nC": "nanocoulomb",
    "mC": "millicoulomb",
    "uF": "microfarad",
    "µF": "microfarad",
    "μF": "microfarad",
    "nF": "nanofarad",
    "pF": "picofarad",
    "mF": "millifarad",
    "kΩ": "kiloohm",
    "MΩ": "megaohm",
    "Pa": "pascal",
    "kPa": "kilopascal",
    "MPa": "megapascal",
    "GPa": "gigapascal",
    # Field strength: a newton per coulomb is a volt per metre.
    "N/C": "newton / coulomb",
    "V/m": "volt / meter",
    "kV/m": "kilovolt / meter",
    # Viscosity, not a pressure: "0.001 Pa*s" is one unit.
    "Pa*s": "pascal * second",
    "Pa·s": "pascal * second",
    "Pa s": "pascal * second",
    "Hz": "hertz",
    "kHz": "kilohertz",
    "MHz": "megahertz",
    "GHz": "gigahertz",
    "kJ": "kilojoule",
    "MJ": "megajoule",
    "kW": "kilowatt",
    "kN": "kilonewton",
    "eV": "electron_volt",
    "keV": "kiloelectron_volt",
    "MeV": "megaelectron_volt",
    "kWh": "kilowatt_hour",
    "mL": "milliliter",
    "ms": "millisecond",
    "mm": "millimeter",
    "Wb": "weber",
}

_WORDS: dict[str, str] = {
    "m/s^2": "meter / second ** 2",
    "m/s2": "meter / second ** 2",
    "m/s²": "meter / second ** 2",
    "m s^-2": "meter / second ** 2",
    "rad/s^2": "radian / second ** 2",
    "rad/s2": "radian / second ** 2",
    "m/s": "meter / second",
    "km/h": "kilometer / hour",
    "kmh": "kilometer / hour",
    "kph": "kilometer / hour",
    "km/s": "kilometer / second",
    "cm/s": "centimeter / second",
    "mm/s": "millimeter / second",
    "mph": "mile / hour",
    "miles per hour": "mile / hour",
    "rad/s": "radian / second",
    "rev/s": "revolution / second",
    "rpm": "revolution / minute",
    "n/m": "newton / meter",
    "kg/m^3": "kilogram / meter ** 3",
    "kg/m3": "kilogram / meter ** 3",
    "g/cm^3": "gram / centimeter ** 3",
    "g/cm3": "gram / centimeter ** 3",
    "kg m^2": "kilogram * meter ** 2",
    "kg·m^2": "kilogram * meter ** 2",
    "kg*m^2": "kilogram * meter ** 2",
    "kgm^2": "kilogram * meter ** 2",
    "kg m/s": "kilogram * meter / second",
    "kg·m/s": "kilogram * meter / second",
    "kg*m/s": "kilogram * meter / second",
    "n s": "newton * second",
    "n·s": "newton * second",
    "n*s": "newton * second",
    "n m": "newton * meter",
    "n·m": "newton * meter",
    "n*m": "newton * meter",
    "j/kg/k": "joule / kilogram / kelvin",
    "j/(kg k)": "joule / kilogram / kelvin",
    "j/(kg·k)": "joule / kilogram / kelvin",
    "j/kgk": "joule / kilogram / kelvin",
    "j/kg°c": "joule / kilogram / kelvin",
    "j/kg/°c": "joule / kilogram / kelvin",
    "j/(kg °c)": "joule / kilogram / kelvin",
    "j kg^-1 k^-1": "joule / kilogram / kelvin",
    "kj/kg": "kilojoule / kilogram",
    "j/kg": "joule / kilogram",
    "w/m^2": "watt / meter ** 2",
    "w/m/k": "watt / meter / kelvin",
    "ohm m": "ohm * meter",
    "ohm·m": "ohm * meter",
    "ω m": "ohm * meter",
    "ω·m": "ohm * meter",
    "m^2": "meter ** 2",
    "m2": "meter ** 2",
    "cm^2": "centimeter ** 2",
    "cm2": "centimeter ** 2",
    "mm^2": "millimeter ** 2",
    "mm2": "millimeter ** 2",
    "m^3": "meter ** 3",
    "m3": "meter ** 3",
    "cm^3": "centimeter ** 3",
    "cm3": "centimeter ** 3",
    # An expansion coefficient: per degree of change, so per °C is per K.
    "per k": "1 / kelvin",
    "/k": "1 / kelvin",
    "k^-1": "1 / kelvin",
    "k⁻¹": "1 / kelvin",
    "per °c": "1 / kelvin",
    "/°c": "1 / kelvin",
    "°c^-1": "1 / kelvin",
    "°c⁻¹": "1 / kelvin",
    "g/mol": "gram / mole",
    "kg/mol": "kilogram / mole",
    "mmhg": "millimeter_Hg",
    "bq": "1 / second",
    "°c": "degC",
    "degc": "degC",
    "celsius": "degC",
    "degrees celsius": "degC",
    "kelvin": "kelvin",
    "kg": "kilogram",
    "mg": "milligram",
    "tonnes": "metric_ton",
    "tonne": "metric_ton",
    "km": "kilometer",
    "cm": "centimeter",
    "nm": "nanometer",
    "um": "micrometer",
    "µm": "micrometer",
    "μm": "micrometer",
    "mi": "mile",
    "miles": "mile",
    "mile": "mile",
    "ft": "foot",
    "feet": "foot",
    "inches": "inch",
    "inch": "inch",
    "metres": "meter",
    "meters": "meter",
    "metre": "meter",
    "meter": "meter",
    "seconds": "second",
    "second": "second",
    "secs": "second",
    "sec": "second",
    "milliseconds": "millisecond",
    "minutes": "minute",
    "minute": "minute",
    "mins": "minute",
    "min": "minute",
    "hours": "hour",
    "hour": "hour",
    "hrs": "hour",
    "hr": "hour",
    "days": "day",
    "day": "day",
    "years": "year",
    "year": "year",
    "newtons": "newton",
    "newton": "newton",
    "joules": "joule",
    "joule": "joule",
    "kilojoules": "kilojoule",
    "watts": "watt",
    "watt": "watt",
    "kilowatts": "kilowatt",
    "amperes": "ampere",
    "ampere": "ampere",
    "amps": "ampere",
    "amp": "ampere",
    "volts": "volt",
    "volt": "volt",
    "ohms": "ohm",
    "ohm": "ohm",
    "kohm": "kiloohm",
    "coulombs": "coulomb",
    "coulomb": "coulomb",
    "microcoulombs": "microcoulomb",
    "farads": "farad",
    "henry": "henry",
    "tesla": "tesla",
    "teslas": "tesla",
    "weber": "weber",
    "hertz": "hertz",
    "pascals": "pascal",
    "pascal": "pascal",
    "atm": "atmosphere",
    "bar": "bar",
    "litres": "liter",
    "litre": "liter",
    "liters": "liter",
    "liter": "liter",
    "ml": "milliliter",
    "moles": "mole",
    "mole": "mole",
    "mol": "mole",
    "degrees": "degree",
    "degree": "degree",
    "deg": "degree",
    "radians": "radian",
    "radian": "radian",
    "rad": "radian",
    "percent": "percent",
    # Counts: a pure number with a name (coil windings, nuclei, microstates).
    "turns": "dimensionless",
    "turn": "dimensionless",
    "nuclei": "dimensionless",
    "atoms": "dimensionless",
    "microstates": "dimensionless",
    # A grating's ruling, as a line density.
    "lines per mm": "1 / millimeter",
    "lines/mm": "1 / millimeter",
    "lines per cm": "1 / centimeter",
    "lines/cm": "1 / centimeter",
    "lines per metre": "1 / meter",
    "lines per meter": "1 / meter",
    "lines/m": "1 / meter",
}
