import { StyleSheet } from "react-native";

import { Radius } from "@/lib/radius";
import { shadowOverlay } from "@/lib/shadow";
import { Space } from "@/lib/space";
import type { Theme } from "@/lib/theme";
import { Type } from "@/lib/type";
import { uiFontFamily } from "@/lib/uiFont";

export function makeTodosStyles(C: Theme) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: C.bg },
    center: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: C.bg,
    },
    dayHeading: {
      ...Type.body,
      fontFamily: uiFontFamily("700"),
      fontWeight: "700",
      color: C.text,
    },
    list: { flex: 1 },
    listEmpty: { flexGrow: 1 },
    // Keep the last row clear of the bottom-right add FAB (56px + offset).
    listContent: { paddingTop: Space.xs, paddingBottom: 96 },
    section: {
      paddingTop: Space.xs,
      paddingBottom: Space.xxs,
    },
    sectionHeader: {
      paddingHorizontal: Space.md,
      paddingTop: Space.sm,
      paddingBottom: Space.xs,
    },
    sectionHeaderFirst: {
      paddingTop: Space.lg,
    },
    sectionHeading: {
      ...Type.label,
      color: C.textSecondary,
    },
    sectionEmpty: {
      ...Type.label,
      fontWeight: "400",
      color: C.textTertiary,
      paddingHorizontal: Space.md,
      paddingBottom: Space.sm,
    },
    daySheet: {
      marginHorizontal: Space.md,
      marginBottom: Space.sm,
      borderRadius: Radius.xl,
      backgroundColor: C.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: C.border,
      overflow: "hidden",
    },
    dayClash: {
      paddingLeft: Space.lg + Space.xl,
      paddingRight: Space.md,
      paddingTop: Space.sm,
      paddingBottom: Space.xxs,
      gap: Space.xxs,
    },
    dayClashText: { ...Type.secondary, color: C.textSecondary },
    sheetRule: {
      height: StyleSheet.hairlineWidth,
      marginLeft: Space.sm + Space.minTouch,
      marginRight: Space.md,
      backgroundColor: C.border,
    },
    todoRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: Space.sm,
      paddingRight: Space.md,
      paddingVertical: Space.xs,
    },
    todoRowHighlighted: {
      backgroundColor: C.primaryLight,
    },
    swipeContainer: {
      overflow: "hidden",
    },
    swipeDeleteAction: {
      width: 80,
      backgroundColor: C.danger,
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
    },
    swipeDeleteText: {
      ...Type.caption,
      fontWeight: "600",
      color: C.onPrimary,
    },
    checkbox: {
      width: Space.minTouch,
      minHeight: Space.minTouch,
      alignItems: "center",
      justifyContent: "center",
    },
    todoMain: { flex: 1, gap: Space.xxs },
    todoText: { ...Type.navTitle, color: C.text },
    todoMeta: { ...Type.meta, color: C.textSecondary },
    todoTime: {
      ...Type.label,
      fontVariant: ["tabular-nums"],
      marginLeft: Space.sm,
    },
    todoTimeToday: { color: C.primary },
    todoTimeOverdue: { color: C.danger },
    todoTimeLater: { color: C.textSecondary },
    overlapNote: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: Space.xxs,
      marginTop: Space.sm,
      padding: Space.sm,
      borderRadius: Radius.sm,
      backgroundColor: C.dangerLight,
    },
    overlapNoteText: { flex: 1, ...Type.caption, fontWeight: "400", color: C.danger },
    pickerOverlapNote: { marginHorizontal: Space.md, marginBottom: Space.xs },
    detailPage: { flex: 1, zIndex: 0, backgroundColor: C.surface },
    reviewTitle: {
      ...Type.display,
      color: C.text,
      backgroundColor: "transparent",
      borderWidth: 0,
      paddingVertical: Space.xs,
      marginTop: Space.sm,
    },
    reviewChip: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xxs,
      paddingHorizontal: Space.sm,
      paddingVertical: Space.xs,
      borderRadius: Radius.full,
      backgroundColor: C.bg,
    },
    reviewChipText: { ...Type.secondary, color: C.text },
    reviewList: { marginTop: Space.lg, gap: Space.xxs },
    reviewRowMain: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: Space.sm,
      minHeight: Space.minTouch,
    },
    reviewSubRow: { paddingLeft: Space.xl },
    reviewLabel: { ...Type.body, color: C.text },
    reviewValue: {
      marginLeft: "auto",
      maxWidth: "52%",
      borderRadius: Radius.sm,
      backgroundColor: C.bg,
      paddingHorizontal: Space.sm,
      paddingVertical: Space.xs,
    },
    reviewValueText: { ...Type.secondary, color: C.text },
    todoDone: {
      ...Type.body,
      color: C.textSecondary,
      textDecorationLine: "line-through",
    },
    formLabel: { ...Type.label, color: C.textSecondary },
    fieldGap: { marginTop: Space.md },
    titleInput: {
      ...Type.navTitle,
      color: C.text,
      backgroundColor: C.surface,
      borderRadius: Radius.md,
      paddingHorizontal: Space.md,
      paddingVertical: Space.sm,
      borderWidth: 1,
      borderColor: C.border,
    },
    dateChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
      backgroundColor: C.primaryLight,
      borderRadius: Radius.sm,
      paddingHorizontal: Space.sm,
      paddingVertical: Space.sm,
      alignSelf: "flex-start",
    },
    dateChipText: { ...Type.secondary, fontWeight: "600", color: C.text },
    dateRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
    },
    fieldGrow: { flex: 1 },
    choiceList: {
      borderWidth: 1,
      borderColor: C.border,
      borderTopWidth: 0,
      borderBottomLeftRadius: Radius.md,
      borderBottomRightRadius: Radius.md,
      overflow: "hidden",
      backgroundColor: C.surface,
    },
    choiceItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: Space.xs,
      minHeight: Space.minTouch,
      paddingHorizontal: Space.md,
    },
    choiceItemActive: { backgroundColor: C.primaryLight },
    choiceItemPressed: { opacity: 0.7 },
    choiceLabel: { ...Type.secondary, color: C.text },
    choiceLabelActive: { ...Type.secondary, fontWeight: "600", color: C.primary },
    choiceCreate: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
      minHeight: Space.minTouch,
      paddingHorizontal: Space.md,
    },
    choiceInput: {
      ...Type.body,
      color: C.text,
      minHeight: Space.minTouch,
      paddingHorizontal: Space.md,
      borderTopWidth: 1,
      borderTopColor: C.border,
    },
    todoRowSelected: { backgroundColor: C.primaryLight },
    menuLayer: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      zIndex: 50,
      elevation: 50,
    },
    menuScrim: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    menuCard: {
      position: "absolute",
      top: Space.xs,
      right: Space.sm,
      minWidth: 220,
      borderRadius: Radius.lg,
      backgroundColor: C.bg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: C.border,
      paddingVertical: Space.xs,
      zIndex: 1,
      elevation: 12,
      ...shadowOverlay(C),
    },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.sm,
      minHeight: Space.minTouch,
      paddingHorizontal: Space.md,
    },
    menuItemPressed: { backgroundColor: C.surfaceAlt },
    menuLabel: { flex: 1, ...Type.body, color: C.text },
    filterEmpty: {
      ...Type.body,
      color: C.textSecondary,
      textAlign: "center",
      padding: Space.lg,
    },
    selectionBar: {
      position: "absolute",
      left: Space.md,
      right: Space.md,
      flexDirection: "row",
      alignItems: "center",
      gap: Space.sm,
      minHeight: Space.minTouch,
      paddingHorizontal: Space.md,
      paddingVertical: Space.xs,
      borderRadius: Radius.lg,
      backgroundColor: C.bg,
    },
    selectionCount: { flex: 1, ...Type.secondary, color: C.textSecondary },
    selectionAction: { ...Type.secondary, fontWeight: "600", color: C.primary },
    selectionDelete: { ...Type.secondary, fontWeight: "600", color: C.danger },
    selectionDisabled: { color: C.textDisabled },
    removeDateButton: {
      minWidth: Space.minTouch,
      minHeight: Space.minTouch,
      alignItems: "center",
      justifyContent: "center",
    },
    repeatField: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: Space.xs,
      minHeight: Space.minTouch,
      backgroundColor: C.surface,
      borderRadius: Radius.md,
      paddingHorizontal: Space.md,
      paddingVertical: Space.sm,
      borderWidth: 1,
      borderColor: C.border,
    },
    repeatFieldOpen: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
    },
    repeatFieldText: {
      flex: 1,
      ...Type.navTitle,
      color: C.text,
    },
    sheet: {
      backgroundColor: C.surface,
      borderTopLeftRadius: Radius.sheet,
      borderTopRightRadius: Radius.sheet,
    },
    sheetBody: { padding: Space.md, paddingBottom: Space.xl, gap: Space.xs },
    pickerSheet: {
      backgroundColor: C.bg,
      borderTopLeftRadius: Radius.xl,
      borderTopRightRadius: Radius.xl,
    },
  });
}
