import { StyleSheet } from "react-native";

import type { Theme } from "@/lib/theme";

export function makeTodosStyles(C: Theme) {
  return StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.bg,
  },
  topBar: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  topBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: C.primaryLight,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 8,
  },
  topBtnText: { fontSize: 15, fontWeight: "700", color: C.primary },
  dayHeading: {
    fontSize: 16,
    fontWeight: "700",
    color: C.text,
    marginTop: 4,
    marginBottom: 8,
  },
  topBtnSolo: { flex: 1 },
  newListLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 16,
  },
  newListLinkText: { fontSize: 15, fontWeight: "600", color: C.primary },
  list: { flex: 1 },
  listEmpty: { flexGrow: 1 },
  section: {
    paddingTop: 8,
    paddingBottom: 4,
  },
  sectionHeading: {
    fontSize: 12,
    fontWeight: "700",
    color: C.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 4,
  },
  sectionEmpty: {
    fontSize: 14,
    color: C.textTertiary,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  todoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  todoRowHighlighted: {
    backgroundColor: C.primaryLight,
  },
  swipeContainer: {
    overflow: "hidden",
  },
  swipeDeleteAction: {
    width: 80,
    backgroundColor: C.danger,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  swipeDeleteText: {
    fontSize: 12,
    fontWeight: "600",
    color: C.onPrimary,
  },
  checkbox: { padding: 2 },
  todoMain: { flex: 1, gap: 4 },
  todoText: { fontSize: 16, lineHeight: 22, color: C.text },
  dueLabel: { fontSize: 12, fontWeight: "600" },
  dueOverdue: { color: C.danger },
  dueToday: { color: C.primary },
  dueSoon: { color: C.textSecondary },
  overlapLabel: { fontSize: 12, fontWeight: "500", color: C.danger },
  overlapNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 12,
    padding: 10,
    borderRadius: 10,
    backgroundColor: C.dangerLight,
  },
  overlapNoteText: { flex: 1, fontSize: 13, lineHeight: 18, color: C.danger },
  pickerOverlapNote: { marginHorizontal: 16, marginBottom: 8 },
  projectLinked: { fontSize: 12, fontWeight: "500", color: C.textSecondary },
  dueBtn: { padding: 2 },
  todoDone: {
    color: C.textTertiary,
    textDecorationLine: "line-through",
  },
  formLabel: { fontSize: 14, fontWeight: "600", color: C.textSecondary },
  fieldGap: { marginTop: 16 },
  titleInput: {
    fontSize: 17,
    fontWeight: "600",
    color: C.text,
    backgroundColor: C.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  dateChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: C.primaryLight,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignSelf: "flex-start",
  },
  dateChipText: { fontSize: 15, fontWeight: "600", color: C.text },
  sheet: {
    backgroundColor: C.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  sheetTitle: { fontSize: 17, fontWeight: "700", color: C.text },
  sheetCancel: { fontSize: 16, color: C.textSecondary },
  sheetSave: { fontSize: 16, fontWeight: "700", color: C.primary },
  sheetSaveDisabled: { opacity: 0.4 },
  sheetBody: { padding: 16, paddingBottom: 32, gap: 8 },
  groupOptions: { gap: 4 },
  groupOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  groupOptionSelected: { backgroundColor: C.primaryLight, borderRadius: 8 },
  groupOptionText: { fontSize: 15, color: C.text },
  pickerSheet: {
    backgroundColor: C.bg,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  pickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  pickerTitle: { fontSize: 16, fontWeight: "700", color: C.text },
  pickerCancel: { fontSize: 16, color: C.textSecondary },
  pickerDone: { fontSize: 16, fontWeight: "700", color: C.primary },
  empty: {
    alignItems: "center",
    paddingTop: 56,
    paddingHorizontal: 32,
    paddingBottom: 24,
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryLight,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: C.text,
    marginBottom: 4,
    textAlign: "center",
  },
  emptyPrimaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: C.primaryLight,
  },
  emptyPrimaryBtnText: { fontSize: 16, fontWeight: "700", color: C.primary },
  emptyBody: {
    fontSize: 14,
    color: C.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  });
}
