import { StyleSheet } from "react-native";

import { Radius } from "@/lib/radius";
import { Space } from "@/lib/space";
import type { Theme } from "@/lib/theme";
import { Type } from "@/lib/type";

export function makeTodosStyles(C: Theme) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: C.bg },
    center: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: C.bg,
    },
    topBar: {
      flexDirection: "row",
      gap: Space.sm,
      paddingHorizontal: Space.md,
      paddingVertical: Space.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: C.border,
    },
    topBtn: { flex: 1 },
    dayHeading: {
      ...Type.body,
      fontWeight: "700",
      color: C.text,
      marginTop: Space.xxs,
      marginBottom: Space.xs,
    },
    list: { flex: 1 },
    listEmpty: { flexGrow: 1 },
    section: {
      paddingTop: Space.xs,
      paddingBottom: Space.xxs,
    },
    sectionHeading: {
      ...Type.caption,
      fontSize: 12,
      fontWeight: "700",
      color: C.textTertiary,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      paddingHorizontal: Space.md,
      paddingTop: Space.sm,
      paddingBottom: Space.xxs,
    },
    sectionEmpty: {
      ...Type.label,
      fontWeight: "400",
      color: C.textTertiary,
      paddingHorizontal: Space.md,
      paddingBottom: Space.sm,
    },
    todoRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.sm,
      paddingHorizontal: Space.md,
      paddingVertical: Space.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: C.border,
    },
    todoRowHighlighted: {
      backgroundColor: C.primaryLight,
    },
    swipeContainer: {
      overflow: "hidden",
    },
    swipeDeleteAction: {
      width: 80,
      backgroundColor: C.danger,
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
    },
    swipeDeleteText: {
      fontSize: 12,
      fontWeight: "600",
      color: C.onPrimary,
    },
    checkbox: { padding: 2 },
    todoMain: { flex: 1, gap: Space.xxs },
    todoText: { ...Type.body, color: C.text },
    dueLabel: { fontSize: 12, fontWeight: "600" },
    dueOverdue: { color: C.danger },
    dueToday: { color: C.primary },
    dueSoon: { color: C.textSecondary },
    overlapLabel: { fontSize: 12, fontWeight: "500", color: C.danger },
    overlapNote: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: Space.xxs,
      marginTop: Space.sm,
      padding: Space.sm,
      borderRadius: Radius.sm,
      backgroundColor: C.dangerLight,
    },
    overlapNoteText: { flex: 1, ...Type.caption, fontWeight: "400", lineHeight: 18, color: C.danger },
    pickerOverlapNote: { marginHorizontal: Space.md, marginBottom: Space.xs },
    projectLinked: { fontSize: 12, fontWeight: "500", color: C.textSecondary },
    dueBtn: { padding: 2 },
    todoDone: {
      color: C.textTertiary,
      textDecorationLine: "line-through",
    },
    formLabel: { ...Type.label, color: C.textSecondary },
    fieldGap: { marginTop: Space.md },
    titleInput: {
      fontSize: 17,
      fontWeight: "600",
      color: C.text,
      backgroundColor: C.surface,
      borderRadius: Radius.md,
      paddingHorizontal: Space.md,
      paddingVertical: Space.sm,
      borderWidth: 1,
      borderColor: C.border,
    },
    dateChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
      backgroundColor: C.primaryLight,
      borderRadius: Radius.sm,
      paddingHorizontal: Space.sm,
      paddingVertical: Space.sm,
      alignSelf: "flex-start",
    },
    dateChipText: { ...Type.secondary, fontWeight: "600", color: C.text },
    sheet: {
      backgroundColor: C.surface,
      borderTopLeftRadius: Radius.sheet,
      borderTopRightRadius: Radius.sheet,
    },
    sheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: Space.md,
      paddingVertical: Space.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: C.border,
    },
    sheetTitle: { fontSize: 17, fontWeight: "700", color: C.text },
    sheetCancel: { ...Type.body, color: C.textSecondary },
    sheetSave: { ...Type.body, fontWeight: "700", color: C.primary },
    sheetSaveDisabled: { opacity: 0.4 },
    sheetBody: { padding: Space.md, paddingBottom: Space.xl, gap: Space.xs },
    groupOptions: { gap: Space.xxs },
    groupOption: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
      paddingVertical: Space.xs,
      paddingHorizontal: Space.xxs,
    },
    groupOptionSelected: { backgroundColor: C.primaryLight, borderRadius: Radius.xs },
    groupOptionText: { ...Type.secondary, color: C.text },
    pickerSheet: {
      backgroundColor: C.bg,
      borderTopLeftRadius: Radius.xl,
      borderTopRightRadius: Radius.xl,
    },
    pickerHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: Space.md,
      paddingVertical: Space.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: C.border,
    },
    pickerTitle: { ...Type.body, fontWeight: "700", color: C.text },
    pickerCancel: { ...Type.body, color: C.textSecondary },
    pickerDone: { ...Type.body, fontWeight: "700", color: C.primary },
  });
}
