# ruff: noqa: RUF001 -- textbook formulas use minus signs, multiplication signs and Greek.
"""Chemistry laws that are one line of arithmetic, each declared once.

A row is the whole operation: its catalog identity (law name and formula), the arithmetic,
and how its answer reads (the given rows and the substitution). The arithmetic is a
``services.law_binding`` expression in the solver's parameter names, which may name
``R_atm``, ``F`` and ``N_A``; nothing is executed. One generic solver (``solvers/formula.py``)
answers every row, so a new law of this kind is one entry.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class FormulaLaw:
    op: str
    kind: str
    law_name: str
    formula: str
    find: str
    # The answer's symbol and unit: "m" in "g".
    result: str
    unit: str
    expression: str
    # Each given: parameter, label as printed, unit as printed. A label, the result and a
    # substitution row may name the intent's "{formula}" and "{target}".
    given: tuple[tuple[str, str, str], ...]
    # Substitution rows: "{name}" is a given's value as typed with its unit ("0.500 L"), and
    # "{name.value}" the bare number, for a row written in numbers alone.
    substitution: tuple[str, ...]
    # Givens that may be negative (an enthalpy); every other one must be positive.
    signed: frozenset[str] = frozenset()
    # Givens that may be zero (an empty solute) but not negative.
    non_negative: frozenset[str] = frozenset()
    # (value, ceiling): the value may not exceed the ceiling.
    not_above: tuple[tuple[str, str], ...] = ()


def _law(
    op: str,
    kind: str,
    law_name: str,
    formula: str,
    find: str,
    result: tuple[str, str],
    expression: str,
    given: tuple[tuple[str, str, str], ...],
    *substitution: str,
    signed: frozenset[str] = frozenset(),
    non_negative: frozenset[str] = frozenset(),
    not_above: tuple[tuple[str, str], ...] = (),
) -> FormulaLaw:
    return FormulaLaw(
        op,
        kind,
        law_name,
        formula,
        find,
        *result,
        expression,
        given,
        substitution,
        signed,
        non_negative,
        not_above,
    )


FORMULA_LAWS: dict[str, FormulaLaw] = {
    law.op: law
    for law in (
        _law(
            "solution_mass",
            "solutions",
            "Mass from molarity",
            "m = cVM",
            "Mass of solute, m",
            ("m", "g"),
            "concentration*volume_l*molar_mass",
            (
                ("concentration", "c", "mol/L"),
                ("volume_l", "V", "L"),
                ("molar_mass", "M({formula})", "g/mol"),
            ),
            "m = ({concentration})({volume_l})({molar_mass})",
        ),
        _law(
            "molality_from_mass",
            "solutions",
            "Molality",
            "b = (m_solute / M) / m_solvent",
            "Molality, b",
            ("b", "mol/kg"),
            "solute_mass/molar_mass/solvent_kg",
            (
                ("solute_mass", "m(solute)", "g"),
                ("molar_mass", "M({formula})", "g/mol"),
                ("solvent_kg", "m(solvent)", "kg"),
            ),
            "b = ({solute_mass} / {molar_mass}) / {solvent_kg}",
        ),
        _law(
            "mass_percent_solvent",
            "solutions",
            "Mass percent",
            "mass % = m_solute / (m_solute + m_solvent) × 100",
            "Mass percent",
            ("Mass percent", "%"),
            "solute_mass/(solute_mass + solvent_mass)*100",
            (("solute_mass", "solute mass", "g"), ("solvent_mass", "solvent mass", "g")),
            "mass % = {solute_mass} / ({solute_mass} + {solvent_mass}) × 100",
        ),
        _law(
            "parts_per_million",
            "solutions",
            "Parts per million",
            "ppm = m_solute / m_solution × 10^6",
            "Concentration, ppm",
            ("ppm", "ppm"),
            "solute_mass/solution_mass*1e6",
            (("solute_mass", "m(solute)", "g"), ("solution_mass", "m(solution)", "g")),
            "ppm = {solute_mass} / {solution_mass} × 10^6",
            non_negative=frozenset({"solute_mass"}),
            not_above=(("solute_mass", "solution_mass"),),
        ),
        _law(
            "parts_per_billion",
            "solutions",
            "Parts per billion",
            "ppb = m_solute / m_solution × 10^9",
            "Concentration, ppb",
            ("ppb", "ppb"),
            "solute_mass/solution_mass*1e9",
            (("solute_mass", "m(solute)", "g"), ("solution_mass", "m(solution)", "g")),
            "ppb = {solute_mass} / {solution_mass} × 10^9",
            non_negative=frozenset({"solute_mass"}),
            not_above=(("solute_mass", "solution_mass"),),
        ),
        _law(
            "volume_percent",
            "solutions",
            "Volume percent",
            "volume % = V_solute / V_solution × 100",
            "Volume percent",
            ("Volume percent", "%"),
            "solute_volume/solution_volume*100",
            (("solute_volume", "V(solute)", "mL"), ("solution_volume", "V(solution)", "mL")),
            "volume % = {solute_volume} / {solution_volume} × 100",
        ),
        _law(
            "mass_volume_percent",
            "solutions",
            "Mass/volume percent",
            "mass/volume % = m_solute / V_solution × 100",
            "Mass/volume percent",
            ("Mass/volume percent", "%"),
            "solute_mass/solution_volume*100",
            (("solute_mass", "m(solute)", "g"), ("solution_volume", "V(solution)", "mL")),
            "mass/volume % = {solute_mass} / {solution_volume} × 100",
        ),
        _law(
            "particles_to_mass",
            "amounts",
            "Avogadro relation",
            "m = (N / Nₐ)M",
            "Mass, m",
            ("m", "g"),
            "particles/N_A*molar_mass",
            (("particles", "N", ""), ("molar_mass", "M({formula})", "g/mol")),
            "m = [{particles} / (6.022 × 10^23 mol⁻¹)]({molar_mass})",
        ),
        _law(
            "mole_fraction",
            "solutions",
            "Mole fraction",
            "χA = nA / (nA + nB)",
            "Mole fraction, χ",
            ("χ", ""),
            "moles_a/(moles_a + moles_b)",
            (("moles_a", "n(A)", "mol"), ("moles_b", "n(B)", "mol")),
            "χA = {moles_a} / ({moles_a} + {moles_b})",
        ),
        _law(
            "binary_vapor_pressure",
            "solutions",
            "Ideal binary vapor pressure",
            "P = X_A P_A° + X_B P_B°",
            "Total vapor pressure, P",
            ("P", "atm"),
            "mole_fraction_a*pressure_a + mole_fraction_b*pressure_b",
            (
                ("mole_fraction_a", "X(A)", ""),
                ("pressure_a", "P°(A)", "atm"),
                ("mole_fraction_b", "X(B)", ""),
                ("pressure_b", "P°(B)", "atm"),
            ),
            "P = {mole_fraction_a.value} × {pressure_a} + {mole_fraction_b.value} × {pressure_b}",
            non_negative=frozenset({"mole_fraction_a", "mole_fraction_b"}),
        ),
        _law(
            "gas_density",
            "gases",
            "Ideal gas density",
            "d = PM / RT",
            "Density, d",
            ("d", "g/L"),
            "pressure*molar_mass/(R_atm*temperature)",
            (
                ("pressure", "P", "atm"),
                ("molar_mass", "M({formula})", "g/mol"),
                ("temperature", "T", "K"),
            ),
            "d = ({pressure})({molar_mass}) / [(0.082057 L·atm/(mol·K))({temperature})]",
        ),
        _law(
            "molar_mass_from_density",
            "gases",
            "Ideal gas density",
            "M = dRT / P",
            "Molar mass, M",
            ("M", "g/mol"),
            "density*R_atm*temperature/pressure",
            (
                ("density", "d", "g/L"),
                ("temperature", "T", "K"),
                ("pressure", "P", "atm"),
            ),
            "M = ({density})(0.082057 L·atm/(mol·K))({temperature}) / {pressure}",
        ),
        _law(
            "percent_ionization",
            "acid_base",
            "Percent ionization",
            "% ionization = [H+] / C × 100",
            "Percent ionization",
            ("Percent ionization", "%"),
            "(-ka + sqrt(ka**2 + 4*ka*concentration))/2/concentration*100",
            (("concentration", "C", "mol/L"), ("ka", "Ka", "")),
            # The quadratic is written in bare numbers; its x is a concentration in mol/L.
            "x = [−{ka.value} + √(({ka.value})^2 + 4({ka.value})({concentration.value}))] / 2",
            "% ionization = x / {concentration} × 100",
        ),
        _law(
            "reaction_heat",
            "thermochemistry",
            "Enthalpy of a reaction amount",
            "q = nΔH",
            "Heat, q",
            ("q", "kJ"),
            "moles*enthalpy",
            (("moles", "n", "mol"), ("enthalpy", "ΔH", "kJ/mol")),
            "q = ({moles})({enthalpy})",
            signed=frozenset({"enthalpy"}),
        ),
        _law(
            "electrolysis_time",
            "electrochemistry",
            "Faraday's law of electrolysis",
            "t = mnF / (IM)",
            "Time, t",
            ("t", "s"),
            "mass*electrons*F/(current*molar_mass)",
            (
                ("mass", "m", "g"),
                ("electrons", "n", ""),
                ("current", "I", "A"),
                ("molar_mass", "M", "g/mol"),
            ),
            "t = ({mass})({electrons})(96485 C/mol) / [({current})({molar_mass})]",
        ),
        _law(
            "titration_concentration",
            "acid_base",
            "Neutralization",
            "C₂ = C₁V₁ × ratio / V₂",
            "Unknown concentration, C₂",
            ("C₂", "mol/L"),
            "known_concentration*known_volume*ratio/unknown_volume",
            (
                ("known_concentration", "C₁", "mol/L"),
                ("known_volume", "V₁", "L"),
                ("unknown_volume", "V₂", "L"),
                ("ratio", "mole ratio", ""),
            ),
            "C₂ = ({known_concentration})({known_volume})({ratio}) / {unknown_volume}",
        ),
        _law(
            "graham_ratio",
            "gases",
            "Graham's law",
            "r₁ / r₂ = √(M₂ / M₁)",
            "Ratio of effusion rates",
            ("rate({formula}) / rate({target})", ""),
            "sqrt(molar_mass_b/molar_mass_a)",
            (
                ("molar_mass_a", "M({formula})", "g/mol"),
                ("molar_mass_b", "M({target})", "g/mol"),
            ),
            "rate({formula}) / rate({target}) = √({molar_mass_b} / {molar_mass_a})",
        ),
        _law(
            "element_mass",
            "amounts",
            "Mass of an element in a sample",
            "m(X) = m × nA(X) / M",
            "Mass of the element",
            ("m({target})", "g"),
            "sample_mass*count*atomic_mass/molar_mass",
            (
                ("sample_mass", "m({formula})", "g"),
                ("count", "atoms of {target} in {formula}", ""),
                ("atomic_mass", "A({target})", "g/mol"),
                ("molar_mass", "M({formula})", "g/mol"),
            ),
            "m({target}) = ({sample_mass})({count})({atomic_mass}) / {molar_mass}",
        ),
        _law(
            "vant_hoff_constant",
            "equilibrium",
            "van 't Hoff equation",
            "ln(K2/K1) = −ΔH°/R (1/T2 − 1/T1)",
            "Equilibrium constant, K2",
            ("K2", ""),
            "k1*exp(-enthalpy*1000/R_J*(1/t2 - 1/t1))",
            (
                ("k1", "K1", ""),
                ("t1", "T1", "K"),
                ("t2", "T2", "K"),
                ("enthalpy", "ΔH°", "kJ/mol"),
            ),
            "K2 = {k1.value} × exp[−({enthalpy.value} × 10^3) / (8.314 J/(mol·K))"
            " × (1/{t2.value} − 1/{t1.value})]",
            signed=frozenset({"enthalpy"}),
        ),
        _law(
            "vant_hoff_enthalpy",
            "equilibrium",
            "van 't Hoff equation",
            "ΔH° = −R ln(K2/K1) / (1/T2 − 1/T1)",
            "Standard enthalpy change, ΔH°",
            ("ΔH°", "kJ/mol"),
            "-(R_J*log(k2/k1)/(1/t2 - 1/t1))/1000",
            (
                ("k1", "K1", ""),
                ("t1", "T1", "K"),
                ("k2", "K2", ""),
                ("t2", "T2", "K"),
            ),
            "ΔH° = [−(8.314 J/(mol·K)) ln({k2.value}/{k1.value})"
            " / (1/{t2.value} − 1/{t1.value})] / 1000",
        ),
        _law(
            "gibbs_from_equilibrium",
            "equilibrium",
            "Standard Gibbs energy and the equilibrium constant",
            "ΔG° = −RT ln K",
            "Standard Gibbs energy, ΔG°",
            ("ΔG°", "kJ/mol"),
            "-(R_J*temperature*log(k))/1000",
            (("k", "K", ""), ("temperature", "T", "K")),
            "ΔG° = −(8.314 J/(mol·K))({temperature.value}) ln({k.value}) / 1000",
        ),
        _law(
            "equilibrium_from_gibbs",
            "equilibrium",
            "Standard Gibbs energy and the equilibrium constant",
            "K = exp(−ΔG°/RT)",
            "Equilibrium constant, K",
            ("K", ""),
            "exp(-gibbs*1000/(R_J*temperature))",
            (("gibbs", "ΔG°", "kJ/mol"), ("temperature", "T", "K")),
            "K = exp[−({gibbs.value} × 10^3)/((8.314 J/(mol·K))({temperature.value}))]",
            signed=frozenset({"gibbs"}),
        ),
        _law(
            "ionic_strength",
            "solutions",
            "Ionic strength",
            "I = ½ (c₁z₁² + c₂z₂²)",
            "Ionic strength, I",
            ("I", "mol/L"),
            "0.5*(concentration_1*charge_1**2 + concentration_2*charge_2**2)",
            (
                ("concentration_1", "c(cation)", "mol/L"),
                ("charge_1", "z(cation)", ""),
                ("concentration_2", "c(anion)", "mol/L"),
                ("charge_2", "z(anion)", ""),
            ),
            "I = ½ [({concentration_1})({charge_1})^2 + ({concentration_2})({charge_2})^2]",
            signed=frozenset({"charge_1", "charge_2"}),
        ),
        _law(
            "absorbance_transmittance",
            "spectroscopy",
            "Absorbance from transmittance",
            "A = −log10(T)",
            "Absorbance, A",
            ("A", ""),
            "-log(transmittance)/log(10)",
            (("transmittance", "T", ""),),
            "A = −log10({transmittance.value})",
        ),
        _law(
            "absorbance_percent_transmittance",
            "spectroscopy",
            "Absorbance from percent transmittance",
            "A = 2 − log10(%T)",
            "Absorbance, A",
            ("A", ""),
            "2 - log(percent_transmittance)/log(10)",
            (("percent_transmittance", "%T", "%"),),
            "A = 2 − log10({percent_transmittance.value})",
        ),
        _law(
            "kirchhoff",
            "thermochemistry",
            "Kirchhoff's law",
            "ΔH(T2) = ΔH(T1) + ΔCp ΔT",
            "Enthalpy at the second temperature, ΔH(T2)",
            ("ΔH(T2)", "kJ/mol"),
            "enthalpy + heat_capacity*(t2 - t1)",
            (
                ("enthalpy", "ΔH(T1)", "kJ/mol"),
                ("t1", "T1", "K"),
                ("t2", "T2", "K"),
                ("heat_capacity", "ΔCp", "kJ/(mol·K)"),
            ),
            "ΔH(T2) = {enthalpy.value} + ({heat_capacity.value})({t2.value} − {t1.value})",
            signed=frozenset({"enthalpy", "heat_capacity"}),
        ),
        _law(
            "optical_purity",
            "organic",
            "Optical purity",
            "optical purity = |α_obs| / |α_pure| × 100",
            "Optical purity",
            ("Optical purity", "%"),
            "sqrt(observed**2)/sqrt(pure**2)*100",
            (
                ("observed", "α(observed)", ""),
                ("pure", "α(pure)", ""),
            ),
            "optical purity = |{observed.value}| / |{pure.value}| × 100",
            signed=frozenset({"observed", "pure"}),
        ),
        _law(
            "partition_coefficient",
            "solutions",
            "Partition coefficient",
            "KD = [A]org / [A]aq",
            "Partition coefficient, KD",
            ("KD", ""),
            "organic/aqueous",
            (
                ("organic", "[A]org", "mol/L"),
                ("aqueous", "[A]aq", "mol/L"),
            ),
            "KD = {organic} / {aqueous}",
        ),
        _law(
            "vant_hoff_factor",
            "solutions",
            "van 't Hoff factor",
            "i = ΔT / (K m)",
            "van 't Hoff factor, i",
            ("i", ""),
            "delta_t/(constant*molality)",
            (
                ("delta_t", "ΔT", "°C"),
                ("constant", "K", "°C/m"),
                ("molality", "m", "mol/kg"),
            ),
            "i = {delta_t.value} / [({constant.value})({molality.value})]",
        ),
        _law(
            "hydrogen_deficiency",
            "organic",
            "Index of hydrogen deficiency",
            "IHD = (2C + 2 + N − H − X) / 2",
            "Index of hydrogen deficiency, IHD",
            ("IHD", ""),
            "(2*carbon + 2 + nitrogen - hydrogen - halogen)/2",
            (
                ("carbon", "C", ""),
                ("hydrogen", "H", ""),
                ("nitrogen", "N", ""),
                ("halogen", "X", ""),
            ),
            "IHD = (2({carbon.value}) + 2 + {nitrogen.value}"
            " − {hydrogen.value} − {halogen.value}) / 2",
            non_negative=frozenset({"hydrogen", "nitrogen", "halogen"}),
        ),
        _law(
            "specific_rotation",
            "organic",
            "Specific rotation",
            "[α] = α / (l c)",
            "Specific rotation, [α]",
            ("[α]", "°·mL/(g·dm)"),
            "observed/(path_length*concentration)",
            (
                ("observed", "α", "°"),
                ("path_length", "l", "dm"),
                ("concentration", "c", "g/mL"),
            ),
            "[α] = {observed.value} / [({path_length.value})({concentration.value})]",
            signed=frozenset({"observed"}),
        ),
        _law(
            "enantiomeric_excess",
            "organic",
            "Enantiomeric excess",
            "ee = |major − minor| / (major + minor) × 100",
            "Enantiomeric excess, ee",
            ("ee", "%"),
            "sqrt((major-minor)**2)/(major+minor)*100",
            (("major", "major", "mol"), ("minor", "minor", "mol")),
            "ee = |{major.value} − {minor.value}| / ({major.value} + {minor.value}) × 100",
            non_negative=frozenset({"minor"}),
        ),
        _law(
            "gibbs_reaction",
            "thermochemistry",
            "Gibbs energy at a reaction quotient",
            "ΔG = ΔG° + RT ln Q",
            "Gibbs energy, ΔG",
            ("ΔG", "kJ/mol"),
            "gibbs_standard + R_J*temperature*log(quotient)/1000",
            (
                ("gibbs_standard", "ΔG°", "kJ/mol"),
                ("temperature", "T", "K"),
                ("quotient", "Q", ""),
            ),
            "ΔG = {gibbs_standard.value} + (8.314 J/(mol·K))({temperature.value})"
            " ln({quotient.value}) / 1000",
            signed=frozenset({"gibbs_standard"}),
        ),
        _law(
            "van_der_waals_pressure",
            "gases",
            "van der Waals pressure",
            "P = nRT/(V − nb) − an²/V²",
            "Pressure, P",
            ("P", "atm"),
            "n*R_atm*temperature/(volume - n*b) - a*n**2/volume**2",
            (
                ("n", "n", "mol"),
                ("temperature", "T", "K"),
                ("volume", "V", "L"),
                ("a", "a", "L²·atm/mol²"),
                ("b", "b", "L/mol"),
            ),
            "P = ({n.value})R({temperature.value}) / ({volume.value} − ({n.value})({b.value}))"
            " − ({a.value})({n.value})² / ({volume.value})²",
            non_negative=frozenset({"a", "b"}),
        ),
        _law(
            "compressibility",
            "gases",
            "Compressibility factor",
            "Z = PV/nRT",
            "Compressibility factor, Z",
            ("Z", ""),
            "pressure*volume/(n*R_atm*temperature)",
            (
                ("pressure", "P", "atm"),
                ("volume", "V", "L"),
                ("n", "n", "mol"),
                ("temperature", "T", "K"),
            ),
            "Z = ({pressure.value})({volume.value}) / [({n.value})R({temperature.value})]",
        ),
        _law(
            "phase_rule",
            "thermochemistry",
            "Gibbs phase rule",
            "F = C − P + 2",
            "Degrees of freedom, F",
            ("F", ""),
            "components - phases + 2",
            (("components", "C", ""), ("phases", "P", "")),
            "F = {components.value} − {phases.value} + 2",
        ),
        _law(
            "mixture_concentration",
            "solutions",
            "Concentration after mixing",
            "C = (C₁V₁ + C₂V₂) / (V₁ + V₂)",
            "Concentration, C",
            ("C", "mol/L"),
            "(concentration_1*volume_1 + concentration_2*volume_2)/(volume_1 + volume_2)",
            (
                ("concentration_1", "C1", "mol/L"),
                ("volume_1", "V1", "L"),
                ("concentration_2", "C2", "mol/L"),
                ("volume_2", "V2", "L"),
            ),
            "C = ({concentration_1.value}×{volume_1.value}"
            " + {concentration_2.value}×{volume_2.value}) / ({volume_1.value} + {volume_2.value})",
            non_negative=frozenset({"concentration_1", "concentration_2"}),
        ),
        _law(
            "entropy_volume",
            "thermochemistry",
            "Entropy change of an isothermal volume change",
            "ΔS = nR ln(V2/V1)",
            "Entropy change, ΔS",
            ("ΔS", "J/K"),
            "n*R_J*log(volume_2/volume_1)",
            (
                ("n", "n", "mol"),
                ("volume_1", "V1", "L"),
                ("volume_2", "V2", "L"),
            ),
            "ΔS = ({n.value})R ln({volume_2.value}/{volume_1.value})",
        ),
        _law(
            "entropy_temperature",
            "thermochemistry",
            "Entropy change at constant pressure",
            "ΔS = n Cp ln(T2/T1)",
            "Entropy change, ΔS",
            ("ΔS", "J/K"),
            "n*heat_capacity*log(t2/t1)",
            (
                ("n", "n", "mol"),
                ("heat_capacity", "Cp", "J/(mol·K)"),
                ("t1", "T1", "K"),
                ("t2", "T2", "K"),
            ),
            "ΔS = ({n.value})({heat_capacity.value}) ln({t2.value}/{t1.value})",
        ),
        _law(
            "clapeyron",
            "thermochemistry",
            "Clapeyron equation",
            "ΔH = T ΔV ΔP / ΔT",
            "Enthalpy change, ΔH",
            ("ΔH", "kJ/mol"),
            "temperature*delta_v*delta_p/(delta_t*1000)",
            (
                ("temperature", "T", "K"),
                ("delta_v", "ΔV", "m³/mol"),
                ("delta_p", "ΔP", "Pa"),
                ("delta_t", "ΔT", "K"),
            ),
            "ΔH = ({temperature.value})({delta_v.value})({delta_p.value})"
            " / [({delta_t.value})(1000)]",
            signed=frozenset({"delta_v", "delta_p", "delta_t"}),
        ),
        _law(
            "langmuir",
            "analytical",
            "Langmuir isotherm",
            "θ = KP / (1 + KP)",
            "Surface coverage, θ",
            ("θ", ""),
            "affinity*pressure/(1 + affinity*pressure)",
            (
                ("affinity", "K", "1/atm"),
                ("pressure", "P", "atm"),
            ),
            "θ = ({affinity.value})({pressure.value}) / [1 + ({affinity.value})({pressure.value})]",
        ),
        _law(
            "eyring",
            "kinetics",
            "Eyring equation",
            "k = (k_B T/h) exp(ΔS‡/R) exp(−ΔH‡/RT)",
            "Rate constant, k",
            ("k", "1/s"),
            "(k_B*temperature/h)*exp(delta_s/R_J)*exp(-delta_h/(R_J*temperature))",
            (
                ("temperature", "T", "K"),
                ("delta_h", "ΔH‡", "J/mol"),
                ("delta_s", "ΔS‡", "J/(mol·K)"),
            ),
            "k = (k_B {temperature.value} / h) exp({delta_s.value}/R)"
            " exp(−{delta_h.value}/(R {temperature.value}))",
            signed=frozenset({"delta_h", "delta_s"}),
        ),
        _law(
            "crystal_field_stabilization",
            "inorganic",
            "Crystal-field stabilization energy",
            "CFSE = (−0.4 n_t2g + 0.6 n_eg) Δo",
            "Crystal-field stabilization energy, CFSE",
            ("CFSE", "kJ/mol"),
            "(-0.4*n_t2g + 0.6*n_eg)*delta_o",
            (
                ("n_t2g", "n(t2g)", ""),
                ("n_eg", "n(eg)", ""),
                ("delta_o", "Δo", "kJ/mol"),
            ),
            "CFSE = (−0.4({n_t2g.value}) + 0.6({n_eg.value}))({delta_o.value})",
            non_negative=frozenset({"n_t2g", "n_eg"}),
        ),
        _law(
            "molar_conductivity",
            "analytical",
            "Molar conductivity",
            "Λm = κ / c",
            "Molar conductivity, Λm",
            ("Λm", "S·m²/mol"),
            "conductivity/concentration",
            (
                ("conductivity", "κ", "S/m"),
                ("concentration", "c", "mol/m³"),
            ),
            "Λm = {conductivity.value} / {concentration.value}",
        ),
    )
}
