"""The unit spellings a chemistry question writes after a number, for the shared binder.

A closed table, as physics keeps (``services.law_binding.units``). Chemistry reads a
capital ``M`` as mol/L and a lowercase ``m`` as mol/kg (molal). A bare ``C`` is not a
unit here: in ``2 C + O2`` it is carbon, so a Celsius reading needs its degree sign.
"""

from __future__ import annotations

from app.services.law_binding.units import UnitTable

# Case-sensitive symbols, matched exactly as written.
_SYMBOLS: dict[str, str] = {
    "g": "gram",
    "kg": "kilogram",
    "mg": "milligram",
    "L": "liter",
    "mL": "milliliter",
    "M": "mole / liter",
    "mM": "millimole / liter",
    "µM": "micromole / liter",
    "μM": "micromole / liter",
    "uM": "micromole / liter",
    "nM": "nanomole / liter",
    "mmol/L": "millimole / liter",
    "m": "mole / kilogram",
    "mol": "mole",
    "K": "kelvin",
    "°C": "degC",
    "° C": "degC",
    "atm": "atmosphere",
    "kPa": "kilopascal",
    "Pa": "pascal",
    "mmHg": "millimeter_Hg",
    "torr": "torr",
    "bar": "bar",
    "s": "second",
    "min": "minute",
    "h": "hour",
    "hr": "hour",
    "A": "ampere",
    "V": "volt",
    "mV": "millivolt",
    "J": "joule",
    "kJ": "kilojoule",
    "cal": "calorie",
    "kcal": "kilocalorie",
    "mmol": "millimole",
    "µmol": "micromole",
    "μmol": "micromole",
    "cm": "centimeter",
    "dm": "decimeter",
    "S/m": "siemens / meter",
    "m^3/mol": "meter ** 3 / mole",
    "m³/mol": "meter ** 3 / mole",
    "1/atm": "1 / atmosphere",
    "atm^-1": "1 / atmosphere",
    "nm": "nanometer",
    "Å": "angstrom",
    "Å": "angstrom",
    "Hz": "hertz",
    "MHz": "megahertz",
    "T": "tesla",
    "Pa·s": "pascal * second",
    "Pa s": "pascal * second",
    "cm^2/s": "centimeter ** 2 / second",
    "cm²/s": "centimeter ** 2 / second",
    "m^2/s": "meter ** 2 / second",
    "m²/s": "meter ** 2 / second",
    "%": "percent",
    "mol/L": "mole / liter",
    "mol/kg": "mole / kilogram",
    "g/mol": "gram / mole",
    # A density: a gas in g/L, a liquid in g/mL.
    "g/L": "gram / liter",
    "g/mL": "gram / milliliter",
    "g/cm³": "gram / centimeter ** 3",
    "g/cm^3": "gram / centimeter ** 3",
    "J/mol": "joule / mole",
    "kJ/mol": "kilojoule / mole",
    "kcal/mol": "kilocalorie / mole",
    "cal/mol": "calorie / mole",
    "J/K": "joule / kelvin",
    "kJ/K": "kilojoule / kelvin",
    # Entropy per mole of reaction.
    "J/mol·K": "joule / mole / kelvin",
    "J/(mol·K)": "joule / mole / kelvin",
    "J/mol/K": "joule / mole / kelvin",
    "J/(mol K)": "joule / mole / kelvin",
    "kJ/mol·K": "kilojoule / mole / kelvin",
    "kJ/(mol·K)": "kilojoule / mole / kelvin",
    # A specific heat.
    "J/g°C": "joule / gram / delta_degC",
    "J/g·°C": "joule / gram / delta_degC",
    "J/(g·°C)": "joule / gram / delta_degC",
    "J/g/°C": "joule / gram / delta_degC",
    "J/(g°C)": "joule / gram / delta_degC",
    "J/g·K": "joule / gram / kelvin",
    "cal/g°C": "calorie / gram / delta_degC",
    "cal/(g·°C)": "calorie / gram / delta_degC",
    "J/(g·K)": "joule / gram / kelvin",
    # A freezing-point or boiling-point constant: degrees per molal.
    "°C/m": "delta_degC * kilogram / mole",
    "°C·kg/mol": "delta_degC * kilogram / mole",
    "°C kg/mol": "delta_degC * kilogram / mole",
    "K·kg/mol": "kelvin * kilogram / mole",
    "K kg/mol": "kelvin * kilogram / mole",
    "K/m": "kelvin * kilogram / mole",
    # Molar absorptivity.
    "L/(mol·cm)": "liter / mole / centimeter",
    "L/mol·cm": "liter / mole / centimeter",
    "L mol⁻¹ cm⁻¹": "liter / mole / centimeter",
    "M⁻¹cm⁻¹": "liter / mole / centimeter",
    "M⁻¹ cm⁻¹": "liter / mole / centimeter",
    "M^-1 cm^-1": "liter / mole / centimeter",
    "M^-1cm^-1": "liter / mole / centimeter",
    # Rate constants of each order.
    "s^-1": "1 / second",
    "s⁻¹": "1 / second",
    "/s": "1 / second",
    "1/s": "1 / second",
    "min^-1": "1 / minute",
    "min⁻¹": "1 / minute",
    "/min": "1 / minute",
    "h^-1": "1 / hour",
    "h⁻¹": "1 / hour",
    "yr^-1": "1 / year",
    "M/s": "mole / liter / second",
    "M s^-1": "mole / liter / second",
    "M s⁻¹": "mole / liter / second",
    "mol/(L·s)": "mole / liter / second",
    "M^-1 s^-1": "liter / mole / second",
    "M^-1s^-1": "liter / mole / second",
    "M⁻¹ s⁻¹": "liter / mole / second",
    "M⁻¹s⁻¹": "liter / mole / second",
    "1/(M·s)": "liter / mole / second",
    "L/(mol·s)": "liter / mole / second",
}

# Spelled-out units, matched without case.
_WORDS: dict[str, str] = {
    "grams": "gram",
    "gram": "gram",
    "kilograms": "kilogram",
    "kilogram": "kilogram",
    "liters": "liter",
    "litres": "liter",
    "liter": "liter",
    "litre": "liter",
    "milliliters": "milliliter",
    "millilitres": "milliliter",
    "milliliter": "milliliter",
    "millilitre": "milliliter",
    "moles": "mole",
    "mole": "mole",
    "molar": "mole / liter",
    "molal": "mole / kilogram",
    "kelvin": "kelvin",
    "degrees celsius": "degC",
    "degrees c": "degC",
    "atmospheres": "atmosphere",
    "atmosphere": "atmosphere",
    "seconds": "second",
    "second": "second",
    "meter": "meter",
    "meters": "meter",
    "angstrom": "angstrom",
    "angstroms": "angstrom",
    "tesla": "tesla",
    "minutes": "minute",
    "minute": "minute",
    "hours": "hour",
    "hour": "hour",
    "years": "year",
    "year": "year",
    "yr": "year",
    "amps": "ampere",
    "amperes": "ampere",
    "volts": "volt",
    "joules": "joule",
    "kilojoules": "kilojoule",
    "calories": "calorie",
    "kilocalories": "kilocalorie",
    "millimolar": "millimole / liter",
    "micromolar": "micromole / liter",
}

CHEMISTRY_UNITS = UnitTable(_SYMBOLS, _WORDS)
