"""How a later one-number chemistry law is named in a question.

The arithmetic lives in ``stated_laws``. ``laws.LAWS`` concatenates these bindings
after the first formula-law table.
"""

from __future__ import annotations

from app.modules.chemistry.law_record import _MOLAR, ChemistryLaw, _law
from app.services.law_binding.spec import var

_PER_MOL = "joule / mole"
_HERTZ = "hertz"
_NM = "nanometer"

STATED_LAW_BINDINGS: tuple[ChemistryLaw, ...] = (
    _law(
        "neutron_count",
        "nuclear",
        ("number of neutrons", "neutron count"),
        "dimensionless",
        (
            var("mass_number", "A", dimensionless=True, words=("mass number",), needs_words=True),
            var(
                "atomic_number",
                "Z",
                dimensionless=True,
                words=("atomic number",),
                needs_words=True,
            ),
        ),
        cues=("neutron",),
    ),
    _law(
        "ion_charge",
        "structure",
        ("ion charge",),
        "dimensionless",
        (
            var(
                "atomic_number",
                "Z",
                dimensionless=True,
                words=("atomic number",),
                needs_words=True,
            ),
            var(
                "electron_count",
                "Ne",
                dimensionless=True,
                words=("electron",),
                needs_words=True,
            ),
        ),
        cues=("ion charge",),
        excludes=("oxidation",),
        nonnegative=False,
    ),
    _law(
        "shell_capacity",
        "structure",
        ("maximum electrons", "shell capacity"),
        "dimensionless",
        (var("shell_n", "n", dimensionless=True, words=("n =", "shell"), needs_words=True),),
        cues=("shell",),
    ),
    _law(
        "bond_order",
        "structure",
        ("bond order",),
        "dimensionless",
        (
            var("bonding", "Nb", dimensionless=True, words=("bonding",), needs_words=True),
            var(
                "antibonding",
                "Na",
                dimensionless=True,
                words=("antibonding",),
                needs_words=True,
            ),
        ),
        cues=("bond order",),
    ),
    _law(
        "wavenumber",
        "spectroscopy",
        ("wavenumber",),
        "1 / centimeter",
        (var("wavelength", "lambda", _NM),),
        cues=("wavenumber",),
    ),
    _law(
        "quantum_yield",
        "spectroscopy",
        ("quantum yield",),
        "dimensionless",
        (
            var("events", "events", dimensionless=True, words=("event",), needs_words=True),
            var("photons", "photons", dimensionless=True, words=("photon",), needs_words=True),
        ),
        cues=("quantum yield",),
    ),
    _law(
        "tetrahedral_splitting",
        "inorganic",
        ("tetrahedral splitting",),
        "kilojoule / mole",
        (
            var(
                "delta_o",
                "do",
                "kilojoule / mole",
                words=("delta_o", "splitting"),
                needs_words=True,
            ),
        ),
        cues=("tetrahedral",),
    ),
    _law(
        "base_buffer_poh",
        "acid_base",
        ("p_oh",),
        "dimensionless",
        (
            var("pkb", "pKb", dimensionless=True, words=("p_kb",), needs_words=True),
            var("conjugate", "[BH+]", _MOLAR, words=("conjugate",), needs_words=True),
            var("base", "[B]", _MOLAR, words=("base",), needs_words=True),
        ),
        cues=("buffer",),
        excludes=("p_ka",),
    ),
    _law(
        "molar_heat",
        "thermochemistry",
        ("molar heat", "heat"),
        "joule",
        (
            var("moles", "n", "mole"),
            var(
                "heat_capacity",
                "C",
                "joule / mole / kelvin",
                words=("molar heat capacity",),
                needs_words=True,
            ),
            var("delta_t", "dT", "kelvin", words=("change",), needs_words=True),
        ),
        cues=("molar heat capacity",),
        nonnegative=False,
    ),
    _law(
        "electron_moles",
        "electrochemistry",
        ("moles of electrons",),
        "mole",
        (var("current", "I", "ampere"), var("time", "t", "second")),
        cues=("moles of electrons",),
    ),
    _law(
        "hill_saturation",
        "biochemistry",
        ("saturation", "hill fraction"),
        "dimensionless",
        (
            var("ligand", "[L]", _MOLAR, words=("ligand",), needs_words=True),
            var("hill_n", "n", dimensionless=True, words=("hill", "n ="), needs_words=True),
            var("dissociation", "Kd", _MOLAR, words=("kd", "dissociation"), needs_words=True),
        ),
        cues=("hill",),
    ),
    _law(
        "freundlich",
        "analytical",
        ("adsorbed amount",),
        "dimensionless",
        (
            var(
                "coefficient",
                "KF",
                dimensionless=True,
                words=("freundlich constant",),
                needs_words=True,
            ),
            var("concentration", "C", _MOLAR),
            var("exponent", "n", dimensionless=True, words=("n =",), needs_words=True),
        ),
        cues=("freundlich",),
    ),
    _law(
        "degree_of_polymerization",
        "organic",
        ("degree of polymerization",),
        "dimensionless",
        (
            var(
                "polymer_mass",
                "Mp",
                "gram / mole",
                words=("polymer",),
                needs_words=True,
            ),
            var(
                "repeat_mass",
                "Mr",
                "gram / mole",
                words=("repeat",),
                needs_words=True,
            ),
        ),
        cues=("repeat",),
    ),
    _law(
        "polydispersity",
        "organic",
        ("polydispersity",),
        "dimensionless",
        (
            var(
                "weight_average",
                "Mw",
                "gram / mole",
                words=("weight-average", "weight average"),
                needs_words=True,
            ),
            var(
                "number_average",
                "Mn",
                "gram / mole",
                words=("number-average", "number average"),
                needs_words=True,
            ),
        ),
        cues=("polydispersity",),
    ),
    _law(
        "carothers",
        "organic",
        ("degree of polymerization",),
        "dimensionless",
        (var("extent", "p", dimensionless=True, words=("extent",), needs_words=True),),
        cues=("carothers", "extent of reaction"),
    ),
    _law(
        "polymerization_rate",
        "kinetics",
        ("polymerization rate",),
        "mole / liter / second",
        (
            var("rate_constant", "kp", "liter / mole / second", words=("rate constant",)),
            var("monomer", "[M]", _MOLAR, words=("monomer",), needs_words=True),
            var("radical", "[R]", _MOLAR, words=("radical",), needs_words=True),
        ),
        cues=("polymerization",),
    ),
    _law(
        "butler_volmer",
        "electrochemistry",
        ("current",),
        "ampere",
        (
            var("exchange", "i0", "ampere", words=("exchange",), needs_words=True),
            var(
                "alpha",
                "alpha",
                dimensionless=True,
                words=("transfer", "alpha"),
                needs_words=True,
            ),
            var(
                "electrons",
                "n",
                dimensionless=True,
                words=("electron", "n ="),
                needs_words=True,
            ),
            var("overpotential", "eta", "volt"),
            var("temperature", "T", "kelvin"),
        ),
        cues=("butler-volmer", "butler volmer"),
        nonnegative=False,
    ),
    _law(
        "tafel",
        "electrochemistry",
        ("overpotential",),
        "volt",
        (
            var("intercept", "a", "volt", words=("intercept",), needs_words=True),
            var("slope", "b", "volt", words=("slope",), needs_words=True),
            var("current", "i", "ampere"),
        ),
        cues=("tafel",),
        nonnegative=False,
    ),
    _law(
        "electrochemical_potential",
        "electrochemistry",
        ("electrochemical potential",),
        _PER_MOL,
        (
            var("chemical_potential", "mu", _PER_MOL, words=("chemical potential",)),
            var(
                "charge_number",
                "z",
                dimensionless=True,
                words=("charge number", "z ="),
                needs_words=True,
            ),
            var("electric_potential", "phi", "volt"),
        ),
        cues=("electrochemical potential",),
        nonnegative=False,
    ),
    _law(
        "chemical_potential",
        "thermochemistry",
        ("chemical potential",),
        _PER_MOL,
        (
            var("standard_potential", "mu0", _PER_MOL, words=("standard",), needs_words=True),
            var("temperature", "T", "kelvin"),
            var("activity", "a", dimensionless=True, words=("activity",), needs_words=True),
        ),
        cues=("chemical potential",),
        excludes=("electrochemical",),
        nonnegative=False,
    ),
    _law(
        "activity",
        "solutions",
        ("activity",),
        "dimensionless",
        (
            var(
                "gamma",
                "gamma",
                dimensionless=True,
                words=("activity coefficient",),
                needs_words=True,
            ),
            var("concentration", "c", _MOLAR, words=("concentration",), needs_words=True),
            var(
                "standard_concentration",
                "c0",
                _MOLAR,
                words=("standard concentration",),
                needs_words=True,
            ),
        ),
        cues=("activity coefficient",),
    ),
    _law(
        "larmor",
        "spectroscopy",
        ("larmor frequency",),
        "1 / second",
        (
            var(
                "gyromagnetic",
                "gamma",
                dimensionless=True,
                words=("gyromagnetic",),
                needs_words=True,
            ),
            var("field", "B", "tesla"),
        ),
        cues=("larmor",),
    ),
    _law(
        "chemical_shift",
        "spectroscopy",
        ("chemical shift",),
        "dimensionless",
        (
            var("sample_freq", "vs", _HERTZ, words=("sample",), needs_words=True),
            var("reference_freq", "vr", _HERTZ, words=("reference",), needs_words=True),
            var("spectrometer_freq", "v0", _HERTZ, words=("spectrometer",), needs_words=True),
        ),
        cues=("chemical shift",),
        nonnegative=False,
    ),
    _law(
        "magnetic_sector",
        "spectroscopy",
        ("mass-to-charge", "mass to charge"),
        "kilogram / coulomb",
        (
            var("field", "B", "tesla"),
            var("radius", "r", "meter", words=("radius",), needs_words=True),
            var("voltage", "V", "volt"),
        ),
        cues=("magnetic sector", "mass spectrometer"),
    ),
    _law(
        "cubic_spacing",
        "inorganic",
        ("interplanar spacing",),
        _NM,
        (
            var("lattice", "a", _NM, words=("lattice",), needs_words=True),
            var("miller_h", "h", dimensionless=True, words=("h =",), needs_words=True),
            var("miller_k", "k", dimensionless=True, words=("k =",), needs_words=True),
            var("miller_l", "l", dimensionless=True, words=("l =",), needs_words=True),
        ),
        cues=("cubic",),
    ),
    _law(
        "lever_alpha",
        "thermochemistry",
        ("alpha fraction",),
        "dimensionless",
        (
            var(
                "alpha_composition",
                "Ca",
                dimensionless=True,
                words=("alpha composition",),
                needs_words=True,
            ),
            var(
                "beta_composition",
                "Cb",
                dimensionless=True,
                words=("beta composition",),
                needs_words=True,
            ),
            var("overall", "C0", dimensionless=True, words=("overall",), needs_words=True),
        ),
        cues=("lever rule",),
    ),
    _law(
        "lever_beta",
        "thermochemistry",
        ("beta fraction",),
        "dimensionless",
        (
            var(
                "alpha_composition",
                "Ca",
                dimensionless=True,
                words=("alpha composition",),
                needs_words=True,
            ),
            var(
                "beta_composition",
                "Cb",
                dimensionless=True,
                words=("beta composition",),
                needs_words=True,
            ),
            var("overall", "C0", dimensionless=True, words=("overall",), needs_words=True),
        ),
        cues=("lever rule",),
    ),
    _law(
        "mean_square_displacement",
        "kinetics",
        ("mean-square displacement", "mean square displacement"),
        "centimeter ** 2",
        (
            var("diffusion", "D", "centimeter ** 2 / second"),
            var("time", "t", "second"),
        ),
        cues=("mean-square", "mean square"),
    ),
    _law(
        "stokes_einstein",
        "kinetics",
        ("diffusion coefficient",),
        "meter ** 2 / second",
        (
            var("temperature", "T", "kelvin"),
            var("viscosity", "eta", "pascal * second"),
            var("radius", "r", _NM),
        ),
        cues=("stokes-einstein", "stokes einstein"),
    ),
    _law(
        "relative_standard_deviation",
        "analytical",
        ("relative standard deviation",),
        "percent",
        (
            var(
                "deviation",
                "s",
                dimensionless=True,
                words=("standard deviation",),
                needs_words=True,
            ),
            var("mean", "mean", dimensionless=True, words=("mean",), needs_words=True),
        ),
        cues=("relative standard deviation",),
    ),
    _law(
        "conjugate_fraction",
        "acid_base",
        ("conjugate fraction",),
        "dimensionless",
        (
            var("ka", "Ka", dimensionless=True, words=("k_a",), needs_words=True),
            var("hydrogen", "[H+]", _MOLAR, words=("ion_h",), needs_words=True),
        ),
        cues=("conjugate fraction",),
    ),
    _law(
        "acid_fraction",
        "acid_base",
        ("acid fraction",),
        "dimensionless",
        (
            var("ka", "Ka", dimensionless=True, words=("k_a",), needs_words=True),
            var("hydrogen", "[H+]", _MOLAR, words=("ion_h",), needs_words=True),
        ),
        cues=("acid fraction",),
        excludes=("conjugate",),
    ),
    _law(
        "conjugate_fraction_ph",
        "acid_base",
        ("conjugate fraction",),
        "dimensionless",
        (
            var("ka", "Ka", dimensionless=True, words=("k_a",), needs_words=True),
            var("ph", "pH", dimensionless=True, words=("p_h",), needs_words=True),
        ),
        cues=("conjugate fraction",),
    ),
    _law(
        "acid_fraction_ph",
        "acid_base",
        ("acid fraction",),
        "dimensionless",
        (
            var("ka", "Ka", dimensionless=True, words=("k_a",), needs_words=True),
            var("ph", "pH", dimensionless=True, words=("p_h",), needs_words=True),
        ),
        cues=("acid fraction",),
        excludes=("conjugate",),
    ),
)
