# ruff: noqa: RUF001 -- textbook formulas use minus signs, multiplication signs and Greek.
"""One-number chemistry laws added after the first formula-law table.

Each row is the same shape as ``formula_laws``: one expression, answered by the same solver.
A missing input declines. ``formula_laws.FORMULA_LAWS`` merges this dict in.
"""

from __future__ import annotations

from app.modules.chemistry.formula_laws import FormulaLaw, _law

_LOG10 = "log(10)"

STATED_LAWS: dict[str, FormulaLaw] = {
    law.op: law
    for law in (
        _law(
            "neutron_count",
            "nuclear",
            "Neutron count",
            "N = A − Z",
            "Number of neutrons, N",
            ("N", ""),
            "mass_number - atomic_number",
            (
                ("mass_number", "A", ""),
                ("atomic_number", "Z", ""),
            ),
            "N = {mass_number.value} − {atomic_number.value}",
        ),
        _law(
            "ion_charge",
            "structure",
            "Ion charge",
            "q = Z − Ne",
            "Ion charge, q",
            ("q", ""),
            "atomic_number - electron_count",
            (
                ("atomic_number", "Z", ""),
                ("electron_count", "Ne", ""),
            ),
            "q = {atomic_number.value} − {electron_count.value}",
            signed=frozenset({"electron_count"}),
        ),
        _law(
            "shell_capacity",
            "structure",
            "Shell capacity",
            "N = 2n²",
            "Maximum electrons, N",
            ("N", ""),
            "2*shell_n**2",
            (("shell_n", "n", ""),),
            "N = 2({shell_n.value})²",
        ),
        _law(
            "bond_order",
            "structure",
            "Bond order",
            "BO = (Nb − Na) / 2",
            "Bond order, BO",
            ("BO", ""),
            "(bonding - antibonding)/2",
            (
                ("bonding", "Nb", ""),
                ("antibonding", "Na", ""),
            ),
            "BO = ({bonding.value} − {antibonding.value}) / 2",
            non_negative=frozenset({"bonding", "antibonding"}),
        ),
        _law(
            "wavenumber",
            "spectroscopy",
            "Wavenumber",
            "ν̃ = 1/λ",
            "Wavenumber, ν̃",
            ("ν̃", "1/cm"),
            "1e7/wavelength",
            (("wavelength", "λ", "nm"),),
            "ν̃ = 10^7 / {wavelength.value}",
        ),
        _law(
            "quantum_yield",
            "spectroscopy",
            "Quantum yield",
            "Φ = events / photons absorbed",
            "Quantum yield, Φ",
            ("Φ", ""),
            "events/photons",
            (
                ("events", "events", ""),
                ("photons", "photons", ""),
            ),
            "Φ = {events.value} / {photons.value}",
        ),
        _law(
            "tetrahedral_splitting",
            "inorganic",
            "Tetrahedral splitting",
            "Δt = (4/9) Δo",
            "Tetrahedral splitting, Δt",
            ("Δt", "kJ/mol"),
            "(4/9)*delta_o",
            (("delta_o", "Δo", "kJ/mol"),),
            "Δt = (4/9)({delta_o.value})",
        ),
        _law(
            "base_buffer_poh",
            "acid_base",
            "Base buffer",
            "pOH = pKb + log10([BH+]/[B])",
            "pOH",
            ("pOH", ""),
            f"pkb + log(conjugate/base)/{_LOG10}",
            (
                ("pkb", "pKb", ""),
                ("conjugate", "[BH+]", "mol/L"),
                ("base", "[B]", "mol/L"),
            ),
            "pOH = {pkb.value} + log10({conjugate.value}/{base.value})",
        ),
        _law(
            "molar_heat",
            "thermochemistry",
            "Molar heat",
            "q = n C ΔT",
            "Heat, q",
            ("q", "J"),
            "moles*heat_capacity*delta_t",
            (
                ("moles", "n", "mol"),
                ("heat_capacity", "C", "J/(mol·K)"),
                ("delta_t", "ΔT", "K"),
            ),
            "q = ({moles.value})({heat_capacity.value})({delta_t.value})",
            signed=frozenset({"delta_t"}),
        ),
        _law(
            "electron_moles",
            "electrochemistry",
            "Moles of electrons",
            "n = It / F",
            "Moles of electrons, n",
            ("n", "mol"),
            "current*time/F",
            (
                ("current", "I", "A"),
                ("time", "t", "s"),
            ),
            "n = ({current.value})({time.value}) / F",
        ),
        _law(
            "hill_saturation",
            "biochemistry",
            "Hill equation",
            "θ = [L]^n / (Kd + [L]^n)",
            "Saturation, θ",
            ("θ", ""),
            "ligand**hill_n/(dissociation + ligand**hill_n)",
            (
                ("ligand", "[L]", "mol/L"),
                ("hill_n", "n", ""),
                ("dissociation", "Kd", "mol/L"),
            ),
            "θ = {ligand.value}^{hill_n.value}"
            " / ({dissociation.value} + {ligand.value}^{hill_n.value})",
        ),
        _law(
            "freundlich",
            "analytical",
            "Freundlich isotherm",
            "q = KF C^(1/n)",
            "Adsorbed amount, q",
            ("q", ""),
            "coefficient*concentration**(1/exponent)",
            (
                ("coefficient", "KF", ""),
                ("concentration", "C", "mol/L"),
                ("exponent", "n", ""),
            ),
            "q = ({coefficient.value})({concentration.value})^(1/{exponent.value})",
        ),
        _law(
            "degree_of_polymerization",
            "organic",
            "Degree of polymerization",
            "DP = M_polymer / M_repeat",
            "Degree of polymerization, DP",
            ("DP", ""),
            "polymer_mass/repeat_mass",
            (
                ("polymer_mass", "M(polymer)", "g/mol"),
                ("repeat_mass", "M(repeat)", "g/mol"),
            ),
            "DP = {polymer_mass.value} / {repeat_mass.value}",
        ),
        _law(
            "polydispersity",
            "organic",
            "Polydispersity",
            "Đ = Mw / Mn",
            "Polydispersity, Đ",
            ("Đ", ""),
            "weight_average/number_average",
            (
                ("weight_average", "Mw", "g/mol"),
                ("number_average", "Mn", "g/mol"),
            ),
            "Đ = {weight_average.value} / {number_average.value}",
        ),
        _law(
            "carothers",
            "organic",
            "Carothers equation",
            "Xn = 1 / (1 − p)",
            "Degree of polymerization, Xn",
            ("Xn", ""),
            "1/(1 - extent)",
            (("extent", "p", ""),),
            "Xn = 1 / (1 − {extent.value})",
            non_negative=frozenset({"extent"}),
        ),
        _law(
            "polymerization_rate",
            "kinetics",
            "Polymerization rate",
            "Rp = kp [M] [R•]",
            "Polymerization rate, Rp",
            ("Rp", "mol/(L·s)"),
            "rate_constant*monomer*radical",
            (
                ("rate_constant", "kp", "L/(mol·s)"),
                ("monomer", "[M]", "mol/L"),
                ("radical", "[R•]", "mol/L"),
            ),
            "Rp = ({rate_constant.value})({monomer.value})({radical.value})",
        ),
        _law(
            "butler_volmer",
            "electrochemistry",
            "Butler–Volmer equation",
            "i = i0 [exp(α n F η / RT) − exp(−(1 − α) n F η / RT)]",
            "Current, i",
            ("i", "A"),
            "exchange*(exp(alpha*electrons*F*overpotential/(R_J*temperature))"
            " - exp(-(1 - alpha)*electrons*F*overpotential/(R_J*temperature)))",
            (
                ("exchange", "i0", "A"),
                ("alpha", "α", ""),
                ("electrons", "n", ""),
                ("overpotential", "η", "V"),
                ("temperature", "T", "K"),
            ),
            "i = ({exchange.value}) [exp(({alpha.value})({electrons.value}) F"
            " ({overpotential.value}) / (R {temperature.value}))"
            " − exp(−(1 − {alpha.value})({electrons.value}) F"
            " ({overpotential.value}) / (R {temperature.value}))]",
            signed=frozenset({"overpotential"}),
        ),
        _law(
            "tafel",
            "electrochemistry",
            "Tafel equation",
            "η = a + b log10(i)",
            "Overpotential, η",
            ("η", "V"),
            f"intercept + slope*log(current)/{_LOG10}",
            (
                ("intercept", "a", "V"),
                ("slope", "b", "V"),
                ("current", "i", "A"),
            ),
            "η = {intercept.value} + ({slope.value}) log10({current.value})",
            signed=frozenset({"intercept", "slope"}),
        ),
        _law(
            "electrochemical_potential",
            "electrochemistry",
            "Electrochemical potential",
            "μ̃ = μ + z F φ",
            "Electrochemical potential, μ̃",
            ("μ̃", "J/mol"),
            "chemical_potential + charge_number*F*electric_potential",
            (
                ("chemical_potential", "μ", "J/mol"),
                ("charge_number", "z", ""),
                ("electric_potential", "φ", "V"),
            ),
            "μ̃ = {chemical_potential.value} + ({charge_number.value})"
            " F ({electric_potential.value})",
            signed=frozenset({"chemical_potential", "charge_number", "electric_potential"}),
        ),
        _law(
            "chemical_potential",
            "thermochemistry",
            "Chemical potential",
            "μ = μ° + RT ln a",
            "Chemical potential, μ",
            ("μ", "J/mol"),
            "standard_potential + R_J*temperature*log(activity)",
            (
                ("standard_potential", "μ°", "J/mol"),
                ("temperature", "T", "K"),
                ("activity", "a", ""),
            ),
            "μ = {standard_potential.value} + R({temperature.value}) ln({activity.value})",
            signed=frozenset({"standard_potential"}),
        ),
        _law(
            "activity",
            "solutions",
            "Activity",
            "a = γ c / c°",
            "Activity, a",
            ("a", ""),
            "gamma*concentration/standard_concentration",
            (
                ("gamma", "γ", ""),
                ("concentration", "c", "mol/L"),
                ("standard_concentration", "c°", "mol/L"),
            ),
            "a = ({gamma.value})({concentration.value}) / {standard_concentration.value}",
        ),
        _law(
            "larmor",
            "spectroscopy",
            "Larmor frequency",
            "ω = γ B",
            "Larmor frequency, ω",
            ("ω", "rad/s"),
            "gyromagnetic*field",
            (
                ("gyromagnetic", "γ", "rad/(s·T)"),
                ("field", "B", "T"),
            ),
            "ω = ({gyromagnetic.value})({field.value})",
        ),
        _law(
            "chemical_shift",
            "spectroscopy",
            "Chemical shift",
            "δ = (ν_sample − ν_ref) / ν0 × 10^6",
            "Chemical shift, δ",
            ("δ", "ppm"),
            "(sample_freq - reference_freq)/spectrometer_freq*1e6",
            (
                ("sample_freq", "ν(sample)", "Hz"),
                ("reference_freq", "ν(reference)", "Hz"),
                ("spectrometer_freq", "ν0", "Hz"),
            ),
            "δ = ({sample_freq.value} − {reference_freq.value}) / {spectrometer_freq.value} × 10^6",
            signed=frozenset({"sample_freq", "reference_freq"}),
        ),
        _law(
            "magnetic_sector",
            "spectroscopy",
            "Magnetic-sector mass-to-charge",
            "m/q = B² r² / (2V)",
            "Mass-to-charge, m/q",
            ("m/q", "kg/C"),
            "field**2*radius**2/(2*voltage)",
            (
                ("field", "B", "T"),
                ("radius", "r", "m"),
                ("voltage", "V", "V"),
            ),
            "m/q = ({field.value})² ({radius.value})² / (2 {voltage.value})",
        ),
        _law(
            "cubic_spacing",
            "inorganic",
            "Cubic interplanar spacing",
            "d = a / √(h² + k² + l²)",
            "Interplanar spacing, d",
            ("d", "nm"),
            "lattice/sqrt(miller_h**2 + miller_k**2 + miller_l**2)",
            (
                ("lattice", "a", "nm"),
                ("miller_h", "h", ""),
                ("miller_k", "k", ""),
                ("miller_l", "l", ""),
            ),
            "d = {lattice.value} / √({miller_h.value}² + {miller_k.value}² + {miller_l.value}²)",
            non_negative=frozenset({"miller_h", "miller_k", "miller_l"}),
        ),
        _law(
            "lever_alpha",
            "thermochemistry",
            "Lever rule",
            "fα = (Cβ − C0) / (Cβ − Cα)",
            "Alpha fraction, fα",
            ("fα", ""),
            "(beta_composition - overall)/(beta_composition - alpha_composition)",
            (
                ("alpha_composition", "Cα", ""),
                ("beta_composition", "Cβ", ""),
                ("overall", "C0", ""),
            ),
            "fα = ({beta_composition.value} − {overall.value})"
            " / ({beta_composition.value} − {alpha_composition.value})",
        ),
        _law(
            "lever_beta",
            "thermochemistry",
            "Lever rule",
            "fβ = (C0 − Cα) / (Cβ − Cα)",
            "Beta fraction, fβ",
            ("fβ", ""),
            "(overall - alpha_composition)/(beta_composition - alpha_composition)",
            (
                ("alpha_composition", "Cα", ""),
                ("beta_composition", "Cβ", ""),
                ("overall", "C0", ""),
            ),
            "fβ = ({overall.value} − {alpha_composition.value})"
            " / ({beta_composition.value} − {alpha_composition.value})",
        ),
        _law(
            "mean_square_displacement",
            "kinetics",
            "Mean-square displacement",
            "⟨x²⟩ = 2 D t",
            "Mean-square displacement, ⟨x²⟩",
            ("⟨x²⟩", "cm²"),
            "2*diffusion*time",
            (
                ("diffusion", "D", "cm²/s"),
                ("time", "t", "s"),
            ),
            "⟨x²⟩ = 2({diffusion.value})({time.value})",
        ),
        _law(
            "stokes_einstein",
            "kinetics",
            "Stokes–Einstein equation",
            "D = kT / (6 π η r)",
            "Diffusion coefficient, D",
            ("D", "m²/s"),
            "k_B*temperature/(6*pi*viscosity*radius*1e-9)",
            (
                ("temperature", "T", "K"),
                ("viscosity", "η", "Pa·s"),
                ("radius", "r", "nm"),
            ),
            "D = k({temperature.value}) / (6 π ({viscosity.value}) ({radius.value} nm))",
        ),
        _law(
            "relative_standard_deviation",
            "analytical",
            "Relative standard deviation",
            "RSD = s / mean × 100",
            "Relative standard deviation, RSD",
            ("RSD", "%"),
            "deviation/mean*100",
            (
                ("deviation", "s", ""),
                ("mean", "mean", ""),
            ),
            "RSD = {deviation.value} / {mean.value} × 100",
        ),
        _law(
            "conjugate_fraction",
            "acid_base",
            "Monoprotic conjugate fraction",
            "αA− = Ka / (Ka + [H+])",
            "Conjugate fraction, αA−",
            ("αA−", ""),
            "ka/(ka + hydrogen)",
            (
                ("ka", "Ka", ""),
                ("hydrogen", "[H+]", "mol/L"),
            ),
            "αA− = {ka.value} / ({ka.value} + {hydrogen.value})",
        ),
        _law(
            "acid_fraction",
            "acid_base",
            "Monoprotic acid fraction",
            "αHA = [H+] / (Ka + [H+])",
            "Acid fraction, αHA",
            ("αHA", ""),
            "hydrogen/(ka + hydrogen)",
            (
                ("ka", "Ka", ""),
                ("hydrogen", "[H+]", "mol/L"),
            ),
            "αHA = {hydrogen.value} / ({ka.value} + {hydrogen.value})",
        ),
        _law(
            "conjugate_fraction_ph",
            "acid_base",
            "Monoprotic conjugate fraction",
            "αA− = Ka / (Ka + [H+])",
            "Conjugate fraction, αA−",
            ("αA−", ""),
            "ka/(ka + 10**(-ph))",
            (
                ("ka", "Ka", ""),
                ("ph", "pH", ""),
            ),
            "αA− = {ka.value} / ({ka.value} + 10^(−{ph.value}))",
        ),
        _law(
            "acid_fraction_ph",
            "acid_base",
            "Monoprotic acid fraction",
            "αHA = [H+] / (Ka + [H+])",
            "Acid fraction, αHA",
            ("αHA", ""),
            "10**(-ph)/(ka + 10**(-ph))",
            (
                ("ka", "Ka", ""),
                ("ph", "pH", ""),
            ),
            "αHA = 10^(−{ph.value}) / ({ka.value} + 10^(−{ph.value}))",
        ),
    )
}
