"""Hosted privacy policy and terms (App Store / Play Console URLs)."""

# ruff: noqa: E501

from __future__ import annotations

import html
import re

PRIVACY_POLICY_MD = """# Privacy Policy

**Last updated: June 2026**

## What We Collect

- **Account information**: Your name and email address from Google Sign-In.
- **Conversations**: Messages you send and responses from the AI.
- **Learned facts**: Information Recall extracts to personalize your experience (preferences, projects, facts you share).
- **Usage data**: Token counts for daily quota tracking.

## How We Use Your Data

- To provide personalized AI responses based on what you've shared.
- To improve response quality via thumbs-up/thumbs-down feedback.
- To enforce daily usage limits.

## Data Storage

Your data is stored in a secure PostgreSQL database. Memories and conversations are associated with your account and are never shared with third parties.

## AI Processing

Messages are sent to AI providers (via LiteLLM) to generate responses. These providers do not retain your data and process it only to generate the current response.

## Your Rights

- **Export**: Download all your data (chats, messages, memories) as JSON at any time from Settings.
- **Delete account**: Permanently delete your account and all associated data from Settings. This is irreversible.
- **Delete memories**: Remove individual learned facts from the Memory screen.

## Children's Privacy

Recall is not intended for users under 13. We do not knowingly collect data from children.

## Changes

We may update this policy. Check this page for the latest version.

## Contact

If you have questions about this policy or your data, reach out through the app or your account provider."""

TERMS_OF_SERVICE_MD = """# Terms of Service

**Last updated: June 2026**

## Using Recall

- Recall is a personal AI chat app that remembers your preferences and context across chats.
- You agree to provide accurate information and to use the app for lawful, personal purposes.
- You are responsible for the content you share with the app.

## Your Account

- You sign in with Google. Keep your Google account secure — you are responsible for activity under it.
- You can export or delete your account and data at any time from Settings.

## AI Responses

- AI responses are generated by third-party models and may be inaccurate or incomplete. They are not professional advice.
- Do not rely on Recall for medical, legal, financial, or safety-critical decisions.
- You are responsible for reviewing AI output before acting on it.

## Acceptable Use

- Do not use Recall to generate unlawful, harmful, harassing, or abusive content.
- Do not attempt to extract provider API keys, reverse-engineer the service, or overload it.
- We may suspend accounts that violate these terms.

## Privacy

- Our handling of your data is described in the Privacy Policy, which is part of these terms.

## Changes

- We may update these terms. Material changes will be surfaced in the app. Continued use after changes means you accept the updated terms.

## Contact

- Questions about these terms can be sent to the contact listed in the Privacy Policy."""


def markdown_to_html(markdown: str, *, page_title: str) -> str:
    """Minimal markdown → HTML for legal pages (headings, bullets, paragraphs)."""
    body_parts: list[str] = []
    in_list = False
    for raw_line in markdown.strip().split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("- "):
            if not in_list:
                body_parts.append("<ul>")
                in_list = True
            item = html.escape(line[2:])
            item = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", item)
            body_parts.append(f"<li>{item}</li>")
            continue
        if in_list:
            body_parts.append("</ul>")
            in_list = False
        if line.startswith("# "):
            body_parts.append(f"<h1>{html.escape(line[2:])}</h1>")
        elif line.startswith("## "):
            body_parts.append(f"<h2>{html.escape(line[3:])}</h2>")
        else:
            escaped = html.escape(line)
            para = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
            body_parts.append(f"<p>{para}</p>")
    if in_list:
        body_parts.append("</ul>")

    html_body = "\n".join(body_parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(page_title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; line-height: 1.55; max-width: 42rem; margin: 2rem auto; padding: 0 1rem; color: #111; }}
    h1 {{ font-size: 1.75rem; margin-bottom: 0.5rem; }}
    h2 {{ font-size: 1.15rem; margin-top: 1.5rem; }}
    p, li {{ font-size: 1rem; }}
    ul {{ padding-left: 1.25rem; }}
  </style>
</head>
<body>
{html_body}
</body>
</html>"""
